// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/archive.dart';
import 'api/conference.dart';
import 'api/crdt.dart';
import 'api/emotes.dart';
import 'api/gifs.dart';
import 'api/identity.dart';
import 'api/network.dart';
import 'api/screen_audio.dart';
import 'api/share.dart';
import 'api/shop.dart';
import 'api/showcase.dart';
import 'api/simple.dart';
import 'api/stickers.dart';
import 'api/storage.dart';
import 'api/twitch.dart';
import 'api/updater.dart';
import 'api/verification.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DownloadProgress> dco_decode_StreamSink_download_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<NetworkEvent> dco_decode_StreamSink_network_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ArchiveChannelInfoFfi dco_decode_archive_channel_info_ffi(dynamic raw);

  @protected
  ArchiveData dco_decode_archive_data(dynamic raw);

  @protected
  ArchiveDeletionFfi dco_decode_archive_deletion_ffi(dynamic raw);

  @protected
  ArchiveEditFfi dco_decode_archive_edit_ffi(dynamic raw);

  @protected
  ArchiveFileFfi dco_decode_archive_file_ffi(dynamic raw);

  @protected
  ArchiveMessageFfi dco_decode_archive_message_ffi(dynamic raw);

  @protected
  ArchivePubKeyFfi dco_decode_archive_pub_key_ffi(dynamic raw);

  @protected
  ArchiveReactionFfi dco_decode_archive_reaction_ffi(dynamic raw);

  @protected
  ArchiveReactionRemovalFfi dco_decode_archive_reaction_removal_ffi(
    dynamic raw,
  );

  @protected
  ArchiveVerifyResult dco_decode_archive_verify_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  DiscoveredPeer dco_decode_box_autoadd_discovered_peer(dynamic raw);

  @protected
  GameCardDetails dco_decode_box_autoadd_game_card_details(dynamic raw);

  @protected
  GuestFileMetaFfi dco_decode_box_autoadd_guest_file_meta_ffi(dynamic raw);

  @protected
  HollowpackImport dco_decode_box_autoadd_hollowpack_import(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LinkPreviewRef dco_decode_box_autoadd_link_preview_ref(dynamic raw);

  @protected
  NetworkEvent dco_decode_box_autoadd_network_event(dynamic raw);

  @protected
  PushChannelMeta dco_decode_box_autoadd_push_channel_meta(dynamic raw);

  @protected
  PushProfile dco_decode_box_autoadd_push_profile(dynamic raw);

  @protected
  ServerAvatarAnimData dco_decode_box_autoadd_server_avatar_anim_data(
    dynamic raw,
  );

  @protected
  ServerBannerData dco_decode_box_autoadd_server_banner_data(dynamic raw);

  @protected
  StoredFileInfo dco_decode_box_autoadd_stored_file_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile dco_decode_box_autoadd_user_profile(dynamic raw);

  @protected
  VideoThumbRef dco_decode_box_autoadd_video_thumb_ref(dynamic raw);

  @protected
  ChannelFfi dco_decode_channel_ffi(dynamic raw);

  @protected
  ChannelGrantFfi dco_decode_channel_grant_ffi(dynamic raw);

  @protected
  ConferenceInfo dco_decode_conference_info(dynamic raw);

  @protected
  DeviceLabel dco_decode_device_label(dynamic raw);

  @protected
  DeviceLink dco_decode_device_link(dynamic raw);

  @protected
  DiscoveredPeer dco_decode_discovered_peer(dynamic raw);

  @protected
  DownloadProgress dco_decode_download_progress(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FetchedMessage dco_decode_fetched_message(dynamic raw);

  @protected
  FfzEmote dco_decode_ffz_emote(dynamic raw);

  @protected
  FriendFfi dco_decode_friend_ffi(dynamic raw);

  @protected
  GameCardDetails dco_decode_game_card_details(dynamic raw);

  @protected
  GameSearchResult dco_decode_game_search_result(dynamic raw);

  @protected
  GifItem dco_decode_gif_item(dynamic raw);

  @protected
  GifPage dco_decode_gif_page(dynamic raw);

  @protected
  GuestFileMetaFfi dco_decode_guest_file_meta_ffi(dynamic raw);

  @protected
  GuestReactionFfi dco_decode_guest_reaction_ffi(dynamic raw);

  @protected
  GuestSyncMessageFfi dco_decode_guest_sync_message_ffi(dynamic raw);

  @protected
  HollowpackFile dco_decode_hollowpack_file(dynamic raw);

  @protected
  HollowpackImport dco_decode_hollowpack_import(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityInfo dco_decode_identity_info(dynamic raw);

  @protected
  KeptRedeemCode dco_decode_kept_redeem_code(dynamic raw);

  @protected
  LabelFfi dco_decode_label_ffi(dynamic raw);

  @protected
  LinkPreviewRef dco_decode_link_preview_ref(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ArchiveChannelInfoFfi> dco_decode_list_archive_channel_info_ffi(
    dynamic raw,
  );

  @protected
  List<ArchiveDeletionFfi> dco_decode_list_archive_deletion_ffi(dynamic raw);

  @protected
  List<ArchiveEditFfi> dco_decode_list_archive_edit_ffi(dynamic raw);

  @protected
  List<ArchiveFileFfi> dco_decode_list_archive_file_ffi(dynamic raw);

  @protected
  List<ArchiveMessageFfi> dco_decode_list_archive_message_ffi(dynamic raw);

  @protected
  List<ArchivePubKeyFfi> dco_decode_list_archive_pub_key_ffi(dynamic raw);

  @protected
  List<ArchiveReactionFfi> dco_decode_list_archive_reaction_ffi(dynamic raw);

  @protected
  List<ArchiveReactionRemovalFfi> dco_decode_list_archive_reaction_removal_ffi(
    dynamic raw,
  );

  @protected
  List<bool> dco_decode_list_bool(dynamic raw);

  @protected
  List<ChannelFfi> dco_decode_list_channel_ffi(dynamic raw);

  @protected
  List<ChannelGrantFfi> dco_decode_list_channel_grant_ffi(dynamic raw);

  @protected
  List<ConferenceInfo> dco_decode_list_conference_info(dynamic raw);

  @protected
  List<DeviceLabel> dco_decode_list_device_label(dynamic raw);

  @protected
  List<DeviceLink> dco_decode_list_device_link(dynamic raw);

  @protected
  List<FetchedMessage> dco_decode_list_fetched_message(dynamic raw);

  @protected
  List<FfzEmote> dco_decode_list_ffz_emote(dynamic raw);

  @protected
  List<FriendFfi> dco_decode_list_friend_ffi(dynamic raw);

  @protected
  List<GameSearchResult> dco_decode_list_game_search_result(dynamic raw);

  @protected
  List<GifItem> dco_decode_list_gif_item(dynamic raw);

  @protected
  List<GuestReactionFfi> dco_decode_list_guest_reaction_ffi(dynamic raw);

  @protected
  List<GuestSyncMessageFfi> dco_decode_list_guest_sync_message_ffi(dynamic raw);

  @protected
  List<HollowpackFile> dco_decode_list_hollowpack_file(dynamic raw);

  @protected
  List<KeptRedeemCode> dco_decode_list_kept_redeem_code(dynamic raw);

  @protected
  List<LabelFfi> dco_decode_list_label_ffi(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<MemberFfi> dco_decode_list_member_ffi(dynamic raw);

  @protected
  List<MutedMemberFfi> dco_decode_list_muted_member_ffi(dynamic raw);

  @protected
  List<OwnSupportCred> dco_decode_list_own_support_cred(dynamic raw);

  @protected
  List<OwnedArt> dco_decode_list_owned_art(dynamic raw);

  @protected
  List<PendingJoinFfi> dco_decode_list_pending_join_ffi(dynamic raw);

  @protected
  List<PersonalEmote> dco_decode_list_personal_emote(dynamic raw);

  @protected
  List<PersonalSticker> dco_decode_list_personal_sticker(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PublicChannelEntryFfi> dco_decode_list_public_channel_entry_ffi(
    dynamic raw,
  );

  @protected
  List<(String, PlatformInt64)> dco_decode_list_record_string_i_64(dynamic raw);

  @protected
  List<SecurityAlertFfi> dco_decode_list_security_alert_ffi(dynamic raw);

  @protected
  List<ServerEmote> dco_decode_list_server_emote(dynamic raw);

  @protected
  List<ServerFfi> dco_decode_list_server_ffi(dynamic raw);

  @protected
  List<ServerSticker> dco_decode_list_server_sticker(dynamic raw);

  @protected
  List<SettingEntry> dco_decode_list_setting_entry(dynamic raw);

  @protected
  List<ShareEntry> dco_decode_list_share_entry(dynamic raw);

  @protected
  List<ShopFile> dco_decode_list_shop_file(dynamic raw);

  @protected
  List<ShopListing> dco_decode_list_shop_listing(dynamic raw);

  @protected
  List<ShowcaseAsset> dco_decode_list_showcase_asset(dynamic raw);

  @protected
  List<StorageContextUsage> dco_decode_list_storage_context_usage(dynamic raw);

  @protected
  List<StoredChannelMessage> dco_decode_list_stored_channel_message(
    dynamic raw,
  );

  @protected
  List<StoredFileInfo> dco_decode_list_stored_file_info(dynamic raw);

  @protected
  List<StoredMessage> dco_decode_list_stored_message(dynamic raw);

  @protected
  List<StoredMessageEdit> dco_decode_list_stored_message_edit(dynamic raw);

  @protected
  List<StoredReaction> dco_decode_list_stored_reaction(dynamic raw);

  @protected
  List<SyncSenderProfileFfi> dco_decode_list_sync_sender_profile_ffi(
    dynamic raw,
  );

  @protected
  List<UserProfile> dco_decode_list_user_profile(dynamic raw);

  @protected
  List<VaultFileStatusFfi> dco_decode_list_vault_file_status_ffi(dynamic raw);

  @protected
  MemberFfi dco_decode_member_ffi(dynamic raw);

  @protected
  MessageProofV2 dco_decode_message_proof_v_2(dynamic raw);

  @protected
  MutedMemberFfi dco_decode_muted_member_ffi(dynamic raw);

  @protected
  NetworkEvent dco_decode_network_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  GameCardDetails? dco_decode_opt_box_autoadd_game_card_details(dynamic raw);

  @protected
  GuestFileMetaFfi? dco_decode_opt_box_autoadd_guest_file_meta_ffi(dynamic raw);

  @protected
  HollowpackImport? dco_decode_opt_box_autoadd_hollowpack_import(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LinkPreviewRef? dco_decode_opt_box_autoadd_link_preview_ref(dynamic raw);

  @protected
  NetworkEvent? dco_decode_opt_box_autoadd_network_event(dynamic raw);

  @protected
  PushChannelMeta? dco_decode_opt_box_autoadd_push_channel_meta(dynamic raw);

  @protected
  PushProfile? dco_decode_opt_box_autoadd_push_profile(dynamic raw);

  @protected
  ServerAvatarAnimData? dco_decode_opt_box_autoadd_server_avatar_anim_data(
    dynamic raw,
  );

  @protected
  ServerBannerData? dco_decode_opt_box_autoadd_server_banner_data(dynamic raw);

  @protected
  StoredFileInfo? dco_decode_opt_box_autoadd_stored_file_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  UserProfile? dco_decode_opt_box_autoadd_user_profile(dynamic raw);

  @protected
  VideoThumbRef? dco_decode_opt_box_autoadd_video_thumb_ref(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ShowcaseAsset>? dco_decode_opt_list_showcase_asset(dynamic raw);

  @protected
  OwnSupportCred dco_decode_own_support_cred(dynamic raw);

  @protected
  OwnedArt dco_decode_owned_art(dynamic raw);

  @protected
  PendingJoinFfi dco_decode_pending_join_ffi(dynamic raw);

  @protected
  PersonalEmote dco_decode_personal_emote(dynamic raw);

  @protected
  PersonalSticker dco_decode_personal_sticker(dynamic raw);

  @protected
  ProcessedEmote dco_decode_processed_emote(dynamic raw);

  @protected
  ProcessedFrame dco_decode_processed_frame(dynamic raw);

  @protected
  ProcessedProfileMedia dco_decode_processed_profile_media(dynamic raw);

  @protected
  ProcessedSticker dco_decode_processed_sticker(dynamic raw);

  @protected
  ProtectionStatus dco_decode_protection_status(dynamic raw);

  @protected
  PublicChannelEntryFfi dco_decode_public_channel_entry_ffi(dynamic raw);

  @protected
  PushChannelMeta dco_decode_push_channel_meta(dynamic raw);

  @protected
  PushProfile dco_decode_push_profile(dynamic raw);

  @protected
  (String, PlatformInt64) dco_decode_record_string_i_64(dynamic raw);

  @protected
  RedeemLookup dco_decode_redeem_lookup(dynamic raw);

  @protected
  RedeemOutcome dco_decode_redeem_outcome(dynamic raw);

  @protected
  SecurityAlertFfi dco_decode_security_alert_ffi(dynamic raw);

  @protected
  ServerAvatarAnimData dco_decode_server_avatar_anim_data(dynamic raw);

  @protected
  ServerBannerData dco_decode_server_banner_data(dynamic raw);

  @protected
  ServerEmote dco_decode_server_emote(dynamic raw);

  @protected
  ServerFfi dco_decode_server_ffi(dynamic raw);

  @protected
  ServerSticker dco_decode_server_sticker(dynamic raw);

  @protected
  SettingEntry dco_decode_setting_entry(dynamic raw);

  @protected
  ShardImportResultFfi dco_decode_shard_import_result_ffi(dynamic raw);

  @protected
  ShareEntry dco_decode_share_entry(dynamic raw);

  @protected
  ShareLinkInfo dco_decode_share_link_info(dynamic raw);

  @protected
  ShopArtist dco_decode_shop_artist(dynamic raw);

  @protected
  ShopCatalog dco_decode_shop_catalog(dynamic raw);

  @protected
  ShopFile dco_decode_shop_file(dynamic raw);

  @protected
  ShopListing dco_decode_shop_listing(dynamic raw);

  @protected
  ShowcaseAsset dco_decode_showcase_asset(dynamic raw);

  @protected
  StickerPackImportResult dco_decode_sticker_pack_import_result(dynamic raw);

  @protected
  StickerPackPreview dco_decode_sticker_pack_preview(dynamic raw);

  @protected
  StorageBreakdown dco_decode_storage_breakdown(dynamic raw);

  @protected
  StorageContextUsage dco_decode_storage_context_usage(dynamic raw);

  @protected
  StorageStatsFfi dco_decode_storage_stats_ffi(dynamic raw);

  @protected
  StoredChannelMessage dco_decode_stored_channel_message(dynamic raw);

  @protected
  StoredFileInfo dco_decode_stored_file_info(dynamic raw);

  @protected
  StoredGif dco_decode_stored_gif(dynamic raw);

  @protected
  StoredMessage dco_decode_stored_message(dynamic raw);

  @protected
  StoredMessageEdit dco_decode_stored_message_edit(dynamic raw);

  @protected
  StoredReaction dco_decode_stored_reaction(dynamic raw);

  @protected
  SyncSenderProfileFfi dco_decode_sync_sender_profile_ffi(dynamic raw);

  @protected
  TwitchDeviceFlowResult dco_decode_twitch_device_flow_result(dynamic raw);

  @protected
  TwitchVerifyOutcome dco_decode_twitch_verify_outcome(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UnreadMentionCount dco_decode_unread_mention_count(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VaultFileStatusFfi dco_decode_vault_file_status_ffi(dynamic raw);

  @protected
  VideoThumbRef dco_decode_video_thumb_ref(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DownloadProgress> sse_decode_StreamSink_download_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetworkEvent> sse_decode_StreamSink_network_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArchiveChannelInfoFfi sse_decode_archive_channel_info_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveData sse_decode_archive_data(SseDeserializer deserializer);

  @protected
  ArchiveDeletionFfi sse_decode_archive_deletion_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveEditFfi sse_decode_archive_edit_ffi(SseDeserializer deserializer);

  @protected
  ArchiveFileFfi sse_decode_archive_file_ffi(SseDeserializer deserializer);

  @protected
  ArchiveMessageFfi sse_decode_archive_message_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchivePubKeyFfi sse_decode_archive_pub_key_ffi(SseDeserializer deserializer);

  @protected
  ArchiveReactionFfi sse_decode_archive_reaction_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveReactionRemovalFfi sse_decode_archive_reaction_removal_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveVerifyResult sse_decode_archive_verify_result(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  DiscoveredPeer sse_decode_box_autoadd_discovered_peer(
    SseDeserializer deserializer,
  );

  @protected
  GameCardDetails sse_decode_box_autoadd_game_card_details(
    SseDeserializer deserializer,
  );

  @protected
  GuestFileMetaFfi sse_decode_box_autoadd_guest_file_meta_ffi(
    SseDeserializer deserializer,
  );

  @protected
  HollowpackImport sse_decode_box_autoadd_hollowpack_import(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LinkPreviewRef sse_decode_box_autoadd_link_preview_ref(
    SseDeserializer deserializer,
  );

  @protected
  NetworkEvent sse_decode_box_autoadd_network_event(
    SseDeserializer deserializer,
  );

  @protected
  PushChannelMeta sse_decode_box_autoadd_push_channel_meta(
    SseDeserializer deserializer,
  );

  @protected
  PushProfile sse_decode_box_autoadd_push_profile(SseDeserializer deserializer);

  @protected
  ServerAvatarAnimData sse_decode_box_autoadd_server_avatar_anim_data(
    SseDeserializer deserializer,
  );

  @protected
  ServerBannerData sse_decode_box_autoadd_server_banner_data(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo sse_decode_box_autoadd_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_box_autoadd_user_profile(SseDeserializer deserializer);

  @protected
  VideoThumbRef sse_decode_box_autoadd_video_thumb_ref(
    SseDeserializer deserializer,
  );

  @protected
  ChannelFfi sse_decode_channel_ffi(SseDeserializer deserializer);

  @protected
  ChannelGrantFfi sse_decode_channel_grant_ffi(SseDeserializer deserializer);

  @protected
  ConferenceInfo sse_decode_conference_info(SseDeserializer deserializer);

  @protected
  DeviceLabel sse_decode_device_label(SseDeserializer deserializer);

  @protected
  DeviceLink sse_decode_device_link(SseDeserializer deserializer);

  @protected
  DiscoveredPeer sse_decode_discovered_peer(SseDeserializer deserializer);

  @protected
  DownloadProgress sse_decode_download_progress(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FetchedMessage sse_decode_fetched_message(SseDeserializer deserializer);

  @protected
  FfzEmote sse_decode_ffz_emote(SseDeserializer deserializer);

  @protected
  FriendFfi sse_decode_friend_ffi(SseDeserializer deserializer);

  @protected
  GameCardDetails sse_decode_game_card_details(SseDeserializer deserializer);

  @protected
  GameSearchResult sse_decode_game_search_result(SseDeserializer deserializer);

  @protected
  GifItem sse_decode_gif_item(SseDeserializer deserializer);

  @protected
  GifPage sse_decode_gif_page(SseDeserializer deserializer);

  @protected
  GuestFileMetaFfi sse_decode_guest_file_meta_ffi(SseDeserializer deserializer);

  @protected
  GuestReactionFfi sse_decode_guest_reaction_ffi(SseDeserializer deserializer);

  @protected
  GuestSyncMessageFfi sse_decode_guest_sync_message_ffi(
    SseDeserializer deserializer,
  );

  @protected
  HollowpackFile sse_decode_hollowpack_file(SseDeserializer deserializer);

  @protected
  HollowpackImport sse_decode_hollowpack_import(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityInfo sse_decode_identity_info(SseDeserializer deserializer);

  @protected
  KeptRedeemCode sse_decode_kept_redeem_code(SseDeserializer deserializer);

  @protected
  LabelFfi sse_decode_label_ffi(SseDeserializer deserializer);

  @protected
  LinkPreviewRef sse_decode_link_preview_ref(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ArchiveChannelInfoFfi> sse_decode_list_archive_channel_info_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveDeletionFfi> sse_decode_list_archive_deletion_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveEditFfi> sse_decode_list_archive_edit_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveFileFfi> sse_decode_list_archive_file_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveMessageFfi> sse_decode_list_archive_message_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchivePubKeyFfi> sse_decode_list_archive_pub_key_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveReactionFfi> sse_decode_list_archive_reaction_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchiveReactionRemovalFfi> sse_decode_list_archive_reaction_removal_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<bool> sse_decode_list_bool(SseDeserializer deserializer);

  @protected
  List<ChannelFfi> sse_decode_list_channel_ffi(SseDeserializer deserializer);

  @protected
  List<ChannelGrantFfi> sse_decode_list_channel_grant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ConferenceInfo> sse_decode_list_conference_info(
    SseDeserializer deserializer,
  );

  @protected
  List<DeviceLabel> sse_decode_list_device_label(SseDeserializer deserializer);

  @protected
  List<DeviceLink> sse_decode_list_device_link(SseDeserializer deserializer);

  @protected
  List<FetchedMessage> sse_decode_list_fetched_message(
    SseDeserializer deserializer,
  );

  @protected
  List<FfzEmote> sse_decode_list_ffz_emote(SseDeserializer deserializer);

  @protected
  List<FriendFfi> sse_decode_list_friend_ffi(SseDeserializer deserializer);

  @protected
  List<GameSearchResult> sse_decode_list_game_search_result(
    SseDeserializer deserializer,
  );

  @protected
  List<GifItem> sse_decode_list_gif_item(SseDeserializer deserializer);

  @protected
  List<GuestReactionFfi> sse_decode_list_guest_reaction_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<GuestSyncMessageFfi> sse_decode_list_guest_sync_message_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<HollowpackFile> sse_decode_list_hollowpack_file(
    SseDeserializer deserializer,
  );

  @protected
  List<KeptRedeemCode> sse_decode_list_kept_redeem_code(
    SseDeserializer deserializer,
  );

  @protected
  List<LabelFfi> sse_decode_list_label_ffi(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<MemberFfi> sse_decode_list_member_ffi(SseDeserializer deserializer);

  @protected
  List<MutedMemberFfi> sse_decode_list_muted_member_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<OwnSupportCred> sse_decode_list_own_support_cred(
    SseDeserializer deserializer,
  );

  @protected
  List<OwnedArt> sse_decode_list_owned_art(SseDeserializer deserializer);

  @protected
  List<PendingJoinFfi> sse_decode_list_pending_join_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonalEmote> sse_decode_list_personal_emote(
    SseDeserializer deserializer,
  );

  @protected
  List<PersonalSticker> sse_decode_list_personal_sticker(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<PublicChannelEntryFfi> sse_decode_list_public_channel_entry_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, PlatformInt64)> sse_decode_list_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<SecurityAlertFfi> sse_decode_list_security_alert_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ServerEmote> sse_decode_list_server_emote(SseDeserializer deserializer);

  @protected
  List<ServerFfi> sse_decode_list_server_ffi(SseDeserializer deserializer);

  @protected
  List<ServerSticker> sse_decode_list_server_sticker(
    SseDeserializer deserializer,
  );

  @protected
  List<SettingEntry> sse_decode_list_setting_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<ShareEntry> sse_decode_list_share_entry(SseDeserializer deserializer);

  @protected
  List<ShopFile> sse_decode_list_shop_file(SseDeserializer deserializer);

  @protected
  List<ShopListing> sse_decode_list_shop_listing(SseDeserializer deserializer);

  @protected
  List<ShowcaseAsset> sse_decode_list_showcase_asset(
    SseDeserializer deserializer,
  );

  @protected
  List<StorageContextUsage> sse_decode_list_storage_context_usage(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredChannelMessage> sse_decode_list_stored_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredFileInfo> sse_decode_list_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredMessage> sse_decode_list_stored_message(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredMessageEdit> sse_decode_list_stored_message_edit(
    SseDeserializer deserializer,
  );

  @protected
  List<StoredReaction> sse_decode_list_stored_reaction(
    SseDeserializer deserializer,
  );

  @protected
  List<SyncSenderProfileFfi> sse_decode_list_sync_sender_profile_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<UserProfile> sse_decode_list_user_profile(SseDeserializer deserializer);

  @protected
  List<VaultFileStatusFfi> sse_decode_list_vault_file_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  MemberFfi sse_decode_member_ffi(SseDeserializer deserializer);

  @protected
  MessageProofV2 sse_decode_message_proof_v_2(SseDeserializer deserializer);

  @protected
  MutedMemberFfi sse_decode_muted_member_ffi(SseDeserializer deserializer);

  @protected
  NetworkEvent sse_decode_network_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  GameCardDetails? sse_decode_opt_box_autoadd_game_card_details(
    SseDeserializer deserializer,
  );

  @protected
  GuestFileMetaFfi? sse_decode_opt_box_autoadd_guest_file_meta_ffi(
    SseDeserializer deserializer,
  );

  @protected
  HollowpackImport? sse_decode_opt_box_autoadd_hollowpack_import(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LinkPreviewRef? sse_decode_opt_box_autoadd_link_preview_ref(
    SseDeserializer deserializer,
  );

  @protected
  NetworkEvent? sse_decode_opt_box_autoadd_network_event(
    SseDeserializer deserializer,
  );

  @protected
  PushChannelMeta? sse_decode_opt_box_autoadd_push_channel_meta(
    SseDeserializer deserializer,
  );

  @protected
  PushProfile? sse_decode_opt_box_autoadd_push_profile(
    SseDeserializer deserializer,
  );

  @protected
  ServerAvatarAnimData? sse_decode_opt_box_autoadd_server_avatar_anim_data(
    SseDeserializer deserializer,
  );

  @protected
  ServerBannerData? sse_decode_opt_box_autoadd_server_banner_data(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo? sse_decode_opt_box_autoadd_stored_file_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  UserProfile? sse_decode_opt_box_autoadd_user_profile(
    SseDeserializer deserializer,
  );

  @protected
  VideoThumbRef? sse_decode_opt_box_autoadd_video_thumb_ref(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ShowcaseAsset>? sse_decode_opt_list_showcase_asset(
    SseDeserializer deserializer,
  );

  @protected
  OwnSupportCred sse_decode_own_support_cred(SseDeserializer deserializer);

  @protected
  OwnedArt sse_decode_owned_art(SseDeserializer deserializer);

  @protected
  PendingJoinFfi sse_decode_pending_join_ffi(SseDeserializer deserializer);

  @protected
  PersonalEmote sse_decode_personal_emote(SseDeserializer deserializer);

  @protected
  PersonalSticker sse_decode_personal_sticker(SseDeserializer deserializer);

  @protected
  ProcessedEmote sse_decode_processed_emote(SseDeserializer deserializer);

  @protected
  ProcessedFrame sse_decode_processed_frame(SseDeserializer deserializer);

  @protected
  ProcessedProfileMedia sse_decode_processed_profile_media(
    SseDeserializer deserializer,
  );

  @protected
  ProcessedSticker sse_decode_processed_sticker(SseDeserializer deserializer);

  @protected
  ProtectionStatus sse_decode_protection_status(SseDeserializer deserializer);

  @protected
  PublicChannelEntryFfi sse_decode_public_channel_entry_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PushChannelMeta sse_decode_push_channel_meta(SseDeserializer deserializer);

  @protected
  PushProfile sse_decode_push_profile(SseDeserializer deserializer);

  @protected
  (String, PlatformInt64) sse_decode_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  RedeemLookup sse_decode_redeem_lookup(SseDeserializer deserializer);

  @protected
  RedeemOutcome sse_decode_redeem_outcome(SseDeserializer deserializer);

  @protected
  SecurityAlertFfi sse_decode_security_alert_ffi(SseDeserializer deserializer);

  @protected
  ServerAvatarAnimData sse_decode_server_avatar_anim_data(
    SseDeserializer deserializer,
  );

  @protected
  ServerBannerData sse_decode_server_banner_data(SseDeserializer deserializer);

  @protected
  ServerEmote sse_decode_server_emote(SseDeserializer deserializer);

  @protected
  ServerFfi sse_decode_server_ffi(SseDeserializer deserializer);

  @protected
  ServerSticker sse_decode_server_sticker(SseDeserializer deserializer);

  @protected
  SettingEntry sse_decode_setting_entry(SseDeserializer deserializer);

  @protected
  ShardImportResultFfi sse_decode_shard_import_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  ShareEntry sse_decode_share_entry(SseDeserializer deserializer);

  @protected
  ShareLinkInfo sse_decode_share_link_info(SseDeserializer deserializer);

  @protected
  ShopArtist sse_decode_shop_artist(SseDeserializer deserializer);

  @protected
  ShopCatalog sse_decode_shop_catalog(SseDeserializer deserializer);

  @protected
  ShopFile sse_decode_shop_file(SseDeserializer deserializer);

  @protected
  ShopListing sse_decode_shop_listing(SseDeserializer deserializer);

  @protected
  ShowcaseAsset sse_decode_showcase_asset(SseDeserializer deserializer);

  @protected
  StickerPackImportResult sse_decode_sticker_pack_import_result(
    SseDeserializer deserializer,
  );

  @protected
  StickerPackPreview sse_decode_sticker_pack_preview(
    SseDeserializer deserializer,
  );

  @protected
  StorageBreakdown sse_decode_storage_breakdown(SseDeserializer deserializer);

  @protected
  StorageContextUsage sse_decode_storage_context_usage(
    SseDeserializer deserializer,
  );

  @protected
  StorageStatsFfi sse_decode_storage_stats_ffi(SseDeserializer deserializer);

  @protected
  StoredChannelMessage sse_decode_stored_channel_message(
    SseDeserializer deserializer,
  );

  @protected
  StoredFileInfo sse_decode_stored_file_info(SseDeserializer deserializer);

  @protected
  StoredGif sse_decode_stored_gif(SseDeserializer deserializer);

  @protected
  StoredMessage sse_decode_stored_message(SseDeserializer deserializer);

  @protected
  StoredMessageEdit sse_decode_stored_message_edit(
    SseDeserializer deserializer,
  );

  @protected
  StoredReaction sse_decode_stored_reaction(SseDeserializer deserializer);

  @protected
  SyncSenderProfileFfi sse_decode_sync_sender_profile_ffi(
    SseDeserializer deserializer,
  );

  @protected
  TwitchDeviceFlowResult sse_decode_twitch_device_flow_result(
    SseDeserializer deserializer,
  );

  @protected
  TwitchVerifyOutcome sse_decode_twitch_verify_outcome(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UnreadMentionCount sse_decode_unread_mention_count(
    SseDeserializer deserializer,
  );

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VaultFileStatusFfi sse_decode_vault_file_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  VideoThumbRef sse_decode_video_thumb_ref(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_progress_Sse(
    RustStreamSink<DownloadProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_network_event_Sse(
    RustStreamSink<NetworkEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_archive_channel_info_ffi(
    ArchiveChannelInfoFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_data(ArchiveData self, SseSerializer serializer);

  @protected
  void sse_encode_archive_deletion_ffi(
    ArchiveDeletionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_edit_ffi(
    ArchiveEditFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_file_ffi(
    ArchiveFileFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_message_ffi(
    ArchiveMessageFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_pub_key_ffi(
    ArchivePubKeyFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_reaction_ffi(
    ArchiveReactionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_reaction_removal_ffi(
    ArchiveReactionRemovalFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_verify_result(
    ArchiveVerifyResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_game_card_details(
    GameCardDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_guest_file_meta_ffi(
    GuestFileMetaFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hollowpack_import(
    HollowpackImport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_link_preview_ref(
    LinkPreviewRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_network_event(
    NetworkEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_push_channel_meta(
    PushChannelMeta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_push_profile(
    PushProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_server_avatar_anim_data(
    ServerAvatarAnimData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_server_banner_data(
    ServerBannerData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_stored_file_info(
    StoredFileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_user_profile(
    UserProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_video_thumb_ref(
    VideoThumbRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_channel_ffi(ChannelFfi self, SseSerializer serializer);

  @protected
  void sse_encode_channel_grant_ffi(
    ChannelGrantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conference_info(
    ConferenceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_device_label(DeviceLabel self, SseSerializer serializer);

  @protected
  void sse_encode_device_link(DeviceLink self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_peer(
    DiscoveredPeer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_progress(
    DownloadProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_fetched_message(
    FetchedMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffz_emote(FfzEmote self, SseSerializer serializer);

  @protected
  void sse_encode_friend_ffi(FriendFfi self, SseSerializer serializer);

  @protected
  void sse_encode_game_card_details(
    GameCardDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_game_search_result(
    GameSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gif_item(GifItem self, SseSerializer serializer);

  @protected
  void sse_encode_gif_page(GifPage self, SseSerializer serializer);

  @protected
  void sse_encode_guest_file_meta_ffi(
    GuestFileMetaFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_guest_reaction_ffi(
    GuestReactionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_guest_sync_message_ffi(
    GuestSyncMessageFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hollowpack_file(
    HollowpackFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hollowpack_import(
    HollowpackImport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_info(IdentityInfo self, SseSerializer serializer);

  @protected
  void sse_encode_kept_redeem_code(
    KeptRedeemCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_label_ffi(LabelFfi self, SseSerializer serializer);

  @protected
  void sse_encode_link_preview_ref(
    LinkPreviewRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_archive_channel_info_ffi(
    List<ArchiveChannelInfoFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_deletion_ffi(
    List<ArchiveDeletionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_edit_ffi(
    List<ArchiveEditFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_file_ffi(
    List<ArchiveFileFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_message_ffi(
    List<ArchiveMessageFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_pub_key_ffi(
    List<ArchivePubKeyFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_reaction_ffi(
    List<ArchiveReactionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_reaction_removal_ffi(
    List<ArchiveReactionRemovalFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bool(List<bool> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel_ffi(
    List<ChannelFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_channel_grant_ffi(
    List<ChannelGrantFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_conference_info(
    List<ConferenceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_label(
    List<DeviceLabel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_device_link(
    List<DeviceLink> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fetched_message(
    List<FetchedMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffz_emote(List<FfzEmote> self, SseSerializer serializer);

  @protected
  void sse_encode_list_friend_ffi(
    List<FriendFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_search_result(
    List<GameSearchResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gif_item(List<GifItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_guest_reaction_ffi(
    List<GuestReactionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_guest_sync_message_ffi(
    List<GuestSyncMessageFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hollowpack_file(
    List<HollowpackFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_kept_redeem_code(
    List<KeptRedeemCode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_label_ffi(List<LabelFfi> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_member_ffi(
    List<MemberFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_muted_member_ffi(
    List<MutedMemberFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_own_support_cred(
    List<OwnSupportCred> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_owned_art(List<OwnedArt> self, SseSerializer serializer);

  @protected
  void sse_encode_list_pending_join_ffi(
    List<PendingJoinFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_personal_emote(
    List<PersonalEmote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_personal_sticker(
    List<PersonalSticker> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_public_channel_entry_ffi(
    List<PublicChannelEntryFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_i_64(
    List<(String, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_security_alert_ffi(
    List<SecurityAlertFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_emote(
    List<ServerEmote> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_ffi(
    List<ServerFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_server_sticker(
    List<ServerSticker> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_setting_entry(
    List<SettingEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_share_entry(
    List<ShareEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_shop_file(List<ShopFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_shop_listing(
    List<ShopListing> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_showcase_asset(
    List<ShowcaseAsset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_storage_context_usage(
    List<StorageContextUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_channel_message(
    List<StoredChannelMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_file_info(
    List<StoredFileInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_message(
    List<StoredMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_message_edit(
    List<StoredMessageEdit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_stored_reaction(
    List<StoredReaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sync_sender_profile_ffi(
    List<SyncSenderProfileFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_profile(
    List<UserProfile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vault_file_status_ffi(
    List<VaultFileStatusFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_member_ffi(MemberFfi self, SseSerializer serializer);

  @protected
  void sse_encode_message_proof_v_2(
    MessageProofV2 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_muted_member_ffi(
    MutedMemberFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_network_event(NetworkEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_game_card_details(
    GameCardDetails? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_guest_file_meta_ffi(
    GuestFileMetaFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_hollowpack_import(
    HollowpackImport? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_link_preview_ref(
    LinkPreviewRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_network_event(
    NetworkEvent? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_push_channel_meta(
    PushChannelMeta? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_push_profile(
    PushProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_server_avatar_anim_data(
    ServerAvatarAnimData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_server_banner_data(
    ServerBannerData? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_stored_file_info(
    StoredFileInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_user_profile(
    UserProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_video_thumb_ref(
    VideoThumbRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_showcase_asset(
    List<ShowcaseAsset>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_own_support_cred(
    OwnSupportCred self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_owned_art(OwnedArt self, SseSerializer serializer);

  @protected
  void sse_encode_pending_join_ffi(
    PendingJoinFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_personal_emote(PersonalEmote self, SseSerializer serializer);

  @protected
  void sse_encode_personal_sticker(
    PersonalSticker self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_emote(
    ProcessedEmote self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_frame(
    ProcessedFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_profile_media(
    ProcessedProfileMedia self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_processed_sticker(
    ProcessedSticker self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_protection_status(
    ProtectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_public_channel_entry_ffi(
    PublicChannelEntryFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_push_channel_meta(
    PushChannelMeta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_push_profile(PushProfile self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_i_64(
    (String, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_redeem_lookup(RedeemLookup self, SseSerializer serializer);

  @protected
  void sse_encode_redeem_outcome(RedeemOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_security_alert_ffi(
    SecurityAlertFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_avatar_anim_data(
    ServerAvatarAnimData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_banner_data(
    ServerBannerData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_emote(ServerEmote self, SseSerializer serializer);

  @protected
  void sse_encode_server_ffi(ServerFfi self, SseSerializer serializer);

  @protected
  void sse_encode_server_sticker(ServerSticker self, SseSerializer serializer);

  @protected
  void sse_encode_setting_entry(SettingEntry self, SseSerializer serializer);

  @protected
  void sse_encode_shard_import_result_ffi(
    ShardImportResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_entry(ShareEntry self, SseSerializer serializer);

  @protected
  void sse_encode_share_link_info(ShareLinkInfo self, SseSerializer serializer);

  @protected
  void sse_encode_shop_artist(ShopArtist self, SseSerializer serializer);

  @protected
  void sse_encode_shop_catalog(ShopCatalog self, SseSerializer serializer);

  @protected
  void sse_encode_shop_file(ShopFile self, SseSerializer serializer);

  @protected
  void sse_encode_shop_listing(ShopListing self, SseSerializer serializer);

  @protected
  void sse_encode_showcase_asset(ShowcaseAsset self, SseSerializer serializer);

  @protected
  void sse_encode_sticker_pack_import_result(
    StickerPackImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sticker_pack_preview(
    StickerPackPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_breakdown(
    StorageBreakdown self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_context_usage(
    StorageContextUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_storage_stats_ffi(
    StorageStatsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_channel_message(
    StoredChannelMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_file_info(
    StoredFileInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_gif(StoredGif self, SseSerializer serializer);

  @protected
  void sse_encode_stored_message(StoredMessage self, SseSerializer serializer);

  @protected
  void sse_encode_stored_message_edit(
    StoredMessageEdit self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_stored_reaction(
    StoredReaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_sender_profile_ffi(
    SyncSenderProfileFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_twitch_device_flow_result(
    TwitchDeviceFlowResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_twitch_verify_outcome(
    TwitchVerifyOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_unread_mention_count(
    UnreadMentionCount self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vault_file_status_ffi(
    VaultFileStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_video_thumb_ref(VideoThumbRef self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
