// GENERATED from Unicode emoji-test.txt v16.0 (2026-07-10).
// Fully-qualified emojis only, skin-tone variants excluded (base emoji kept).

/// One Unicode emoji with its CLDR short name (lowercase, searchable).
class UnicodeEmoji {
  final String char;
  final String name;
  const UnicodeEmoji(this.char, this.name);
}

/// CLDR-ordered emoji, grouped by Unicode category.
const Map<String, List<UnicodeEmoji>> kUnicodeEmojiGroups = {
  'Smileys & Emotion': [
    UnicodeEmoji('😀', 'grinning face'),
    UnicodeEmoji('😃', 'grinning face with big eyes'),
    UnicodeEmoji('😄', 'grinning face with smiling eyes'),
    UnicodeEmoji('😁', 'beaming face with smiling eyes'),
    UnicodeEmoji('😆', 'grinning squinting face'),
    UnicodeEmoji('😅', 'grinning face with sweat'),
    UnicodeEmoji('🤣', 'rolling on the floor laughing'),
    UnicodeEmoji('😂', 'face with tears of joy'),
    UnicodeEmoji('🙂', 'slightly smiling face'),
    UnicodeEmoji('🙃', 'upside-down face'),
    UnicodeEmoji('🫠', 'melting face'),
    UnicodeEmoji('😉', 'winking face'),
    UnicodeEmoji('😊', 'smiling face with smiling eyes'),
    UnicodeEmoji('😇', 'smiling face with halo'),
    UnicodeEmoji('🥰', 'smiling face with hearts'),
    UnicodeEmoji('😍', 'smiling face with heart-eyes'),
    UnicodeEmoji('🤩', 'star-struck'),
    UnicodeEmoji('😘', 'face blowing a kiss'),
    UnicodeEmoji('😗', 'kissing face'),
    UnicodeEmoji('☺️', 'smiling face'),
    UnicodeEmoji('😚', 'kissing face with closed eyes'),
    UnicodeEmoji('😙', 'kissing face with smiling eyes'),
    UnicodeEmoji('🥲', 'smiling face with tear'),
    UnicodeEmoji('😋', 'face savoring food'),
    UnicodeEmoji('😛', 'face with tongue'),
    UnicodeEmoji('😜', 'winking face with tongue'),
    UnicodeEmoji('🤪', 'zany face'),
    UnicodeEmoji('😝', 'squinting face with tongue'),
    UnicodeEmoji('🤑', 'money-mouth face'),
    UnicodeEmoji('🤗', 'smiling face with open hands'),
    UnicodeEmoji('🤭', 'face with hand over mouth'),
    UnicodeEmoji('🫢', 'face with open eyes and hand over mouth'),
    UnicodeEmoji('🫣', 'face with peeking eye'),
    UnicodeEmoji('🤫', 'shushing face'),
    UnicodeEmoji('🤔', 'thinking face'),
    UnicodeEmoji('🫡', 'saluting face'),
    UnicodeEmoji('🤐', 'zipper-mouth face'),
    UnicodeEmoji('🤨', 'face with raised eyebrow'),
    UnicodeEmoji('😐', 'neutral face'),
    UnicodeEmoji('😑', 'expressionless face'),
    UnicodeEmoji('😶', 'face without mouth'),
    UnicodeEmoji('🫥', 'dotted line face'),
    UnicodeEmoji('😶‍🌫️', 'face in clouds'),
    UnicodeEmoji('😏', 'smirking face'),
    UnicodeEmoji('😒', 'unamused face'),
    UnicodeEmoji('🙄', 'face with rolling eyes'),
    UnicodeEmoji('😬', 'grimacing face'),
    UnicodeEmoji('😮‍💨', 'face exhaling'),
    UnicodeEmoji('🤥', 'lying face'),
    UnicodeEmoji('🫨', 'shaking face'),
    UnicodeEmoji('🙂‍↔️', 'head shaking horizontally'),
    UnicodeEmoji('🙂‍↕️', 'head shaking vertically'),
    UnicodeEmoji('😌', 'relieved face'),
    UnicodeEmoji('😔', 'pensive face'),
    UnicodeEmoji('😪', 'sleepy face'),
    UnicodeEmoji('🤤', 'drooling face'),
    UnicodeEmoji('😴', 'sleeping face'),
    UnicodeEmoji('🫩', 'face with bags under eyes'),
    UnicodeEmoji('😷', 'face with medical mask'),
    UnicodeEmoji('🤒', 'face with thermometer'),
    UnicodeEmoji('🤕', 'face with head-bandage'),
    UnicodeEmoji('🤢', 'nauseated face'),
    UnicodeEmoji('🤮', 'face vomiting'),
    UnicodeEmoji('🤧', 'sneezing face'),
    UnicodeEmoji('🥵', 'hot face'),
    UnicodeEmoji('🥶', 'cold face'),
    UnicodeEmoji('🥴', 'woozy face'),
    UnicodeEmoji('😵', 'face with crossed-out eyes'),
    UnicodeEmoji('😵‍💫', 'face with spiral eyes'),
    UnicodeEmoji('🤯', 'exploding head'),
    UnicodeEmoji('🤠', 'cowboy hat face'),
    UnicodeEmoji('🥳', 'partying face'),
    UnicodeEmoji('🥸', 'disguised face'),
    UnicodeEmoji('😎', 'smiling face with sunglasses'),
    UnicodeEmoji('🤓', 'nerd face'),
    UnicodeEmoji('🧐', 'face with monocle'),
    UnicodeEmoji('😕', 'confused face'),
    UnicodeEmoji('🫤', 'face with diagonal mouth'),
    UnicodeEmoji('😟', 'worried face'),
    UnicodeEmoji('🙁', 'slightly frowning face'),
    UnicodeEmoji('☹️', 'frowning face'),
    UnicodeEmoji('😮', 'face with open mouth'),
    UnicodeEmoji('😯', 'hushed face'),
    UnicodeEmoji('😲', 'astonished face'),
    UnicodeEmoji('😳', 'flushed face'),
    UnicodeEmoji('🥺', 'pleading face'),
    UnicodeEmoji('🥹', 'face holding back tears'),
    UnicodeEmoji('😦', 'frowning face with open mouth'),
    UnicodeEmoji('😧', 'anguished face'),
    UnicodeEmoji('😨', 'fearful face'),
    UnicodeEmoji('😰', 'anxious face with sweat'),
    UnicodeEmoji('😥', 'sad but relieved face'),
    UnicodeEmoji('😢', 'crying face'),
    UnicodeEmoji('😭', 'loudly crying face'),
    UnicodeEmoji('😱', 'face screaming in fear'),
    UnicodeEmoji('😖', 'confounded face'),
    UnicodeEmoji('😣', 'persevering face'),
    UnicodeEmoji('😞', 'disappointed face'),
    UnicodeEmoji('😓', 'downcast face with sweat'),
    UnicodeEmoji('😩', 'weary face'),
    UnicodeEmoji('😫', 'tired face'),
    UnicodeEmoji('🥱', 'yawning face'),
    UnicodeEmoji('😤', 'face with steam from nose'),
    UnicodeEmoji('😡', 'enraged face'),
    UnicodeEmoji('😠', 'angry face'),
    UnicodeEmoji('🤬', 'face with symbols on mouth'),
    UnicodeEmoji('😈', 'smiling face with horns'),
    UnicodeEmoji('👿', 'angry face with horns'),
    UnicodeEmoji('💀', 'skull'),
    UnicodeEmoji('☠️', 'skull and crossbones'),
    UnicodeEmoji('💩', 'pile of poo'),
    UnicodeEmoji('🤡', 'clown face'),
    UnicodeEmoji('👹', 'ogre'),
    UnicodeEmoji('👺', 'goblin'),
    UnicodeEmoji('👻', 'ghost'),
    UnicodeEmoji('👽', 'alien'),
    UnicodeEmoji('👾', 'alien monster'),
    UnicodeEmoji('🤖', 'robot'),
    UnicodeEmoji('😺', 'grinning cat'),
    UnicodeEmoji('😸', 'grinning cat with smiling eyes'),
    UnicodeEmoji('😹', 'cat with tears of joy'),
    UnicodeEmoji('😻', 'smiling cat with heart-eyes'),
    UnicodeEmoji('😼', 'cat with wry smile'),
    UnicodeEmoji('😽', 'kissing cat'),
    UnicodeEmoji('🙀', 'weary cat'),
    UnicodeEmoji('😿', 'crying cat'),
    UnicodeEmoji('😾', 'pouting cat'),
    UnicodeEmoji('🙈', 'see-no-evil monkey'),
    UnicodeEmoji('🙉', 'hear-no-evil monkey'),
    UnicodeEmoji('🙊', 'speak-no-evil monkey'),
    UnicodeEmoji('💌', 'love letter'),
    UnicodeEmoji('💘', 'heart with arrow'),
    UnicodeEmoji('💝', 'heart with ribbon'),
    UnicodeEmoji('💖', 'sparkling heart'),
    UnicodeEmoji('💗', 'growing heart'),
    UnicodeEmoji('💓', 'beating heart'),
    UnicodeEmoji('💞', 'revolving hearts'),
    UnicodeEmoji('💕', 'two hearts'),
    UnicodeEmoji('💟', 'heart decoration'),
    UnicodeEmoji('❣️', 'heart exclamation'),
    UnicodeEmoji('💔', 'broken heart'),
    UnicodeEmoji('❤️‍🔥', 'heart on fire'),
    UnicodeEmoji('❤️‍🩹', 'mending heart'),
    UnicodeEmoji('❤️', 'red heart'),
    UnicodeEmoji('🩷', 'pink heart'),
    UnicodeEmoji('🧡', 'orange heart'),
    UnicodeEmoji('💛', 'yellow heart'),
    UnicodeEmoji('💚', 'green heart'),
    UnicodeEmoji('💙', 'blue heart'),
    UnicodeEmoji('🩵', 'light blue heart'),
    UnicodeEmoji('💜', 'purple heart'),
    UnicodeEmoji('🤎', 'brown heart'),
    UnicodeEmoji('🖤', 'black heart'),
    UnicodeEmoji('🩶', 'grey heart'),
    UnicodeEmoji('🤍', 'white heart'),
    UnicodeEmoji('💋', 'kiss mark'),
    UnicodeEmoji('💯', 'hundred points'),
    UnicodeEmoji('💢', 'anger symbol'),
    UnicodeEmoji('💥', 'collision'),
    UnicodeEmoji('💫', 'dizzy'),
    UnicodeEmoji('💦', 'sweat droplets'),
    UnicodeEmoji('💨', 'dashing away'),
    UnicodeEmoji('🕳️', 'hole'),
    UnicodeEmoji('💬', 'speech balloon'),
    UnicodeEmoji('👁️‍🗨️', 'eye in speech bubble'),
    UnicodeEmoji('🗨️', 'left speech bubble'),
    UnicodeEmoji('🗯️', 'right anger bubble'),
    UnicodeEmoji('💭', 'thought balloon'),
    UnicodeEmoji('💤', 'zzz'),
  ],
  'People & Body': [
    UnicodeEmoji('👋', 'waving hand'),
    UnicodeEmoji('🤚', 'raised back of hand'),
    UnicodeEmoji('🖐️', 'hand with fingers splayed'),
    UnicodeEmoji('✋', 'raised hand'),
    UnicodeEmoji('🖖', 'vulcan salute'),
    UnicodeEmoji('🫱', 'rightwards hand'),
    UnicodeEmoji('🫲', 'leftwards hand'),
    UnicodeEmoji('🫳', 'palm down hand'),
    UnicodeEmoji('🫴', 'palm up hand'),
    UnicodeEmoji('🫷', 'leftwards pushing hand'),
    UnicodeEmoji('🫸', 'rightwards pushing hand'),
    UnicodeEmoji('👌', 'ok hand'),
    UnicodeEmoji('🤌', 'pinched fingers'),
    UnicodeEmoji('🤏', 'pinching hand'),
    UnicodeEmoji('✌️', 'victory hand'),
    UnicodeEmoji('🤞', 'crossed fingers'),
    UnicodeEmoji('🫰', 'hand with index finger and thumb crossed'),
    UnicodeEmoji('🤟', 'love-you gesture'),
    UnicodeEmoji('🤘', 'sign of the horns'),
    UnicodeEmoji('🤙', 'call me hand'),
    UnicodeEmoji('👈', 'backhand index pointing left'),
    UnicodeEmoji('👉', 'backhand index pointing right'),
    UnicodeEmoji('👆', 'backhand index pointing up'),
    UnicodeEmoji('🖕', 'middle finger'),
    UnicodeEmoji('👇', 'backhand index pointing down'),
    UnicodeEmoji('☝️', 'index pointing up'),
    UnicodeEmoji('🫵', 'index pointing at the viewer'),
    UnicodeEmoji('👍', 'thumbs up'),
    UnicodeEmoji('👎', 'thumbs down'),
    UnicodeEmoji('✊', 'raised fist'),
    UnicodeEmoji('👊', 'oncoming fist'),
    UnicodeEmoji('🤛', 'left-facing fist'),
    UnicodeEmoji('🤜', 'right-facing fist'),
    UnicodeEmoji('👏', 'clapping hands'),
    UnicodeEmoji('🙌', 'raising hands'),
    UnicodeEmoji('🫶', 'heart hands'),
    UnicodeEmoji('👐', 'open hands'),
    UnicodeEmoji('🤲', 'palms up together'),
    UnicodeEmoji('🤝', 'handshake'),
    UnicodeEmoji('🙏', 'folded hands'),
    UnicodeEmoji('✍️', 'writing hand'),
    UnicodeEmoji('💅', 'nail polish'),
    UnicodeEmoji('🤳', 'selfie'),
    UnicodeEmoji('💪', 'flexed biceps'),
    UnicodeEmoji('🦾', 'mechanical arm'),
    UnicodeEmoji('🦿', 'mechanical leg'),
    UnicodeEmoji('🦵', 'leg'),
    UnicodeEmoji('🦶', 'foot'),
    UnicodeEmoji('👂', 'ear'),
    UnicodeEmoji('🦻', 'ear with hearing aid'),
    UnicodeEmoji('👃', 'nose'),
    UnicodeEmoji('🧠', 'brain'),
    UnicodeEmoji('🫀', 'anatomical heart'),
    UnicodeEmoji('🫁', 'lungs'),
    UnicodeEmoji('🦷', 'tooth'),
    UnicodeEmoji('🦴', 'bone'),
    UnicodeEmoji('👀', 'eyes'),
    UnicodeEmoji('👁️', 'eye'),
    UnicodeEmoji('👅', 'tongue'),
    UnicodeEmoji('👄', 'mouth'),
    UnicodeEmoji('🫦', 'biting lip'),
    UnicodeEmoji('👶', 'baby'),
    UnicodeEmoji('🧒', 'child'),
    UnicodeEmoji('👦', 'boy'),
    UnicodeEmoji('👧', 'girl'),
    UnicodeEmoji('🧑', 'person'),
    UnicodeEmoji('👱', 'person: blond hair'),
    UnicodeEmoji('👨', 'man'),
    UnicodeEmoji('🧔', 'person: beard'),
    UnicodeEmoji('🧔‍♂️', 'man: beard'),
    UnicodeEmoji('🧔‍♀️', 'woman: beard'),
    UnicodeEmoji('👨‍🦰', 'man: red hair'),
    UnicodeEmoji('👨‍🦱', 'man: curly hair'),
    UnicodeEmoji('👨‍🦳', 'man: white hair'),
    UnicodeEmoji('👨‍🦲', 'man: bald'),
    UnicodeEmoji('👩', 'woman'),
    UnicodeEmoji('👩‍🦰', 'woman: red hair'),
    UnicodeEmoji('🧑‍🦰', 'person: red hair'),
    UnicodeEmoji('👩‍🦱', 'woman: curly hair'),
    UnicodeEmoji('🧑‍🦱', 'person: curly hair'),
    UnicodeEmoji('👩‍🦳', 'woman: white hair'),
    UnicodeEmoji('🧑‍🦳', 'person: white hair'),
    UnicodeEmoji('👩‍🦲', 'woman: bald'),
    UnicodeEmoji('🧑‍🦲', 'person: bald'),
    UnicodeEmoji('👱‍♀️', 'woman: blond hair'),
    UnicodeEmoji('👱‍♂️', 'man: blond hair'),
    UnicodeEmoji('🧓', 'older person'),
    UnicodeEmoji('👴', 'old man'),
    UnicodeEmoji('👵', 'old woman'),
    UnicodeEmoji('🙍', 'person frowning'),
    UnicodeEmoji('🙍‍♂️', 'man frowning'),
    UnicodeEmoji('🙍‍♀️', 'woman frowning'),
    UnicodeEmoji('🙎', 'person pouting'),
    UnicodeEmoji('🙎‍♂️', 'man pouting'),
    UnicodeEmoji('🙎‍♀️', 'woman pouting'),
    UnicodeEmoji('🙅', 'person gesturing no'),
    UnicodeEmoji('🙅‍♂️', 'man gesturing no'),
    UnicodeEmoji('🙅‍♀️', 'woman gesturing no'),
    UnicodeEmoji('🙆', 'person gesturing ok'),
    UnicodeEmoji('🙆‍♂️', 'man gesturing ok'),
    UnicodeEmoji('🙆‍♀️', 'woman gesturing ok'),
    UnicodeEmoji('💁', 'person tipping hand'),
    UnicodeEmoji('💁‍♂️', 'man tipping hand'),
    UnicodeEmoji('💁‍♀️', 'woman tipping hand'),
    UnicodeEmoji('🙋', 'person raising hand'),
    UnicodeEmoji('🙋‍♂️', 'man raising hand'),
    UnicodeEmoji('🙋‍♀️', 'woman raising hand'),
    UnicodeEmoji('🧏', 'deaf person'),
    UnicodeEmoji('🧏‍♂️', 'deaf man'),
    UnicodeEmoji('🧏‍♀️', 'deaf woman'),
    UnicodeEmoji('🙇', 'person bowing'),
    UnicodeEmoji('🙇‍♂️', 'man bowing'),
    UnicodeEmoji('🙇‍♀️', 'woman bowing'),
    UnicodeEmoji('🤦', 'person facepalming'),
    UnicodeEmoji('🤦‍♂️', 'man facepalming'),
    UnicodeEmoji('🤦‍♀️', 'woman facepalming'),
    UnicodeEmoji('🤷', 'person shrugging'),
    UnicodeEmoji('🤷‍♂️', 'man shrugging'),
    UnicodeEmoji('🤷‍♀️', 'woman shrugging'),
    UnicodeEmoji('🧑‍⚕️', 'health worker'),
    UnicodeEmoji('👨‍⚕️', 'man health worker'),
    UnicodeEmoji('👩‍⚕️', 'woman health worker'),
    UnicodeEmoji('🧑‍🎓', 'student'),
    UnicodeEmoji('👨‍🎓', 'man student'),
    UnicodeEmoji('👩‍🎓', 'woman student'),
    UnicodeEmoji('🧑‍🏫', 'teacher'),
    UnicodeEmoji('👨‍🏫', 'man teacher'),
    UnicodeEmoji('👩‍🏫', 'woman teacher'),
    UnicodeEmoji('🧑‍⚖️', 'judge'),
    UnicodeEmoji('👨‍⚖️', 'man judge'),
    UnicodeEmoji('👩‍⚖️', 'woman judge'),
    UnicodeEmoji('🧑‍🌾', 'farmer'),
    UnicodeEmoji('👨‍🌾', 'man farmer'),
    UnicodeEmoji('👩‍🌾', 'woman farmer'),
    UnicodeEmoji('🧑‍🍳', 'cook'),
    UnicodeEmoji('👨‍🍳', 'man cook'),
    UnicodeEmoji('👩‍🍳', 'woman cook'),
    UnicodeEmoji('🧑‍🔧', 'mechanic'),
    UnicodeEmoji('👨‍🔧', 'man mechanic'),
    UnicodeEmoji('👩‍🔧', 'woman mechanic'),
    UnicodeEmoji('🧑‍🏭', 'factory worker'),
    UnicodeEmoji('👨‍🏭', 'man factory worker'),
    UnicodeEmoji('👩‍🏭', 'woman factory worker'),
    UnicodeEmoji('🧑‍💼', 'office worker'),
    UnicodeEmoji('👨‍💼', 'man office worker'),
    UnicodeEmoji('👩‍💼', 'woman office worker'),
    UnicodeEmoji('🧑‍🔬', 'scientist'),
    UnicodeEmoji('👨‍🔬', 'man scientist'),
    UnicodeEmoji('👩‍🔬', 'woman scientist'),
    UnicodeEmoji('🧑‍💻', 'technologist'),
    UnicodeEmoji('👨‍💻', 'man technologist'),
    UnicodeEmoji('👩‍💻', 'woman technologist'),
    UnicodeEmoji('🧑‍🎤', 'singer'),
    UnicodeEmoji('👨‍🎤', 'man singer'),
    UnicodeEmoji('👩‍🎤', 'woman singer'),
    UnicodeEmoji('🧑‍🎨', 'artist'),
    UnicodeEmoji('👨‍🎨', 'man artist'),
    UnicodeEmoji('👩‍🎨', 'woman artist'),
    UnicodeEmoji('🧑‍✈️', 'pilot'),
    UnicodeEmoji('👨‍✈️', 'man pilot'),
    UnicodeEmoji('👩‍✈️', 'woman pilot'),
    UnicodeEmoji('🧑‍🚀', 'astronaut'),
    UnicodeEmoji('👨‍🚀', 'man astronaut'),
    UnicodeEmoji('👩‍🚀', 'woman astronaut'),
    UnicodeEmoji('🧑‍🚒', 'firefighter'),
    UnicodeEmoji('👨‍🚒', 'man firefighter'),
    UnicodeEmoji('👩‍🚒', 'woman firefighter'),
    UnicodeEmoji('👮', 'police officer'),
    UnicodeEmoji('👮‍♂️', 'man police officer'),
    UnicodeEmoji('👮‍♀️', 'woman police officer'),
    UnicodeEmoji('🕵️', 'detective'),
    UnicodeEmoji('🕵️‍♂️', 'man detective'),
    UnicodeEmoji('🕵️‍♀️', 'woman detective'),
    UnicodeEmoji('💂', 'guard'),
    UnicodeEmoji('💂‍♂️', 'man guard'),
    UnicodeEmoji('💂‍♀️', 'woman guard'),
    UnicodeEmoji('🥷', 'ninja'),
    UnicodeEmoji('👷', 'construction worker'),
    UnicodeEmoji('👷‍♂️', 'man construction worker'),
    UnicodeEmoji('👷‍♀️', 'woman construction worker'),
    UnicodeEmoji('🫅', 'person with crown'),
    UnicodeEmoji('🤴', 'prince'),
    UnicodeEmoji('👸', 'princess'),
    UnicodeEmoji('👳', 'person wearing turban'),
    UnicodeEmoji('👳‍♂️', 'man wearing turban'),
    UnicodeEmoji('👳‍♀️', 'woman wearing turban'),
    UnicodeEmoji('👲', 'person with skullcap'),
    UnicodeEmoji('🧕', 'woman with headscarf'),
    UnicodeEmoji('🤵', 'person in tuxedo'),
    UnicodeEmoji('🤵‍♂️', 'man in tuxedo'),
    UnicodeEmoji('🤵‍♀️', 'woman in tuxedo'),
    UnicodeEmoji('👰', 'person with veil'),
    UnicodeEmoji('👰‍♂️', 'man with veil'),
    UnicodeEmoji('👰‍♀️', 'woman with veil'),
    UnicodeEmoji('🤰', 'pregnant woman'),
    UnicodeEmoji('🫃', 'pregnant man'),
    UnicodeEmoji('🫄', 'pregnant person'),
    UnicodeEmoji('🤱', 'breast-feeding'),
    UnicodeEmoji('👩‍🍼', 'woman feeding baby'),
    UnicodeEmoji('👨‍🍼', 'man feeding baby'),
    UnicodeEmoji('🧑‍🍼', 'person feeding baby'),
    UnicodeEmoji('👼', 'baby angel'),
    UnicodeEmoji('🎅', 'santa claus'),
    UnicodeEmoji('🤶', 'mrs. claus'),
    UnicodeEmoji('🧑‍🎄', 'mx claus'),
    UnicodeEmoji('🦸', 'superhero'),
    UnicodeEmoji('🦸‍♂️', 'man superhero'),
    UnicodeEmoji('🦸‍♀️', 'woman superhero'),
    UnicodeEmoji('🦹', 'supervillain'),
    UnicodeEmoji('🦹‍♂️', 'man supervillain'),
    UnicodeEmoji('🦹‍♀️', 'woman supervillain'),
    UnicodeEmoji('🧙', 'mage'),
    UnicodeEmoji('🧙‍♂️', 'man mage'),
    UnicodeEmoji('🧙‍♀️', 'woman mage'),
    UnicodeEmoji('🧚', 'fairy'),
    UnicodeEmoji('🧚‍♂️', 'man fairy'),
    UnicodeEmoji('🧚‍♀️', 'woman fairy'),
    UnicodeEmoji('🧛', 'vampire'),
    UnicodeEmoji('🧛‍♂️', 'man vampire'),
    UnicodeEmoji('🧛‍♀️', 'woman vampire'),
    UnicodeEmoji('🧜', 'merperson'),
    UnicodeEmoji('🧜‍♂️', 'merman'),
    UnicodeEmoji('🧜‍♀️', 'mermaid'),
    UnicodeEmoji('🧝', 'elf'),
    UnicodeEmoji('🧝‍♂️', 'man elf'),
    UnicodeEmoji('🧝‍♀️', 'woman elf'),
    UnicodeEmoji('🧞', 'genie'),
    UnicodeEmoji('🧞‍♂️', 'man genie'),
    UnicodeEmoji('🧞‍♀️', 'woman genie'),
    UnicodeEmoji('🧟', 'zombie'),
    UnicodeEmoji('🧟‍♂️', 'man zombie'),
    UnicodeEmoji('🧟‍♀️', 'woman zombie'),
    UnicodeEmoji('🧌', 'troll'),
    UnicodeEmoji('💆', 'person getting massage'),
    UnicodeEmoji('💆‍♂️', 'man getting massage'),
    UnicodeEmoji('💆‍♀️', 'woman getting massage'),
    UnicodeEmoji('💇', 'person getting haircut'),
    UnicodeEmoji('💇‍♂️', 'man getting haircut'),
    UnicodeEmoji('💇‍♀️', 'woman getting haircut'),
    UnicodeEmoji('🚶', 'person walking'),
    UnicodeEmoji('🚶‍♂️', 'man walking'),
    UnicodeEmoji('🚶‍♀️', 'woman walking'),
    UnicodeEmoji('🚶‍➡️', 'person walking facing right'),
    UnicodeEmoji('🚶‍♀️‍➡️', 'woman walking facing right'),
    UnicodeEmoji('🚶‍♂️‍➡️', 'man walking facing right'),
    UnicodeEmoji('🧍', 'person standing'),
    UnicodeEmoji('🧍‍♂️', 'man standing'),
    UnicodeEmoji('🧍‍♀️', 'woman standing'),
    UnicodeEmoji('🧎', 'person kneeling'),
    UnicodeEmoji('🧎‍♂️', 'man kneeling'),
    UnicodeEmoji('🧎‍♀️', 'woman kneeling'),
    UnicodeEmoji('🧎‍➡️', 'person kneeling facing right'),
    UnicodeEmoji('🧎‍♀️‍➡️', 'woman kneeling facing right'),
    UnicodeEmoji('🧎‍♂️‍➡️', 'man kneeling facing right'),
    UnicodeEmoji('🧑‍🦯', 'person with white cane'),
    UnicodeEmoji('🧑‍🦯‍➡️', 'person with white cane facing right'),
    UnicodeEmoji('👨‍🦯', 'man with white cane'),
    UnicodeEmoji('👨‍🦯‍➡️', 'man with white cane facing right'),
    UnicodeEmoji('👩‍🦯', 'woman with white cane'),
    UnicodeEmoji('👩‍🦯‍➡️', 'woman with white cane facing right'),
    UnicodeEmoji('🧑‍🦼', 'person in motorized wheelchair'),
    UnicodeEmoji('🧑‍🦼‍➡️', 'person in motorized wheelchair facing right'),
    UnicodeEmoji('👨‍🦼', 'man in motorized wheelchair'),
    UnicodeEmoji('👨‍🦼‍➡️', 'man in motorized wheelchair facing right'),
    UnicodeEmoji('👩‍🦼', 'woman in motorized wheelchair'),
    UnicodeEmoji('👩‍🦼‍➡️', 'woman in motorized wheelchair facing right'),
    UnicodeEmoji('🧑‍🦽', 'person in manual wheelchair'),
    UnicodeEmoji('🧑‍🦽‍➡️', 'person in manual wheelchair facing right'),
    UnicodeEmoji('👨‍🦽', 'man in manual wheelchair'),
    UnicodeEmoji('👨‍🦽‍➡️', 'man in manual wheelchair facing right'),
    UnicodeEmoji('👩‍🦽', 'woman in manual wheelchair'),
    UnicodeEmoji('👩‍🦽‍➡️', 'woman in manual wheelchair facing right'),
    UnicodeEmoji('🏃', 'person running'),
    UnicodeEmoji('🏃‍♂️', 'man running'),
    UnicodeEmoji('🏃‍♀️', 'woman running'),
    UnicodeEmoji('🏃‍➡️', 'person running facing right'),
    UnicodeEmoji('🏃‍♀️‍➡️', 'woman running facing right'),
    UnicodeEmoji('🏃‍♂️‍➡️', 'man running facing right'),
    UnicodeEmoji('💃', 'woman dancing'),
    UnicodeEmoji('🕺', 'man dancing'),
    UnicodeEmoji('🕴️', 'person in suit levitating'),
    UnicodeEmoji('👯', 'people with bunny ears'),
    UnicodeEmoji('👯‍♂️', 'men with bunny ears'),
    UnicodeEmoji('👯‍♀️', 'women with bunny ears'),
    UnicodeEmoji('🧖', 'person in steamy room'),
    UnicodeEmoji('🧖‍♂️', 'man in steamy room'),
    UnicodeEmoji('🧖‍♀️', 'woman in steamy room'),
    UnicodeEmoji('🧗', 'person climbing'),
    UnicodeEmoji('🧗‍♂️', 'man climbing'),
    UnicodeEmoji('🧗‍♀️', 'woman climbing'),
    UnicodeEmoji('🤺', 'person fencing'),
    UnicodeEmoji('🏇', 'horse racing'),
    UnicodeEmoji('⛷️', 'skier'),
    UnicodeEmoji('🏂', 'snowboarder'),
    UnicodeEmoji('🏌️', 'person golfing'),
    UnicodeEmoji('🏌️‍♂️', 'man golfing'),
    UnicodeEmoji('🏌️‍♀️', 'woman golfing'),
    UnicodeEmoji('🏄', 'person surfing'),
    UnicodeEmoji('🏄‍♂️', 'man surfing'),
    UnicodeEmoji('🏄‍♀️', 'woman surfing'),
    UnicodeEmoji('🚣', 'person rowing boat'),
    UnicodeEmoji('🚣‍♂️', 'man rowing boat'),
    UnicodeEmoji('🚣‍♀️', 'woman rowing boat'),
    UnicodeEmoji('🏊', 'person swimming'),
    UnicodeEmoji('🏊‍♂️', 'man swimming'),
    UnicodeEmoji('🏊‍♀️', 'woman swimming'),
    UnicodeEmoji('⛹️', 'person bouncing ball'),
    UnicodeEmoji('⛹️‍♂️', 'man bouncing ball'),
    UnicodeEmoji('⛹️‍♀️', 'woman bouncing ball'),
    UnicodeEmoji('🏋️', 'person lifting weights'),
    UnicodeEmoji('🏋️‍♂️', 'man lifting weights'),
    UnicodeEmoji('🏋️‍♀️', 'woman lifting weights'),
    UnicodeEmoji('🚴', 'person biking'),
    UnicodeEmoji('🚴‍♂️', 'man biking'),
    UnicodeEmoji('🚴‍♀️', 'woman biking'),
    UnicodeEmoji('🚵', 'person mountain biking'),
    UnicodeEmoji('🚵‍♂️', 'man mountain biking'),
    UnicodeEmoji('🚵‍♀️', 'woman mountain biking'),
    UnicodeEmoji('🤸', 'person cartwheeling'),
    UnicodeEmoji('🤸‍♂️', 'man cartwheeling'),
    UnicodeEmoji('🤸‍♀️', 'woman cartwheeling'),
    UnicodeEmoji('🤼', 'people wrestling'),
    UnicodeEmoji('🤼‍♂️', 'men wrestling'),
    UnicodeEmoji('🤼‍♀️', 'women wrestling'),
    UnicodeEmoji('🤽', 'person playing water polo'),
    UnicodeEmoji('🤽‍♂️', 'man playing water polo'),
    UnicodeEmoji('🤽‍♀️', 'woman playing water polo'),
    UnicodeEmoji('🤾', 'person playing handball'),
    UnicodeEmoji('🤾‍♂️', 'man playing handball'),
    UnicodeEmoji('🤾‍♀️', 'woman playing handball'),
    UnicodeEmoji('🤹', 'person juggling'),
    UnicodeEmoji('🤹‍♂️', 'man juggling'),
    UnicodeEmoji('🤹‍♀️', 'woman juggling'),
    UnicodeEmoji('🧘', 'person in lotus position'),
    UnicodeEmoji('🧘‍♂️', 'man in lotus position'),
    UnicodeEmoji('🧘‍♀️', 'woman in lotus position'),
    UnicodeEmoji('🛀', 'person taking bath'),
    UnicodeEmoji('🛌', 'person in bed'),
    UnicodeEmoji('🧑‍🤝‍🧑', 'people holding hands'),
    UnicodeEmoji('👭', 'women holding hands'),
    UnicodeEmoji('👫', 'woman and man holding hands'),
    UnicodeEmoji('👬', 'men holding hands'),
    UnicodeEmoji('💏', 'kiss'),
    UnicodeEmoji('👩‍❤️‍💋‍👨', 'kiss: woman, man'),
    UnicodeEmoji('👨‍❤️‍💋‍👨', 'kiss: man, man'),
    UnicodeEmoji('👩‍❤️‍💋‍👩', 'kiss: woman, woman'),
    UnicodeEmoji('💑', 'couple with heart'),
    UnicodeEmoji('👩‍❤️‍👨', 'couple with heart: woman, man'),
    UnicodeEmoji('👨‍❤️‍👨', 'couple with heart: man, man'),
    UnicodeEmoji('👩‍❤️‍👩', 'couple with heart: woman, woman'),
    UnicodeEmoji('👨‍👩‍👦', 'family: man, woman, boy'),
    UnicodeEmoji('👨‍👩‍👧', 'family: man, woman, girl'),
    UnicodeEmoji('👨‍👩‍👧‍👦', 'family: man, woman, girl, boy'),
    UnicodeEmoji('👨‍👩‍👦‍👦', 'family: man, woman, boy, boy'),
    UnicodeEmoji('👨‍👩‍👧‍👧', 'family: man, woman, girl, girl'),
    UnicodeEmoji('👨‍👨‍👦', 'family: man, man, boy'),
    UnicodeEmoji('👨‍👨‍👧', 'family: man, man, girl'),
    UnicodeEmoji('👨‍👨‍👧‍👦', 'family: man, man, girl, boy'),
    UnicodeEmoji('👨‍👨‍👦‍👦', 'family: man, man, boy, boy'),
    UnicodeEmoji('👨‍👨‍👧‍👧', 'family: man, man, girl, girl'),
    UnicodeEmoji('👩‍👩‍👦', 'family: woman, woman, boy'),
    UnicodeEmoji('👩‍👩‍👧', 'family: woman, woman, girl'),
    UnicodeEmoji('👩‍👩‍👧‍👦', 'family: woman, woman, girl, boy'),
    UnicodeEmoji('👩‍👩‍👦‍👦', 'family: woman, woman, boy, boy'),
    UnicodeEmoji('👩‍👩‍👧‍👧', 'family: woman, woman, girl, girl'),
    UnicodeEmoji('👨‍👦', 'family: man, boy'),
    UnicodeEmoji('👨‍👦‍👦', 'family: man, boy, boy'),
    UnicodeEmoji('👨‍👧', 'family: man, girl'),
    UnicodeEmoji('👨‍👧‍👦', 'family: man, girl, boy'),
    UnicodeEmoji('👨‍👧‍👧', 'family: man, girl, girl'),
    UnicodeEmoji('👩‍👦', 'family: woman, boy'),
    UnicodeEmoji('👩‍👦‍👦', 'family: woman, boy, boy'),
    UnicodeEmoji('👩‍👧', 'family: woman, girl'),
    UnicodeEmoji('👩‍👧‍👦', 'family: woman, girl, boy'),
    UnicodeEmoji('👩‍👧‍👧', 'family: woman, girl, girl'),
    UnicodeEmoji('🗣️', 'speaking head'),
    UnicodeEmoji('👤', 'bust in silhouette'),
    UnicodeEmoji('👥', 'busts in silhouette'),
    UnicodeEmoji('🫂', 'people hugging'),
    UnicodeEmoji('👪', 'family'),
    UnicodeEmoji('🧑‍🧑‍🧒', 'family: adult, adult, child'),
    UnicodeEmoji('🧑‍🧑‍🧒‍🧒', 'family: adult, adult, child, child'),
    UnicodeEmoji('🧑‍🧒', 'family: adult, child'),
    UnicodeEmoji('🧑‍🧒‍🧒', 'family: adult, child, child'),
    UnicodeEmoji('👣', 'footprints'),
    UnicodeEmoji('🫆', 'fingerprint'),
  ],
  'Animals & Nature': [
    UnicodeEmoji('🐵', 'monkey face'),
    UnicodeEmoji('🐒', 'monkey'),
    UnicodeEmoji('🦍', 'gorilla'),
    UnicodeEmoji('🦧', 'orangutan'),
    UnicodeEmoji('🐶', 'dog face'),
    UnicodeEmoji('🐕', 'dog'),
    UnicodeEmoji('🦮', 'guide dog'),
    UnicodeEmoji('🐕‍🦺', 'service dog'),
    UnicodeEmoji('🐩', 'poodle'),
    UnicodeEmoji('🐺', 'wolf'),
    UnicodeEmoji('🦊', 'fox'),
    UnicodeEmoji('🦝', 'raccoon'),
    UnicodeEmoji('🐱', 'cat face'),
    UnicodeEmoji('🐈', 'cat'),
    UnicodeEmoji('🐈‍⬛', 'black cat'),
    UnicodeEmoji('🦁', 'lion'),
    UnicodeEmoji('🐯', 'tiger face'),
    UnicodeEmoji('🐅', 'tiger'),
    UnicodeEmoji('🐆', 'leopard'),
    UnicodeEmoji('🐴', 'horse face'),
    UnicodeEmoji('🫎', 'moose'),
    UnicodeEmoji('🫏', 'donkey'),
    UnicodeEmoji('🐎', 'horse'),
    UnicodeEmoji('🦄', 'unicorn'),
    UnicodeEmoji('🦓', 'zebra'),
    UnicodeEmoji('🦌', 'deer'),
    UnicodeEmoji('🦬', 'bison'),
    UnicodeEmoji('🐮', 'cow face'),
    UnicodeEmoji('🐂', 'ox'),
    UnicodeEmoji('🐃', 'water buffalo'),
    UnicodeEmoji('🐄', 'cow'),
    UnicodeEmoji('🐷', 'pig face'),
    UnicodeEmoji('🐖', 'pig'),
    UnicodeEmoji('🐗', 'boar'),
    UnicodeEmoji('🐽', 'pig nose'),
    UnicodeEmoji('🐏', 'ram'),
    UnicodeEmoji('🐑', 'ewe'),
    UnicodeEmoji('🐐', 'goat'),
    UnicodeEmoji('🐪', 'camel'),
    UnicodeEmoji('🐫', 'two-hump camel'),
    UnicodeEmoji('🦙', 'llama'),
    UnicodeEmoji('🦒', 'giraffe'),
    UnicodeEmoji('🐘', 'elephant'),
    UnicodeEmoji('🦣', 'mammoth'),
    UnicodeEmoji('🦏', 'rhinoceros'),
    UnicodeEmoji('🦛', 'hippopotamus'),
    UnicodeEmoji('🐭', 'mouse face'),
    UnicodeEmoji('🐁', 'mouse'),
    UnicodeEmoji('🐀', 'rat'),
    UnicodeEmoji('🐹', 'hamster'),
    UnicodeEmoji('🐰', 'rabbit face'),
    UnicodeEmoji('🐇', 'rabbit'),
    UnicodeEmoji('🐿️', 'chipmunk'),
    UnicodeEmoji('🦫', 'beaver'),
    UnicodeEmoji('🦔', 'hedgehog'),
    UnicodeEmoji('🦇', 'bat'),
    UnicodeEmoji('🐻', 'bear'),
    UnicodeEmoji('🐻‍❄️', 'polar bear'),
    UnicodeEmoji('🐨', 'koala'),
    UnicodeEmoji('🐼', 'panda'),
    UnicodeEmoji('🦥', 'sloth'),
    UnicodeEmoji('🦦', 'otter'),
    UnicodeEmoji('🦨', 'skunk'),
    UnicodeEmoji('🦘', 'kangaroo'),
    UnicodeEmoji('🦡', 'badger'),
    UnicodeEmoji('🐾', 'paw prints'),
    UnicodeEmoji('🦃', 'turkey'),
    UnicodeEmoji('🐔', 'chicken'),
    UnicodeEmoji('🐓', 'rooster'),
    UnicodeEmoji('🐣', 'hatching chick'),
    UnicodeEmoji('🐤', 'baby chick'),
    UnicodeEmoji('🐥', 'front-facing baby chick'),
    UnicodeEmoji('🐦', 'bird'),
    UnicodeEmoji('🐧', 'penguin'),
    UnicodeEmoji('🕊️', 'dove'),
    UnicodeEmoji('🦅', 'eagle'),
    UnicodeEmoji('🦆', 'duck'),
    UnicodeEmoji('🦢', 'swan'),
    UnicodeEmoji('🦉', 'owl'),
    UnicodeEmoji('🦤', 'dodo'),
    UnicodeEmoji('🪶', 'feather'),
    UnicodeEmoji('🦩', 'flamingo'),
    UnicodeEmoji('🦚', 'peacock'),
    UnicodeEmoji('🦜', 'parrot'),
    UnicodeEmoji('🪽', 'wing'),
    UnicodeEmoji('🐦‍⬛', 'black bird'),
    UnicodeEmoji('🪿', 'goose'),
    UnicodeEmoji('🐦‍🔥', 'phoenix'),
    UnicodeEmoji('🐸', 'frog'),
    UnicodeEmoji('🐊', 'crocodile'),
    UnicodeEmoji('🐢', 'turtle'),
    UnicodeEmoji('🦎', 'lizard'),
    UnicodeEmoji('🐍', 'snake'),
    UnicodeEmoji('🐲', 'dragon face'),
    UnicodeEmoji('🐉', 'dragon'),
    UnicodeEmoji('🦕', 'sauropod'),
    UnicodeEmoji('🦖', 't-rex'),
    UnicodeEmoji('🐳', 'spouting whale'),
    UnicodeEmoji('🐋', 'whale'),
    UnicodeEmoji('🐬', 'dolphin'),
    UnicodeEmoji('🦭', 'seal'),
    UnicodeEmoji('🐟', 'fish'),
    UnicodeEmoji('🐠', 'tropical fish'),
    UnicodeEmoji('🐡', 'blowfish'),
    UnicodeEmoji('🦈', 'shark'),
    UnicodeEmoji('🐙', 'octopus'),
    UnicodeEmoji('🐚', 'spiral shell'),
    UnicodeEmoji('🪸', 'coral'),
    UnicodeEmoji('🪼', 'jellyfish'),
    UnicodeEmoji('🦀', 'crab'),
    UnicodeEmoji('🦞', 'lobster'),
    UnicodeEmoji('🦐', 'shrimp'),
    UnicodeEmoji('🦑', 'squid'),
    UnicodeEmoji('🦪', 'oyster'),
    UnicodeEmoji('🐌', 'snail'),
    UnicodeEmoji('🦋', 'butterfly'),
    UnicodeEmoji('🐛', 'bug'),
    UnicodeEmoji('🐜', 'ant'),
    UnicodeEmoji('🐝', 'honeybee'),
    UnicodeEmoji('🪲', 'beetle'),
    UnicodeEmoji('🐞', 'lady beetle'),
    UnicodeEmoji('🦗', 'cricket'),
    UnicodeEmoji('🪳', 'cockroach'),
    UnicodeEmoji('🕷️', 'spider'),
    UnicodeEmoji('🕸️', 'spider web'),
    UnicodeEmoji('🦂', 'scorpion'),
    UnicodeEmoji('🦟', 'mosquito'),
    UnicodeEmoji('🪰', 'fly'),
    UnicodeEmoji('🪱', 'worm'),
    UnicodeEmoji('🦠', 'microbe'),
    UnicodeEmoji('💐', 'bouquet'),
    UnicodeEmoji('🌸', 'cherry blossom'),
    UnicodeEmoji('💮', 'white flower'),
    UnicodeEmoji('🪷', 'lotus'),
    UnicodeEmoji('🏵️', 'rosette'),
    UnicodeEmoji('🌹', 'rose'),
    UnicodeEmoji('🥀', 'wilted flower'),
    UnicodeEmoji('🌺', 'hibiscus'),
    UnicodeEmoji('🌻', 'sunflower'),
    UnicodeEmoji('🌼', 'blossom'),
    UnicodeEmoji('🌷', 'tulip'),
    UnicodeEmoji('🪻', 'hyacinth'),
    UnicodeEmoji('🌱', 'seedling'),
    UnicodeEmoji('🪴', 'potted plant'),
    UnicodeEmoji('🌲', 'evergreen tree'),
    UnicodeEmoji('🌳', 'deciduous tree'),
    UnicodeEmoji('🌴', 'palm tree'),
    UnicodeEmoji('🌵', 'cactus'),
    UnicodeEmoji('🌾', 'sheaf of rice'),
    UnicodeEmoji('🌿', 'herb'),
    UnicodeEmoji('☘️', 'shamrock'),
    UnicodeEmoji('🍀', 'four leaf clover'),
    UnicodeEmoji('🍁', 'maple leaf'),
    UnicodeEmoji('🍂', 'fallen leaf'),
    UnicodeEmoji('🍃', 'leaf fluttering in wind'),
    UnicodeEmoji('🪹', 'empty nest'),
    UnicodeEmoji('🪺', 'nest with eggs'),
    UnicodeEmoji('🍄', 'mushroom'),
    UnicodeEmoji('🪾', 'leafless tree'),
  ],
  'Food & Drink': [
    UnicodeEmoji('🍇', 'grapes'),
    UnicodeEmoji('🍈', 'melon'),
    UnicodeEmoji('🍉', 'watermelon'),
    UnicodeEmoji('🍊', 'tangerine'),
    UnicodeEmoji('🍋', 'lemon'),
    UnicodeEmoji('🍋‍🟩', 'lime'),
    UnicodeEmoji('🍌', 'banana'),
    UnicodeEmoji('🍍', 'pineapple'),
    UnicodeEmoji('🥭', 'mango'),
    UnicodeEmoji('🍎', 'red apple'),
    UnicodeEmoji('🍏', 'green apple'),
    UnicodeEmoji('🍐', 'pear'),
    UnicodeEmoji('🍑', 'peach'),
    UnicodeEmoji('🍒', 'cherries'),
    UnicodeEmoji('🍓', 'strawberry'),
    UnicodeEmoji('🫐', 'blueberries'),
    UnicodeEmoji('🥝', 'kiwi fruit'),
    UnicodeEmoji('🍅', 'tomato'),
    UnicodeEmoji('🫒', 'olive'),
    UnicodeEmoji('🥥', 'coconut'),
    UnicodeEmoji('🥑', 'avocado'),
    UnicodeEmoji('🍆', 'eggplant'),
    UnicodeEmoji('🥔', 'potato'),
    UnicodeEmoji('🥕', 'carrot'),
    UnicodeEmoji('🌽', 'ear of corn'),
    UnicodeEmoji('🌶️', 'hot pepper'),
    UnicodeEmoji('🫑', 'bell pepper'),
    UnicodeEmoji('🥒', 'cucumber'),
    UnicodeEmoji('🥬', 'leafy green'),
    UnicodeEmoji('🥦', 'broccoli'),
    UnicodeEmoji('🧄', 'garlic'),
    UnicodeEmoji('🧅', 'onion'),
    UnicodeEmoji('🥜', 'peanuts'),
    UnicodeEmoji('🫘', 'beans'),
    UnicodeEmoji('🌰', 'chestnut'),
    UnicodeEmoji('🫚', 'ginger root'),
    UnicodeEmoji('🫛', 'pea pod'),
    UnicodeEmoji('🍄‍🟫', 'brown mushroom'),
    UnicodeEmoji('🫜', 'root vegetable'),
    UnicodeEmoji('🍞', 'bread'),
    UnicodeEmoji('🥐', 'croissant'),
    UnicodeEmoji('🥖', 'baguette bread'),
    UnicodeEmoji('🫓', 'flatbread'),
    UnicodeEmoji('🥨', 'pretzel'),
    UnicodeEmoji('🥯', 'bagel'),
    UnicodeEmoji('🥞', 'pancakes'),
    UnicodeEmoji('🧇', 'waffle'),
    UnicodeEmoji('🧀', 'cheese wedge'),
    UnicodeEmoji('🍖', 'meat on bone'),
    UnicodeEmoji('🍗', 'poultry leg'),
    UnicodeEmoji('🥩', 'cut of meat'),
    UnicodeEmoji('🥓', 'bacon'),
    UnicodeEmoji('🍔', 'hamburger'),
    UnicodeEmoji('🍟', 'french fries'),
    UnicodeEmoji('🍕', 'pizza'),
    UnicodeEmoji('🌭', 'hot dog'),
    UnicodeEmoji('🥪', 'sandwich'),
    UnicodeEmoji('🌮', 'taco'),
    UnicodeEmoji('🌯', 'burrito'),
    UnicodeEmoji('🫔', 'tamale'),
    UnicodeEmoji('🥙', 'stuffed flatbread'),
    UnicodeEmoji('🧆', 'falafel'),
    UnicodeEmoji('🥚', 'egg'),
    UnicodeEmoji('🍳', 'cooking'),
    UnicodeEmoji('🥘', 'shallow pan of food'),
    UnicodeEmoji('🍲', 'pot of food'),
    UnicodeEmoji('🫕', 'fondue'),
    UnicodeEmoji('🥣', 'bowl with spoon'),
    UnicodeEmoji('🥗', 'green salad'),
    UnicodeEmoji('🍿', 'popcorn'),
    UnicodeEmoji('🧈', 'butter'),
    UnicodeEmoji('🧂', 'salt'),
    UnicodeEmoji('🥫', 'canned food'),
    UnicodeEmoji('🍱', 'bento box'),
    UnicodeEmoji('🍘', 'rice cracker'),
    UnicodeEmoji('🍙', 'rice ball'),
    UnicodeEmoji('🍚', 'cooked rice'),
    UnicodeEmoji('🍛', 'curry rice'),
    UnicodeEmoji('🍜', 'steaming bowl'),
    UnicodeEmoji('🍝', 'spaghetti'),
    UnicodeEmoji('🍠', 'roasted sweet potato'),
    UnicodeEmoji('🍢', 'oden'),
    UnicodeEmoji('🍣', 'sushi'),
    UnicodeEmoji('🍤', 'fried shrimp'),
    UnicodeEmoji('🍥', 'fish cake with swirl'),
    UnicodeEmoji('🥮', 'moon cake'),
    UnicodeEmoji('🍡', 'dango'),
    UnicodeEmoji('🥟', 'dumpling'),
    UnicodeEmoji('🥠', 'fortune cookie'),
    UnicodeEmoji('🥡', 'takeout box'),
    UnicodeEmoji('🍦', 'soft ice cream'),
    UnicodeEmoji('🍧', 'shaved ice'),
    UnicodeEmoji('🍨', 'ice cream'),
    UnicodeEmoji('🍩', 'doughnut'),
    UnicodeEmoji('🍪', 'cookie'),
    UnicodeEmoji('🎂', 'birthday cake'),
    UnicodeEmoji('🍰', 'shortcake'),
    UnicodeEmoji('🧁', 'cupcake'),
    UnicodeEmoji('🥧', 'pie'),
    UnicodeEmoji('🍫', 'chocolate bar'),
    UnicodeEmoji('🍬', 'candy'),
    UnicodeEmoji('🍭', 'lollipop'),
    UnicodeEmoji('🍮', 'custard'),
    UnicodeEmoji('🍯', 'honey pot'),
    UnicodeEmoji('🍼', 'baby bottle'),
    UnicodeEmoji('🥛', 'glass of milk'),
    UnicodeEmoji('☕', 'hot beverage'),
    UnicodeEmoji('🫖', 'teapot'),
    UnicodeEmoji('🍵', 'teacup without handle'),
    UnicodeEmoji('🍶', 'sake'),
    UnicodeEmoji('🍾', 'bottle with popping cork'),
    UnicodeEmoji('🍷', 'wine glass'),
    UnicodeEmoji('🍸', 'cocktail glass'),
    UnicodeEmoji('🍹', 'tropical drink'),
    UnicodeEmoji('🍺', 'beer mug'),
    UnicodeEmoji('🍻', 'clinking beer mugs'),
    UnicodeEmoji('🥂', 'clinking glasses'),
    UnicodeEmoji('🥃', 'tumbler glass'),
    UnicodeEmoji('🫗', 'pouring liquid'),
    UnicodeEmoji('🥤', 'cup with straw'),
    UnicodeEmoji('🧋', 'bubble tea'),
    UnicodeEmoji('🧃', 'beverage box'),
    UnicodeEmoji('🧉', 'mate'),
    UnicodeEmoji('🧊', 'ice'),
    UnicodeEmoji('🥢', 'chopsticks'),
    UnicodeEmoji('🍽️', 'fork and knife with plate'),
    UnicodeEmoji('🍴', 'fork and knife'),
    UnicodeEmoji('🥄', 'spoon'),
    UnicodeEmoji('🔪', 'kitchen knife'),
    UnicodeEmoji('🫙', 'jar'),
    UnicodeEmoji('🏺', 'amphora'),
  ],
  'Travel & Places': [
    UnicodeEmoji('🌍', 'globe showing europe-africa'),
    UnicodeEmoji('🌎', 'globe showing americas'),
    UnicodeEmoji('🌏', 'globe showing asia-australia'),
    UnicodeEmoji('🌐', 'globe with meridians'),
    UnicodeEmoji('🗺️', 'world map'),
    UnicodeEmoji('🗾', 'map of japan'),
    UnicodeEmoji('🧭', 'compass'),
    UnicodeEmoji('🏔️', 'snow-capped mountain'),
    UnicodeEmoji('⛰️', 'mountain'),
    UnicodeEmoji('🌋', 'volcano'),
    UnicodeEmoji('🗻', 'mount fuji'),
    UnicodeEmoji('🏕️', 'camping'),
    UnicodeEmoji('🏖️', 'beach with umbrella'),
    UnicodeEmoji('🏜️', 'desert'),
    UnicodeEmoji('🏝️', 'desert island'),
    UnicodeEmoji('🏞️', 'national park'),
    UnicodeEmoji('🏟️', 'stadium'),
    UnicodeEmoji('🏛️', 'classical building'),
    UnicodeEmoji('🏗️', 'building construction'),
    UnicodeEmoji('🧱', 'brick'),
    UnicodeEmoji('🪨', 'rock'),
    UnicodeEmoji('🪵', 'wood'),
    UnicodeEmoji('🛖', 'hut'),
    UnicodeEmoji('🏘️', 'houses'),
    UnicodeEmoji('🏚️', 'derelict house'),
    UnicodeEmoji('🏠', 'house'),
    UnicodeEmoji('🏡', 'house with garden'),
    UnicodeEmoji('🏢', 'office building'),
    UnicodeEmoji('🏣', 'japanese post office'),
    UnicodeEmoji('🏤', 'post office'),
    UnicodeEmoji('🏥', 'hospital'),
    UnicodeEmoji('🏦', 'bank'),
    UnicodeEmoji('🏨', 'hotel'),
    UnicodeEmoji('🏩', 'love hotel'),
    UnicodeEmoji('🏪', 'convenience store'),
    UnicodeEmoji('🏫', 'school'),
    UnicodeEmoji('🏬', 'department store'),
    UnicodeEmoji('🏭', 'factory'),
    UnicodeEmoji('🏯', 'japanese castle'),
    UnicodeEmoji('🏰', 'castle'),
    UnicodeEmoji('💒', 'wedding'),
    UnicodeEmoji('🗼', 'tokyo tower'),
    UnicodeEmoji('🗽', 'statue of liberty'),
    UnicodeEmoji('⛪', 'church'),
    UnicodeEmoji('🕌', 'mosque'),
    UnicodeEmoji('🛕', 'hindu temple'),
    UnicodeEmoji('🕍', 'synagogue'),
    UnicodeEmoji('⛩️', 'shinto shrine'),
    UnicodeEmoji('🕋', 'kaaba'),
    UnicodeEmoji('⛲', 'fountain'),
    UnicodeEmoji('⛺', 'tent'),
    UnicodeEmoji('🌁', 'foggy'),
    UnicodeEmoji('🌃', 'night with stars'),
    UnicodeEmoji('🏙️', 'cityscape'),
    UnicodeEmoji('🌄', 'sunrise over mountains'),
    UnicodeEmoji('🌅', 'sunrise'),
    UnicodeEmoji('🌆', 'cityscape at dusk'),
    UnicodeEmoji('🌇', 'sunset'),
    UnicodeEmoji('🌉', 'bridge at night'),
    UnicodeEmoji('♨️', 'hot springs'),
    UnicodeEmoji('🎠', 'carousel horse'),
    UnicodeEmoji('🛝', 'playground slide'),
    UnicodeEmoji('🎡', 'ferris wheel'),
    UnicodeEmoji('🎢', 'roller coaster'),
    UnicodeEmoji('💈', 'barber pole'),
    UnicodeEmoji('🎪', 'circus tent'),
    UnicodeEmoji('🚂', 'locomotive'),
    UnicodeEmoji('🚃', 'railway car'),
    UnicodeEmoji('🚄', 'high-speed train'),
    UnicodeEmoji('🚅', 'bullet train'),
    UnicodeEmoji('🚆', 'train'),
    UnicodeEmoji('🚇', 'metro'),
    UnicodeEmoji('🚈', 'light rail'),
    UnicodeEmoji('🚉', 'station'),
    UnicodeEmoji('🚊', 'tram'),
    UnicodeEmoji('🚝', 'monorail'),
    UnicodeEmoji('🚞', 'mountain railway'),
    UnicodeEmoji('🚋', 'tram car'),
    UnicodeEmoji('🚌', 'bus'),
    UnicodeEmoji('🚍', 'oncoming bus'),
    UnicodeEmoji('🚎', 'trolleybus'),
    UnicodeEmoji('🚐', 'minibus'),
    UnicodeEmoji('🚑', 'ambulance'),
    UnicodeEmoji('🚒', 'fire engine'),
    UnicodeEmoji('🚓', 'police car'),
    UnicodeEmoji('🚔', 'oncoming police car'),
    UnicodeEmoji('🚕', 'taxi'),
    UnicodeEmoji('🚖', 'oncoming taxi'),
    UnicodeEmoji('🚗', 'automobile'),
    UnicodeEmoji('🚘', 'oncoming automobile'),
    UnicodeEmoji('🚙', 'sport utility vehicle'),
    UnicodeEmoji('🛻', 'pickup truck'),
    UnicodeEmoji('🚚', 'delivery truck'),
    UnicodeEmoji('🚛', 'articulated lorry'),
    UnicodeEmoji('🚜', 'tractor'),
    UnicodeEmoji('🏎️', 'racing car'),
    UnicodeEmoji('🏍️', 'motorcycle'),
    UnicodeEmoji('🛵', 'motor scooter'),
    UnicodeEmoji('🦽', 'manual wheelchair'),
    UnicodeEmoji('🦼', 'motorized wheelchair'),
    UnicodeEmoji('🛺', 'auto rickshaw'),
    UnicodeEmoji('🚲', 'bicycle'),
    UnicodeEmoji('🛴', 'kick scooter'),
    UnicodeEmoji('🛹', 'skateboard'),
    UnicodeEmoji('🛼', 'roller skate'),
    UnicodeEmoji('🚏', 'bus stop'),
    UnicodeEmoji('🛣️', 'motorway'),
    UnicodeEmoji('🛤️', 'railway track'),
    UnicodeEmoji('🛢️', 'oil drum'),
    UnicodeEmoji('⛽', 'fuel pump'),
    UnicodeEmoji('🛞', 'wheel'),
    UnicodeEmoji('🚨', 'police car light'),
    UnicodeEmoji('🚥', 'horizontal traffic light'),
    UnicodeEmoji('🚦', 'vertical traffic light'),
    UnicodeEmoji('🛑', 'stop sign'),
    UnicodeEmoji('🚧', 'construction'),
    UnicodeEmoji('⚓', 'anchor'),
    UnicodeEmoji('🛟', 'ring buoy'),
    UnicodeEmoji('⛵', 'sailboat'),
    UnicodeEmoji('🛶', 'canoe'),
    UnicodeEmoji('🚤', 'speedboat'),
    UnicodeEmoji('🛳️', 'passenger ship'),
    UnicodeEmoji('⛴️', 'ferry'),
    UnicodeEmoji('🛥️', 'motor boat'),
    UnicodeEmoji('🚢', 'ship'),
    UnicodeEmoji('✈️', 'airplane'),
    UnicodeEmoji('🛩️', 'small airplane'),
    UnicodeEmoji('🛫', 'airplane departure'),
    UnicodeEmoji('🛬', 'airplane arrival'),
    UnicodeEmoji('🪂', 'parachute'),
    UnicodeEmoji('💺', 'seat'),
    UnicodeEmoji('🚁', 'helicopter'),
    UnicodeEmoji('🚟', 'suspension railway'),
    UnicodeEmoji('🚠', 'mountain cableway'),
    UnicodeEmoji('🚡', 'aerial tramway'),
    UnicodeEmoji('🛰️', 'satellite'),
    UnicodeEmoji('🚀', 'rocket'),
    UnicodeEmoji('🛸', 'flying saucer'),
    UnicodeEmoji('🛎️', 'bellhop bell'),
    UnicodeEmoji('🧳', 'luggage'),
    UnicodeEmoji('⌛', 'hourglass done'),
    UnicodeEmoji('⏳', 'hourglass not done'),
    UnicodeEmoji('⌚', 'watch'),
    UnicodeEmoji('⏰', 'alarm clock'),
    UnicodeEmoji('⏱️', 'stopwatch'),
    UnicodeEmoji('⏲️', 'timer clock'),
    UnicodeEmoji('🕰️', 'mantelpiece clock'),
    UnicodeEmoji('🕛', 'twelve o’clock'),
    UnicodeEmoji('🕧', 'twelve-thirty'),
    UnicodeEmoji('🕐', 'one o’clock'),
    UnicodeEmoji('🕜', 'one-thirty'),
    UnicodeEmoji('🕑', 'two o’clock'),
    UnicodeEmoji('🕝', 'two-thirty'),
    UnicodeEmoji('🕒', 'three o’clock'),
    UnicodeEmoji('🕞', 'three-thirty'),
    UnicodeEmoji('🕓', 'four o’clock'),
    UnicodeEmoji('🕟', 'four-thirty'),
    UnicodeEmoji('🕔', 'five o’clock'),
    UnicodeEmoji('🕠', 'five-thirty'),
    UnicodeEmoji('🕕', 'six o’clock'),
    UnicodeEmoji('🕡', 'six-thirty'),
    UnicodeEmoji('🕖', 'seven o’clock'),
    UnicodeEmoji('🕢', 'seven-thirty'),
    UnicodeEmoji('🕗', 'eight o’clock'),
    UnicodeEmoji('🕣', 'eight-thirty'),
    UnicodeEmoji('🕘', 'nine o’clock'),
    UnicodeEmoji('🕤', 'nine-thirty'),
    UnicodeEmoji('🕙', 'ten o’clock'),
    UnicodeEmoji('🕥', 'ten-thirty'),
    UnicodeEmoji('🕚', 'eleven o’clock'),
    UnicodeEmoji('🕦', 'eleven-thirty'),
    UnicodeEmoji('🌑', 'new moon'),
    UnicodeEmoji('🌒', 'waxing crescent moon'),
    UnicodeEmoji('🌓', 'first quarter moon'),
    UnicodeEmoji('🌔', 'waxing gibbous moon'),
    UnicodeEmoji('🌕', 'full moon'),
    UnicodeEmoji('🌖', 'waning gibbous moon'),
    UnicodeEmoji('🌗', 'last quarter moon'),
    UnicodeEmoji('🌘', 'waning crescent moon'),
    UnicodeEmoji('🌙', 'crescent moon'),
    UnicodeEmoji('🌚', 'new moon face'),
    UnicodeEmoji('🌛', 'first quarter moon face'),
    UnicodeEmoji('🌜', 'last quarter moon face'),
    UnicodeEmoji('🌡️', 'thermometer'),
    UnicodeEmoji('☀️', 'sun'),
    UnicodeEmoji('🌝', 'full moon face'),
    UnicodeEmoji('🌞', 'sun with face'),
    UnicodeEmoji('🪐', 'ringed planet'),
    UnicodeEmoji('⭐', 'star'),
    UnicodeEmoji('🌟', 'glowing star'),
    UnicodeEmoji('🌠', 'shooting star'),
    UnicodeEmoji('🌌', 'milky way'),
    UnicodeEmoji('☁️', 'cloud'),
    UnicodeEmoji('⛅', 'sun behind cloud'),
    UnicodeEmoji('⛈️', 'cloud with lightning and rain'),
    UnicodeEmoji('🌤️', 'sun behind small cloud'),
    UnicodeEmoji('🌥️', 'sun behind large cloud'),
    UnicodeEmoji('🌦️', 'sun behind rain cloud'),
    UnicodeEmoji('🌧️', 'cloud with rain'),
    UnicodeEmoji('🌨️', 'cloud with snow'),
    UnicodeEmoji('🌩️', 'cloud with lightning'),
    UnicodeEmoji('🌪️', 'tornado'),
    UnicodeEmoji('🌫️', 'fog'),
    UnicodeEmoji('🌬️', 'wind face'),
    UnicodeEmoji('🌀', 'cyclone'),
    UnicodeEmoji('🌈', 'rainbow'),
    UnicodeEmoji('🌂', 'closed umbrella'),
    UnicodeEmoji('☂️', 'umbrella'),
    UnicodeEmoji('☔', 'umbrella with rain drops'),
    UnicodeEmoji('⛱️', 'umbrella on ground'),
    UnicodeEmoji('⚡', 'high voltage'),
    UnicodeEmoji('❄️', 'snowflake'),
    UnicodeEmoji('☃️', 'snowman'),
    UnicodeEmoji('⛄', 'snowman without snow'),
    UnicodeEmoji('☄️', 'comet'),
    UnicodeEmoji('🔥', 'fire'),
    UnicodeEmoji('💧', 'droplet'),
    UnicodeEmoji('🌊', 'water wave'),
  ],
  'Activities': [
    UnicodeEmoji('🎃', 'jack-o-lantern'),
    UnicodeEmoji('🎄', 'christmas tree'),
    UnicodeEmoji('🎆', 'fireworks'),
    UnicodeEmoji('🎇', 'sparkler'),
    UnicodeEmoji('🧨', 'firecracker'),
    UnicodeEmoji('✨', 'sparkles'),
    UnicodeEmoji('🎈', 'balloon'),
    UnicodeEmoji('🎉', 'party popper'),
    UnicodeEmoji('🎊', 'confetti ball'),
    UnicodeEmoji('🎋', 'tanabata tree'),
    UnicodeEmoji('🎍', 'pine decoration'),
    UnicodeEmoji('🎎', 'japanese dolls'),
    UnicodeEmoji('🎏', 'carp streamer'),
    UnicodeEmoji('🎐', 'wind chime'),
    UnicodeEmoji('🎑', 'moon viewing ceremony'),
    UnicodeEmoji('🧧', 'red envelope'),
    UnicodeEmoji('🎀', 'ribbon'),
    UnicodeEmoji('🎁', 'wrapped gift'),
    UnicodeEmoji('🎗️', 'reminder ribbon'),
    UnicodeEmoji('🎟️', 'admission tickets'),
    UnicodeEmoji('🎫', 'ticket'),
    UnicodeEmoji('🎖️', 'military medal'),
    UnicodeEmoji('🏆', 'trophy'),
    UnicodeEmoji('🏅', 'sports medal'),
    UnicodeEmoji('🥇', '1st place medal'),
    UnicodeEmoji('🥈', '2nd place medal'),
    UnicodeEmoji('🥉', '3rd place medal'),
    UnicodeEmoji('⚽', 'soccer ball'),
    UnicodeEmoji('⚾', 'baseball'),
    UnicodeEmoji('🥎', 'softball'),
    UnicodeEmoji('🏀', 'basketball'),
    UnicodeEmoji('🏐', 'volleyball'),
    UnicodeEmoji('🏈', 'american football'),
    UnicodeEmoji('🏉', 'rugby football'),
    UnicodeEmoji('🎾', 'tennis'),
    UnicodeEmoji('🥏', 'flying disc'),
    UnicodeEmoji('🎳', 'bowling'),
    UnicodeEmoji('🏏', 'cricket game'),
    UnicodeEmoji('🏑', 'field hockey'),
    UnicodeEmoji('🏒', 'ice hockey'),
    UnicodeEmoji('🥍', 'lacrosse'),
    UnicodeEmoji('🏓', 'ping pong'),
    UnicodeEmoji('🏸', 'badminton'),
    UnicodeEmoji('🥊', 'boxing glove'),
    UnicodeEmoji('🥋', 'martial arts uniform'),
    UnicodeEmoji('🥅', 'goal net'),
    UnicodeEmoji('⛳', 'flag in hole'),
    UnicodeEmoji('⛸️', 'ice skate'),
    UnicodeEmoji('🎣', 'fishing pole'),
    UnicodeEmoji('🤿', 'diving mask'),
    UnicodeEmoji('🎽', 'running shirt'),
    UnicodeEmoji('🎿', 'skis'),
    UnicodeEmoji('🛷', 'sled'),
    UnicodeEmoji('🥌', 'curling stone'),
    UnicodeEmoji('🎯', 'bullseye'),
    UnicodeEmoji('🪀', 'yo-yo'),
    UnicodeEmoji('🪁', 'kite'),
    UnicodeEmoji('🔫', 'water pistol'),
    UnicodeEmoji('🎱', 'pool 8 ball'),
    UnicodeEmoji('🔮', 'crystal ball'),
    UnicodeEmoji('🪄', 'magic wand'),
    UnicodeEmoji('🎮', 'video game'),
    UnicodeEmoji('🕹️', 'joystick'),
    UnicodeEmoji('🎰', 'slot machine'),
    UnicodeEmoji('🎲', 'game die'),
    UnicodeEmoji('🧩', 'puzzle piece'),
    UnicodeEmoji('🧸', 'teddy bear'),
    UnicodeEmoji('🪅', 'piñata'),
    UnicodeEmoji('🪩', 'mirror ball'),
    UnicodeEmoji('🪆', 'nesting dolls'),
    UnicodeEmoji('♠️', 'spade suit'),
    UnicodeEmoji('♥️', 'heart suit'),
    UnicodeEmoji('♦️', 'diamond suit'),
    UnicodeEmoji('♣️', 'club suit'),
    UnicodeEmoji('♟️', 'chess pawn'),
    UnicodeEmoji('🃏', 'joker'),
    UnicodeEmoji('🀄', 'mahjong red dragon'),
    UnicodeEmoji('🎴', 'flower playing cards'),
    UnicodeEmoji('🎭', 'performing arts'),
    UnicodeEmoji('🖼️', 'framed picture'),
    UnicodeEmoji('🎨', 'artist palette'),
    UnicodeEmoji('🧵', 'thread'),
    UnicodeEmoji('🪡', 'sewing needle'),
    UnicodeEmoji('🧶', 'yarn'),
    UnicodeEmoji('🪢', 'knot'),
  ],
  'Objects': [
    UnicodeEmoji('👓', 'glasses'),
    UnicodeEmoji('🕶️', 'sunglasses'),
    UnicodeEmoji('🥽', 'goggles'),
    UnicodeEmoji('🥼', 'lab coat'),
    UnicodeEmoji('🦺', 'safety vest'),
    UnicodeEmoji('👔', 'necktie'),
    UnicodeEmoji('👕', 't-shirt'),
    UnicodeEmoji('👖', 'jeans'),
    UnicodeEmoji('🧣', 'scarf'),
    UnicodeEmoji('🧤', 'gloves'),
    UnicodeEmoji('🧥', 'coat'),
    UnicodeEmoji('🧦', 'socks'),
    UnicodeEmoji('👗', 'dress'),
    UnicodeEmoji('👘', 'kimono'),
    UnicodeEmoji('🥻', 'sari'),
    UnicodeEmoji('🩱', 'one-piece swimsuit'),
    UnicodeEmoji('🩲', 'briefs'),
    UnicodeEmoji('🩳', 'shorts'),
    UnicodeEmoji('👙', 'bikini'),
    UnicodeEmoji('👚', 'woman’s clothes'),
    UnicodeEmoji('🪭', 'folding hand fan'),
    UnicodeEmoji('👛', 'purse'),
    UnicodeEmoji('👜', 'handbag'),
    UnicodeEmoji('👝', 'clutch bag'),
    UnicodeEmoji('🛍️', 'shopping bags'),
    UnicodeEmoji('🎒', 'backpack'),
    UnicodeEmoji('🩴', 'thong sandal'),
    UnicodeEmoji('👞', 'man’s shoe'),
    UnicodeEmoji('👟', 'running shoe'),
    UnicodeEmoji('🥾', 'hiking boot'),
    UnicodeEmoji('🥿', 'flat shoe'),
    UnicodeEmoji('👠', 'high-heeled shoe'),
    UnicodeEmoji('👡', 'woman’s sandal'),
    UnicodeEmoji('🩰', 'ballet shoes'),
    UnicodeEmoji('👢', 'woman’s boot'),
    UnicodeEmoji('🪮', 'hair pick'),
    UnicodeEmoji('👑', 'crown'),
    UnicodeEmoji('👒', 'woman’s hat'),
    UnicodeEmoji('🎩', 'top hat'),
    UnicodeEmoji('🎓', 'graduation cap'),
    UnicodeEmoji('🧢', 'billed cap'),
    UnicodeEmoji('🪖', 'military helmet'),
    UnicodeEmoji('⛑️', 'rescue worker’s helmet'),
    UnicodeEmoji('📿', 'prayer beads'),
    UnicodeEmoji('💄', 'lipstick'),
    UnicodeEmoji('💍', 'ring'),
    UnicodeEmoji('💎', 'gem stone'),
    UnicodeEmoji('🔇', 'muted speaker'),
    UnicodeEmoji('🔈', 'speaker low volume'),
    UnicodeEmoji('🔉', 'speaker medium volume'),
    UnicodeEmoji('🔊', 'speaker high volume'),
    UnicodeEmoji('📢', 'loudspeaker'),
    UnicodeEmoji('📣', 'megaphone'),
    UnicodeEmoji('📯', 'postal horn'),
    UnicodeEmoji('🔔', 'bell'),
    UnicodeEmoji('🔕', 'bell with slash'),
    UnicodeEmoji('🎼', 'musical score'),
    UnicodeEmoji('🎵', 'musical note'),
    UnicodeEmoji('🎶', 'musical notes'),
    UnicodeEmoji('🎙️', 'studio microphone'),
    UnicodeEmoji('🎚️', 'level slider'),
    UnicodeEmoji('🎛️', 'control knobs'),
    UnicodeEmoji('🎤', 'microphone'),
    UnicodeEmoji('🎧', 'headphone'),
    UnicodeEmoji('📻', 'radio'),
    UnicodeEmoji('🎷', 'saxophone'),
    UnicodeEmoji('🪗', 'accordion'),
    UnicodeEmoji('🎸', 'guitar'),
    UnicodeEmoji('🎹', 'musical keyboard'),
    UnicodeEmoji('🎺', 'trumpet'),
    UnicodeEmoji('🎻', 'violin'),
    UnicodeEmoji('🪕', 'banjo'),
    UnicodeEmoji('🥁', 'drum'),
    UnicodeEmoji('🪘', 'long drum'),
    UnicodeEmoji('🪇', 'maracas'),
    UnicodeEmoji('🪈', 'flute'),
    UnicodeEmoji('🪉', 'harp'),
    UnicodeEmoji('📱', 'mobile phone'),
    UnicodeEmoji('📲', 'mobile phone with arrow'),
    UnicodeEmoji('☎️', 'telephone'),
    UnicodeEmoji('📞', 'telephone receiver'),
    UnicodeEmoji('📟', 'pager'),
    UnicodeEmoji('📠', 'fax machine'),
    UnicodeEmoji('🔋', 'battery'),
    UnicodeEmoji('🪫', 'low battery'),
    UnicodeEmoji('🔌', 'electric plug'),
    UnicodeEmoji('💻', 'laptop'),
    UnicodeEmoji('🖥️', 'desktop computer'),
    UnicodeEmoji('🖨️', 'printer'),
    UnicodeEmoji('⌨️', 'keyboard'),
    UnicodeEmoji('🖱️', 'computer mouse'),
    UnicodeEmoji('🖲️', 'trackball'),
    UnicodeEmoji('💽', 'computer disk'),
    UnicodeEmoji('💾', 'floppy disk'),
    UnicodeEmoji('💿', 'optical disk'),
    UnicodeEmoji('📀', 'dvd'),
    UnicodeEmoji('🧮', 'abacus'),
    UnicodeEmoji('🎥', 'movie camera'),
    UnicodeEmoji('🎞️', 'film frames'),
    UnicodeEmoji('📽️', 'film projector'),
    UnicodeEmoji('🎬', 'clapper board'),
    UnicodeEmoji('📺', 'television'),
    UnicodeEmoji('📷', 'camera'),
    UnicodeEmoji('📸', 'camera with flash'),
    UnicodeEmoji('📹', 'video camera'),
    UnicodeEmoji('📼', 'videocassette'),
    UnicodeEmoji('🔍', 'magnifying glass tilted left'),
    UnicodeEmoji('🔎', 'magnifying glass tilted right'),
    UnicodeEmoji('🕯️', 'candle'),
    UnicodeEmoji('💡', 'light bulb'),
    UnicodeEmoji('🔦', 'flashlight'),
    UnicodeEmoji('🏮', 'red paper lantern'),
    UnicodeEmoji('🪔', 'diya lamp'),
    UnicodeEmoji('📔', 'notebook with decorative cover'),
    UnicodeEmoji('📕', 'closed book'),
    UnicodeEmoji('📖', 'open book'),
    UnicodeEmoji('📗', 'green book'),
    UnicodeEmoji('📘', 'blue book'),
    UnicodeEmoji('📙', 'orange book'),
    UnicodeEmoji('📚', 'books'),
    UnicodeEmoji('📓', 'notebook'),
    UnicodeEmoji('📒', 'ledger'),
    UnicodeEmoji('📃', 'page with curl'),
    UnicodeEmoji('📜', 'scroll'),
    UnicodeEmoji('📄', 'page facing up'),
    UnicodeEmoji('📰', 'newspaper'),
    UnicodeEmoji('🗞️', 'rolled-up newspaper'),
    UnicodeEmoji('📑', 'bookmark tabs'),
    UnicodeEmoji('🔖', 'bookmark'),
    UnicodeEmoji('🏷️', 'label'),
    UnicodeEmoji('💰', 'money bag'),
    UnicodeEmoji('🪙', 'coin'),
    UnicodeEmoji('💴', 'yen banknote'),
    UnicodeEmoji('💵', 'dollar banknote'),
    UnicodeEmoji('💶', 'euro banknote'),
    UnicodeEmoji('💷', 'pound banknote'),
    UnicodeEmoji('💸', 'money with wings'),
    UnicodeEmoji('💳', 'credit card'),
    UnicodeEmoji('🧾', 'receipt'),
    UnicodeEmoji('💹', 'chart increasing with yen'),
    UnicodeEmoji('✉️', 'envelope'),
    UnicodeEmoji('📧', 'e-mail'),
    UnicodeEmoji('📨', 'incoming envelope'),
    UnicodeEmoji('📩', 'envelope with arrow'),
    UnicodeEmoji('📤', 'outbox tray'),
    UnicodeEmoji('📥', 'inbox tray'),
    UnicodeEmoji('📦', 'package'),
    UnicodeEmoji('📫', 'closed mailbox with raised flag'),
    UnicodeEmoji('📪', 'closed mailbox with lowered flag'),
    UnicodeEmoji('📬', 'open mailbox with raised flag'),
    UnicodeEmoji('📭', 'open mailbox with lowered flag'),
    UnicodeEmoji('📮', 'postbox'),
    UnicodeEmoji('🗳️', 'ballot box with ballot'),
    UnicodeEmoji('✏️', 'pencil'),
    UnicodeEmoji('✒️', 'black nib'),
    UnicodeEmoji('🖋️', 'fountain pen'),
    UnicodeEmoji('🖊️', 'pen'),
    UnicodeEmoji('🖌️', 'paintbrush'),
    UnicodeEmoji('🖍️', 'crayon'),
    UnicodeEmoji('📝', 'memo'),
    UnicodeEmoji('💼', 'briefcase'),
    UnicodeEmoji('📁', 'file folder'),
    UnicodeEmoji('📂', 'open file folder'),
    UnicodeEmoji('🗂️', 'card index dividers'),
    UnicodeEmoji('📅', 'calendar'),
    UnicodeEmoji('📆', 'tear-off calendar'),
    UnicodeEmoji('🗒️', 'spiral notepad'),
    UnicodeEmoji('🗓️', 'spiral calendar'),
    UnicodeEmoji('📇', 'card index'),
    UnicodeEmoji('📈', 'chart increasing'),
    UnicodeEmoji('📉', 'chart decreasing'),
    UnicodeEmoji('📊', 'bar chart'),
    UnicodeEmoji('📋', 'clipboard'),
    UnicodeEmoji('📌', 'pushpin'),
    UnicodeEmoji('📍', 'round pushpin'),
    UnicodeEmoji('📎', 'paperclip'),
    UnicodeEmoji('🖇️', 'linked paperclips'),
    UnicodeEmoji('📏', 'straight ruler'),
    UnicodeEmoji('📐', 'triangular ruler'),
    UnicodeEmoji('✂️', 'scissors'),
    UnicodeEmoji('🗃️', 'card file box'),
    UnicodeEmoji('🗄️', 'file cabinet'),
    UnicodeEmoji('🗑️', 'wastebasket'),
    UnicodeEmoji('🔒', 'locked'),
    UnicodeEmoji('🔓', 'unlocked'),
    UnicodeEmoji('🔏', 'locked with pen'),
    UnicodeEmoji('🔐', 'locked with key'),
    UnicodeEmoji('🔑', 'key'),
    UnicodeEmoji('🗝️', 'old key'),
    UnicodeEmoji('🔨', 'hammer'),
    UnicodeEmoji('🪓', 'axe'),
    UnicodeEmoji('⛏️', 'pick'),
    UnicodeEmoji('⚒️', 'hammer and pick'),
    UnicodeEmoji('🛠️', 'hammer and wrench'),
    UnicodeEmoji('🗡️', 'dagger'),
    UnicodeEmoji('⚔️', 'crossed swords'),
    UnicodeEmoji('💣', 'bomb'),
    UnicodeEmoji('🪃', 'boomerang'),
    UnicodeEmoji('🏹', 'bow and arrow'),
    UnicodeEmoji('🛡️', 'shield'),
    UnicodeEmoji('🪚', 'carpentry saw'),
    UnicodeEmoji('🔧', 'wrench'),
    UnicodeEmoji('🪛', 'screwdriver'),
    UnicodeEmoji('🔩', 'nut and bolt'),
    UnicodeEmoji('⚙️', 'gear'),
    UnicodeEmoji('🗜️', 'clamp'),
    UnicodeEmoji('⚖️', 'balance scale'),
    UnicodeEmoji('🦯', 'white cane'),
    UnicodeEmoji('🔗', 'link'),
    UnicodeEmoji('⛓️‍💥', 'broken chain'),
    UnicodeEmoji('⛓️', 'chains'),
    UnicodeEmoji('🪝', 'hook'),
    UnicodeEmoji('🧰', 'toolbox'),
    UnicodeEmoji('🧲', 'magnet'),
    UnicodeEmoji('🪜', 'ladder'),
    UnicodeEmoji('🪏', 'shovel'),
    UnicodeEmoji('⚗️', 'alembic'),
    UnicodeEmoji('🧪', 'test tube'),
    UnicodeEmoji('🧫', 'petri dish'),
    UnicodeEmoji('🧬', 'dna'),
    UnicodeEmoji('🔬', 'microscope'),
    UnicodeEmoji('🔭', 'telescope'),
    UnicodeEmoji('📡', 'satellite antenna'),
    UnicodeEmoji('💉', 'syringe'),
    UnicodeEmoji('🩸', 'drop of blood'),
    UnicodeEmoji('💊', 'pill'),
    UnicodeEmoji('🩹', 'adhesive bandage'),
    UnicodeEmoji('🩼', 'crutch'),
    UnicodeEmoji('🩺', 'stethoscope'),
    UnicodeEmoji('🩻', 'x-ray'),
    UnicodeEmoji('🚪', 'door'),
    UnicodeEmoji('🛗', 'elevator'),
    UnicodeEmoji('🪞', 'mirror'),
    UnicodeEmoji('🪟', 'window'),
    UnicodeEmoji('🛏️', 'bed'),
    UnicodeEmoji('🛋️', 'couch and lamp'),
    UnicodeEmoji('🪑', 'chair'),
    UnicodeEmoji('🚽', 'toilet'),
    UnicodeEmoji('🪠', 'plunger'),
    UnicodeEmoji('🚿', 'shower'),
    UnicodeEmoji('🛁', 'bathtub'),
    UnicodeEmoji('🪤', 'mouse trap'),
    UnicodeEmoji('🪒', 'razor'),
    UnicodeEmoji('🧴', 'lotion bottle'),
    UnicodeEmoji('🧷', 'safety pin'),
    UnicodeEmoji('🧹', 'broom'),
    UnicodeEmoji('🧺', 'basket'),
    UnicodeEmoji('🧻', 'roll of paper'),
    UnicodeEmoji('🪣', 'bucket'),
    UnicodeEmoji('🧼', 'soap'),
    UnicodeEmoji('🫧', 'bubbles'),
    UnicodeEmoji('🪥', 'toothbrush'),
    UnicodeEmoji('🧽', 'sponge'),
    UnicodeEmoji('🧯', 'fire extinguisher'),
    UnicodeEmoji('🛒', 'shopping cart'),
    UnicodeEmoji('🚬', 'cigarette'),
    UnicodeEmoji('⚰️', 'coffin'),
    UnicodeEmoji('🪦', 'headstone'),
    UnicodeEmoji('⚱️', 'funeral urn'),
    UnicodeEmoji('🧿', 'nazar amulet'),
    UnicodeEmoji('🪬', 'hamsa'),
    UnicodeEmoji('🗿', 'moai'),
    UnicodeEmoji('🪧', 'placard'),
    UnicodeEmoji('🪪', 'identification card'),
  ],
  'Symbols': [
    UnicodeEmoji('🏧', 'atm sign'),
    UnicodeEmoji('🚮', 'litter in bin sign'),
    UnicodeEmoji('🚰', 'potable water'),
    UnicodeEmoji('♿', 'wheelchair symbol'),
    UnicodeEmoji('🚹', 'men’s room'),
    UnicodeEmoji('🚺', 'women’s room'),
    UnicodeEmoji('🚻', 'restroom'),
    UnicodeEmoji('🚼', 'baby symbol'),
    UnicodeEmoji('🚾', 'water closet'),
    UnicodeEmoji('🛂', 'passport control'),
    UnicodeEmoji('🛃', 'customs'),
    UnicodeEmoji('🛄', 'baggage claim'),
    UnicodeEmoji('🛅', 'left luggage'),
    UnicodeEmoji('⚠️', 'warning'),
    UnicodeEmoji('🚸', 'children crossing'),
    UnicodeEmoji('⛔', 'no entry'),
    UnicodeEmoji('🚫', 'prohibited'),
    UnicodeEmoji('🚳', 'no bicycles'),
    UnicodeEmoji('🚭', 'no smoking'),
    UnicodeEmoji('🚯', 'no littering'),
    UnicodeEmoji('🚱', 'non-potable water'),
    UnicodeEmoji('🚷', 'no pedestrians'),
    UnicodeEmoji('📵', 'no mobile phones'),
    UnicodeEmoji('🔞', 'no one under eighteen'),
    UnicodeEmoji('☢️', 'radioactive'),
    UnicodeEmoji('☣️', 'biohazard'),
    UnicodeEmoji('⬆️', 'up arrow'),
    UnicodeEmoji('↗️', 'up-right arrow'),
    UnicodeEmoji('➡️', 'right arrow'),
    UnicodeEmoji('↘️', 'down-right arrow'),
    UnicodeEmoji('⬇️', 'down arrow'),
    UnicodeEmoji('↙️', 'down-left arrow'),
    UnicodeEmoji('⬅️', 'left arrow'),
    UnicodeEmoji('↖️', 'up-left arrow'),
    UnicodeEmoji('↕️', 'up-down arrow'),
    UnicodeEmoji('↔️', 'left-right arrow'),
    UnicodeEmoji('↩️', 'right arrow curving left'),
    UnicodeEmoji('↪️', 'left arrow curving right'),
    UnicodeEmoji('⤴️', 'right arrow curving up'),
    UnicodeEmoji('⤵️', 'right arrow curving down'),
    UnicodeEmoji('🔃', 'clockwise vertical arrows'),
    UnicodeEmoji('🔄', 'counterclockwise arrows button'),
    UnicodeEmoji('🔙', 'back arrow'),
    UnicodeEmoji('🔚', 'end arrow'),
    UnicodeEmoji('🔛', 'on! arrow'),
    UnicodeEmoji('🔜', 'soon arrow'),
    UnicodeEmoji('🔝', 'top arrow'),
    UnicodeEmoji('🛐', 'place of worship'),
    UnicodeEmoji('⚛️', 'atom symbol'),
    UnicodeEmoji('🕉️', 'om'),
    UnicodeEmoji('✡️', 'star of david'),
    UnicodeEmoji('☸️', 'wheel of dharma'),
    UnicodeEmoji('☯️', 'yin yang'),
    UnicodeEmoji('✝️', 'latin cross'),
    UnicodeEmoji('☦️', 'orthodox cross'),
    UnicodeEmoji('☪️', 'star and crescent'),
    UnicodeEmoji('☮️', 'peace symbol'),
    UnicodeEmoji('🕎', 'menorah'),
    UnicodeEmoji('🔯', 'dotted six-pointed star'),
    UnicodeEmoji('🪯', 'khanda'),
    UnicodeEmoji('♈', 'aries'),
    UnicodeEmoji('♉', 'taurus'),
    UnicodeEmoji('♊', 'gemini'),
    UnicodeEmoji('♋', 'cancer'),
    UnicodeEmoji('♌', 'leo'),
    UnicodeEmoji('♍', 'virgo'),
    UnicodeEmoji('♎', 'libra'),
    UnicodeEmoji('♏', 'scorpio'),
    UnicodeEmoji('♐', 'sagittarius'),
    UnicodeEmoji('♑', 'capricorn'),
    UnicodeEmoji('♒', 'aquarius'),
    UnicodeEmoji('♓', 'pisces'),
    UnicodeEmoji('⛎', 'ophiuchus'),
    UnicodeEmoji('🔀', 'shuffle tracks button'),
    UnicodeEmoji('🔁', 'repeat button'),
    UnicodeEmoji('🔂', 'repeat single button'),
    UnicodeEmoji('▶️', 'play button'),
    UnicodeEmoji('⏩', 'fast-forward button'),
    UnicodeEmoji('⏭️', 'next track button'),
    UnicodeEmoji('⏯️', 'play or pause button'),
    UnicodeEmoji('◀️', 'reverse button'),
    UnicodeEmoji('⏪', 'fast reverse button'),
    UnicodeEmoji('⏮️', 'last track button'),
    UnicodeEmoji('🔼', 'upwards button'),
    UnicodeEmoji('⏫', 'fast up button'),
    UnicodeEmoji('🔽', 'downwards button'),
    UnicodeEmoji('⏬', 'fast down button'),
    UnicodeEmoji('⏸️', 'pause button'),
    UnicodeEmoji('⏹️', 'stop button'),
    UnicodeEmoji('⏺️', 'record button'),
    UnicodeEmoji('⏏️', 'eject button'),
    UnicodeEmoji('🎦', 'cinema'),
    UnicodeEmoji('🔅', 'dim button'),
    UnicodeEmoji('🔆', 'bright button'),
    UnicodeEmoji('📶', 'antenna bars'),
    UnicodeEmoji('🛜', 'wireless'),
    UnicodeEmoji('📳', 'vibration mode'),
    UnicodeEmoji('📴', 'mobile phone off'),
    UnicodeEmoji('♀️', 'female sign'),
    UnicodeEmoji('♂️', 'male sign'),
    UnicodeEmoji('⚧️', 'transgender symbol'),
    UnicodeEmoji('✖️', 'multiply'),
    UnicodeEmoji('➕', 'plus'),
    UnicodeEmoji('➖', 'minus'),
    UnicodeEmoji('➗', 'divide'),
    UnicodeEmoji('🟰', 'heavy equals sign'),
    UnicodeEmoji('♾️', 'infinity'),
    UnicodeEmoji('‼️', 'double exclamation mark'),
    UnicodeEmoji('⁉️', 'exclamation question mark'),
    UnicodeEmoji('❓', 'red question mark'),
    UnicodeEmoji('❔', 'white question mark'),
    UnicodeEmoji('❕', 'white exclamation mark'),
    UnicodeEmoji('❗', 'red exclamation mark'),
    UnicodeEmoji('〰️', 'wavy dash'),
    UnicodeEmoji('💱', 'currency exchange'),
    UnicodeEmoji('💲', 'heavy dollar sign'),
    UnicodeEmoji('⚕️', 'medical symbol'),
    UnicodeEmoji('♻️', 'recycling symbol'),
    UnicodeEmoji('⚜️', 'fleur-de-lis'),
    UnicodeEmoji('🔱', 'trident emblem'),
    UnicodeEmoji('📛', 'name badge'),
    UnicodeEmoji('🔰', 'japanese symbol for beginner'),
    UnicodeEmoji('⭕', 'hollow red circle'),
    UnicodeEmoji('✅', 'check mark button'),
    UnicodeEmoji('☑️', 'check box with check'),
    UnicodeEmoji('✔️', 'check mark'),
    UnicodeEmoji('❌', 'cross mark'),
    UnicodeEmoji('❎', 'cross mark button'),
    UnicodeEmoji('➰', 'curly loop'),
    UnicodeEmoji('➿', 'double curly loop'),
    UnicodeEmoji('〽️', 'part alternation mark'),
    UnicodeEmoji('✳️', 'eight-spoked asterisk'),
    UnicodeEmoji('✴️', 'eight-pointed star'),
    UnicodeEmoji('❇️', 'sparkle'),
    UnicodeEmoji('©️', 'copyright'),
    UnicodeEmoji('®️', 'registered'),
    UnicodeEmoji('™️', 'trade mark'),
    UnicodeEmoji('🫟', 'splatter'),
    UnicodeEmoji('#️⃣', 'keycap: #'),
    UnicodeEmoji('*️⃣', 'keycap: *'),
    UnicodeEmoji('0️⃣', 'keycap: 0'),
    UnicodeEmoji('1️⃣', 'keycap: 1'),
    UnicodeEmoji('2️⃣', 'keycap: 2'),
    UnicodeEmoji('3️⃣', 'keycap: 3'),
    UnicodeEmoji('4️⃣', 'keycap: 4'),
    UnicodeEmoji('5️⃣', 'keycap: 5'),
    UnicodeEmoji('6️⃣', 'keycap: 6'),
    UnicodeEmoji('7️⃣', 'keycap: 7'),
    UnicodeEmoji('8️⃣', 'keycap: 8'),
    UnicodeEmoji('9️⃣', 'keycap: 9'),
    UnicodeEmoji('🔟', 'keycap: 10'),
    UnicodeEmoji('🔠', 'input latin uppercase'),
    UnicodeEmoji('🔡', 'input latin lowercase'),
    UnicodeEmoji('🔢', 'input numbers'),
    UnicodeEmoji('🔣', 'input symbols'),
    UnicodeEmoji('🔤', 'input latin letters'),
    UnicodeEmoji('🅰️', 'a button (blood type)'),
    UnicodeEmoji('🆎', 'ab button (blood type)'),
    UnicodeEmoji('🅱️', 'b button (blood type)'),
    UnicodeEmoji('🆑', 'cl button'),
    UnicodeEmoji('🆒', 'cool button'),
    UnicodeEmoji('🆓', 'free button'),
    UnicodeEmoji('ℹ️', 'information'),
    UnicodeEmoji('🆔', 'id button'),
    UnicodeEmoji('Ⓜ️', 'circled m'),
    UnicodeEmoji('🆕', 'new button'),
    UnicodeEmoji('🆖', 'ng button'),
    UnicodeEmoji('🅾️', 'o button (blood type)'),
    UnicodeEmoji('🆗', 'ok button'),
    UnicodeEmoji('🅿️', 'p button'),
    UnicodeEmoji('🆘', 'sos button'),
    UnicodeEmoji('🆙', 'up! button'),
    UnicodeEmoji('🆚', 'vs button'),
    UnicodeEmoji('🈁', 'japanese “here” button'),
    UnicodeEmoji('🈂️', 'japanese “service charge” button'),
    UnicodeEmoji('🈷️', 'japanese “monthly amount” button'),
    UnicodeEmoji('🈶', 'japanese “not free of charge” button'),
    UnicodeEmoji('🈯', 'japanese “reserved” button'),
    UnicodeEmoji('🉐', 'japanese “bargain” button'),
    UnicodeEmoji('🈹', 'japanese “discount” button'),
    UnicodeEmoji('🈚', 'japanese “free of charge” button'),
    UnicodeEmoji('🈲', 'japanese “prohibited” button'),
    UnicodeEmoji('🉑', 'japanese “acceptable” button'),
    UnicodeEmoji('🈸', 'japanese “application” button'),
    UnicodeEmoji('🈴', 'japanese “passing grade” button'),
    UnicodeEmoji('🈳', 'japanese “vacancy” button'),
    UnicodeEmoji('㊗️', 'japanese “congratulations” button'),
    UnicodeEmoji('㊙️', 'japanese “secret” button'),
    UnicodeEmoji('🈺', 'japanese “open for business” button'),
    UnicodeEmoji('🈵', 'japanese “no vacancy” button'),
    UnicodeEmoji('🔴', 'red circle'),
    UnicodeEmoji('🟠', 'orange circle'),
    UnicodeEmoji('🟡', 'yellow circle'),
    UnicodeEmoji('🟢', 'green circle'),
    UnicodeEmoji('🔵', 'blue circle'),
    UnicodeEmoji('🟣', 'purple circle'),
    UnicodeEmoji('🟤', 'brown circle'),
    UnicodeEmoji('⚫', 'black circle'),
    UnicodeEmoji('⚪', 'white circle'),
    UnicodeEmoji('🟥', 'red square'),
    UnicodeEmoji('🟧', 'orange square'),
    UnicodeEmoji('🟨', 'yellow square'),
    UnicodeEmoji('🟩', 'green square'),
    UnicodeEmoji('🟦', 'blue square'),
    UnicodeEmoji('🟪', 'purple square'),
    UnicodeEmoji('🟫', 'brown square'),
    UnicodeEmoji('⬛', 'black large square'),
    UnicodeEmoji('⬜', 'white large square'),
    UnicodeEmoji('◼️', 'black medium square'),
    UnicodeEmoji('◻️', 'white medium square'),
    UnicodeEmoji('◾', 'black medium-small square'),
    UnicodeEmoji('◽', 'white medium-small square'),
    UnicodeEmoji('▪️', 'black small square'),
    UnicodeEmoji('▫️', 'white small square'),
    UnicodeEmoji('🔶', 'large orange diamond'),
    UnicodeEmoji('🔷', 'large blue diamond'),
    UnicodeEmoji('🔸', 'small orange diamond'),
    UnicodeEmoji('🔹', 'small blue diamond'),
    UnicodeEmoji('🔺', 'red triangle pointed up'),
    UnicodeEmoji('🔻', 'red triangle pointed down'),
    UnicodeEmoji('💠', 'diamond with a dot'),
    UnicodeEmoji('🔘', 'radio button'),
    UnicodeEmoji('🔳', 'white square button'),
    UnicodeEmoji('🔲', 'black square button'),
  ],
  'Flags': [
    UnicodeEmoji('🏁', 'chequered flag'),
    UnicodeEmoji('🚩', 'triangular flag'),
    UnicodeEmoji('🎌', 'crossed flags'),
    UnicodeEmoji('🏴', 'black flag'),
    UnicodeEmoji('🏳️', 'white flag'),
    UnicodeEmoji('🏳️‍🌈', 'rainbow flag'),
    UnicodeEmoji('🏳️‍⚧️', 'transgender flag'),
    UnicodeEmoji('🏴‍☠️', 'pirate flag'),
    UnicodeEmoji('🇦🇨', 'flag: ascension island'),
    UnicodeEmoji('🇦🇩', 'flag: andorra'),
    UnicodeEmoji('🇦🇪', 'flag: united arab emirates'),
    UnicodeEmoji('🇦🇫', 'flag: afghanistan'),
    UnicodeEmoji('🇦🇬', 'flag: antigua & barbuda'),
    UnicodeEmoji('🇦🇮', 'flag: anguilla'),
    UnicodeEmoji('🇦🇱', 'flag: albania'),
    UnicodeEmoji('🇦🇲', 'flag: armenia'),
    UnicodeEmoji('🇦🇴', 'flag: angola'),
    UnicodeEmoji('🇦🇶', 'flag: antarctica'),
    UnicodeEmoji('🇦🇷', 'flag: argentina'),
    UnicodeEmoji('🇦🇸', 'flag: american samoa'),
    UnicodeEmoji('🇦🇹', 'flag: austria'),
    UnicodeEmoji('🇦🇺', 'flag: australia'),
    UnicodeEmoji('🇦🇼', 'flag: aruba'),
    UnicodeEmoji('🇦🇽', 'flag: åland islands'),
    UnicodeEmoji('🇦🇿', 'flag: azerbaijan'),
    UnicodeEmoji('🇧🇦', 'flag: bosnia & herzegovina'),
    UnicodeEmoji('🇧🇧', 'flag: barbados'),
    UnicodeEmoji('🇧🇩', 'flag: bangladesh'),
    UnicodeEmoji('🇧🇪', 'flag: belgium'),
    UnicodeEmoji('🇧🇫', 'flag: burkina faso'),
    UnicodeEmoji('🇧🇬', 'flag: bulgaria'),
    UnicodeEmoji('🇧🇭', 'flag: bahrain'),
    UnicodeEmoji('🇧🇮', 'flag: burundi'),
    UnicodeEmoji('🇧🇯', 'flag: benin'),
    UnicodeEmoji('🇧🇱', 'flag: st. barthélemy'),
    UnicodeEmoji('🇧🇲', 'flag: bermuda'),
    UnicodeEmoji('🇧🇳', 'flag: brunei'),
    UnicodeEmoji('🇧🇴', 'flag: bolivia'),
    UnicodeEmoji('🇧🇶', 'flag: caribbean netherlands'),
    UnicodeEmoji('🇧🇷', 'flag: brazil'),
    UnicodeEmoji('🇧🇸', 'flag: bahamas'),
    UnicodeEmoji('🇧🇹', 'flag: bhutan'),
    UnicodeEmoji('🇧🇻', 'flag: bouvet island'),
    UnicodeEmoji('🇧🇼', 'flag: botswana'),
    UnicodeEmoji('🇧🇾', 'flag: belarus'),
    UnicodeEmoji('🇧🇿', 'flag: belize'),
    UnicodeEmoji('🇨🇦', 'flag: canada'),
    UnicodeEmoji('🇨🇨', 'flag: cocos (keeling) islands'),
    UnicodeEmoji('🇨🇩', 'flag: congo - kinshasa'),
    UnicodeEmoji('🇨🇫', 'flag: central african republic'),
    UnicodeEmoji('🇨🇬', 'flag: congo - brazzaville'),
    UnicodeEmoji('🇨🇭', 'flag: switzerland'),
    UnicodeEmoji('🇨🇮', 'flag: côte d’ivoire'),
    UnicodeEmoji('🇨🇰', 'flag: cook islands'),
    UnicodeEmoji('🇨🇱', 'flag: chile'),
    UnicodeEmoji('🇨🇲', 'flag: cameroon'),
    UnicodeEmoji('🇨🇳', 'flag: china'),
    UnicodeEmoji('🇨🇴', 'flag: colombia'),
    UnicodeEmoji('🇨🇵', 'flag: clipperton island'),
    UnicodeEmoji('🇨🇶', 'flag: sark'),
    UnicodeEmoji('🇨🇷', 'flag: costa rica'),
    UnicodeEmoji('🇨🇺', 'flag: cuba'),
    UnicodeEmoji('🇨🇻', 'flag: cape verde'),
    UnicodeEmoji('🇨🇼', 'flag: curaçao'),
    UnicodeEmoji('🇨🇽', 'flag: christmas island'),
    UnicodeEmoji('🇨🇾', 'flag: cyprus'),
    UnicodeEmoji('🇨🇿', 'flag: czechia'),
    UnicodeEmoji('🇩🇪', 'flag: germany'),
    UnicodeEmoji('🇩🇬', 'flag: diego garcia'),
    UnicodeEmoji('🇩🇯', 'flag: djibouti'),
    UnicodeEmoji('🇩🇰', 'flag: denmark'),
    UnicodeEmoji('🇩🇲', 'flag: dominica'),
    UnicodeEmoji('🇩🇴', 'flag: dominican republic'),
    UnicodeEmoji('🇩🇿', 'flag: algeria'),
    UnicodeEmoji('🇪🇦', 'flag: ceuta & melilla'),
    UnicodeEmoji('🇪🇨', 'flag: ecuador'),
    UnicodeEmoji('🇪🇪', 'flag: estonia'),
    UnicodeEmoji('🇪🇬', 'flag: egypt'),
    UnicodeEmoji('🇪🇭', 'flag: western sahara'),
    UnicodeEmoji('🇪🇷', 'flag: eritrea'),
    UnicodeEmoji('🇪🇸', 'flag: spain'),
    UnicodeEmoji('🇪🇹', 'flag: ethiopia'),
    UnicodeEmoji('🇪🇺', 'flag: european union'),
    UnicodeEmoji('🇫🇮', 'flag: finland'),
    UnicodeEmoji('🇫🇯', 'flag: fiji'),
    UnicodeEmoji('🇫🇰', 'flag: falkland islands'),
    UnicodeEmoji('🇫🇲', 'flag: micronesia'),
    UnicodeEmoji('🇫🇴', 'flag: faroe islands'),
    UnicodeEmoji('🇫🇷', 'flag: france'),
    UnicodeEmoji('🇬🇦', 'flag: gabon'),
    UnicodeEmoji('🇬🇧', 'flag: united kingdom'),
    UnicodeEmoji('🇬🇩', 'flag: grenada'),
    UnicodeEmoji('🇬🇪', 'flag: georgia'),
    UnicodeEmoji('🇬🇫', 'flag: french guiana'),
    UnicodeEmoji('🇬🇬', 'flag: guernsey'),
    UnicodeEmoji('🇬🇭', 'flag: ghana'),
    UnicodeEmoji('🇬🇮', 'flag: gibraltar'),
    UnicodeEmoji('🇬🇱', 'flag: greenland'),
    UnicodeEmoji('🇬🇲', 'flag: gambia'),
    UnicodeEmoji('🇬🇳', 'flag: guinea'),
    UnicodeEmoji('🇬🇵', 'flag: guadeloupe'),
    UnicodeEmoji('🇬🇶', 'flag: equatorial guinea'),
    UnicodeEmoji('🇬🇷', 'flag: greece'),
    UnicodeEmoji('🇬🇸', 'flag: south georgia & south sandwich islands'),
    UnicodeEmoji('🇬🇹', 'flag: guatemala'),
    UnicodeEmoji('🇬🇺', 'flag: guam'),
    UnicodeEmoji('🇬🇼', 'flag: guinea-bissau'),
    UnicodeEmoji('🇬🇾', 'flag: guyana'),
    UnicodeEmoji('🇭🇰', 'flag: hong kong sar china'),
    UnicodeEmoji('🇭🇲', 'flag: heard & mcdonald islands'),
    UnicodeEmoji('🇭🇳', 'flag: honduras'),
    UnicodeEmoji('🇭🇷', 'flag: croatia'),
    UnicodeEmoji('🇭🇹', 'flag: haiti'),
    UnicodeEmoji('🇭🇺', 'flag: hungary'),
    UnicodeEmoji('🇮🇨', 'flag: canary islands'),
    UnicodeEmoji('🇮🇩', 'flag: indonesia'),
    UnicodeEmoji('🇮🇪', 'flag: ireland'),
    UnicodeEmoji('🇮🇱', 'flag: israel'),
    UnicodeEmoji('🇮🇲', 'flag: isle of man'),
    UnicodeEmoji('🇮🇳', 'flag: india'),
    UnicodeEmoji('🇮🇴', 'flag: british indian ocean territory'),
    UnicodeEmoji('🇮🇶', 'flag: iraq'),
    UnicodeEmoji('🇮🇷', 'flag: iran'),
    UnicodeEmoji('🇮🇸', 'flag: iceland'),
    UnicodeEmoji('🇮🇹', 'flag: italy'),
    UnicodeEmoji('🇯🇪', 'flag: jersey'),
    UnicodeEmoji('🇯🇲', 'flag: jamaica'),
    UnicodeEmoji('🇯🇴', 'flag: jordan'),
    UnicodeEmoji('🇯🇵', 'flag: japan'),
    UnicodeEmoji('🇰🇪', 'flag: kenya'),
    UnicodeEmoji('🇰🇬', 'flag: kyrgyzstan'),
    UnicodeEmoji('🇰🇭', 'flag: cambodia'),
    UnicodeEmoji('🇰🇮', 'flag: kiribati'),
    UnicodeEmoji('🇰🇲', 'flag: comoros'),
    UnicodeEmoji('🇰🇳', 'flag: st. kitts & nevis'),
    UnicodeEmoji('🇰🇵', 'flag: north korea'),
    UnicodeEmoji('🇰🇷', 'flag: south korea'),
    UnicodeEmoji('🇰🇼', 'flag: kuwait'),
    UnicodeEmoji('🇰🇾', 'flag: cayman islands'),
    UnicodeEmoji('🇰🇿', 'flag: kazakhstan'),
    UnicodeEmoji('🇱🇦', 'flag: laos'),
    UnicodeEmoji('🇱🇧', 'flag: lebanon'),
    UnicodeEmoji('🇱🇨', 'flag: st. lucia'),
    UnicodeEmoji('🇱🇮', 'flag: liechtenstein'),
    UnicodeEmoji('🇱🇰', 'flag: sri lanka'),
    UnicodeEmoji('🇱🇷', 'flag: liberia'),
    UnicodeEmoji('🇱🇸', 'flag: lesotho'),
    UnicodeEmoji('🇱🇹', 'flag: lithuania'),
    UnicodeEmoji('🇱🇺', 'flag: luxembourg'),
    UnicodeEmoji('🇱🇻', 'flag: latvia'),
    UnicodeEmoji('🇱🇾', 'flag: libya'),
    UnicodeEmoji('🇲🇦', 'flag: morocco'),
    UnicodeEmoji('🇲🇨', 'flag: monaco'),
    UnicodeEmoji('🇲🇩', 'flag: moldova'),
    UnicodeEmoji('🇲🇪', 'flag: montenegro'),
    UnicodeEmoji('🇲🇫', 'flag: st. martin'),
    UnicodeEmoji('🇲🇬', 'flag: madagascar'),
    UnicodeEmoji('🇲🇭', 'flag: marshall islands'),
    UnicodeEmoji('🇲🇰', 'flag: north macedonia'),
    UnicodeEmoji('🇲🇱', 'flag: mali'),
    UnicodeEmoji('🇲🇲', 'flag: myanmar (burma)'),
    UnicodeEmoji('🇲🇳', 'flag: mongolia'),
    UnicodeEmoji('🇲🇴', 'flag: macao sar china'),
    UnicodeEmoji('🇲🇵', 'flag: northern mariana islands'),
    UnicodeEmoji('🇲🇶', 'flag: martinique'),
    UnicodeEmoji('🇲🇷', 'flag: mauritania'),
    UnicodeEmoji('🇲🇸', 'flag: montserrat'),
    UnicodeEmoji('🇲🇹', 'flag: malta'),
    UnicodeEmoji('🇲🇺', 'flag: mauritius'),
    UnicodeEmoji('🇲🇻', 'flag: maldives'),
    UnicodeEmoji('🇲🇼', 'flag: malawi'),
    UnicodeEmoji('🇲🇽', 'flag: mexico'),
    UnicodeEmoji('🇲🇾', 'flag: malaysia'),
    UnicodeEmoji('🇲🇿', 'flag: mozambique'),
    UnicodeEmoji('🇳🇦', 'flag: namibia'),
    UnicodeEmoji('🇳🇨', 'flag: new caledonia'),
    UnicodeEmoji('🇳🇪', 'flag: niger'),
    UnicodeEmoji('🇳🇫', 'flag: norfolk island'),
    UnicodeEmoji('🇳🇬', 'flag: nigeria'),
    UnicodeEmoji('🇳🇮', 'flag: nicaragua'),
    UnicodeEmoji('🇳🇱', 'flag: netherlands'),
    UnicodeEmoji('🇳🇴', 'flag: norway'),
    UnicodeEmoji('🇳🇵', 'flag: nepal'),
    UnicodeEmoji('🇳🇷', 'flag: nauru'),
    UnicodeEmoji('🇳🇺', 'flag: niue'),
    UnicodeEmoji('🇳🇿', 'flag: new zealand'),
    UnicodeEmoji('🇴🇲', 'flag: oman'),
    UnicodeEmoji('🇵🇦', 'flag: panama'),
    UnicodeEmoji('🇵🇪', 'flag: peru'),
    UnicodeEmoji('🇵🇫', 'flag: french polynesia'),
    UnicodeEmoji('🇵🇬', 'flag: papua new guinea'),
    UnicodeEmoji('🇵🇭', 'flag: philippines'),
    UnicodeEmoji('🇵🇰', 'flag: pakistan'),
    UnicodeEmoji('🇵🇱', 'flag: poland'),
    UnicodeEmoji('🇵🇲', 'flag: st. pierre & miquelon'),
    UnicodeEmoji('🇵🇳', 'flag: pitcairn islands'),
    UnicodeEmoji('🇵🇷', 'flag: puerto rico'),
    UnicodeEmoji('🇵🇸', 'flag: palestinian territories'),
    UnicodeEmoji('🇵🇹', 'flag: portugal'),
    UnicodeEmoji('🇵🇼', 'flag: palau'),
    UnicodeEmoji('🇵🇾', 'flag: paraguay'),
    UnicodeEmoji('🇶🇦', 'flag: qatar'),
    UnicodeEmoji('🇷🇪', 'flag: réunion'),
    UnicodeEmoji('🇷🇴', 'flag: romania'),
    UnicodeEmoji('🇷🇸', 'flag: serbia'),
    UnicodeEmoji('🇷🇺', 'flag: russia'),
    UnicodeEmoji('🇷🇼', 'flag: rwanda'),
    UnicodeEmoji('🇸🇦', 'flag: saudi arabia'),
    UnicodeEmoji('🇸🇧', 'flag: solomon islands'),
    UnicodeEmoji('🇸🇨', 'flag: seychelles'),
    UnicodeEmoji('🇸🇩', 'flag: sudan'),
    UnicodeEmoji('🇸🇪', 'flag: sweden'),
    UnicodeEmoji('🇸🇬', 'flag: singapore'),
    UnicodeEmoji('🇸🇭', 'flag: st. helena'),
    UnicodeEmoji('🇸🇮', 'flag: slovenia'),
    UnicodeEmoji('🇸🇯', 'flag: svalbard & jan mayen'),
    UnicodeEmoji('🇸🇰', 'flag: slovakia'),
    UnicodeEmoji('🇸🇱', 'flag: sierra leone'),
    UnicodeEmoji('🇸🇲', 'flag: san marino'),
    UnicodeEmoji('🇸🇳', 'flag: senegal'),
    UnicodeEmoji('🇸🇴', 'flag: somalia'),
    UnicodeEmoji('🇸🇷', 'flag: suriname'),
    UnicodeEmoji('🇸🇸', 'flag: south sudan'),
    UnicodeEmoji('🇸🇹', 'flag: são tomé & príncipe'),
    UnicodeEmoji('🇸🇻', 'flag: el salvador'),
    UnicodeEmoji('🇸🇽', 'flag: sint maarten'),
    UnicodeEmoji('🇸🇾', 'flag: syria'),
    UnicodeEmoji('🇸🇿', 'flag: eswatini'),
    UnicodeEmoji('🇹🇦', 'flag: tristan da cunha'),
    UnicodeEmoji('🇹🇨', 'flag: turks & caicos islands'),
    UnicodeEmoji('🇹🇩', 'flag: chad'),
    UnicodeEmoji('🇹🇫', 'flag: french southern territories'),
    UnicodeEmoji('🇹🇬', 'flag: togo'),
    UnicodeEmoji('🇹🇭', 'flag: thailand'),
    UnicodeEmoji('🇹🇯', 'flag: tajikistan'),
    UnicodeEmoji('🇹🇰', 'flag: tokelau'),
    UnicodeEmoji('🇹🇱', 'flag: timor-leste'),
    UnicodeEmoji('🇹🇲', 'flag: turkmenistan'),
    UnicodeEmoji('🇹🇳', 'flag: tunisia'),
    UnicodeEmoji('🇹🇴', 'flag: tonga'),
    UnicodeEmoji('🇹🇷', 'flag: türkiye'),
    UnicodeEmoji('🇹🇹', 'flag: trinidad & tobago'),
    UnicodeEmoji('🇹🇻', 'flag: tuvalu'),
    UnicodeEmoji('🇹🇼', 'flag: taiwan'),
    UnicodeEmoji('🇹🇿', 'flag: tanzania'),
    UnicodeEmoji('🇺🇦', 'flag: ukraine'),
    UnicodeEmoji('🇺🇬', 'flag: uganda'),
    UnicodeEmoji('🇺🇲', 'flag: u.s. outlying islands'),
    UnicodeEmoji('🇺🇳', 'flag: united nations'),
    UnicodeEmoji('🇺🇸', 'flag: united states'),
    UnicodeEmoji('🇺🇾', 'flag: uruguay'),
    UnicodeEmoji('🇺🇿', 'flag: uzbekistan'),
    UnicodeEmoji('🇻🇦', 'flag: vatican city'),
    UnicodeEmoji('🇻🇨', 'flag: st. vincent & grenadines'),
    UnicodeEmoji('🇻🇪', 'flag: venezuela'),
    UnicodeEmoji('🇻🇬', 'flag: british virgin islands'),
    UnicodeEmoji('🇻🇮', 'flag: u.s. virgin islands'),
    UnicodeEmoji('🇻🇳', 'flag: vietnam'),
    UnicodeEmoji('🇻🇺', 'flag: vanuatu'),
    UnicodeEmoji('🇼🇫', 'flag: wallis & futuna'),
    UnicodeEmoji('🇼🇸', 'flag: samoa'),
    UnicodeEmoji('🇽🇰', 'flag: kosovo'),
    UnicodeEmoji('🇾🇪', 'flag: yemen'),
    UnicodeEmoji('🇾🇹', 'flag: mayotte'),
    UnicodeEmoji('🇿🇦', 'flag: south africa'),
    UnicodeEmoji('🇿🇲', 'flag: zambia'),
    UnicodeEmoji('🇿🇼', 'flag: zimbabwe'),
    UnicodeEmoji('🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'flag: england'),
    UnicodeEmoji('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'flag: scotland'),
    UnicodeEmoji('🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'flag: wales'),
  ],
};
