# Generates assets/rust_licenses.txt, the Rust half of the app's licenses page.
# Run from rust/hollow_core with the features the app ships (cargokit.yaml):
#   cargo about generate --locked --features forwarder about.hbs -o ../../assets/rust_licenses.txt
# cargo-about 0.6.6 drops deep_filter's optional rust-ini subtree (rust-ini,
# ordered-multimap, dlv-list, hashbrown 0.13, const-random); those are
# credited by hand in assets/extra_licenses.txt, with the native libraries.

accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
    "BSL-1.0",
    "CC0-1.0",
    "OpenSSL",
    "MPL-2.0",
    "BlueOak-1.0.0",
    "CDLA-Permissive-2.0",
]
