import os
from pathlib import Path

PROJECT_ROOT = Path("C:/Users/Jabun/Documents/Coding/HOLLOW")
TOOL_DIR = Path(__file__).parent

# Doc sources
MEMORY_DIR = Path("C:/Users/Jabun/.claude/projects/C--Users-Jabun-Documents-Coding-HOLLOW/memory")
HOLLOW_PLAN_PATH = PROJECT_ROOT / "HOLLOW_PLAN.md"
WHITEPAPER_PATH = PROJECT_ROOT / "WHITEPAPER.md"
CLAUDE_MD_PATH = PROJECT_ROOT / "CLAUDE.md"
WIKI_DIR = TOOL_DIR / "wiki"
REPORTS_DIR = PROJECT_ROOT / "reports"
# Generated by scripts/ui_nav_map.ps1; its uniform rows crowd out real answers.
REPORTS_SKIP = {"UI_NAVIGATION_MAP.md"}

# Code sources (git-tracked files only)
CODE_ROOTS = ["rust/hollow_core/src", "lib", "relay-uws/src"]
CODE_EXTENSIONS = (".rs", ".dart", ".cpp", ".h")
CODE_SKIP_PREFIXES = ("lib/src/rust/",)
CODE_SKIP_NAMES = {"frb_generated.rs", "json.hpp"}

# A new file, so a session still running the old MiniLM server keeps its own index.
DB_PATH = TOOL_DIR / "hollow_memory_v2.db"

MODEL_ID = "Qwen/Qwen3-Embedding-0.6B"
EMBEDDING_DIM = 1024
MAX_SEQ_TOKENS = 2048
MAX_CHUNK_CHARS = 3500
DOC_QUERY_PROMPT = "Instruct: Given a question about a software project, retrieve the notes or design passage that answers it\nQuery:"
CODE_QUERY_PROMPT = "Instruct: Given a description of what some code does, retrieve the code snippet that does it\nQuery:"

# Free the GPU after this long without a query or reindex.
IDLE_UNLOAD_SECS = int(os.environ.get("HOLLOW_MEMORY_IDLE_SECS", "600"))
# Chunks a search may re-embed before answering; the rest catch up on later searches.
SEARCH_REFRESH_BUDGET = 400
