import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// Adds what Flutter's own license list cannot see to the licenses page.
///
/// `assets/rust_licenses.txt` is generated by cargo-about from
/// `rust/hollow_core` (see `about.toml`). `assets/extra_licenses.txt` is kept
/// by hand: the native libraries the app bundles (OpenSSL, SQLCipher, WebRTC
/// and everything linked into libwebrtc, the FFmpeg binaries, libwebp, the
/// notices inside the Firebase and Play services AARs), the fonts, and the
/// Rust crates cargo-about leaves out of its graph. Both use the same format.
void registerRustLicenses() {
  LicenseRegistry.addLicense(() async* {
    for (final asset in const [
      'assets/rust_licenses.txt',
      'assets/extra_licenses.txt',
    ]) {
      yield* Stream.fromIterable(
          parseLicenseFile(await rootBundle.loadString(asset)));
    }
  });
}

/// The entries of one license file in the cargo-about template's format.
@visibleForTesting
List<LicenseEntry> parseLicenseFile(String data) {
  final entries = <LicenseEntry>[];
  for (final entry in data.split('====LICENSE_START====')) {
    if (!entry.contains('---TEXT---')) continue;

    final headerAndText = entry.split('---TEXT---');
    if (headerAndText.length < 2) continue;

    final header = headerAndText[0];
    final text =
        headerAndText[1].replaceFirst('====LICENSE_END====', '').trim();

    if (text.isEmpty) continue;

    final packages = <String>[];
    for (final line in header.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.isNotEmpty &&
          !trimmed.startsWith('License:') &&
          !trimmed.startsWith('Used by:')) {
        packages.add(trimmed);
      }
    }

    if (packages.isEmpty) continue;

    entries.add(LicenseEntryWithLineBreaks(packages, text));
  }
  return entries;
}
