// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `under_data_root`

Future<Uint8List> readAtRest({required String path}) =>
    RustLib.instance.api.crateApiAtRestReadAtRest(path: path);

Future<Uint8List> readAtRestRange({
  required String path,
  required BigInt offset,
  required int len,
}) => RustLib.instance.api.crateApiAtRestReadAtRestRange(
  path: path,
  offset: offset,
  len: len,
);

Future<void> writeAtRest({required String path, required List<int> bytes}) =>
    RustLib.instance.api.crateApiAtRestWriteAtRest(path: path, bytes: bytes);

Future<void> removeAtRest({required String path}) =>
    RustLib.instance.api.crateApiAtRestRemoveAtRest(path: path);

Future<BigInt> exportAtRest({
  required String srcPath,
  required String destPath,
}) => RustLib.instance.api.crateApiAtRestExportAtRest(
  srcPath: srcPath,
  destPath: destPath,
);

Future<BigInt> atRestPlaintextLen({required String path}) =>
    RustLib.instance.api.crateApiAtRestAtRestPlaintextLen(path: path);

Future<String> atRestMediaUrl({required String path}) =>
    RustLib.instance.api.crateApiAtRestAtRestMediaUrl(path: path);

Future<AtRestStatus> atRestStatus() =>
    RustLib.instance.api.crateApiAtRestAtRestStatus();

/// Progress of the one-per-boot sweep that protects files an older version left
/// in plaintext.
class AtRestStatus {
  final int total;
  final int done;
  final int failed;
  final bool running;

  const AtRestStatus({
    required this.total,
    required this.done,
    required this.failed,
    required this.running,
  });

  @override
  int get hashCode =>
      total.hashCode ^ done.hashCode ^ failed.hashCode ^ running.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AtRestStatus &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          done == other.done &&
          failed == other.failed &&
          running == other.running;
}
