// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `send_command`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Create or update a conference room.
///
/// `conf_id: None` creates a new room with a random unguessable id (the link
/// capability). `access_code` follows the profile COALESCE convention:
/// `None` = keep the existing code, `Some("")` = clear it, `Some(code)` = set
/// (stored as a conf-scoped hash, never plaintext).
Future<ConferenceInfo> conferenceUpsert({
  String? confId,
  required String name,
  required bool waitingRoom,
  String? accessCode,
  required bool broadcastMode,
}) => RustLib.instance.api.crateApiConferenceConferenceUpsert(
  confId: confId,
  name: name,
  waitingRoom: waitingRoom,
  accessCode: accessCode,
  broadcastMode: broadcastMode,
);

/// List this device's conference rooms (newest first).
Future<List<ConferenceInfo>> conferenceList() =>
    RustLib.instance.api.crateApiConferenceConferenceList();

/// Delete a room — retires its link forever.
Future<void> conferenceDelete({required String confId}) =>
    RustLib.instance.api.crateApiConferenceConferenceDelete(confId: confId);

/// (Host) start a meeting: mints a FRESH MLS group + joins the relay room.
/// Follow up with `voice_channel_join("conf:{conf_id}", "main")` from Dart.
Future<void> conferenceStart({
  required String confId,
  required String hostDisplayName,
  required String hostAvatarHash,
}) => RustLib.instance.api.crateApiConferenceConferenceStart(
  confId: confId,
  hostDisplayName: hostDisplayName,
  hostAvatarHash: hostAvatarHash,
);

/// (Host) end the meeting for everyone.
Future<void> conferenceEnd({required String confId}) =>
    RustLib.instance.api.crateApiConferenceConferenceEnd(confId: confId);

/// (Joiner) knock: enter the relay room and send a join request. Watch for
/// `ConferenceLobbyInfo` / `ConferenceAdmitted` / `ConferenceJoinDenied`.
Future<void> conferenceRequestJoin({
  required String confId,
  required String displayName,
  required String avatarHash,
  String? accessCode,
}) => RustLib.instance.api.crateApiConferenceConferenceRequestJoin(
  confId: confId,
  displayName: displayName,
  avatarHash: avatarHash,
  accessCode: accessCode,
);

/// (Host) admit a waiting-room entry — commits the MLS add.
Future<void> conferenceAdmit({
  required String confId,
  required String peerId,
}) => RustLib.instance.api.crateApiConferenceConferenceAdmit(
  confId: confId,
  peerId: peerId,
);

/// (Host) decline a waiting-room entry.
Future<void> conferenceDeny({
  required String confId,
  required String peerId,
  required String reason,
}) => RustLib.instance.api.crateApiConferenceConferenceDeny(
  confId: confId,
  peerId: peerId,
  reason: reason,
);

/// (Host) remove a CURRENT member — MLS remove commit + teardown signal.
Future<void> conferenceKick({required String confId, required String peerId}) =>
    RustLib.instance.api.crateApiConferenceConferenceKick(
      confId: confId,
      peerId: peerId,
    );

/// (Joiner) leave the conference room (also voice_channel_leave from Dart).
Future<void> conferenceLeave({required String confId}) =>
    RustLib.instance.api.crateApiConferenceConferenceLeave(confId: confId);

/// Send a RAM-only conference chat line (MLS application message).
Future<PlatformInt64> conferenceSendChat({
  required String confId,
  required String text,
}) => RustLib.instance.api.crateApiConferenceConferenceSendChat(
  confId: confId,
  text: text,
);

/// FFI-facing room descriptor. The access code never leaves Rust — Dart only
/// learns whether one is set.
class ConferenceInfo {
  final String confId;
  final String name;
  final bool waitingRoom;
  final bool hasAccessCode;
  final bool broadcastMode;
  final PlatformInt64 createdAt;

  const ConferenceInfo({
    required this.confId,
    required this.name,
    required this.waitingRoom,
    required this.hasAccessCode,
    required this.broadcastMode,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      confId.hashCode ^
      name.hashCode ^
      waitingRoom.hashCode ^
      hasAccessCode.hashCode ^
      broadcastMode.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConferenceInfo &&
          runtimeType == other.runtimeType &&
          confId == other.confId &&
          name == other.name &&
          waitingRoom == other.waitingRoom &&
          hasAccessCode == other.hasAccessCode &&
          broadcastMode == other.broadcastMode &&
          createdAt == other.createdAt;
}
