// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a new server. Returns the server_id.
Future<String> createServer({required String name}) =>
    RustLib.instance.api.crateApiCrdtCreateServer(name: name);

/// Create a channel in a server. Returns "pending" (actual channel_id comes via event).
Future<String> createChannel({
  required String serverId,
  required String name,
  String? category,
}) => RustLib.instance.api.crateApiCrdtCreateChannel(
  serverId: serverId,
  name: name,
  category: category,
);

/// Remove a channel from a server.
Future<void> removeChannel({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiCrdtRemoveChannel(
  serverId: serverId,
  channelId: channelId,
);

/// Get all servers the user has joined. Reads from the local DB.
Future<List<ServerFfi>> getJoinedServers() =>
    RustLib.instance.api.crateApiCrdtGetJoinedServers();

/// Get channels for a specific server. Reads from the local DB.
Future<List<ChannelFfi>> getServerChannels({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerChannels(serverId: serverId);

/// Get members for a specific server. Reads from the local DB.
Future<List<MemberFfi>> getServerMembers({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerMembers(serverId: serverId);

/// Channel info for FFI (Dart-visible).
class ChannelFfi {
  final String channelId;
  final String name;
  final String? category;

  const ChannelFfi({
    required this.channelId,
    required this.name,
    this.category,
  });

  @override
  int get hashCode => channelId.hashCode ^ name.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          name == other.name &&
          category == other.category;
}

/// Member info for FFI (Dart-visible).
class MemberFfi {
  final String peerId;
  final String displayName;
  final String role;

  const MemberFfi({
    required this.peerId,
    required this.displayName,
    required this.role,
  });

  @override
  int get hashCode => peerId.hashCode ^ displayName.hashCode ^ role.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          role == other.role;
}

/// Server info for FFI (Dart-visible).
class ServerFfi {
  final String serverId;
  final String name;
  final int memberCount;
  final int channelCount;

  const ServerFfi({
    required this.serverId,
    required this.name,
    required this.memberCount,
    required this.channelCount,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      name.hashCode ^
      memberCount.hashCode ^
      channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerFfi &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          name == other.name &&
          memberCount == other.memberCount &&
          channelCount == other.channelCount;
}
