// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a new server. Returns the server_id.
Future<String> createServer({required String name}) =>
    RustLib.instance.api.crateApiCrdtCreateServer(name: name);

/// Create a channel in a server. Returns "pending" (actual channel_id comes via event).
Future<String> createChannel({
  required String serverId,
  required String name,
  String? category,
  required String channelType,
}) => RustLib.instance.api.crateApiCrdtCreateChannel(
  serverId: serverId,
  name: name,
  category: category,
  channelType: channelType,
);

/// Remove a channel from a server.
Future<void> removeChannel({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiCrdtRemoveChannel(
  serverId: serverId,
  channelId: channelId,
);

/// Get all servers the user has joined. Reads from the local DB.
Future<List<ServerFfi>> getJoinedServers() =>
    RustLib.instance.api.crateApiCrdtGetJoinedServers();

/// Get channels for a specific server. Reads from the local DB.
Future<List<ChannelFfi>> getServerChannels({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerChannels(serverId: serverId);

/// Get members for a specific server. Reads from the local DB.
Future<List<MemberFfi>> getServerMembers({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerMembers(serverId: serverId);

/// Get a server setting value by key. Returns empty string if not set.
Future<String> getServerSetting({
  required String serverId,
  required String key,
}) => RustLib.instance.api.crateApiCrdtGetServerSetting(
  serverId: serverId,
  key: key,
);

/// Rename a server.
Future<void> renameServer({
  required String serverId,
  required String newName,
}) => RustLib.instance.api.crateApiCrdtRenameServer(
  serverId: serverId,
  newName: newName,
);

/// Rename a channel in a server.
Future<void> renameChannel({
  required String serverId,
  required String channelId,
  required String newName,
}) => RustLib.instance.api.crateApiCrdtRenameChannel(
  serverId: serverId,
  channelId: channelId,
  newName: newName,
);

/// Update a server setting (key-value pair).
Future<void> updateServerSetting({
  required String serverId,
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiCrdtUpdateServerSetting(
  serverId: serverId,
  key: key,
  value: value,
);

/// Set a server avatar. Processes the raw image to 128x128 WebP and stores via CRDT.
Future<void> setServerAvatar({
  required String serverId,
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiCrdtSetServerAvatar(
  serverId: serverId,
  rawBytes: rawBytes,
);

/// Clear a server avatar.
Future<void> clearServerAvatar({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtClearServerAvatar(serverId: serverId);

/// Get a server avatar as raw bytes. Returns None if no avatar set.
Future<Uint8List?> getServerAvatar({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerAvatar(serverId: serverId);

/// Set a server banner (issue #25). Processes the raw image (3:1 center
/// crop → 960x320 WebP, animated allowed), caches the blob content-addressed
/// with kind='banner', and writes ONLY the hash into CRDT settings.
Future<void> setServerBanner({
  required String serverId,
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiCrdtSetServerBanner(
  serverId: serverId,
  rawBytes: rawBytes,
);

/// Clear a server banner. The blob stays cached until asset-cache eviction
/// collects it (it drops out of `referenced_asset_hashes`).
Future<void> clearServerBanner({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtClearServerBanner(serverId: serverId);

/// Get the server banner. `None` = no banner set (or cleared); `bytes` is
/// `None` when the hash is known but the blob hasn't been pulled yet.
Future<ServerBannerData?> getServerBanner({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerBanner(serverId: serverId);

/// Join a server via invite link. Connects to the server's signaling room and
/// requests membership from existing members.
Future<void> joinServer({
  required String serverId,
  String? twitchProofJson,
  required bool nsfwConfirmed,
}) => RustLib.instance.api.crateApiCrdtJoinServer(
  serverId: serverId,
  twitchProofJson: twitchProofJson,
  nsfwConfirmed: nsfwConfirmed,
);

/// Get the local user's role in a server.
/// Returns "owner", "admin", "moderator", or "member".
Future<String> getMyRole({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetMyRole(serverId: serverId);

/// Get the local user's permissions bitmask in a server.
Future<int> getMyPermissions({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetMyPermissions(serverId: serverId);

/// Change a member's role in a server.
/// Requires MANAGE_ROLES permission and must outrank the target.
Future<void> changeMemberRole({
  required String serverId,
  required String peerId,
  required String newRole,
}) => RustLib.instance.api.crateApiCrdtChangeMemberRole(
  serverId: serverId,
  peerId: peerId,
  newRole: newRole,
);

/// Kick a member from a server.
/// Requires KICK_MEMBERS permission and must outrank the target.
Future<void> kickMember({required String serverId, required String peerId}) =>
    RustLib.instance.api.crateApiCrdtKickMember(
      serverId: serverId,
      peerId: peerId,
    );

/// Set a member's server nickname. Pass an empty string to clear.
Future<void> setNickname({
  required String serverId,
  required String peerId,
  required String nickname,
}) => RustLib.instance.api.crateApiCrdtSetNickname(
  serverId: serverId,
  peerId: peerId,
  nickname: nickname,
);

Future<void> setTwitchUsername({
  required String serverId,
  required String peerId,
  required String twitchUsername,
}) => RustLib.instance.api.crateApiCrdtSetTwitchUsername(
  serverId: serverId,
  peerId: peerId,
  twitchUsername: twitchUsername,
);

/// Update the channel layout (ordering/categories) for a server.
/// layout_json is a JSON array of ChannelLayoutItem objects.
Future<void> updateChannelLayout({
  required String serverId,
  required String layoutJson,
}) => RustLib.instance.api.crateApiCrdtUpdateChannelLayout(
  serverId: serverId,
  layoutJson: layoutJson,
);

/// Get the channel layout for a server. Returns a JSON array of ChannelLayoutItem.
Future<String> getChannelLayout({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetChannelLayout(serverId: serverId);

/// Pin a message in a channel. Requires MANAGE_CHANNELS permission.
Future<void> pinMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiCrdtPinMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Unpin a message from a channel. Requires MANAGE_CHANNELS permission.
Future<void> unpinMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiCrdtUnpinMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Get pinned message IDs for a channel.
Future<List<String>> getPinnedMessages({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiCrdtGetPinnedMessages(
  serverId: serverId,
  channelId: channelId,
);

/// Delete a server entirely (removes from local DB and memory).
Future<void> deleteServer({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtDeleteServer(serverId: serverId);

/// Create a new label (cosmetic role) in a server.
Future<void> createLabel({
  required String serverId,
  required String name,
  required String color,
}) => RustLib.instance.api.crateApiCrdtCreateLabel(
  serverId: serverId,
  name: name,
  color: color,
);

/// Delete a label from a server.
Future<void> deleteLabel({required String serverId, required String labelId}) =>
    RustLib.instance.api.crateApiCrdtDeleteLabel(
      serverId: serverId,
      labelId: labelId,
    );

/// Update a label's name and color.
Future<void> updateLabel({
  required String serverId,
  required String labelId,
  required String name,
  required String color,
}) => RustLib.instance.api.crateApiCrdtUpdateLabel(
  serverId: serverId,
  labelId: labelId,
  name: name,
  color: color,
);

/// Assign a label to a member.
Future<void> assignLabel({
  required String serverId,
  required String labelId,
  required String peerId,
}) => RustLib.instance.api.crateApiCrdtAssignLabel(
  serverId: serverId,
  labelId: labelId,
  peerId: peerId,
);

/// Remove a label from a member.
Future<void> unassignLabel({
  required String serverId,
  required String labelId,
  required String peerId,
}) => RustLib.instance.api.crateApiCrdtUnassignLabel(
  serverId: serverId,
  labelId: labelId,
  peerId: peerId,
);

/// Get all labels defined in a server.
Future<List<LabelFfi>> getServerLabels({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetServerLabels(serverId: serverId);

/// Set the visibility mode for a channel (everyone/moderator/admin).
Future<void> setChannelVisibility({
  required String serverId,
  required String channelId,
  required String visibility,
}) => RustLib.instance.api.crateApiCrdtSetChannelVisibility(
  serverId: serverId,
  channelId: channelId,
  visibility: visibility,
);

/// Set the posting mode for a channel (everyone/moderator/admin).
Future<void> setChannelPosting({
  required String serverId,
  required String channelId,
  required String posting,
}) => RustLib.instance.api.crateApiCrdtSetChannelPosting(
  serverId: serverId,
  channelId: channelId,
  posting: posting,
);

/// Toggle public access for a channel.
Future<void> setChannelPublic({
  required String serverId,
  required String channelId,
  required bool isPublic,
}) => RustLib.instance.api.crateApiCrdtSetChannelPublic(
  serverId: serverId,
  channelId: channelId,
  isPublic: isPublic,
);

/// Request the public channel list from a server (guest mode).
/// Joins the WS room and broadcasts a list request to online members.
Future<void> requestPublicChannels({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtRequestPublicChannels(serverId: serverId);

/// Request message history for a public channel (guest mode).
Future<void> requestPublicChannelSync({
  required String serverId,
  required String channelId,
  PlatformInt64? beforeTimestamp,
}) => RustLib.instance.api.crateApiCrdtRequestPublicChannelSync(
  serverId: serverId,
  channelId: channelId,
  beforeTimestamp: beforeTimestamp,
);

/// Leave a guest-mode WS room.
Future<void> leaveGuestRoom({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtLeaveGuestRoom(serverId: serverId);

/// Ban a member from the server. Prevents rejoin.
Future<void> banMember({required String serverId, required String peerId}) =>
    RustLib.instance.api.crateApiCrdtBanMember(
      serverId: serverId,
      peerId: peerId,
    );

/// Unban a member, allowing them to rejoin.
Future<void> unbanMember({required String serverId, required String peerId}) =>
    RustLib.instance.api.crateApiCrdtUnbanMember(
      serverId: serverId,
      peerId: peerId,
    );

/// Get the list of banned peer IDs for a server.
Future<List<String>> getBannedMembers({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetBannedMembers(serverId: serverId);

/// Mute a member server-wide (read-only: they can't post in any channel).
/// `duration_secs <= 0` = permanent mute; otherwise the mute expires
/// `duration_secs` from now.
Future<void> muteMember({
  required String serverId,
  required String peerId,
  required PlatformInt64 durationSecs,
}) => RustLib.instance.api.crateApiCrdtMuteMember(
  serverId: serverId,
  peerId: peerId,
  durationSecs: durationSecs,
);

/// Unmute a member.
Future<void> unmuteMember({required String serverId, required String peerId}) =>
    RustLib.instance.api.crateApiCrdtUnmuteMember(
      serverId: serverId,
      peerId: peerId,
    );

/// Get the currently active mutes for a server.
Future<List<MutedMemberFfi>> getMutedMembers({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetMutedMembers(serverId: serverId);

/// Set a channel's slow-mode interval in seconds (0 = off). Moderator+ exempt.
Future<void> setChannelSlowMode({
  required String serverId,
  required String channelId,
  required int seconds,
}) => RustLib.instance.api.crateApiCrdtSetChannelSlowMode(
  serverId: serverId,
  channelId: channelId,
  seconds: seconds,
);

/// Toggle a channel's media-only mode (only images/GIFs/videos may be posted).
Future<void> setChannelMediaOnly({
  required String serverId,
  required String channelId,
  required bool mediaOnly,
}) => RustLib.instance.api.crateApiCrdtSetChannelMediaOnly(
  serverId: serverId,
  channelId: channelId,
  mediaOnly: mediaOnly,
);

/// Change the permissions bitmask for a role. Owner-only.
Future<void> changeRolePermissions({
  required String serverId,
  required String role,
  required int permissions,
}) => RustLib.instance.api.crateApiCrdtChangeRolePermissions(
  serverId: serverId,
  role: role,
  permissions: permissions,
);

/// Get the permissions bitmask for a role (custom or default).
Future<int> getRolePermissions({
  required String serverId,
  required String role,
}) => RustLib.instance.api.crateApiCrdtGetRolePermissions(
  serverId: serverId,
  role: role,
);

/// Default permissions bitmask for a role name — the single source of truth
/// for the Dart Roles UIs (Reset button + pre-load fallback). Pure function,
/// no store needed. "owner" → ALL; unknown strings fall back to Member
/// (MemberRole::from_str semantics).
int defaultRolePermissions({required String role}) =>
    RustLib.instance.api.crateApiCrdtDefaultRolePermissions(role: role);

/// Leave a server. The local user is removed from the server.
/// Owner cannot leave — must delete or transfer ownership first.
Future<void> leaveServer({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtLeaveServer(serverId: serverId);

/// Set the local user's storage pledge for a server (in bytes).
Future<void> setStoragePledge({
  required String serverId,
  required BigInt pledgeBytes,
}) => RustLib.instance.api.crateApiCrdtSetStoragePledge(
  serverId: serverId,
  pledgeBytes: pledgeBytes,
);

/// Get storage stats for a server (pledges from CRDT state, usage from vault_shards table).
Future<StorageStatsFfi> getStorageStats({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtGetStorageStats(serverId: serverId);

/// Get vault file statuses for a server — shows which erasure-coded files
/// exist, how many shards are held locally, and whether each is reconstructable.
/// Used by the Archive tab's shard status indicator (Evidence Recovery).
Future<List<VaultFileStatusFfi>> getVaultFileStatuses({
  required String serverId,
}) => RustLib.instance.api.crateApiCrdtGetVaultFileStatuses(serverId: serverId);

/// Initiate a recovery pool for a server. Generates a random token,
/// joins the WSS relay room, and returns the invite link.
Future<String> initiateRecoveryPool({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtInitiateRecoveryPool(serverId: serverId);

/// Join an existing recovery pool via invite link.
/// Link format: `hollow://recovery?server={server_id}&token={token}`
Future<void> joinRecoveryPool({required String inviteLink}) =>
    RustLib.instance.api.crateApiCrdtJoinRecoveryPool(inviteLink: inviteLink);

/// Stop an active recovery pool.
Future<void> stopRecoveryPool({required String serverId}) =>
    RustLib.instance.api.crateApiCrdtStopRecoveryPool(serverId: serverId);

/// Delete vault content from a server (admin-only, requires MANAGE_SERVER).
/// Broadcasts ShardDelete to all connected members and removes local shards.
Future<void> deleteVaultContent({
  required String serverId,
  required String contentId,
}) => RustLib.instance.api.crateApiCrdtDeleteVaultContent(
  serverId: serverId,
  contentId: contentId,
);

/// Upload a file to the vault. Encrypts with AES-256-GCM, computes content_id,
/// then sends to swarm for erasure coding + distribution + manifest broadcast.
/// Returns the content_id immediately.
Future<String> vaultUploadFile({
  required String serverId,
  required String channelId,
  required String filePath,
  required String messageId,
}) => RustLib.instance.api.crateApiCrdtVaultUploadFile(
  serverId: serverId,
  channelId: channelId,
  filePath: filePath,
  messageId: messageId,
);

/// Download a vault file. Checks local cache first, then attempts local reconstruction.
/// Returns the disk path if the file is available locally (cache hit or reconstructable
/// from local shards). Returns empty string if async network fetch is needed (Dart
/// watches VaultDownloadComplete event for the disk_path).
Future<String> vaultDownloadFile({
  required String serverId,
  required String contentId,
}) => RustLib.instance.api.crateApiCrdtVaultDownloadFile(
  serverId: serverId,
  contentId: contentId,
);

/// Channel info for FFI (Dart-visible).
class ChannelFfi {
  final String channelId;
  final String name;
  final String? category;
  final String channelType;
  final String visibility;
  final String posting;
  final bool isPublic;
  final int slowMode;
  final bool mediaOnly;

  const ChannelFfi({
    required this.channelId,
    required this.name,
    this.category,
    required this.channelType,
    required this.visibility,
    required this.posting,
    required this.isPublic,
    required this.slowMode,
    required this.mediaOnly,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      name.hashCode ^
      category.hashCode ^
      channelType.hashCode ^
      visibility.hashCode ^
      posting.hashCode ^
      isPublic.hashCode ^
      slowMode.hashCode ^
      mediaOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          name == other.name &&
          category == other.category &&
          channelType == other.channelType &&
          visibility == other.visibility &&
          posting == other.posting &&
          isPublic == other.isPublic &&
          slowMode == other.slowMode &&
          mediaOnly == other.mediaOnly;
}

/// Label info for FFI (Dart-visible).
class LabelFfi {
  final String labelId;
  final String name;
  final String color;

  const LabelFfi({
    required this.labelId,
    required this.name,
    required this.color,
  });

  @override
  int get hashCode => labelId.hashCode ^ name.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LabelFfi &&
          runtimeType == other.runtimeType &&
          labelId == other.labelId &&
          name == other.name &&
          color == other.color;
}

/// Member info for FFI (Dart-visible).
class MemberFfi {
  final String peerId;
  final String displayName;
  final String role;
  final String nickname;
  final String twitchUsername;
  final List<LabelFfi> labels;

  const MemberFfi({
    required this.peerId,
    required this.displayName,
    required this.role,
    required this.nickname,
    required this.twitchUsername,
    required this.labels,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      displayName.hashCode ^
      role.hashCode ^
      nickname.hashCode ^
      twitchUsername.hashCode ^
      labels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemberFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          role == other.role &&
          nickname == other.nickname &&
          twitchUsername == other.twitchUsername &&
          labels == other.labels;
}

/// A muted member for FFI (Dart-visible). `permanent` = no expiry;
/// otherwise `expires_at_ms` is the epoch-ms expiry.
class MutedMemberFfi {
  final String peerId;
  final PlatformInt64 expiresAtMs;
  final bool permanent;

  const MutedMemberFfi({
    required this.peerId,
    required this.expiresAtMs,
    required this.permanent,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^ expiresAtMs.hashCode ^ permanent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MutedMemberFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          expiresAtMs == other.expiresAtMs &&
          permanent == other.permanent;
}

/// Server banner as seen locally. The CRDT carries only the hash; bytes
/// live in the content-addressed asset store (kind='banner') and replicate
/// via the asset rail — never through the CRDT.
class ServerBannerData {
  /// 64-hex SHA-256 of the processed WebP bytes.
  final String hash;
  final bool animated;

  /// Cached blob bytes, if we hold them. `None` = pull via
  /// `request_assets(kind: "banner")` and re-read on `EmoteAssetsReceived`.
  final Uint8List? bytes;

  const ServerBannerData({
    required this.hash,
    required this.animated,
    this.bytes,
  });

  @override
  int get hashCode => hash.hashCode ^ animated.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerBannerData &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          animated == other.animated &&
          bytes == other.bytes;
}

/// Server info for FFI (Dart-visible).
class ServerFfi {
  final String serverId;
  final String name;
  final int memberCount;
  final int channelCount;

  const ServerFfi({
    required this.serverId,
    required this.name,
    required this.memberCount,
    required this.channelCount,
  });

  @override
  int get hashCode =>
      serverId.hashCode ^
      name.hashCode ^
      memberCount.hashCode ^
      channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerFfi &&
          runtimeType == other.runtimeType &&
          serverId == other.serverId &&
          name == other.name &&
          memberCount == other.memberCount &&
          channelCount == other.channelCount;
}

/// Storage stats for a server, returned to Dart via FFI.
class StorageStatsFfi {
  final BigInt totalPledgedBytes;
  final BigInt totalUsedBytes;
  final BigInt myPledgeBytes;
  final BigInt myUsedBytes;
  final int memberCount;
  final BigInt minPledgeMb;

  const StorageStatsFfi({
    required this.totalPledgedBytes,
    required this.totalUsedBytes,
    required this.myPledgeBytes,
    required this.myUsedBytes,
    required this.memberCount,
    required this.minPledgeMb,
  });

  @override
  int get hashCode =>
      totalPledgedBytes.hashCode ^
      totalUsedBytes.hashCode ^
      myPledgeBytes.hashCode ^
      myUsedBytes.hashCode ^
      memberCount.hashCode ^
      minPledgeMb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageStatsFfi &&
          runtimeType == other.runtimeType &&
          totalPledgedBytes == other.totalPledgedBytes &&
          totalUsedBytes == other.totalUsedBytes &&
          myPledgeBytes == other.myPledgeBytes &&
          myUsedBytes == other.myUsedBytes &&
          memberCount == other.memberCount &&
          minPledgeMb == other.minPledgeMb;
}

/// Status of a single vault file (erasure-coded), returned to Dart for the
/// Archive tab's shard status indicator.
class VaultFileStatusFfi {
  final String contentId;
  final String fileName;
  final BigInt originalSize;
  final int k;
  final int m;
  final int localShardCount;
  final bool isReconstructable;
  final String channelId;
  final PlatformInt64 createdAt;

  const VaultFileStatusFfi({
    required this.contentId,
    required this.fileName,
    required this.originalSize,
    required this.k,
    required this.m,
    required this.localShardCount,
    required this.isReconstructable,
    required this.channelId,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      contentId.hashCode ^
      fileName.hashCode ^
      originalSize.hashCode ^
      k.hashCode ^
      m.hashCode ^
      localShardCount.hashCode ^
      isReconstructable.hashCode ^
      channelId.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultFileStatusFfi &&
          runtimeType == other.runtimeType &&
          contentId == other.contentId &&
          fileName == other.fileName &&
          originalSize == other.originalSize &&
          k == other.k &&
          m == other.m &&
          localShardCount == other.localShardCount &&
          isReconstructable == other.isReconstructable &&
          channelId == other.channelId &&
          createdAt == other.createdAt;
}
