// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `gif_proxy_base`, `gif_query_page`, `gif_query`, `parse_gif_page`, `proxy_base_store`, `valid_gif_id`

/// Configure the GIF proxy base URL (None/empty = back to the default).
/// Persisted on the Dart side and pushed at startup, like `set_relay_url`.
Future<void> setGifProxyUrl({String? base}) =>
    RustLib.instance.api.crateApiGifsSetGifProxyUrl(base: base);

/// Search GIFs via the website's no-log proxy. Authoring only.
Future<GifPage> gifSearch({required String query, required int page}) =>
    RustLib.instance.api.crateApiGifsGifSearch(query: query, page: page);

/// Trending GIFs — the picker's default (empty-search) view.
Future<GifPage> gifTrending({required int page}) =>
    RustLib.instance.api.crateApiGifsGifTrending(page: page);

/// Category names for the browse chips (server-cached for 7 days).
Future<List<String>> gifCategories() =>
    RustLib.instance.api.crateApiGifsGifCategories();

/// Download a picked GIF's full-quality source through the proxy, re-encode
/// it into the ≤480px/≤2MB send format, and cache it as a `kind='gif'` asset
/// blob. Takes an ID and builds the URL itself — never a caller-supplied URL.
Future<StoredGif> gifFetchAndStore({required String id}) =>
    RustLib.instance.api.crateApiGifsGifFetchAndStore(id: id);

/// One GIF search/browse result. All URLs point at OUR proxy, never at the
/// upstream provider — rows with foreign URLs are dropped at parse time.
class GifItem {
  final String id;
  final int w;
  final int h;
  final String title;

  /// First-frame still WebP (~150px) — the grid default.
  final String stillUrl;

  /// Small animated variant (~150px WebP or GIF) — hover/viewport preview.
  final String smUrl;

  const GifItem({
    required this.id,
    required this.w,
    required this.h,
    required this.title,
    required this.stillUrl,
    required this.smUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      w.hashCode ^
      h.hashCode ^
      title.hashCode ^
      stillUrl.hashCode ^
      smUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GifItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          w == other.w &&
          h == other.h &&
          title == other.title &&
          stillUrl == other.stillUrl &&
          smUrl == other.smUrl;
}

/// One page of the proxy's normalized search/trending response.
class GifPage {
  final List<GifItem> items;
  final int page;
  final bool hasNext;

  /// Unix seconds until which the proxy's upstream is cooling down
  /// (0 = healthy). An empty page with a non-zero value means "retry
  /// later", not "no results".
  final PlatformInt64 backoffUntil;

  const GifPage({
    required this.items,
    required this.page,
    required this.hasNext,
    required this.backoffUntil,
  });

  @override
  int get hashCode =>
      items.hashCode ^ page.hashCode ^ hasNext.hashCode ^ backoffUntil.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GifPage &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          page == other.page &&
          hasNext == other.hasNext &&
          backoffUntil == other.backoffUntil;
}

/// A picked GIF, transcoded and cached as a `kind='gif'` asset blob. Feed
/// hash/w/h into the `[a:g:hash:w:h]` wire token.
class StoredGif {
  final String hash;
  final int w;
  final int h;
  final bool animated;

  const StoredGif({
    required this.hash,
    required this.w,
    required this.h,
    required this.animated,
  });

  @override
  int get hashCode =>
      hash.hashCode ^ w.hashCode ^ h.hashCode ^ animated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredGif &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          w == other.w &&
          h == other.h &&
          animated == other.animated;
}
