// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'showcase.dart';
part 'network.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `event_forwarding_task`, `get_event_rx`, `get_http_runtime`, `get_license_key`, `get_node`, `get_proxy_config`, `get_proxy_socks_addr`, `get_relay_domain`, `get_runtime`, `open_local_store`, `send_node_command`, `set_proxy_socks_addr`, `to_ffi_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NodeState`, `ProxyConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`, `from`, `from`, `from`

Future<void> setLicenseKey({String? key}) =>
    RustLib.instance.api.crateApiNetworkSetLicenseKey(key: key);

Future<void> setRelayUrl({String? domain}) =>
    RustLib.instance.api.crateApiNetworkSetRelayUrl(domain: domain);

/// Configure (or clear) the anti-censorship REALITY proxy. Call BEFORE
/// start_node() — like set_relay_url, it seeds a global that start_node reads to
/// launch the `shoes` tunnel. Passing all-empty / null fields disables the proxy
/// (direct connection). Takes effect on the next node start (toggling at runtime
/// requires a node restart, same as changing the relay domain).
Future<void> setProxyConfig({
  required bool enabled,
  required String server,
  required String uuid,
  required String publicKey,
  required String shortId,
  required String sni,
}) => RustLib.instance.api.crateApiNetworkSetProxyConfig(
  enabled: enabled,
  server: server,
  uuid: uuid,
  publicKey: publicKey,
  shortId: shortId,
  sni: sni,
);

/// Start the libp2p node with mDNS peer discovery and E2EE.
/// Uses the persistent identity from disk.
/// Returns the local peer ID as a string.
Future<String> startNode() => RustLib.instance.api.crateApiNetworkStartNode();

/// Stream network events to Dart in real time.
/// Must be called after `start_node()`. Can only be called once per node lifetime.
Stream<NetworkEvent> watchNetworkEvents() =>
    RustLib.instance.api.crateApiNetworkWatchNetworkEvents();

/// Poll for the next network event. Returns None if no event is available.
/// Fallback for when streaming is not active.
Future<NetworkEvent?> pollNetworkEvent() =>
    RustLib.instance.api.crateApiNetworkPollNetworkEvent();

/// Get the local peer ID. Returns None if the node hasn't started.
Future<String?> getLocalPeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalPeerId();

/// Get the Olm identity fingerprint (Curve25519 base64).
/// Returns None if the node hasn't started.
Future<String?> getOlmFingerprint() =>
    RustLib.instance.api.crateApiNetworkGetOlmFingerprint();

/// Get the local Ed25519 public key as base64-encoded protobuf.
/// Used by the Verify Peer screen to display "Your Fingerprint".
Future<String> getLocalPublicKey() =>
    RustLib.instance.api.crateApiNetworkGetLocalPublicKey();

/// Resolve a (possibly per-device) peer_id to its MASTER identity peer_id.
///
/// Dart calls this to collapse a friend's multiple device peer_ids into one
/// person for display/attribution. Unknown peers (single-device installs, or a
/// peer whose signed device list we haven't ingested yet) resolve to themselves,
/// so this is safe to call on any id. Reads the running node's in-memory resolver
/// — no DB hit.
Future<String> identityFor({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkIdentityFor(peerId: peerId);

/// Resolve a (possibly per-device) peer_id to its MASTER identity, falling back
/// to the PERSISTED device links in SQLCipher when the in-memory resolver is
/// still cold.
///
/// The push-tap navigation path needs this (HOLLOW_PLAN "iOS DM push opens a
/// different chat"): a cold-start notification tap is buffered and fires the
/// moment the mobile shell mounts, which can be BEFORE the node's event loop
/// task has warmed the in-memory resolver from the DB — `identity_for` then
/// resolves the friend's DEVICE id to itself (no error, so callers can't tell a
/// cold miss from a genuine single-device peer) and the DM opens a device-keyed
/// empty thread. The NSE proves the link IS on disk at tap time (it warms from
/// `device_links` and stores the fetched DM under the master), so a direct DB
/// read closes the race. Any failure (locked identity, DB open error) degrades
/// to identity-passthrough — same contract as `identity_for`.
Future<String> identityForPersisted({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkIdentityForPersisted(peerId: peerId);

/// Snapshot every known (device → master) link for the Dart attribution layer.
///
/// Dart builds a `device_link_provider` from this and refreshes it whenever a
/// `DeviceListUpdated` event fires. A single-device install returns only
/// self-mappings (or an empty list), so the provider is a no-op there.
Future<List<DeviceLink>> getDeviceLinks() =>
    RustLib.instance.api.crateApiNetworkGetDeviceLinks();

/// Full sibling teardown ("Reset Device List"): tombstone EVERY device except the
/// one we're running on, in a single master-signed version bump, and PROPAGATE it —
/// friends converge and drop the revoked siblings (and can never un-revoke them),
/// each revoked sibling self-nukes (wipe + relaunch) on ingest, and we drop their
/// Olm sessions + MLS leaves. This is the permanent fix for accumulated ghost
/// devices from link/re-link cycles (the old version did a blunt LOCAL wipe of the
/// device-list table, which the grow-only union-merge simply regrew from siblings
/// on the next profile exchange — so ghosts came right back). Requires the node to
/// be running. After this, only THIS device remains; re-link others fresh.
Future<void> resetDeviceLists() =>
    RustLib.instance.api.crateApiNetworkResetDeviceLists();

/// The transport peer_id of the device this app is RUNNING on (Step 8). Distinct
/// from `get_local_peer_id`, which returns the MASTER identity. Dart uses this to
/// mark "This device" in the Devices panel and to hide its "Remove" button (a
/// device can't revoke itself). Returns `None` if no device key exists yet.
Future<String?> getLocalDevicePeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalDevicePeerId();

/// Revoke one of OUR OWN devices (Step 7, lost/stolen). Bumps our master-signed
/// device list with the device tombstoned + drops the Olm session + (where we
/// coordinate) removes its MLS leaf from shared servers. Manual-only; rejected for
/// the device we're running on or an id that isn't ours. Friends converge via the
/// re-broadcast device list and can never un-revoke it with a stale (lower-version)
/// list. The node must be running.
Future<void> revokeDevice({required String devicePeerId}) => RustLib
    .instance
    .api
    .crateApiNetworkRevokeDevice(devicePeerId: devicePeerId);

/// Multi-device MANUAL state sync (Security → Your Devices "Sync from this
/// device"). Ask the chosen SOURCE sibling (`source_device_id`) to re-announce
/// all its servers + re-share its friends to THIS device. Deterministic,
/// user-triggered escape hatch for when the automatic sibling sync didn't
/// converge. The source must be online.
Future<void> requestStateSync({required String sourceDeviceId}) => RustLib
    .instance
    .api
    .crateApiNetworkRequestStateSync(sourceDeviceId: sourceDeviceId);

/// Set (or clear, when `label` is empty) the local human label for a device.
/// Local-only — not synced or signed, so a person's two devices may show different
/// labels for the same third device.
Future<void> setDeviceLabel({
  required String devicePeerId,
  required String label,
}) => RustLib.instance.api.crateApiNetworkSetDeviceLabel(
  devicePeerId: devicePeerId,
  label: label,
);

/// All local device labels for the Devices panel.
Future<List<DeviceLabel>> getDeviceLabels() =>
    RustLib.instance.api.crateApiNetworkGetDeviceLabels();

/// Verify an Ed25519 message signature against a canonical payload.
///
/// Used by the Message Proof dialog ("The RAT Files") to show real-time
/// VERIFIED / INVALID status. Pure crypto — no node state needed.
///
/// Arguments:
/// - `sender_peer_id`: the sender's PeerId (Base58btc)
/// - `signature_b64`: base64-encoded Ed25519 signature
/// - `public_key_b64`: base64-encoded protobuf public key
/// - `canonical_payload`: the signing payload string (e.g. "hollow-msg:dm:...")
Future<bool> verifyMessageProof({
  required String senderPeerId,
  required String signatureB64,
  required String publicKeyB64,
  required String canonicalPayload,
}) => RustLib.instance.api.crateApiNetworkVerifyMessageProof(
  senderPeerId: senderPeerId,
  signatureB64: signatureB64,
  publicKeyB64: publicKeyB64,
  canonicalPayload: canonicalPayload,
);

/// v2 verification for the Message Proof dialog (no v1 fallback since 0.8.5).
///
/// The v2 payload binds the message's structured fields (mid / reply_to /
/// file_id / order_us / link-preview digest), which live in the DB row — so
/// this loads the row by `message_id` and builds the canonical payload in
/// RUST, keeping the grammar single-sourced instead of mirroring it in Dart.
/// An EDITED row verifies against its edit signature (edited_at + current
/// text), same rule as every other verifier.
///
/// - `msg_type`: "dm" | "ch"
/// - `context`: recipient MASTER peer_id for DMs, "server_id:channel_id" for
///   channels (same values the v1 dialog already computes).
Future<MessageProofV2> verifyMessageProofV2({
  required String msgType,
  required String context,
  required String senderPeerId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkVerifyMessageProofV2(
  msgType: msgType,
  context: context,
  senderPeerId: senderPeerId,
  messageId: messageId,
);

/// Fetch OpenGraph metadata for a URL and return a link preview the sender
/// can embed in their next outgoing message. Runs on the shared Tokio
/// runtime. Fails silently at every step — the caller should treat errors
/// as "no preview" and send the message as plain text.
///
/// **Privacy:** This MUST only be called on the sender side. Receivers
/// render the preview from embedded data and never fetch the URL. See
/// `node::link_preview` for the full contract.
///
/// Phase 6.75.
Future<LinkPreviewRef> fetchLinkPreview({required String url}) =>
    RustLib.instance.api.crateApiNetworkFetchLinkPreview(url: url);

/// Send a text message to a peer. The peer must be reachable (discovered via mDNS).
Future<void> sendMessage({
  required String peerId,
  required String text,
  required String messageId,
  String? replyToMid,
  LinkPreviewRef? linkPreview,
}) => RustLib.instance.api.crateApiNetworkSendMessage(
  peerId: peerId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
  linkPreview: linkPreview,
);

/// Send a text message to a server channel.
/// The message will be encrypted and sent to all connected server members.
Future<void> sendChannelMessage({
  required String serverId,
  required String channelId,
  required String text,
  required String messageId,
  String? replyToMid,
  LinkPreviewRef? linkPreview,
}) => RustLib.instance.api.crateApiNetworkSendChannelMessage(
  serverId: serverId,
  channelId: channelId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
  linkPreview: linkPreview,
);

/// Edit a channel message. Broadcasts the edit to all server members.
Future<void> editChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  newText: newText,
);

/// Edit a DM message. Sends the edit to the DM peer.
Future<void> editDmMessage({
  required String peerId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditDmMessage(
  peerId: peerId,
  messageId: messageId,
  newText: newText,
);

/// Delete (hide) a channel message. Broadcasts the deletion to all server members.
/// The message stays in the DB (Rat Files evidence) but is hidden from UI.
Future<void> deleteChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Delete (hide) a DM message. Sends the deletion to the DM peer.
Future<void> deleteDmMessage({
  required String peerId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteDmMessage(
  peerId: peerId,
  messageId: messageId,
);

/// Add an emoji reaction to a channel message.
Future<void> addChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a channel message.
Future<void> removeChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Add an emoji reaction to a DM message.
Future<void> addDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a DM message.
Future<void> removeDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Send a friend request to a peer.
Future<void> sendFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkSendFriendRequest(peerId: peerId);

/// Accept a friend request from a peer.
Future<void> acceptFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkAcceptFriendRequest(peerId: peerId);

/// Reject a friend request from a peer.
Future<void> rejectFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRejectFriendRequest(peerId: peerId);

/// Remove a friend.
Future<void> removeFriend({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRemoveFriend(peerId: peerId);

/// Send a friend request to a peer, resolving their temporary nickname first.
Future<void> sendFriendRequestByNickname({required String nickname}) => RustLib
    .instance
    .api
    .crateApiNetworkSendFriendRequestByNickname(nickname: nickname);

/// Claim a temporary nickname on the relay (RAM only, released on disconnect).
Future<void> claimNickname({required String nickname}) =>
    RustLib.instance.api.crateApiNetworkClaimNickname(nickname: nickname);

/// Ask the relay for this connection's daily byte-budget status (used /
/// budget / seconds until the UTC-day reset). Fire-and-forget: the reply
/// arrives as `NetworkEvent::BandwidthStatus` on the event stream.
Future<void> requestRelayBandwidth() =>
    RustLib.instance.api.crateApiNetworkRequestRelayBandwidth();

/// File a user report with the relay (category: "spam", "harassment",
/// "illegal_content", or "impersonation"). Fire-and-forget; the relay keeps
/// only per-(target, category) counts and dedups one report per reporter per
/// target per category via hashed keys — it never stores who reported whom.
Future<void> reportUser({required String target, required String category}) =>
    RustLib.instance.api.crateApiNetworkReportUser(
      target: target,
      category: category,
    );

/// Release the currently claimed temporary nickname.
Future<void> releaseNickname() =>
    RustLib.instance.api.crateApiNetworkReleaseNickname();

/// (Populated device) Claim a 6-char link code on the relay + join its rendezvous
/// room, so an empty sibling can pull your data by entering the code. The code
/// (echoed back via the `LinkCodeClaimed` event) should be generated client-side
/// from an unambiguous alphabet and displayed with a 5-minute countdown.
Future<void> claimLinkCode({required String code}) =>
    RustLib.instance.api.crateApiNetworkClaimLinkCode(code: code);

/// (Populated device) Release the currently claimed link code + leave its room.
Future<void> releaseLinkCode() =>
    RustLib.instance.api.crateApiNetworkReleaseLinkCode();

/// (Empty device) Resolve a link code shown on the populated device, then request
/// its full snapshot. `include_vault`/`include_files` control snapshot scope.
Future<void> resolveLinkCode({
  required String code,
  required bool includeVault,
  required bool includeFiles,
}) => RustLib.instance.api.crateApiNetworkResolveLinkCode(
  code: code,
  includeVault: includeVault,
  includeFiles: includeFiles,
);

/// (Empty device, mnemonic path) Request a full snapshot directly from a known
/// sibling device (no code; used when the sibling is already in a shared room).
Future<void> requestLinkSnapshot({
  required String targetPeer,
  required bool includeVault,
  required bool includeFiles,
}) => RustLib.instance.api.crateApiNetworkRequestLinkSnapshot(
  targetPeer: targetPeer,
  includeVault: includeVault,
  includeFiles: includeFiles,
);

/// (Populated device) Accept an inbound link request and push the snapshot to the
/// target device. Build scope is chosen here (files/vault).
Future<void> acceptLinkPush({
  required String targetPeer,
  required bool includeVault,
  required bool includeFiles,
}) => RustLib.instance.api.crateApiNetworkAcceptLinkPush(
  targetPeer: targetPeer,
  includeVault: includeVault,
  includeFiles: includeFiles,
);

/// (Populated device) Decline an inbound link request.
Future<void> declineLinkPush({required String targetPeer}) =>
    RustLib.instance.api.crateApiNetworkDeclineLinkPush(targetPeer: targetPeer);

/// Load a peer's cached profile directly from SQLCipher for push notification display.
/// Works without a running node — opens its own DB connection.
/// Returns None if the peer has no cached profile or identity is locked.
Future<PushProfile?> getPushProfile({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkGetPushProfile(peerId: peerId);

/// Nudge the LIVE full node to (re)join the DM room for `sender_peer_id` so
/// the relay replays that room's buffered offline DMs to it (Android push
/// path). The FCM background isolate shares its process with the still-
/// running full node, so `start_fetch_node` refuses to start — but the live
/// node itself can collect the buffered ciphertext: joining the DM room
/// triggers the relay replay, and if the WS is a doze-killed zombie the
/// queued JoinRoom rides the reconnect (send failure → pending_commands →
/// reconnect). The live receive path then decrypts, persists, and emits
/// MessageReceived — the MAIN isolate (alive, since the node is) shows the
/// content notification through the normal routing (mute + dedup respected).
///
/// Returns Ok(true) when a live node accepted the command, Ok(false) when no
/// node is running (caller should use the fetch node instead).
Future<bool> nudgeLiveDmFetch({required String senderPeerId}) => RustLib
    .instance
    .api
    .crateApiNetworkNudgeLiveDmFetch(senderPeerId: senderPeerId);

/// Channel-wake sibling of [`nudge_live_dm_fetch`]: ask the LIVE full node to
/// (re)join an arbitrary relay room (the server room for a channel push) so
/// the relay replays that room's buffered ciphertext to it. Same rationale:
/// on Android the backgrounded app keeps the full node registered, so the
/// fetch node refuses to start; the queued JoinRoom rides the WS reconnect if
/// the socket is a doze-killed zombie. Returns Ok(false) when no node runs.
Future<bool> nudgeLiveRoomJoin({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkNudgeLiveRoomJoin(roomCode: roomCode);

/// Start a lightweight invisible fetch node to receive buffered messages.
///
/// DM wake (`server_room` = None): joins only the DM room for sender_peer_id
/// and decrypts via Olm. Channel wake (`server_room` = Some(server_id)): joins
/// the server room and decrypts buffered channel messages via MLS (or reads
/// signed public-channel plaintext).
/// Cannot run while the full node is active. Blocks the calling thread.
Future<List<FetchedMessage>> startFetchNode({
  required String senderPeerId,
  required int timeoutSecs,
  String? serverRoom,
}) => RustLib.instance.api.crateApiNetworkStartFetchNode(
  senderPeerId: senderPeerId,
  timeoutSecs: timeoutSecs,
  serverRoom: serverRoom,
);

/// Register an FCM/APNs push token with the relay for offline wake-up notifications.
Future<void> registerPushToken({
  required String token,
  required String platform,
}) => RustLib.instance.api.crateApiNetworkRegisterPushToken(
  token: token,
  platform: platform,
);

/// Register per-server/channel push notification prefs with the relay.
/// `prefs_json` = {"<server_id>": {"level": "all|mentions|nothing",
/// "channels": {"<channel_id>": "all|mentions|nothing"}}}. RAM-only on the
/// relay; re-sent automatically on every reconnect. The relay filters channel
/// pushes against these BEFORE contacting FCM/APNs (iOS alert pushes cannot be
/// suppressed after delivery).
Future<void> setPushPrefs({required String prefsJson}) =>
    RustLib.instance.api.crateApiNetworkSetPushPrefs(prefsJson: prefsJson);

/// Opt in/out of the relay's extended offline DM delivery ("offline inbox").
/// When enabled, the relay keeps Olm-encrypted DM text + FileHeader frames
/// addressed to this device for `retention_secs` (relay clamps to 1h..7d)
/// instead of the 24h push baseline, and replays them on the next connect —
/// delivered entries are deleted relay-side. Text and file METADATA only,
/// never file bytes. RAM-only registry: ws_client re-registers automatically
/// on every reconnect; Dart must call this once per app start (and on change).
Future<void> setOfflineInbox({
  required bool enabled,
  required PlatformInt64 retentionSecs,
}) => RustLib.instance.api.crateApiNetworkSetOfflineInbox(
  enabled: enabled,
  retentionSecs: retentionSecs,
);

/// Resolve server + channel names and the effective local notification level
/// directly from SQLCipher (no running node). Returns None when the server is
/// unknown locally or identity is locked.
Future<PushChannelMeta?> getPushChannelMeta({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkGetPushChannelMeta(
  serverId: serverId,
  channelId: channelId,
);

/// Send a typing indicator to peers. Ephemeral, not stored.
/// For DMs: server_id = "", channel_id = peer ID.
/// For channels: server_id and channel_id as normal.
Future<void> sendTypingIndicator({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkSendTypingIndicator(
  serverId: serverId,
  channelId: channelId,
);

/// Toggle invisible mode. Broadcasts StatusUpdate to all connected peers.
Future<void> setInvisible({required bool invisible}) =>
    RustLib.instance.api.crateApiNetworkSetInvisible(invisible: invisible);

/// Subscribe to specific channels in a server for topic-based relay routing.
/// Only messages for subscribed channels are delivered in real-time.
/// Unsubscribed channel messages are synced on-demand when navigating to them.
Future<void> subscribeChannels({
  required String serverId,
  required List<String> channelIds,
}) => RustLib.instance.api.crateApiNetworkSubscribeChannels(
  serverId: serverId,
  channelIds: channelIds,
);

/// Request message sync for a specific channel from all connected server members.
/// Called when the user opens a channel to catch up on missed messages.
Future<void> requestChannelSync({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkRequestChannelSync(
  serverId: serverId,
  channelId: channelId,
);

/// Notify all connected peers that we're shutting down gracefully.
/// Call this before closing the app so peers can immediately update their state.
/// Update our display name, status, about me, and optionally avatar/banner —
/// saves to DB and broadcasts to all connected peers.
/// `showcase_board`: None = unchanged, Some("") = clear, Some(json) = set.
/// `showcase_assets`: None = unchanged, Some(empty list) = clear, else the
/// full replacement asset set for the board.
Future<void> updateProfile({
  required String displayName,
  required String status,
  required String aboutMe,
  Uint8List? avatarBytes,
  Uint8List? bannerBytes,
  required String twitchUsername,
  String? showcaseBoard,
  List<ShowcaseAsset>? showcaseAssets,
}) => RustLib.instance.api.crateApiNetworkUpdateProfile(
  displayName: displayName,
  status: status,
  aboutMe: aboutMe,
  avatarBytes: avatarBytes,
  bannerBytes: bannerBytes,
  twitchUsername: twitchUsername,
  showcaseBoard: showcaseBoard,
  showcaseAssets: showcaseAssets,
);

/// Process a raw image into avatar format (128x128 WebP). Returns processed bytes.
Future<Uint8List> processAvatar({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessAvatar(rawBytes: rawBytes);

/// Process a raw image into banner format (600x200 WebP). Returns processed bytes.
Future<Uint8List> processBanner({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessBanner(rawBytes: rawBytes);

Future<void> notifyShutdown() =>
    RustLib.instance.api.crateApiNetworkNotifyShutdown();

/// Join a room via the signaling service.
/// Registers our addresses and bootstraps from other peers in the room.
Future<void> joinRoom({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkJoinRoom(roomCode: roomCode);

/// Stop the running node.
Future<void> stopNode() => RustLib.instance.api.crateApiNetworkStopNode();

/// Send a file to a DM peer or server channel.
/// `peer_id`: target peer (for DMs, empty for channels).
/// `server_id` + `channel_id`: target channel (for servers, empty for DMs).
/// `vthumb`: optional video thumbnail back-reference. When set, the file at
///           `file_path` is a thumbnail image for the vault-stored video
///           identified by `vthumb.cid`. Phase 6.75 video preview.
/// `override_width` / `override_height`: Phase 6.75 video preview — when the
///           file at `file_path` is a video, Dart passes the video's pixel
///           dimensions here so the FileHeader carries them and receivers can
///           render the bubble at the correct aspect ratio. Ignored for image
///           files (Rust extracts those dimensions itself).
Future<void> sendFile({
  String? peerId,
  String? serverId,
  String? channelId,
  required String filePath,
  required String messageId,
  required String messageText,
  VideoThumbRef? vthumb,
  int? overrideWidth,
  int? overrideHeight,
  String? shareRootHash,
  String? shareKeyHex,
}) => RustLib.instance.api.crateApiNetworkSendFile(
  peerId: peerId,
  serverId: serverId,
  channelId: channelId,
  filePath: filePath,
  messageId: messageId,
  messageText: messageText,
  vthumb: vthumb,
  overrideWidth: overrideWidth,
  overrideHeight: overrideHeight,
  shareRootHash: shareRootHash,
  shareKeyHex: shareKeyHex,
);

/// Request file chunks from a specific peer.
Future<void> requestFileFromPeer({
  required String fileId,
  required String peerId,
  required List<int> chunks,
}) => RustLib.instance.api.crateApiNetworkRequestFileFromPeer(
  fileId: fileId,
  peerId: peerId,
  chunks: chunks,
);

/// Convert a WebP image file to another format (PNG/JPEG).
/// Used for "Save As" functionality.
Future<Uint8List> convertImageFormat({
  required String sourcePath,
  required String targetFormat,
}) => RustLib.instance.api.crateApiNetworkConvertImageFormat(
  sourcePath: sourcePath,
  targetFormat: targetFormat,
);

/// Get the files directory path.
Future<String> getFilesDir() =>
    RustLib.instance.api.crateApiNetworkGetFilesDir();

/// Log a message from Dart to hollow_debug.log (visible in release builds).
Future<void> logFromDart({required String message}) =>
    RustLib.instance.api.crateApiNetworkLogFromDart(message: message);

/// Notify Rust that a WebRTC data channel is established with a peer.
Future<void> webrtcPeerConnected({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPeerConnected(peerId: peerId);

/// Notify Rust that a WebRTC data channel has been closed for a peer.
Future<void> webrtcPeerDisconnected({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPeerDisconnected(peerId: peerId);

/// Send a WebRTC signaling message (SDP offer/answer or ICE candidate) to a peer.
/// Rust routes it through the WSS relay to the target peer.
Future<void> webrtcSendSignal({
  required String peerId,
  required String signalType,
  required String payload,
  required String connId,
}) => RustLib.instance.api.crateApiNetworkWebrtcSendSignal(
  peerId: peerId,
  signalType: signalType,
  payload: payload,
  connId: connId,
);

/// Notify Rust that a WebRTC file transfer completed (receiver side).
/// Rust will decrypt and process the received file.
Future<void> webrtcTransferComplete({
  required String transferId,
  required String tempPath,
  required String senderPeerId,
  required String kind,
  required int shardIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcTransferComplete(
  transferId: transferId,
  tempPath: tempPath,
  senderPeerId: senderPeerId,
  kind: kind,
  shardIndex: shardIndex,
);

/// Notify Rust that a WebRTC share-chunk transfer completed.
/// Distinct from `webrtc_transfer_complete` because share chunks need a
/// 32-bit chunk_index (a single share can have up to 4 billion chunks).
/// Routes into share_handler verify+decrypt+write path.
Future<void> webrtcShareChunkComplete({
  required String transferId,
  required String tempPath,
  required String senderPeerId,
  required int chunkIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcShareChunkComplete(
  transferId: transferId,
  tempPath: tempPath,
  senderPeerId: senderPeerId,
  chunkIndex: chunkIndex,
);

/// Notify Rust that a WebRTC file send completed (sender side).
/// Rust cleans up the temp encrypted file.
Future<void> webrtcSendComplete({required String transferId}) => RustLib
    .instance
    .api
    .crateApiNetworkWebrtcSendComplete(transferId: transferId);

/// Notify Rust that a WebRTC transfer failed. Triggers WSS relay fallback.
Future<void> webrtcTransferFailed({
  required String transferId,
  required String peerId,
  required String error,
}) => RustLib.instance.api.crateApiNetworkWebrtcTransferFailed(
  transferId: transferId,
  peerId: peerId,
  error: error,
);

/// Send a voice call signaling message to a peer (Phase 5B).
Future<void> callSendSignal({
  required String peerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkCallSendSignal(
  peerId: peerId,
  signalType: signalType,
  payload: payload,
);

/// Join a voice channel in a server (Phase 5C).
Future<void> voiceChannelJoin({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelJoin(
  serverId: serverId,
  channelId: channelId,
);

/// Leave a voice channel in a server (Phase 5C).
Future<void> voiceChannelLeave({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelLeave(
  serverId: serverId,
  channelId: channelId,
);

/// Send a voice channel signaling message (SDP/ICE) to a specific peer (Phase 5C).
Future<void> voiceChannelSendSignal({
  required String serverId,
  required String channelId,
  required String peerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelSendSignal(
  serverId: serverId,
  channelId: channelId,
  peerId: peerId,
  signalType: signalType,
  payload: payload,
);

/// SFrame heal (issue #27): the voice cryptors report sustained decrypt
/// failures against `peer_id`. Re-emits the current MLS epoch key; with
/// `escalate` the node also re-bootstraps the MLS group (non-authority) or
/// removes + re-adds the failing peer's leaves (authority).
Future<void> voiceSframeHeal({
  required String serverId,
  required String channelId,
  required String peerId,
  required bool escalate,
}) => RustLib.instance.api.crateApiNetworkVoiceSframeHeal(
  serverId: serverId,
  channelId: channelId,
  peerId: peerId,
  escalate: escalate,
);

/// Report data channel keepalive RTT for gossip peer scoring.
Future<void> webrtcPingReport({required String peerId, required int rttMs}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPingReport(
      peerId: peerId,
      rttMs: rttMs,
    );

/// Report the ICE route class of a live data-channel connection (Tier 3
/// reachability-aware overlay): `is_direct` = host/srflx/LAN vs TURN-relayed.
Future<void> webrtcRouteReport({
  required String peerId,
  required bool isDirect,
}) => RustLib.instance.api.crateApiNetworkWebrtcRouteReport(
  peerId: peerId,
  isDirect: isDirect,
);

/// Hand back a gossip CRDT-op frame (type byte 0x04) received on a data
/// channel. Tier 2 large-server scaling: the op is ingested through the same
/// validated path as a relay CrdtOpBroadcast and re-flooded to our own mesh
/// neighbors only if it was new.
Future<void> webrtcGossipOpReceived({
  required String senderPeerId,
  required List<int> payload,
}) => RustLib.instance.api.crateApiNetworkWebrtcGossipOpReceived(
  senderPeerId: senderPeerId,
  payload: payload,
);

/// Notify Rust that a broadcast file was received via gossip data channel.
Future<void> webrtcBroadcastReceived({
  required String transferId,
  required String broadcastId,
  required int ttl,
  required String originPeerId,
  required String senderPeerId,
  required String tempPath,
  required BigInt totalSize,
  required String kind,
  required int shardIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcBroadcastReceived(
  transferId: transferId,
  broadcastId: broadcastId,
  ttl: ttl,
  originPeerId: originPeerId,
  senderPeerId: senderPeerId,
  tempPath: tempPath,
  totalSize: totalSize,
  kind: kind,
  shardIndex: shardIndex,
);

/// A local human label for a device (Step 8 Devices panel).
class DeviceLabel {
  final String devicePeerId;
  final String label;

  const DeviceLabel({required this.devicePeerId, required this.label});

  @override
  int get hashCode => devicePeerId.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLabel &&
          runtimeType == other.runtimeType &&
          devicePeerId == other.devicePeerId &&
          label == other.label;
}

/// A learned device → master identity link (multi-device, Phase 6).
class DeviceLink {
  /// A device's transport peer_id (`12D3KooW…`).
  final String devicePeerId;

  /// The master identity peer_id it belongs to.
  final String masterPeerId;

  const DeviceLink({required this.devicePeerId, required this.masterPeerId});

  @override
  int get hashCode => devicePeerId.hashCode ^ masterPeerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLink &&
          runtimeType == other.runtimeType &&
          devicePeerId == other.devicePeerId &&
          masterPeerId == other.masterPeerId;
}

/// A discovered peer on the local network.
class DiscoveredPeer {
  final String peerId;
  final List<String> addresses;

  const DiscoveredPeer({required this.peerId, required this.addresses});

  @override
  int get hashCode => peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

/// A message fetched during background push processing (Tier 2).
class FetchedMessage {
  final String fromPeer;
  final String text;
  final PlatformInt64 timestamp;
  final String messageId;

  /// On-disk path to the message's image, if this DM carried an inlined image
  /// that the fetch node decrypted and wrote. Lets the push notification show
  /// a BigPicture preview. None for text-only messages.
  final String? imagePath;

  /// Set for channel messages (channel wake): owning server.
  final String? serverId;

  /// Set for channel messages (channel wake): owning channel.
  final String? channelId;

  const FetchedMessage({
    required this.fromPeer,
    required this.text,
    required this.timestamp,
    required this.messageId,
    this.imagePath,
    this.serverId,
    this.channelId,
  });

  @override
  int get hashCode =>
      fromPeer.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      messageId.hashCode ^
      imagePath.hashCode ^
      serverId.hashCode ^
      channelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchedMessage &&
          runtimeType == other.runtimeType &&
          fromPeer == other.fromPeer &&
          text == other.text &&
          timestamp == other.timestamp &&
          messageId == other.messageId &&
          imagePath == other.imagePath &&
          serverId == other.serverId &&
          channelId == other.channelId;
}

/// FFI-facing guest reaction.
class GuestReactionFfi {
  final String emoji;
  final String peerId;
  final PlatformInt64 addedAt;

  const GuestReactionFfi({
    required this.emoji,
    required this.peerId,
    required this.addedAt,
  });

  @override
  int get hashCode => emoji.hashCode ^ peerId.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestReactionFfi &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          addedAt == other.addedAt;
}

/// FFI-facing guest sync message.
class GuestSyncMessageFfi {
  final String senderId;
  final String text;
  final PlatformInt64 timestamp;
  final String? messageId;
  final String? signature;
  final String? publicKey;
  final PlatformInt64? editedAt;
  final String? replyTo;
  final PlatformInt64? hiddenAt;
  final List<GuestReactionFfi> reactions;

  const GuestSyncMessageFfi({
    required this.senderId,
    required this.text,
    required this.timestamp,
    this.messageId,
    this.signature,
    this.publicKey,
    this.editedAt,
    this.replyTo,
    this.hiddenAt,
    required this.reactions,
  });

  @override
  int get hashCode =>
      senderId.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      messageId.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      editedAt.hashCode ^
      replyTo.hashCode ^
      hiddenAt.hashCode ^
      reactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestSyncMessageFfi &&
          runtimeType == other.runtimeType &&
          senderId == other.senderId &&
          text == other.text &&
          timestamp == other.timestamp &&
          messageId == other.messageId &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          editedAt == other.editedAt &&
          replyTo == other.replyTo &&
          hiddenAt == other.hiddenAt &&
          reactions == other.reactions;
}

/// FFI-facing link preview for a URL embedded in a message.
///
/// Generated by the sender (fetch OG tags, download + compress thumbnail to
/// lossy WebP Q=50) and travels with the message. Receivers render the card
/// directly from these fields and NEVER make an HTTP request to the
/// previewed URL — this is a privacy property, not a cache optimization.
///
/// Phase 6.75 link previews. See HOLLOW_PLAN.md.
class LinkPreviewRef {
  /// The URL that was previewed.
  final String url;

  /// og:title or <title> fallback. Already truncated by the sender.
  final String title;

  /// og:description or meta description. Already truncated by the sender.
  final String description;

  /// Display domain parsed from the URL (e.g. "github.com").
  final String domain;

  /// og:site_name if present. Empty string = fall back to domain in UI.
  final String siteName;

  /// Base64-encoded lossy WebP thumbnail (Q=50, max dim 400px).
  /// None when no og:image was found or the image fetch failed.
  final String? thumbWebpB64;

  /// Thumbnail width after resize.
  final int? thumbW;

  /// Thumbnail height after resize.
  final int? thumbH;

  const LinkPreviewRef({
    required this.url,
    required this.title,
    required this.description,
    required this.domain,
    required this.siteName,
    this.thumbWebpB64,
    this.thumbW,
    this.thumbH,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      title.hashCode ^
      description.hashCode ^
      domain.hashCode ^
      siteName.hashCode ^
      thumbWebpB64.hashCode ^
      thumbW.hashCode ^
      thumbH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkPreviewRef &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          description == other.description &&
          domain == other.domain &&
          siteName == other.siteName &&
          thumbWebpB64 == other.thumbWebpB64 &&
          thumbW == other.thumbW &&
          thumbH == other.thumbH;
}

/// Result of a versioned Message Proof verification — see
/// [`verify_message_proof_v2`].
class MessageProofV2 {
  final bool hasSignature;
  final bool valid;

  /// 2 = verified against the v2 payload (structured fields covered),
  /// 0 = did not verify. `1` (legacy v1, text only) is no longer produced —
  /// v1 verification was dropped in 0.8.5; the variant is kept out of the
  /// contract rather than out of the range so old Dart builds that switch on
  /// `== 2` keep behaving correctly.
  final int sigVersion;

  /// The canonical v2 payload string — displayed and exported by the dialog
  /// whether or not it verified.
  final String canonicalPayload;

  /// The row's signed fields, for the exported proof JSON.
  final String text;
  final PlatformInt64 timestampMs;
  final PlatformInt64? editedAt;
  final String? replyTo;
  final String? fileId;
  final PlatformInt64? orderUs;
  final String? lpDigest;
  final String? signatureB64;
  final String? publicKeyB64;

  const MessageProofV2({
    required this.hasSignature,
    required this.valid,
    required this.sigVersion,
    required this.canonicalPayload,
    required this.text,
    required this.timestampMs,
    this.editedAt,
    this.replyTo,
    this.fileId,
    this.orderUs,
    this.lpDigest,
    this.signatureB64,
    this.publicKeyB64,
  });

  @override
  int get hashCode =>
      hasSignature.hashCode ^
      valid.hashCode ^
      sigVersion.hashCode ^
      canonicalPayload.hashCode ^
      text.hashCode ^
      timestampMs.hashCode ^
      editedAt.hashCode ^
      replyTo.hashCode ^
      fileId.hashCode ^
      orderUs.hashCode ^
      lpDigest.hashCode ^
      signatureB64.hashCode ^
      publicKeyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageProofV2 &&
          runtimeType == other.runtimeType &&
          hasSignature == other.hasSignature &&
          valid == other.valid &&
          sigVersion == other.sigVersion &&
          canonicalPayload == other.canonicalPayload &&
          text == other.text &&
          timestampMs == other.timestampMs &&
          editedAt == other.editedAt &&
          replyTo == other.replyTo &&
          fileId == other.fileId &&
          orderUs == other.orderUs &&
          lpDigest == other.lpDigest &&
          signatureB64 == other.signatureB64 &&
          publicKeyB64 == other.publicKeyB64;
}

@freezed
sealed class NetworkEvent with _$NetworkEvent {
  const NetworkEvent._();

  const factory NetworkEvent.peerDiscovered({required DiscoveredPeer peer}) =
      NetworkEvent_PeerDiscovered;
  const factory NetworkEvent.peerExpired({required String peerId}) =
      NetworkEvent_PeerExpired;
  const factory NetworkEvent.peerDisconnected({required String peerId}) =
      NetworkEvent_PeerDisconnected;
  const factory NetworkEvent.roomCleared() = NetworkEvent_RoomCleared;
  const factory NetworkEvent.listening({required String address}) =
      NetworkEvent_Listening;
  const factory NetworkEvent.messageReceived({
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
    LinkPreviewRef? linkPreview,
    String? signature,
    String? publicKey,
    required bool isOwn,
    required bool duplicate,
  }) = NetworkEvent_MessageReceived;
  const factory NetworkEvent.channelMessageReceived({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
    LinkPreviewRef? linkPreview,
    String? signature,
    String? publicKey,
    required bool duplicate,
  }) = NetworkEvent_ChannelMessageReceived;
  const factory NetworkEvent.messageSent({
    required String toPeer,
    required String messageId,
    required PlatformInt64 timestamp,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_MessageSent;
  const factory NetworkEvent.channelMessageSent({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 timestamp,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageSent;
  const factory NetworkEvent.messageSendFailed({
    required String toPeer,
    required String error,
  }) = NetworkEvent_MessageSendFailed;
  const factory NetworkEvent.sessionEstablished({required String peerId}) =
      NetworkEvent_SessionEstablished;
  const factory NetworkEvent.error({required String message}) =
      NetworkEvent_Error;
  const factory NetworkEvent.serverCreated({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerCreated;
  const factory NetworkEvent.serverUpdated({required String serverId}) =
      NetworkEvent_ServerUpdated;

  /// Custom emote bytes arrived and were verified + cached — Dart
  /// invalidates the hash-keyed emote image providers so pending
  /// `[e:name:hash]` tokens re-render as images.
  const factory NetworkEvent.emoteAssetsReceived({
    required List<String> hashes,
  }) = NetworkEvent_EmoteAssetsReceived;
  const factory NetworkEvent.channelAdded({
    required String serverId,
    required String channelId,
    required String name,
    required String channelType,
  }) = NetworkEvent_ChannelAdded;
  const factory NetworkEvent.channelRemoved({
    required String serverId,
    required String channelId,
  }) = NetworkEvent_ChannelRemoved;
  const factory NetworkEvent.channelRenamed({
    required String serverId,
    required String channelId,
    required String newName,
  }) = NetworkEvent_ChannelRenamed;
  const factory NetworkEvent.serverDeleted({required String serverId}) =
      NetworkEvent_ServerDeleted;
  const factory NetworkEvent.memberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberJoined;
  const factory NetworkEvent.memberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberLeft;
  const factory NetworkEvent.syncCompleted({
    required String serverId,
    required int opsApplied,
  }) = NetworkEvent_SyncCompleted;
  const factory NetworkEvent.serverJoined({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerJoined;
  const factory NetworkEvent.serverJoinFailed({
    required String serverId,
    required String reason,
  }) = NetworkEvent_ServerJoinFailed;
  const factory NetworkEvent.messageSyncStarted({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MessageSyncStarted;
  const factory NetworkEvent.messageSyncCompleted({
    required String serverId,
    required int newMessageCount,
  }) = NetworkEvent_MessageSyncCompleted;
  const factory NetworkEvent.messageSyncFailed({
    required String serverId,
    required String error,
  }) = NetworkEvent_MessageSyncFailed;
  const factory NetworkEvent.messageSyncProgress({
    required String serverId,
    required String channelId,
    required int receivedCount,
    required int totalCount,
  }) = NetworkEvent_MessageSyncProgress;
  const factory NetworkEvent.roleChanged({
    required String serverId,
    required String peerId,
    required String newRole,
  }) = NetworkEvent_RoleChanged;
  const factory NetworkEvent.dmSyncCompleted({
    required String peerId,
    required int newMessageCount,
  }) = NetworkEvent_DmSyncCompleted;
  const factory NetworkEvent.profileUpdated({required String peerId}) =
      NetworkEvent_ProfileUpdated;

  /// A device list was ingested for `master_peer_id` (multi-device, Phase 6).
  const factory NetworkEvent.deviceListUpdated({required String masterPeerId}) =
      NetworkEvent_DeviceListUpdated;

  /// A contact's identity changed in a way worth showing (Issue 1-C): a new
  /// device joined their identity, or one of their devices re-keyed. `peer_id`
  /// is the MASTER; `kind` is `new_device` or `identity_key_changed`.
  const factory NetworkEvent.securityAlert({
    required String peerId,
    required String kind,
    required String detail,
    required PlatformInt64 createdAt,
  }) = NetworkEvent_SecurityAlert;

  /// THIS device was revoked (Step 7) — Dart self-nukes (wipe + relaunch).
  const factory NetworkEvent.selfRevoked() = NetworkEvent_SelfRevoked;
  const factory NetworkEvent.channelMessageEdited({
    required String serverId,
    required String channelId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageEdited;
  const factory NetworkEvent.dmMessageEdited({
    required String peerId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_DmMessageEdited;
  const factory NetworkEvent.channelMessageDeleted({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_ChannelMessageDeleted;
  const factory NetworkEvent.dmMessageDeleted({
    required String peerId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_DmMessageDeleted;
  const factory NetworkEvent.channelReactionAdded({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_ChannelReactionAdded;
  const factory NetworkEvent.dmReactionAdded({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_DmReactionAdded;
  const factory NetworkEvent.channelReactionRemoved({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_ChannelReactionRemoved;
  const factory NetworkEvent.dmReactionRemoved({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_DmReactionRemoved;
  const factory NetworkEvent.friendRequestReceived({required String peerId}) =
      NetworkEvent_FriendRequestReceived;
  const factory NetworkEvent.friendRequestAccepted({required String peerId}) =
      NetworkEvent_FriendRequestAccepted;
  const factory NetworkEvent.friendRequestRejected({required String peerId}) =
      NetworkEvent_FriendRequestRejected;
  const factory NetworkEvent.friendRemoved({required String peerId}) =
      NetworkEvent_FriendRemoved;

  /// Multi-device: a sibling device backfilled `count` new friends (Phase 6).
  const factory NetworkEvent.friendsBackfilled({required int count}) =
      NetworkEvent_FriendsBackfilled;
  const factory NetworkEvent.nicknameClaimed({required String nickname}) =
      NetworkEvent_NicknameClaimed;
  const factory NetworkEvent.nicknameReleased() = NetworkEvent_NicknameReleased;
  const factory NetworkEvent.nicknameClaimFailed({required String error}) =
      NetworkEvent_NicknameClaimFailed;
  const factory NetworkEvent.nicknameResolveFailed({
    required String nickname,
    required String error,
  }) = NetworkEvent_NicknameResolveFailed;
  const factory NetworkEvent.relayDisconnected() =
      NetworkEvent_RelayDisconnected;

  /// The WS relay connection was (re)established and authenticated.
  const factory NetworkEvent.relayConnected() = NetworkEvent_RelayConnected;

  /// A WS connect attempt is in progress. `reconnecting` distinguishes a
  /// backoff retry (after a drop) from the initial connect.
  const factory NetworkEvent.relayConnecting({required bool reconnecting}) =
      NetworkEvent_RelayConnecting;

  /// Reply to `request_relay_bandwidth()` — this IP's daily relay byte
  /// budget (binary frames both directions, fixed UTC-day window).
  const factory NetworkEvent.bandwidthStatus({
    required BigInt usedBytes,
    required BigInt budgetBytes,
    required BigInt resetInSecs,
  }) = NetworkEvent_BandwidthStatus;

  /// The relay closed us with "bandwidth_limit" — daily byte budget spent
  /// until the UTC-day rollover.
  const factory NetworkEvent.bandwidthLimited() = NetworkEvent_BandwidthLimited;
  const factory NetworkEvent.channelNotificationHint({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String messageId,
    required bool hasEveryone,
    required List<String> mentionedNames,
    required bool isReply,
  }) = NetworkEvent_ChannelNotificationHint;
  const factory NetworkEvent.typingStarted({
    required String peerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_TypingStarted;
  const factory NetworkEvent.peerStatusChanged({
    required String peerId,
    required String status,
  }) = NetworkEvent_PeerStatusChanged;
  const factory NetworkEvent.messagePinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessagePinned;
  const factory NetworkEvent.messageUnpinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessageUnpinned;
  const factory NetworkEvent.fileHeaderReceived({
    required String fileId,
    required String fileName,
    required BigInt sizeBytes,
    required bool isImage,
    int? width,
    int? height,
    required String messageId,
    required String senderId,
    required String serverId,
    required String channelId,

    /// Video thumbnail back-reference (Phase 6.75 video preview).
    /// Present when the received FileHeader is a thumbnail for a vault video.
    VideoThumbRef? videoThumb,

    /// Hidden Share back-reference for large files / progressive video streaming.
    String? shareRootHash,
    String? shareKeyHex,
  }) = NetworkEvent_FileHeaderReceived;
  const factory NetworkEvent.fileProgress({
    required String fileId,
    required int chunksReceived,
    required int totalChunks,
  }) = NetworkEvent_FileProgress;
  const factory NetworkEvent.fileCompleted({
    required String fileId,
    required String diskPath,
  }) = NetworkEvent_FileCompleted;
  const factory NetworkEvent.fileFailed({
    required String fileId,
    required String error,
  }) = NetworkEvent_FileFailed;

  /// Time-limited TURN credentials from the relay (over the authed WS).
  const factory NetworkEvent.turnCredentials({
    required String username,
    required String password,
    required BigInt ttl,
    required List<String> uris,
  }) = NetworkEvent_TurnCredentials;
  const factory NetworkEvent.linkCodeClaimed({required String code}) =
      NetworkEvent_LinkCodeClaimed;
  const factory NetworkEvent.linkCodeError({
    required String error,
    required String code,
  }) = NetworkEvent_LinkCodeError;
  const factory NetworkEvent.siblingLinkAvailable({
    required String peerId,
    required int theirMsgCount,
    required int theirFriendCount,
    required bool theirHasProfile,
  }) = NetworkEvent_SiblingLinkAvailable;
  const factory NetworkEvent.linkProgress({
    required String linkId,
    required BigInt bytesReceived,
    required BigInt totalBytes,
  }) = NetworkEvent_LinkProgress;
  const factory NetworkEvent.linkComplete({
    required String linkId,
    required int msgCount,
    required int friendCount,
    required int serverCount,
  }) = NetworkEvent_LinkComplete;
  const factory NetworkEvent.linkFailed({
    required String linkId,
    required String error,
  }) = NetworkEvent_LinkFailed;
  const factory NetworkEvent.linkPushComplete({required BigInt bytes}) =
      NetworkEvent_LinkPushComplete;
  const factory NetworkEvent.shardStored({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardStored;
  const factory NetworkEvent.shardStoreAckReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required bool success,
    required String error,
  }) = NetworkEvent_ShardStoreAckReceived;
  const factory NetworkEvent.shardStoreFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String targetPeer,
    required String error,
  }) = NetworkEvent_ShardStoreFailed;
  const factory NetworkEvent.shardDeleted({
    required String serverId,
    required String contentId,
  }) = NetworkEvent_ShardDeleted;
  const factory NetworkEvent.shardReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardReceived;
  const factory NetworkEvent.shardRequestFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String error,
  }) = NetworkEvent_ShardRequestFailed;
  const factory NetworkEvent.vaultUploadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultUploadProgress;
  const factory NetworkEvent.vaultUploadComplete({
    required String serverId,
    required String contentId,
    required String channelId,
  }) = NetworkEvent_VaultUploadComplete;
  const factory NetworkEvent.vaultUploadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultUploadFailed;
  const factory NetworkEvent.vaultDownloadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultDownloadProgress;
  const factory NetworkEvent.vaultDownloadComplete({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_VaultDownloadComplete;
  const factory NetworkEvent.vaultDownloadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultDownloadFailed;
  const factory NetworkEvent.rebalanceStarted({
    required String serverId,
    required int shardsToMove,
  }) = NetworkEvent_RebalanceStarted;
  const factory NetworkEvent.rebalanceProgress({
    required String serverId,
    required int moved,
    required int total,
  }) = NetworkEvent_RebalanceProgress;
  const factory NetworkEvent.rebalanceCompleted({required String serverId}) =
      NetworkEvent_RebalanceCompleted;
  const factory NetworkEvent.vaultUploadReplicationFallback({
    required String serverId,
    required String contentId,
    required BigInt online,
    required BigInt needed,
  }) = NetworkEvent_VaultUploadReplicationFallback;
  const factory NetworkEvent.keyExchangeStarted({required String peerId}) =
      NetworkEvent_KeyExchangeStarted;
  const factory NetworkEvent.keyExchangeProgress({
    required String peerId,
    required String stage,
  }) = NetworkEvent_KeyExchangeProgress;

  /// Forward incoming WebRTC signaling message to Dart.
  const factory NetworkEvent.webRtcSignal({
    required String peerId,
    required String signalType,
    required String payload,
    required String connId,
  }) = NetworkEvent_WebRtcSignal;

  /// Tell Dart to send a file over WebRTC data channel.
  const factory NetworkEvent.webRtcSendFile({
    required String peerId,
    required String transferId,
    required String filePath,
    required BigInt totalSize,
    required String kind,
    required int shardIndex,
    required int chunkIndex,
  }) = NetworkEvent_WebRtcSendFile;

  /// Forward incoming voice call signaling message to Dart.
  const factory NetworkEvent.callSignal({
    required String peerId,
    required String signalType,
    required String payload,
  }) = NetworkEvent_CallSignal;
  const factory NetworkEvent.voiceChannelJoined({
    required String serverId,
    required String channelId,
    required String peerId,
  }) = NetworkEvent_VoiceChannelJoined;
  const factory NetworkEvent.voiceChannelLeft({
    required String serverId,
    required String channelId,
    required String peerId,
  }) = NetworkEvent_VoiceChannelLeft;
  const factory NetworkEvent.voiceChannelSignal({
    required String serverId,
    required String channelId,
    required String peerId,
    required String signalType,
    required String payload,
  }) = NetworkEvent_VoiceChannelSignal;
  const factory NetworkEvent.gossipConnect({required String peerId}) =
      NetworkEvent_GossipConnect;
  const factory NetworkEvent.gossipDisconnect({required String peerId}) =
      NetworkEvent_GossipDisconnect;
  const factory NetworkEvent.gossipRelayFile({
    required String broadcastId,
    required int ttl,
    required String originPeerId,
    required String filePath,
    required BigInt totalSize,
    required String kind,
    required int shardIndex,
    required String excludePeerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_GossipRelayFile;

  /// Send a small gossip frame (type byte 0x04 on 'hollow-data') to each
  /// target's open data channel. Tier 2 large-server scaling: CRDT ops
  /// flood peer-to-peer instead of paying the relay's O(N) egress.
  const factory NetworkEvent.gossipRelayOp({
    required List<String> targets,
    required Uint8List payload,
  }) = NetworkEvent_GossipRelayOp;
  const factory NetworkEvent.voiceChannelModeChanged({
    required String serverId,
    required String channelId,
    required String mode,
    required List<String> gossipNeighbors,
  }) = NetworkEvent_VoiceChannelModeChanged;

  /// MLS epoch changed — SFrame key for voice E2EE.
  /// `channel_id` is set when the key belongs to a restricted channel's MLS
  /// subgroup (per-channel subgroups voice); Dart routes it to that voice
  /// channel's cryptor only. `None` = the server-wide group key.
  const factory NetworkEvent.mlsEpochChanged({
    required String serverId,
    required BigInt epoch,
    required Uint8List sframeKey,
    String? channelId,
  }) = NetworkEvent_MlsEpochChanged;

  /// (Host) someone is in the waiting room. `avatar_hash` is a hash, never
  /// blob bytes; Dart computes the friend badge locally.
  const factory NetworkEvent.conferenceJoinRequestReceived({
    required String confId,
    required String peerId,
    required String displayName,
    required String avatarHash,
  }) = NetworkEvent_ConferenceJoinRequestReceived;

  /// (Joiner) declined / wrong code / meeting gone.
  const factory NetworkEvent.conferenceJoinDenied({
    required String confId,
    required String reason,
  }) = NetworkEvent_ConferenceJoinDenied;

  /// (Joiner) lobby banner: whose meeting we're waiting for.
  const factory NetworkEvent.conferenceLobbyInfo({
    required String confId,
    required String hostPeerId,
    required String hostName,
    required String hostAvatarHash,
  }) = NetworkEvent_ConferenceLobbyInfo;

  /// (Joiner) admitted — the conf MLS Welcome landed; join the call now.
  const factory NetworkEvent.conferenceAdmitted({required String confId}) =
      NetworkEvent_ConferenceAdmitted;

  /// RAM-only conference chat line (no persistence, no unread machinery).
  const factory NetworkEvent.conferenceChatMessage({
    required String confId,
    required String senderPeerId,
    required String text,
    required PlatformInt64 timestamp,
  }) = NetworkEvent_ConferenceChatMessage;

  /// Meeting over. Dart validates `by_peer_id` against the known host.
  const factory NetworkEvent.conferenceEnded({
    required String confId,
    required String byPeerId,
  }) = NetworkEvent_ConferenceEnded;

  /// We were removed from the meeting (host-validated in Dart).
  const factory NetworkEvent.conferenceKicked({
    required String confId,
    required String byPeerId,
  }) = NetworkEvent_ConferenceKicked;
  const factory NetworkEvent.recoveryPoolCreated({
    required String serverId,
    required String inviteLink,
  }) = NetworkEvent_RecoveryPoolCreated;
  const factory NetworkEvent.recoveryPoolJoined({required String serverId}) =
      NetworkEvent_RecoveryPoolJoined;
  const factory NetworkEvent.recoveryPoolJoinFailed({
    required String serverId,
    required String reason,
  }) = NetworkEvent_RecoveryPoolJoinFailed;
  const factory NetworkEvent.recoveryPoolMemberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_RecoveryPoolMemberJoined;
  const factory NetworkEvent.recoveryPoolMemberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_RecoveryPoolMemberLeft;
  const factory NetworkEvent.recoveryPoolStatus({
    required String serverId,
    required int totalFiles,
    required int reconstructable,
    required int partial,
    required int noShards,
    required double progressPct,
  }) = NetworkEvent_RecoveryPoolStatus;
  const factory NetworkEvent.recoveryPoolShardTransferred({
    required String serverId,
    required String contentId,
    required int shardIndex,
  }) = NetworkEvent_RecoveryPoolShardTransferred;
  const factory NetworkEvent.recoveryPoolFileRecovered({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_RecoveryPoolFileRecovered;
  const factory NetworkEvent.recoveryPoolStopped({required String serverId}) =
      NetworkEvent_RecoveryPoolStopped;
  const factory NetworkEvent.shareManifestReady({
    required String rootHash,
    required String fileName,
    required BigInt totalSize,
    required int chunkCount,
  }) = NetworkEvent_ShareManifestReady;
  const factory NetworkEvent.shareProgress({
    required String rootHash,
    required int chunksHave,
    required int chunksTotal,
    required int seeders,
    required int leechers,
    required BigInt bytesPerSec,
  }) = NetworkEvent_ShareProgress;
  const factory NetworkEvent.shareCompleted({
    required String rootHash,
    required String diskPath,
  }) = NetworkEvent_ShareCompleted;
  const factory NetworkEvent.shareFailed({
    required String rootHash,
    required String error,
  }) = NetworkEvent_ShareFailed;
  const factory NetworkEvent.shareSeedingChanged({
    required String rootHash,
    required bool seeding,
    required int seeders,
    required int leechers,
    required BigInt bytesUploaded,
  }) = NetworkEvent_ShareSeedingChanged;
  const factory NetworkEvent.shareCreated({
    required String rootHash,
    required String link,
    required String fileName,
    required BigInt totalSize,
  }) = NetworkEvent_ShareCreated;
  const factory NetworkEvent.shareCreatedHidden({
    required String rootHash,
    required String keyHex,
    required String fileName,
    required BigInt totalSize,
  }) = NetworkEvent_ShareCreatedHidden;
  const factory NetworkEvent.shareList({required List<ShareEntry> entries}) =
      NetworkEvent_ShareList;
  const factory NetworkEvent.shareNeedWebRtc({
    required String peerId,
    required bool hidden,
  }) = NetworkEvent_ShareNeedWebRtc;
  const factory NetworkEvent.licenseError({required String reason}) =
      NetworkEvent_LicenseError;
  const factory NetworkEvent.twitchJoinRejected({
    required String serverId,
    required String reason,
  }) = NetworkEvent_TwitchJoinRejected;
  const factory NetworkEvent.roomBudgetUpdate({
    required int joined,
    required int limit,
  }) = NetworkEvent_RoomBudgetUpdate;
  const factory NetworkEvent.roomCapHit({required String room}) =
      NetworkEvent_RoomCapHit;
  const factory NetworkEvent.publicChannelListReceived({
    required String serverId,
    required String serverName,
    required List<PublicChannelEntryFfi> channels,
    Uint8List? serverAvatar,
    Uint8List? serverBannerThumb,
  }) = NetworkEvent_PublicChannelListReceived;
  const factory NetworkEvent.publicChannelSyncReceived({
    required String serverId,
    required String channelId,
    required List<GuestSyncMessageFfi> messages,
    required bool hasMore,
    required List<SyncSenderProfileFfi> senderProfiles,
  }) = NetworkEvent_PublicChannelSyncReceived;
  const factory NetworkEvent.publicChannelConfigChanged({
    required String serverId,
    required String channelId,
    required bool isPublic,
    required String channelName,
    String? category,
  }) = NetworkEvent_PublicChannelConfigChanged;
}

/// FFI-facing public channel entry for guest viewer.
class PublicChannelEntryFfi {
  final String channelId;
  final String name;
  final String? category;

  const PublicChannelEntryFfi({
    required this.channelId,
    required this.name,
    this.category,
  });

  @override
  int get hashCode => channelId.hashCode ^ name.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicChannelEntryFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          name == other.name &&
          category == other.category;
}

/// Display metadata for a channel push notification (Tier 1-style: resolved
/// from the local DB, no node needed).
class PushChannelMeta {
  final String serverName;
  final String channelName;

  /// Effective LOCAL notification level for this channel ("all" / "mentions"
  /// / "nothing") — channel override falling back to the server default.
  /// Lets the Android background handler drop a push whose relay-side filter
  /// was stale.
  final String notifLevel;

  const PushChannelMeta({
    required this.serverName,
    required this.channelName,
    required this.notifLevel,
  });

  @override
  int get hashCode =>
      serverName.hashCode ^ channelName.hashCode ^ notifLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushChannelMeta &&
          runtimeType == other.runtimeType &&
          serverName == other.serverName &&
          channelName == other.channelName &&
          notifLevel == other.notifLevel;
}

/// Profile data for push notifications (Tier 1: cached profile, no node needed).
class PushProfile {
  final String displayName;
  final Uint8List? avatarBytes;

  const PushProfile({required this.displayName, this.avatarBytes});

  @override
  int get hashCode => displayName.hashCode ^ avatarBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushProfile &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          avatarBytes == other.avatarBytes;
}

/// Lightweight FFI mirror of node::types::ShareEntryRef.
class ShareEntry {
  final String rootHash;
  final String fileName;
  final BigInt totalSize;
  final int chunksHave;
  final int chunksTotal;
  final String state;
  final bool seeding;
  final String? diskPath;
  final BigInt bytesUploaded;
  final String shareLink;
  final PlatformInt64 createdAt;
  final String? serverId;
  final String? contextType;

  const ShareEntry({
    required this.rootHash,
    required this.fileName,
    required this.totalSize,
    required this.chunksHave,
    required this.chunksTotal,
    required this.state,
    required this.seeding,
    this.diskPath,
    required this.bytesUploaded,
    required this.shareLink,
    required this.createdAt,
    this.serverId,
    this.contextType,
  });

  @override
  int get hashCode =>
      rootHash.hashCode ^
      fileName.hashCode ^
      totalSize.hashCode ^
      chunksHave.hashCode ^
      chunksTotal.hashCode ^
      state.hashCode ^
      seeding.hashCode ^
      diskPath.hashCode ^
      bytesUploaded.hashCode ^
      shareLink.hashCode ^
      createdAt.hashCode ^
      serverId.hashCode ^
      contextType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareEntry &&
          runtimeType == other.runtimeType &&
          rootHash == other.rootHash &&
          fileName == other.fileName &&
          totalSize == other.totalSize &&
          chunksHave == other.chunksHave &&
          chunksTotal == other.chunksTotal &&
          state == other.state &&
          seeding == other.seeding &&
          diskPath == other.diskPath &&
          bytesUploaded == other.bytesUploaded &&
          shareLink == other.shareLink &&
          createdAt == other.createdAt &&
          serverId == other.serverId &&
          contextType == other.contextType;
}

/// FFI-facing sender profile for guest sync.
class SyncSenderProfileFfi {
  final String peerId;
  final String? name;
  final Uint8List? avatar;

  const SyncSenderProfileFfi({required this.peerId, this.name, this.avatar});

  @override
  int get hashCode => peerId.hashCode ^ name.hashCode ^ avatar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSenderProfileFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          avatar == other.avatar;
}

/// FFI-facing video thumbnail back-reference.
///
/// When a `FileHeaderReceived` event carries this, the file is a thumbnail
/// image for an underlying video stored in the vault. Dart side uses these
/// fields to render the play button overlay, format duration/size badges,
/// and trigger `vault_download_file(cid)` when the user taps play.
///
/// Phase 6.75 video preview in chats. See HOLLOW_PLAN.md.
class VideoThumbRef {
  /// Vault content_id (sha256 of ciphertext) of the underlying video.
  final String cid;

  /// Original video file extension (mp4, webm, mkv, ...).
  final String ext;

  /// Original video file name (used as the default for the Save As dialog).
  final String name;

  /// Video size in bytes.
  final BigInt size;

  /// Video duration in milliseconds.
  final int durMs;

  const VideoThumbRef({
    required this.cid,
    required this.ext,
    required this.name,
    required this.size,
    required this.durMs,
  });

  @override
  int get hashCode =>
      cid.hashCode ^
      ext.hashCode ^
      name.hashCode ^
      size.hashCode ^
      durMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoThumbRef &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          ext == other.ext &&
          name == other.name &&
          size == other.size &&
          durMs == other.durMs;
}
