// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'showcase.dart';
part 'network.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `event_forwarding_task`, `get_event_rx`, `get_http_runtime`, `get_license_key`, `get_node`, `get_proxy_config`, `get_proxy_socks_addr`, `get_relay_domain`, `get_runtime`, `import_hollowpack_bytes`, `import_verified_pack`, `open_local_store`, `send_node_command`, `set_proxy_socks_addr`, `store_profile_media`, `to_ffi_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NodeState`, `ProxyConfig`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

Future<void> setLicenseKey({String? key}) =>
    RustLib.instance.api.crateApiNetworkSetLicenseKey(key: key);

/// Tell the relay client that a real-time session (DM call, voice channel,
/// conference) is live, or has ended.
/// The only thing this changes is the reconnect policy: while true the socket
/// retries every second instead of backing off toward thirty. A call recovering
/// from a blip needs an ICE restart offer over this socket within tens of seconds,
/// so a socket asleep in a long backoff is the difference between a call that
/// recovers and one that is given up on.
///
/// Safe to call repeatedly with the same value. Dart refcounts the sessions and
/// only pushes the edges.
Future<void> setRealtimeSessionActive({required bool active}) => RustLib
    .instance
    .api
    .crateApiNetworkSetRealtimeSessionActive(active: active);

Future<void> setRelayUrl({String? domain}) =>
    RustLib.instance.api.crateApiNetworkSetRelayUrl(domain: domain);

/// Push the auto-download settings into the node (issue #41). Runtime-effective
/// — no node restart needed. `threshold_mb == 0` turns automatic downloads off.
/// `overrides_json` is a JSON object mapping `dm:{master}` / `server:{id}` keys
/// to a bool (`false` = never auto-download there, `true` = always).
Future<void> setAutoDownloadConfig({
  required int thresholdMb,
  required String overridesJson,
}) => RustLib.instance.api.crateApiNetworkSetAutoDownloadConfig(
  thresholdMb: thresholdMb,
  overridesJson: overridesJson,
);

/// Configure (or clear) the anti-censorship REALITY proxy. Call BEFORE start_node():
/// it seeds a global that start_node reads to launch the `shoes` tunnel, so a
/// runtime change needs a node restart. All-empty fields disable the proxy.
Future<void> setProxyConfig({
  required bool enabled,
  required String server,
  required String uuid,
  required String publicKey,
  required String shortId,
  required String sni,
}) => RustLib.instance.api.crateApiNetworkSetProxyConfig(
  enabled: enabled,
  server: server,
  uuid: uuid,
  publicKey: publicKey,
  shortId: shortId,
  sni: sni,
);

/// Start the node with the persistent identity from disk. Returns the local peer ID.
Future<String> startNode() => RustLib.instance.api.crateApiNetworkStartNode();

/// Stream network events to Dart in real time.
/// Must be called after `start_node()`. Can only be called once per node lifetime.
Stream<NetworkEvent> watchNetworkEvents() =>
    RustLib.instance.api.crateApiNetworkWatchNetworkEvents();

/// Poll for the next network event, the fallback for when streaming is not active.
Future<NetworkEvent?> pollNetworkEvent() =>
    RustLib.instance.api.crateApiNetworkPollNetworkEvent();

/// Get the local peer ID. Returns None if the node hasn't started.
Future<String?> getLocalPeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalPeerId();

/// Get the Olm identity fingerprint (Curve25519 base64), `None` before start.
Future<String?> getOlmFingerprint() =>
    RustLib.instance.api.crateApiNetworkGetOlmFingerprint();

/// Get the local Ed25519 public key as base64-encoded protobuf.
/// Used by the Verify Peer screen to display "Your Fingerprint".
Future<String> getLocalPublicKey() =>
    RustLib.instance.api.crateApiNetworkGetLocalPublicKey();

/// Resolve a (possibly per-device) peer_id to its MASTER identity peer_id.
///
/// Collapses a friend's device peer_ids into one person for display. Unknown peers
/// resolve to themselves, so this is safe on any id, and it reads the running
/// node's in-memory resolver with no DB hit.
Future<String> identityFor({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkIdentityFor(peerId: peerId);

/// Resolve a (possibly per-device) peer_id to its MASTER identity, falling back
/// to the PERSISTED device links in SQLCipher when the in-memory resolver is
/// still cold.
///
/// The push-tap path needs the fallback: a cold-start tap fires the moment the
/// shell mounts, which can be BEFORE the event loop warmed the resolver, and
/// `identity_for` would then resolve the friend's DEVICE id to itself (no error, so
/// callers cannot tell a cold miss from a genuine single-device peer) and open a
/// device-keyed empty thread. Any failure degrades to identity-passthrough.
Future<String> identityForPersisted({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkIdentityForPersisted(peerId: peerId);

/// Snapshot every known (device → master) link for the Dart attribution layer.
///
/// Dart builds a `device_link_provider` from this and refreshes it on
/// `DeviceListUpdated`. A single-device install returns only self-mappings.
Future<List<DeviceLink>> getDeviceLinks() =>
    RustLib.instance.api.crateApiNetworkGetDeviceLinks();

/// Full sibling teardown: tombstone EVERY device except this one in a single
/// master-signed version bump and PROPAGATE it, so friends drop the revoked
/// siblings and can never un-revoke them, each revoked sibling self-nukes on
/// ingest, and their Olm sessions and MLS leaves go. A blunt LOCAL wipe cannot
/// work: the grow-only union merge regrows the ghosts from siblings on the next
/// profile exchange. Requires a running node; re-link the others fresh afterwards.
Future<void> resetDeviceLists() =>
    RustLib.instance.api.crateApiNetworkResetDeviceLists();

/// The transport peer_id of the device this app is RUNNING on, distinct from
/// `get_local_peer_id` (the MASTER). Dart marks "This device" with it and hides its
/// Remove button, since a device cannot revoke itself. `None` before a device key
/// exists.
Future<String?> getLocalDevicePeerId() =>
    RustLib.instance.api.crateApiNetworkGetLocalDevicePeerId();

/// Revoke one of OUR OWN devices (lost or stolen): bump our master-signed device
/// list with the device tombstoned, drop its Olm session and, where we coordinate,
/// remove its MLS leaf. Rejected for the device we are running on or an id that is
/// not ours. Friends can never un-revoke it with a stale lower-version list.
Future<void> revokeDevice({required String devicePeerId}) => RustLib
    .instance
    .api
    .crateApiNetworkRevokeDevice(devicePeerId: devicePeerId);

/// Manual state sync: ask the chosen SOURCE sibling to re-announce all its servers
/// and re-share its friends to THIS device. The deterministic escape hatch for when
/// automatic sibling sync did not converge; the source must be online.
Future<void> requestStateSync({required String sourceDeviceId}) => RustLib
    .instance
    .api
    .crateApiNetworkRequestStateSync(sourceDeviceId: sourceDeviceId);

/// Set (or clear, when `label` is empty) the local human label for a device.
/// Local-only, so a person's two devices may show different labels for a third.
Future<void> setDeviceLabel({
  required String devicePeerId,
  required String label,
}) => RustLib.instance.api.crateApiNetworkSetDeviceLabel(
  devicePeerId: devicePeerId,
  label: label,
);

/// All local device labels for the Devices panel.
Future<List<DeviceLabel>> getDeviceLabels() =>
    RustLib.instance.api.crateApiNetworkGetDeviceLabels();

/// Verify an Ed25519 message signature against a canonical payload.
///
/// Used by the Message Proof dialog to show live VERIFIED / INVALID status. Pure
/// crypto, no node state. `canonical_payload` is the signing payload string, e.g.
/// "hollow-msg:dm:...".
Future<bool> verifyMessageProof({
  required String senderPeerId,
  required String signatureB64,
  required String publicKeyB64,
  required String canonicalPayload,
}) => RustLib.instance.api.crateApiNetworkVerifyMessageProof(
  senderPeerId: senderPeerId,
  signatureB64: signatureB64,
  publicKeyB64: publicKeyB64,
  canonicalPayload: canonicalPayload,
);

/// v2 verification for the Message Proof dialog (no v1 fallback since 0.8.5).
///
/// The v2 payload binds the row's structured fields (mid, reply_to, file_id,
/// order_us, link-preview digest), so this loads the row by `message_id` and builds
/// the canonical payload in RUST, keeping the grammar single-sourced instead of
/// mirrored in Dart. An EDITED row verifies against its edit signature.
///
/// `msg_type` is "dm" | "ch"; `context` is the recipient MASTER peer_id for DMs and
/// "server_id:channel_id" for channels.
Future<MessageProofV2> verifyMessageProofV2({
  required String msgType,
  required String context,
  required String senderPeerId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkVerifyMessageProofV2(
  msgType: msgType,
  context: context,
  senderPeerId: senderPeerId,
  messageId: messageId,
);

/// Fetch OpenGraph metadata for a URL and return a link preview the sender can
/// embed in their next message. Fails silently at every step, so the caller treats
/// errors as "no preview".
///
/// Runs on the dedicated HTTP runtime, never the node runtime: an authoring fetch
/// is third-party I/O on an unknown-latency host and would compete with the
/// SQLCipher blocking pool.
///
/// **Privacy:** sender side ONLY. Receivers render from embedded data and never
/// fetch the URL.
Future<LinkPreviewRef> fetchLinkPreview({required String url}) =>
    RustLib.instance.api.crateApiNetworkFetchLinkPreview(url: url);

/// Send a text message to a peer. The peer must be reachable (discovered via mDNS).
Future<void> sendMessage({
  required String peerId,
  required String text,
  required String messageId,
  String? replyToMid,
  LinkPreviewRef? linkPreview,
}) => RustLib.instance.api.crateApiNetworkSendMessage(
  peerId: peerId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
  linkPreview: linkPreview,
);

/// Send a text message to a server channel, encrypted to all connected members.
Future<void> sendChannelMessage({
  required String serverId,
  required String channelId,
  required String text,
  required String messageId,
  String? replyToMid,
  LinkPreviewRef? linkPreview,
}) => RustLib.instance.api.crateApiNetworkSendChannelMessage(
  serverId: serverId,
  channelId: channelId,
  text: text,
  messageId: messageId,
  replyToMid: replyToMid,
  linkPreview: linkPreview,
);

/// Edit a channel message. Broadcasts the edit to all server members.
Future<void> editChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  newText: newText,
);

/// Edit a DM message. Sends the edit to the DM peer.
Future<void> editDmMessage({
  required String peerId,
  required String messageId,
  required String newText,
}) => RustLib.instance.api.crateApiNetworkEditDmMessage(
  peerId: peerId,
  messageId: messageId,
  newText: newText,
);

/// Configure the social-preview proxy base URL (None or empty = direct, the
/// default). Empty is not a degraded mode: X and TikTok lookups go straight to the
/// upstream public APIs. Setting this hands those lookups to a service speaking the
/// same normalized shape, for anyone who would rather the upstream never saw their
/// IP.
Future<void> setEmbedProxyUrl({String? base}) =>
    RustLib.instance.api.crateApiNetworkSetEmbedProxyUrl(base: base);

/// Attach (or clear) a link preview on a channel message that was ALREADY
/// sent, without editing it.
///
/// This exists for the send-beat-the-fetch race: the compose box fetches OG
/// metadata in the background and a fast sender used to lose the card entirely.
/// `preview: None` clears it, which is what an edit that removed the URL wants.
///
/// The row is re-signed over its unchanged text and timestamp with the new preview
/// digest, so it keeps verifying, and `edited_at` is untouched: a late card must
/// not make the bubble say "(edited)". Only the author may attach.
Future<void> attachChannelLinkPreview({
  required String serverId,
  required String channelId,
  required String messageId,
  LinkPreviewRef? preview,
}) => RustLib.instance.api.crateApiNetworkAttachChannelLinkPreview(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  preview: preview,
);

/// DM twin of [`attach_channel_link_preview`].
Future<void> attachDmLinkPreview({
  required String peerId,
  required String messageId,
  LinkPreviewRef? preview,
}) => RustLib.instance.api.crateApiNetworkAttachDmLinkPreview(
  peerId: peerId,
  messageId: messageId,
  preview: preview,
);

/// Delete (hide) a channel message for all members. The row stays in the DB as
/// evidence but is hidden from the UI.
Future<void> deleteChannelMessage({
  required String serverId,
  required String channelId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteChannelMessage(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
);

/// Delete (hide) a DM message. Sends the deletion to the DM peer.
Future<void> deleteDmMessage({
  required String peerId,
  required String messageId,
}) => RustLib.instance.api.crateApiNetworkDeleteDmMessage(
  peerId: peerId,
  messageId: messageId,
);

/// Add an emoji reaction to a channel message.
Future<void> addChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a channel message.
Future<void> removeChannelReaction({
  required String serverId,
  required String channelId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveChannelReaction(
  serverId: serverId,
  channelId: channelId,
  messageId: messageId,
  emoji: emoji,
);

/// Add an emoji reaction to a DM message.
Future<void> addDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkAddDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Remove an emoji reaction from a DM message.
Future<void> removeDmReaction({
  required String peerId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiNetworkRemoveDmReaction(
  peerId: peerId,
  messageId: messageId,
  emoji: emoji,
);

/// Send a friend request to a peer.
Future<void> sendFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkSendFriendRequest(peerId: peerId);

/// Accept a friend request from a peer.
Future<void> acceptFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkAcceptFriendRequest(peerId: peerId);

/// Reject a friend request from a peer.
Future<void> rejectFriendRequest({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRejectFriendRequest(peerId: peerId);

/// Remove a friend.
Future<void> removeFriend({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkRemoveFriend(peerId: peerId);

/// Send a friend request to a peer, resolving their temporary nickname first.
Future<void> sendFriendRequestByNickname({required String nickname}) => RustLib
    .instance
    .api
    .crateApiNetworkSendFriendRequestByNickname(nickname: nickname);

/// Claim a temporary nickname on the relay (RAM only, released on disconnect).
Future<void> claimNickname({required String nickname}) =>
    RustLib.instance.api.crateApiNetworkClaimNickname(nickname: nickname);

/// File a user report with the relay ("spam", "harassment", "illegal_content" or
/// "impersonation"). Fire-and-forget: the relay keeps only per-(target, category)
/// counts, dedups via hashed keys, and never stores who reported whom.
Future<void> reportUser({required String target, required String category}) =>
    RustLib.instance.api.crateApiNetworkReportUser(
      target: target,
      category: category,
    );

/// Release the currently claimed temporary nickname.
Future<void> releaseNickname() =>
    RustLib.instance.api.crateApiNetworkReleaseNickname();

/// (Populated device) Claim a 6-char link code on the relay and join its rendezvous
/// room, so an empty sibling can pull your data by entering it. The code is
/// generated client-side and displayed with a 5-minute countdown.
Future<void> claimLinkCode({required String code}) =>
    RustLib.instance.api.crateApiNetworkClaimLinkCode(code: code);

/// (Populated device) Release the currently claimed link code + leave its room.
Future<void> releaseLinkCode() =>
    RustLib.instance.api.crateApiNetworkReleaseLinkCode();

/// (Empty device) Resolve a link code shown on the populated device, then request
/// its full snapshot. `include_vault`/`include_files` control snapshot scope.
Future<void> resolveLinkCode({
  required String code,
  required bool includeVault,
  required bool includeFiles,
}) => RustLib.instance.api.crateApiNetworkResolveLinkCode(
  code: code,
  includeVault: includeVault,
  includeFiles: includeFiles,
);

/// (Empty device, mnemonic path) Request a full snapshot directly from a known
/// sibling device (no code; used when the sibling is already in a shared room).
Future<void> requestLinkSnapshot({
  required String targetPeer,
  required bool includeVault,
  required bool includeFiles,
}) => RustLib.instance.api.crateApiNetworkRequestLinkSnapshot(
  targetPeer: targetPeer,
  includeVault: includeVault,
  includeFiles: includeFiles,
);

/// (Populated device) Accept an inbound link request and push the snapshot to the
/// target device. Build scope is chosen here (files/vault).
Future<void> acceptLinkPush({
  required String targetPeer,
  required bool includeVault,
  required bool includeFiles,
}) => RustLib.instance.api.crateApiNetworkAcceptLinkPush(
  targetPeer: targetPeer,
  includeVault: includeVault,
  includeFiles: includeFiles,
);

/// (Populated device) Decline an inbound link request.
Future<void> declineLinkPush({required String targetPeer}) =>
    RustLib.instance.api.crateApiNetworkDeclineLinkPush(targetPeer: targetPeer);

/// Load a peer's cached profile straight from SQLCipher for push display. Works
/// without a running node; `None` when there is no profile or identity is locked.
Future<PushProfile?> getPushProfile({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkGetPushProfile(peerId: peerId);

/// Nudge the LIVE full node to (re)join the DM room for `sender_peer_id` so the
/// relay replays that room's buffered offline DMs.
///
/// The FCM background isolate shares its process with the still-running full node,
/// so `start_fetch_node` refuses to start; the live node can collect the buffered
/// ciphertext instead, and a queued JoinRoom rides the reconnect if the WS is a
/// doze-killed zombie. Returns Ok(false) when no node is running, in which case the
/// caller should use the fetch node.
Future<bool> nudgeLiveDmFetch({required String senderPeerId}) => RustLib
    .instance
    .api
    .crateApiNetworkNudgeLiveDmFetch(senderPeerId: senderPeerId);

/// Channel-wake sibling of [`nudge_live_dm_fetch`]: ask the LIVE full node to
/// (re)join the server room for a channel push so the relay replays its buffered
/// ciphertext. Returns Ok(false) when no node runs.
Future<bool> nudgeLiveRoomJoin({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkNudgeLiveRoomJoin(roomCode: roomCode);

/// Start a lightweight invisible fetch node to receive buffered messages.
///
/// DM wake (`server_room` = None) joins only the DM room and decrypts via Olm; a
/// channel wake joins the server room and decrypts via MLS or signed public
/// plaintext. Cannot run while the full node is active. Blocks the calling thread.
Future<List<FetchedMessage>> startFetchNode({
  required String senderPeerId,
  required int timeoutSecs,
  String? serverRoom,
}) => RustLib.instance.api.crateApiNetworkStartFetchNode(
  senderPeerId: senderPeerId,
  timeoutSecs: timeoutSecs,
  serverRoom: serverRoom,
);

/// Register an FCM/APNs push token with the relay for offline wake-up notifications.
Future<void> registerPushToken({
  required String token,
  required String platform,
}) => RustLib.instance.api.crateApiNetworkRegisterPushToken(
  token: token,
  platform: platform,
);

/// Register per-server/channel push prefs with the relay: `{"<server_id>":
/// {"level": "all|mentions|nothing", "channels": {...}}}`. RAM-only and re-sent on
/// every reconnect. The relay filters channel pushes against these BEFORE
/// contacting FCM/APNs, because an iOS alert push cannot be suppressed after
/// delivery.
Future<void> setPushPrefs({required String prefsJson}) =>
    RustLib.instance.api.crateApiNetworkSetPushPrefs(prefsJson: prefsJson);

/// Opt in or out of the relay's extended offline DM delivery. When enabled the
/// relay keeps Olm-encrypted DM text and FileHeader frames for this device for
/// `retention_secs` (clamped to 1h..7d) instead of the 24h push baseline and
/// replays them on the next connect, deleting what it delivers. Text and file
/// METADATA only, never bytes. RAM-only, so Dart calls this once per app start.
Future<void> setOfflineInbox({
  required bool enabled,
  required PlatformInt64 retentionSecs,
}) => RustLib.instance.api.crateApiNetworkSetOfflineInbox(
  enabled: enabled,
  retentionSecs: retentionSecs,
);

/// Resolve server + channel names and the effective local notification level
/// directly from SQLCipher (no running node). Returns None when the server is
/// unknown locally or identity is locked.
Future<PushChannelMeta?> getPushChannelMeta({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkGetPushChannelMeta(
  serverId: serverId,
  channelId: channelId,
);

/// Send a typing indicator, ephemeral and never stored. DMs pass server_id = ""
/// and the peer id as channel_id.
Future<void> sendTypingIndicator({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkSendTypingIndicator(
  serverId: serverId,
  channelId: channelId,
);

/// Toggle invisible mode. Broadcasts StatusUpdate to all connected peers.
Future<void> setInvisible({required bool invisible}) =>
    RustLib.instance.api.crateApiNetworkSetInvisible(invisible: invisible);

/// Subscribe to specific channels for topic-based relay routing: only subscribed
/// channels arrive in real time, the rest sync on demand when opened.
Future<void> subscribeChannels({
  required String serverId,
  required List<String> channelIds,
}) => RustLib.instance.api.crateApiNetworkSubscribeChannels(
  serverId: serverId,
  channelIds: channelIds,
);

/// Request message sync for one channel from all connected server members.
Future<void> requestChannelSync({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkRequestChannelSync(
  serverId: serverId,
  channelId: channelId,
);

/// Notify all connected peers that we are shutting down, so they update state at
/// once. Call before closing the app.
/// Update our profile: save to the DB and broadcast to connected peers.
///
/// Every optional field is three-state: `None` = unchanged, `Some("")` = clear,
/// `Some(v)` = set. `avatar_frame` is a built-in `b:<hue>` or the 64-hex hash of a
/// blob stored by [`process_and_store_avatar_frame`], never bytes; `avatar_anim` /
/// `banner_anim` name hashes whose bytes ride the asset rail, and their `still` must
/// be passed as the matching `avatar_bytes` / `banner_bytes`. A still-only pick must
/// pass `Some("")` so a previous animation is dropped.
Future<void> updateProfile({
  required String displayName,
  required String status,
  required String aboutMe,
  Uint8List? avatarBytes,
  Uint8List? bannerBytes,
  required String twitchUsername,
  String? showcaseBoard,
  List<ShowcaseAsset>? showcaseAssets,
  String? avatarFrame,
  String? avatarAnim,
  String? bannerAnim,
  String? supportCreds,
}) => RustLib.instance.api.crateApiNetworkUpdateProfile(
  displayName: displayName,
  status: status,
  aboutMe: aboutMe,
  avatarBytes: avatarBytes,
  bannerBytes: bannerBytes,
  twitchUsername: twitchUsername,
  showcaseBoard: showcaseBoard,
  showcaseAssets: showcaseAssets,
  avatarFrame: avatarFrame,
  avatarAnim: avatarAnim,
  bannerAnim: bannerAnim,
  supportCreds: supportCreds,
);

/// Process a raw image into a person's avatar (512x512 WebP — see
/// `image_convert::AVATAR_DIM`). Returns processed bytes.
Future<Uint8List> processAvatar({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessAvatar(rawBytes: rawBytes);

/// Process a user-picked image or GIF into an AVATAR FRAME and cache it
/// content-addressed under `AssetKind::Frame`. The caller then names the returned
/// hash in `update_profile(avatar_frame: ...)`; the bytes ride the asset rail on
/// demand, never the profile push.
///
/// Errors are user-facing: over the cap, or the authoring gate that a frame's middle
/// has to be see-through, since frames paint IN FRONT of the avatar.
/// middle has to be see-through (frames paint IN FRONT of the avatar).
Future<ProcessedFrame> processAndStoreAvatarFrame({
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiNetworkProcessAndStoreAvatarFrame(
  rawBytes: rawBytes,
);

/// Process a user-picked animated image into an ANIMATED AVATAR cached under
/// `AssetKind::Profile`. The caller names the hash in `update_profile(avatar_anim:
/// ...)` and passes `still` as `avatar_bytes`; the animation rides the asset rail,
/// never the profile push.
///
/// Errors are user-facing: over the 2 MB cap even after the quality ladder, or too
/// many frames to hold decoded.
/// too many frames to hold decoded (a screen recording used as profile art).
Future<ProcessedProfileMedia> processAndStoreAvatarAnim({
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiNetworkProcessAndStoreAvatarAnim(
  rawBytes: rawBytes,
);

/// The banner twin of [`process_and_store_avatar_anim`] (2.5:1 crop, 1200x480
/// ceiling). Pass `still` as `banner_bytes` and the hash as `banner_anim`.
Future<ProcessedProfileMedia> processAndStoreBannerAnim({
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiNetworkProcessAndStoreBannerAnim(
  rawBytes: rawBytes,
);

/// Import a `.hollowpack` bought from the artist shop: verify it whole, put its
/// files on the asset rail exactly as they arrived, and record what was bought and
/// from whom. Importing does NOT touch the profile; wearing the art is separate.
///
/// The bytes are stored AS-IS and never re-encoded: the art's identity is the
/// SHA-256 of the processed bytes the shop's encoders produced, and a second
/// generation through a lossy encoder would mint a different hash and orphan the
/// support credential bound to the first.
///
/// Verification is [`crate::hollowpack::verify_pack`], the same call `hollowpack
/// inspect` makes, and it refuses the WHOLE pack rather than dropping a bad file:
/// caps on file count and size, recomputed SHA-256 against the manifest, decoded
/// dimensions against the role's ceiling, and the see-through-centre gate re-applied
/// so a hand-built pack cannot smuggle a frame past the picker. Nothing is written
/// until every file has passed.
Future<HollowpackImport> importHollowpack({required String path}) =>
    RustLib.instance.api.crateApiNetworkImportHollowpack(path: path);

/// Every piece of shop art this install owns, newest first.
Future<List<OwnedArt>> listOwnedArt() =>
    RustLib.instance.api.crateApiNetworkListOwnedArt();

/// One-shot migration for a profile authored BEFORE animated media moved to the
/// asset rail, where the animation sat in `avatar`/`banner` as raw source bytes and
/// rode every profile push. Converts ours in place and re-announces once.
///
/// Without it the bandwidth win only lands for people who re-pick their avatar and
/// everyone else keeps re-shipping megabytes of unchanged GIF on every reconnect. A
/// settings marker makes it idempotent, and a conversion FAILURE still sets the
/// marker: a source we cannot convert keeps working, it just never becomes cheap.
///
/// Returns true when something was actually converted.
Future<bool> migrateProfileMediaOnce() =>
    RustLib.instance.api.crateApiNetworkMigrateProfileMediaOnce();

/// Process a raw image into banner format (2.5:1, at most 1200x480 WebP).
Future<Uint8List> processBanner({required List<int> rawBytes}) =>
    RustLib.instance.api.crateApiNetworkProcessBanner(rawBytes: rawBytes);

Future<void> notifyShutdown() =>
    RustLib.instance.api.crateApiNetworkNotifyShutdown();

/// Join a room via the signaling service, registering our addresses and
/// bootstrapping from other peers in the room.
Future<void> joinRoom({required String roomCode}) =>
    RustLib.instance.api.crateApiNetworkJoinRoom(roomCode: roomCode);

/// Stop the running node.
Future<void> stopNode() => RustLib.instance.api.crateApiNetworkStopNode();

/// Send a file to a DM peer (`peer_id`) or a server channel (`server_id` +
/// `channel_id`); the unused side is empty.
///
/// `vthumb` marks the file as the thumbnail for a vault-stored video.
/// `override_width`/`override_height` carry a video's pixel dimensions so receivers
/// render the right aspect ratio (ignored for images, whose dimensions Rust reads).
/// `is_voice` must be set explicitly for recorded voice messages, because the wire
/// name is the recorder's temp basename and the flag is what exempts them from the
/// receiver's auto-download gate. `poster_bytes` is a video's extracted first frame,
/// re-encoded here into the FileHeader's small poster.
Future<void> sendFile({
  String? peerId,
  String? serverId,
  String? channelId,
  required String filePath,
  required String messageId,
  required String messageText,
  VideoThumbRef? vthumb,
  int? overrideWidth,
  int? overrideHeight,
  String? shareRootHash,
  String? shareKeyHex,
  bool? isVoice,
  Uint8List? posterBytes,
}) => RustLib.instance.api.crateApiNetworkSendFile(
  peerId: peerId,
  serverId: serverId,
  channelId: channelId,
  filePath: filePath,
  messageId: messageId,
  messageText: messageText,
  vthumb: vthumb,
  overrideWidth: overrideWidth,
  overrideHeight: overrideHeight,
  shareRootHash: shareRootHash,
  shareKeyHex: shareKeyHex,
  isVoice: isVoice,
  posterBytes: posterBytes,
);

/// Request file chunks from a specific peer.
Future<void> requestFileFromPeer({
  required String fileId,
  required String peerId,
  required List<int> chunks,
}) => RustLib.instance.api.crateApiNetworkRequestFileFromPeer(
  fileId: fileId,
  peerId: peerId,
  chunks: chunks,
);

/// Stop waiting for a file: drop the queued ask and its explicit-pull receipt.
///
/// The receipt goes with the ask on purpose. An answer already in flight then
/// arrives with no receipt to bypass anything, so the size cap and the
/// auto-download gate judge it exactly as they judge an unsolicited push, which is
/// what "stop waiting" means. Nothing is emitted: the card clears its own state on
/// the tap and an event here would race it.
Future<void> cancelFileRequest({required String fileId}) =>
    RustLib.instance.api.crateApiNetworkCancelFileRequest(fileId: fileId);

/// Convert a WebP image file to another format (PNG/JPEG) for "Save As".
Future<Uint8List> convertImageFormat({
  required String sourcePath,
  required String targetFormat,
}) => RustLib.instance.api.crateApiNetworkConvertImageFormat(
  sourcePath: sourcePath,
  targetFormat: targetFormat,
);

/// Get the files directory path.
Future<String> getFilesDir() =>
    RustLib.instance.api.crateApiNetworkGetFilesDir();

/// Log a message from Dart to hollow_debug.log (visible in release builds).
Future<void> logFromDart({required String message}) =>
    RustLib.instance.api.crateApiNetworkLogFromDart(message: message);

/// Notify Rust that a WebRTC data channel is established with a peer.
Future<void> webrtcPeerConnected({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPeerConnected(peerId: peerId);

/// Notify Rust that a WebRTC data channel has been closed for a peer.
Future<void> webrtcPeerDisconnected({required String peerId}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPeerDisconnected(peerId: peerId);

/// Notify Rust that the DEDICATED Hollow Share data channel is open with a peer.
///
/// Tracked in its own set: Share runs a second, STUN-only peer connection so its
/// bytes never ride the relay, and reporting it as a general channel would let Rust
/// schedule Share chunks over the TURN-capable one.
Future<void> webrtcSharePeerConnected({required String peerId}) => RustLib
    .instance
    .api
    .crateApiNetworkWebrtcSharePeerConnected(peerId: peerId);

/// Notify Rust that the dedicated Hollow Share data channel has closed.
Future<void> webrtcSharePeerDisconnected({required String peerId}) => RustLib
    .instance
    .api
    .crateApiNetworkWebrtcSharePeerDisconnected(peerId: peerId);

/// Notify Rust that a Share chunk transfer failed on the Share data channel.
/// Kept apart from [`webrtc_transfer_failed`], which also evicts the peer from the
/// general set and drives the WS relay retry; neither applies to Share.
Future<void> webrtcShareTransferFailed({
  required String transferId,
  required String peerId,
  required String error,
}) => RustLib.instance.api.crateApiNetworkWebrtcShareTransferFailed(
  transferId: transferId,
  peerId: peerId,
  error: error,
);

/// Send a WebRTC signaling message to a peer, routed through the WSS relay.
Future<void> webrtcSendSignal({
  required String peerId,
  required String signalType,
  required String payload,
  required String connId,
}) => RustLib.instance.api.crateApiNetworkWebrtcSendSignal(
  peerId: peerId,
  signalType: signalType,
  payload: payload,
  connId: connId,
);

/// Notify Rust that a WebRTC file transfer completed (receiver side), so it can
/// decrypt and process the file.
Future<void> webrtcTransferComplete({
  required String transferId,
  required String tempPath,
  required String senderPeerId,
  required String kind,
  required int shardIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcTransferComplete(
  transferId: transferId,
  tempPath: tempPath,
  senderPeerId: senderPeerId,
  kind: kind,
  shardIndex: shardIndex,
);

/// Notify Rust that a WebRTC share-chunk transfer completed. Distinct from
/// `webrtc_transfer_complete` because share chunks need a 32-bit chunk_index.
Future<void> webrtcShareChunkComplete({
  required String transferId,
  required String tempPath,
  required String senderPeerId,
  required int chunkIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcShareChunkComplete(
  transferId: transferId,
  tempPath: tempPath,
  senderPeerId: senderPeerId,
  chunkIndex: chunkIndex,
);

/// Notify Rust that a WebRTC file send completed, so it cleans up the temp file.
Future<void> webrtcSendComplete({required String transferId}) => RustLib
    .instance
    .api
    .crateApiNetworkWebrtcSendComplete(transferId: transferId);

/// Notify Rust that a WebRTC transfer failed. Triggers WSS relay fallback.
Future<void> webrtcTransferFailed({
  required String transferId,
  required String peerId,
  required String error,
}) => RustLib.instance.api.crateApiNetworkWebrtcTransferFailed(
  transferId: transferId,
  peerId: peerId,
  error: error,
);

/// Send a voice call signaling message to a peer (Phase 5B).
Future<void> callSendSignal({
  required String peerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkCallSendSignal(
  peerId: peerId,
  signalType: signalType,
  payload: payload,
);

/// Join a voice channel in a server (Phase 5C).
Future<void> voiceChannelJoin({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelJoin(
  serverId: serverId,
  channelId: channelId,
);

/// Leave a voice channel in a server (Phase 5C).
Future<void> voiceChannelLeave({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelLeave(
  serverId: serverId,
  channelId: channelId,
);

/// Send a voice channel signaling message (SDP/ICE) to a specific peer (Phase 5C).
Future<void> voiceChannelSendSignal({
  required String serverId,
  required String channelId,
  required String peerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkVoiceChannelSendSignal(
  serverId: serverId,
  channelId: channelId,
  peerId: peerId,
  signalType: signalType,
  payload: payload,
);

/// SFrame heal: the voice cryptors report sustained decrypt failures against
/// `peer_id`, so re-emit the current MLS epoch key. With `escalate` the node also
/// re-bootstraps the MLS group (non-authority) or removes and re-adds the failing
/// peer's leaves (authority).
Future<void> voiceSframeHeal({
  required String serverId,
  required String channelId,
  required String peerId,
  required bool escalate,
}) => RustLib.instance.api.crateApiNetworkVoiceSframeHeal(
  serverId: serverId,
  channelId: channelId,
  peerId: peerId,
  escalate: escalate,
);

/// Send an Olm-encrypted `fwd_*` control signal to a media forwarder in its
/// `fwd:{peer_id}` room. Signal types are whitelisted to the client-sendable set and
/// the JSON payload requires an `origin` object. Queues and fires a signed
/// KeyRequest when no Olm session exists yet.
Future<void> forwarderSendSignal({
  required String forwarderPeerId,
  required String signalType,
  required String payload,
}) => RustLib.instance.api.crateApiNetworkForwarderSendSignal(
  forwarderPeerId: forwarderPeerId,
  signalType: signalType,
  payload: payload,
);

/// Join a media forwarder's dedicated relay room so fwd control signals can flow.
/// Pure transport join: it never touches DM conversation-pane state.
Future<void> joinForwarderRoom({required String forwarderPeerId}) => RustLib
    .instance
    .api
    .crateApiNetworkJoinForwarderRoom(forwarderPeerId: forwarderPeerId);

/// Leave a media forwarder's relay room (share stopped / no forwarder viewers
/// left / no longer watching through it).
Future<void> leaveForwarderRoom({required String forwarderPeerId}) => RustLib
    .instance
    .api
    .crateApiNetworkLeaveForwarderRoom(forwarderPeerId: forwarderPeerId);

/// Mirror the "Peer media forwarding" Settings toggle into the node. Desktop-only
/// in effect: a no-op on mobile and non-forwarder builds.
Future<void> setPeerForwardingEnabled({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiNetworkSetPeerForwardingEnabled(enabled: enabled);

/// Declare (or withdraw) willingness to forward the screen share identified by
/// `(origin_peer, kind)`, set when a `vc_screen_watch` advertises `fwd_capable`. The
/// embedded engine only accepts a `fwd_stream_register` whose origin matches an
/// active expectation: a peer forwarder forwards ONLY streams its user watches.
Future<void> setForwarderExpectation({
  required String originPeer,
  required String kind,
  required bool active,
}) => RustLib.instance.api.crateApiNetworkSetForwarderExpectation(
  originPeer: originPeer,
  kind: kind,
  active: active,
);

/// Feeder election: start or stop FEEDING another forwarder with a stream this
/// client's embedded engine already forwards, on a branch head whose stream OWNER
/// delegated it. The far forwarder still applies its own admission and accepts our
/// ingest only because the owner named us as `feeder` in an owner-authenticated
/// register, so this grants no authority the owner had not already granted.
Future<void> setForwarderFeed({
  required String originPeer,
  required String kind,
  required String stream,
  required String targetForwarder,
  required bool active,
}) => RustLib.instance.api.crateApiNetworkSetForwarderFeed(
  originPeer: originPeer,
  kind: kind,
  stream: stream,
  targetForwarder: targetForwarder,
  active: active,
);

/// Report data channel keepalive RTT for gossip peer scoring.
Future<void> webrtcPingReport({required String peerId, required int rttMs}) =>
    RustLib.instance.api.crateApiNetworkWebrtcPingReport(
      peerId: peerId,
      rttMs: rttMs,
    );

/// Report the ICE route class of a live data-channel connection: `is_direct` =
/// host/srflx/LAN rather than TURN-relayed.
Future<void> webrtcRouteReport({
  required String peerId,
  required bool isDirect,
}) => RustLib.instance.api.crateApiNetworkWebrtcRouteReport(
  peerId: peerId,
  isDirect: isDirect,
);

/// Hand back a gossip CRDT-op frame received on a data channel. It is ingested
/// through the same validated path as a relay CrdtOpBroadcast and re-flooded to our
/// own mesh neighbours only if it was new.
Future<void> webrtcGossipOpReceived({
  required String senderPeerId,
  required List<int> payload,
}) => RustLib.instance.api.crateApiNetworkWebrtcGossipOpReceived(
  senderPeerId: senderPeerId,
  payload: payload,
);

/// Notify Rust that a broadcast file was received via gossip data channel.
Future<void> webrtcBroadcastReceived({
  required String transferId,
  required String broadcastId,
  required int ttl,
  required String originPeerId,
  required String senderPeerId,
  required String tempPath,
  required BigInt totalSize,
  required String kind,
  required int shardIndex,
}) => RustLib.instance.api.crateApiNetworkWebrtcBroadcastReceived(
  transferId: transferId,
  broadcastId: broadcastId,
  ttl: ttl,
  originPeerId: originPeerId,
  senderPeerId: senderPeerId,
  tempPath: tempPath,
  totalSize: totalSize,
  kind: kind,
  shardIndex: shardIndex,
);

/// A local human label for a device (Step 8 Devices panel).
class DeviceLabel {
  final String devicePeerId;
  final String label;

  const DeviceLabel({required this.devicePeerId, required this.label});

  @override
  int get hashCode => devicePeerId.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLabel &&
          runtimeType == other.runtimeType &&
          devicePeerId == other.devicePeerId &&
          label == other.label;
}

/// A learned device → master identity link (multi-device, Phase 6).
class DeviceLink {
  /// A device's transport peer_id (`12D3KooW…`).
  final String devicePeerId;

  /// The master identity peer_id it belongs to.
  final String masterPeerId;

  const DeviceLink({required this.devicePeerId, required this.masterPeerId});

  @override
  int get hashCode => devicePeerId.hashCode ^ masterPeerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceLink &&
          runtimeType == other.runtimeType &&
          devicePeerId == other.devicePeerId &&
          masterPeerId == other.masterPeerId;
}

/// A discovered peer on the local network.
class DiscoveredPeer {
  final String peerId;
  final List<String> addresses;

  const DiscoveredPeer({required this.peerId, required this.addresses});

  @override
  int get hashCode => peerId.hashCode ^ addresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredPeer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          addresses == other.addresses;
}

/// A message fetched during background push processing (Tier 2).
class FetchedMessage {
  final String fromPeer;
  final String text;
  final PlatformInt64 timestamp;
  final String messageId;

  /// On-disk path to the message's image when this DM carried an inlined one, so the
  /// notification can show a BigPicture preview. `None` for text-only.
  final String? imagePath;

  /// Set for channel messages (channel wake): owning server.
  final String? serverId;

  /// Set for channel messages (channel wake): owning channel.
  final String? channelId;

  const FetchedMessage({
    required this.fromPeer,
    required this.text,
    required this.timestamp,
    required this.messageId,
    this.imagePath,
    this.serverId,
    this.channelId,
  });

  @override
  int get hashCode =>
      fromPeer.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      messageId.hashCode ^
      imagePath.hashCode ^
      serverId.hashCode ^
      channelId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FetchedMessage &&
          runtimeType == other.runtimeType &&
          fromPeer == other.fromPeer &&
          text == other.text &&
          timestamp == other.timestamp &&
          messageId == other.messageId &&
          imagePath == other.imagePath &&
          serverId == other.serverId &&
          channelId == other.channelId;
}

/// FFI-facing file metadata for a guest message (metadata only, no bytes).
class GuestFileMetaFfi {
  final String fileId;
  final String fileName;
  final String fileExt;
  final String mimeType;
  final BigInt sizeBytes;
  final bool isImage;
  final int? width;
  final int? height;

  /// Set ONLY when previewing our own server and the file is complete on OUR disk,
  /// so the card renders without any peer fetch.
  final String? diskPath;

  const GuestFileMetaFfi({
    required this.fileId,
    required this.fileName,
    required this.fileExt,
    required this.mimeType,
    required this.sizeBytes,
    required this.isImage,
    this.width,
    this.height,
    this.diskPath,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      fileName.hashCode ^
      fileExt.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      isImage.hashCode ^
      width.hashCode ^
      height.hashCode ^
      diskPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestFileMetaFfi &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          fileName == other.fileName &&
          fileExt == other.fileExt &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          isImage == other.isImage &&
          width == other.width &&
          height == other.height &&
          diskPath == other.diskPath;
}

/// FFI-facing guest reaction.
class GuestReactionFfi {
  final String emoji;
  final String peerId;
  final PlatformInt64 addedAt;

  const GuestReactionFfi({
    required this.emoji,
    required this.peerId,
    required this.addedAt,
  });

  @override
  int get hashCode => emoji.hashCode ^ peerId.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestReactionFfi &&
          runtimeType == other.runtimeType &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          addedAt == other.addedAt;
}

/// FFI-facing guest sync message.
class GuestSyncMessageFfi {
  final String senderId;
  final String text;
  final PlatformInt64 timestamp;
  final String? messageId;
  final String? signature;
  final String? publicKey;
  final PlatformInt64? editedAt;
  final String? replyTo;
  final PlatformInt64? hiddenAt;
  final List<GuestReactionFfi> reactions;

  /// Attachment metadata (never bytes) — Dart builds the file card from it.
  final GuestFileMetaFfi? fileMeta;

  /// The message's link preview card, signature-covered before it got here, so the
  /// guest browser renders it like a member would and never fetches the URL.
  final LinkPreviewRef? linkPreview;

  const GuestSyncMessageFfi({
    required this.senderId,
    required this.text,
    required this.timestamp,
    this.messageId,
    this.signature,
    this.publicKey,
    this.editedAt,
    this.replyTo,
    this.hiddenAt,
    required this.reactions,
    this.fileMeta,
    this.linkPreview,
  });

  @override
  int get hashCode =>
      senderId.hashCode ^
      text.hashCode ^
      timestamp.hashCode ^
      messageId.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      editedAt.hashCode ^
      replyTo.hashCode ^
      hiddenAt.hashCode ^
      reactions.hashCode ^
      fileMeta.hashCode ^
      linkPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GuestSyncMessageFfi &&
          runtimeType == other.runtimeType &&
          senderId == other.senderId &&
          text == other.text &&
          timestamp == other.timestamp &&
          messageId == other.messageId &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          editedAt == other.editedAt &&
          replyTo == other.replyTo &&
          hiddenAt == other.hiddenAt &&
          reactions == other.reactions &&
          fileMeta == other.fileMeta &&
          linkPreview == other.linkPreview;
}

/// One file that came out of a `.hollowpack`, with every value RECOMPUTED from the
/// bytes rather than read out of the pack's manifest.
class HollowpackFile {
  /// `frame`, `avatar`, `avatar_anim`, `avatar_still`, `banner`,
  /// `banner_anim` or `banner_still`.
  final String role;

  /// 64-hex SHA-256 of the bytes. This IS the art's identity: what `update_profile`
  /// names and what peers pull on the asset rail.
  final String hash;
  final BigInt bytes;
  final int w;
  final int h;
  final bool animated;

  const HollowpackFile({
    required this.role,
    required this.hash,
    required this.bytes,
    required this.w,
    required this.h,
    required this.animated,
  });

  @override
  int get hashCode =>
      role.hashCode ^
      hash.hashCode ^
      bytes.hashCode ^
      w.hashCode ^
      h.hashCode ^
      animated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HollowpackFile &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          hash == other.hash &&
          bytes == other.bytes &&
          w == other.w &&
          h == other.h &&
          animated == other.animated;
}

/// What an import landed, so the UI can say what was added and offer to wear
/// it.
class HollowpackImport {
  final String itemId;
  final String title;
  final String artistName;
  final String artistSlug;
  final String artistUrl;
  final String license;
  final List<HollowpackFile> files;

  const HollowpackImport({
    required this.itemId,
    required this.title,
    required this.artistName,
    required this.artistSlug,
    required this.artistUrl,
    required this.license,
    required this.files,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      artistSlug.hashCode ^
      artistUrl.hashCode ^
      license.hashCode ^
      files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HollowpackImport &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          title == other.title &&
          artistName == other.artistName &&
          artistSlug == other.artistSlug &&
          artistUrl == other.artistUrl &&
          license == other.license &&
          files == other.files;
}

/// FFI-facing link preview for a URL embedded in a message.
/// Generated by the SENDER and carried with the message. Receivers render from
/// these fields and NEVER request the previewed URL, which is a privacy property,
/// not a cache optimization.
class LinkPreviewRef {
  /// The URL that was previewed.
  final String url;

  /// og:title or <title> fallback. Already truncated by the sender.
  final String title;

  /// og:description or meta description. Already truncated by the sender.
  final String description;

  /// Display domain parsed from the URL (e.g. "github.com").
  final String domain;

  /// og:site_name if present. Empty string = fall back to domain in UI.
  final String siteName;

  /// Base64-encoded lossy WebP thumbnail (Q=50, max dim 400px).
  /// None when no og:image was found or the image fetch failed.
  final String? thumbWebpB64;

  /// Thumbnail width after resize.
  final int? thumbW;

  /// Thumbnail height after resize.
  final int? thumbH;

  /// `"large"` = social-post layout (image on top), `None` = compact row.
  final String? kind;

  /// Post author line, e.g. `"Jane Doe (@jane)"`. Social adapters only.
  final String? author;

  /// Where the post's video lives: a direct `.mp4`/`.webm` that plays inline on tap,
  /// or the media page. Never fetched to render the card, never autoplayed.
  final String? videoUrl;

  /// Video width, for the card's aspect ratio.
  final int? videoW;

  /// Video height, for the card's aspect ratio.
  final int? videoH;

  const LinkPreviewRef({
    required this.url,
    required this.title,
    required this.description,
    required this.domain,
    required this.siteName,
    this.thumbWebpB64,
    this.thumbW,
    this.thumbH,
    this.kind,
    this.author,
    this.videoUrl,
    this.videoW,
    this.videoH,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      title.hashCode ^
      description.hashCode ^
      domain.hashCode ^
      siteName.hashCode ^
      thumbWebpB64.hashCode ^
      thumbW.hashCode ^
      thumbH.hashCode ^
      kind.hashCode ^
      author.hashCode ^
      videoUrl.hashCode ^
      videoW.hashCode ^
      videoH.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkPreviewRef &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          description == other.description &&
          domain == other.domain &&
          siteName == other.siteName &&
          thumbWebpB64 == other.thumbWebpB64 &&
          thumbW == other.thumbW &&
          thumbH == other.thumbH &&
          kind == other.kind &&
          author == other.author &&
          videoUrl == other.videoUrl &&
          videoW == other.videoW &&
          videoH == other.videoH;
}

/// Result of a versioned Message Proof verification — see
/// [`verify_message_proof_v2`].
class MessageProofV2 {
  final bool hasSignature;
  final bool valid;

  /// 2 = verified against the v2 payload, 0 = did not verify. `1` (legacy v1, text
  /// only) is no longer produced; the variant stays out of the contract rather than
  /// out of the range so old Dart builds that switch on `== 2` keep behaving.
  final int sigVersion;

  /// The canonical v2 payload string, displayed and exported whether or not it
  /// verified.
  final String canonicalPayload;

  /// The row's signed fields, for the exported proof JSON.
  final String text;
  final PlatformInt64 timestampMs;
  final PlatformInt64? editedAt;
  final String? replyTo;
  final String? fileId;
  final PlatformInt64? orderUs;
  final String? lpDigest;
  final String? signatureB64;
  final String? publicKeyB64;

  const MessageProofV2({
    required this.hasSignature,
    required this.valid,
    required this.sigVersion,
    required this.canonicalPayload,
    required this.text,
    required this.timestampMs,
    this.editedAt,
    this.replyTo,
    this.fileId,
    this.orderUs,
    this.lpDigest,
    this.signatureB64,
    this.publicKeyB64,
  });

  @override
  int get hashCode =>
      hasSignature.hashCode ^
      valid.hashCode ^
      sigVersion.hashCode ^
      canonicalPayload.hashCode ^
      text.hashCode ^
      timestampMs.hashCode ^
      editedAt.hashCode ^
      replyTo.hashCode ^
      fileId.hashCode ^
      orderUs.hashCode ^
      lpDigest.hashCode ^
      signatureB64.hashCode ^
      publicKeyB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MessageProofV2 &&
          runtimeType == other.runtimeType &&
          hasSignature == other.hasSignature &&
          valid == other.valid &&
          sigVersion == other.sigVersion &&
          canonicalPayload == other.canonicalPayload &&
          text == other.text &&
          timestampMs == other.timestampMs &&
          editedAt == other.editedAt &&
          replyTo == other.replyTo &&
          fileId == other.fileId &&
          orderUs == other.orderUs &&
          lpDigest == other.lpDigest &&
          signatureB64 == other.signatureB64 &&
          publicKeyB64 == other.publicKeyB64;
}

@freezed
sealed class NetworkEvent with _$NetworkEvent {
  const NetworkEvent._();

  const factory NetworkEvent.peerDiscovered({required DiscoveredPeer peer}) =
      NetworkEvent_PeerDiscovered;
  const factory NetworkEvent.peerExpired({required String peerId}) =
      NetworkEvent_PeerExpired;
  const factory NetworkEvent.peerDisconnected({required String peerId}) =
      NetworkEvent_PeerDisconnected;
  const factory NetworkEvent.roomCleared() = NetworkEvent_RoomCleared;
  const factory NetworkEvent.listening({required String address}) =
      NetworkEvent_Listening;
  const factory NetworkEvent.messageReceived({
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
    LinkPreviewRef? linkPreview,
    String? signature,
    String? publicKey,
    required bool isOwn,
    required bool duplicate,
  }) = NetworkEvent_MessageReceived;
  const factory NetworkEvent.channelMessageReceived({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String text,
    required PlatformInt64 timestamp,
    required String messageId,
    required String replyToMid,
    LinkPreviewRef? linkPreview,
    String? signature,
    String? publicKey,
    required bool replyToOwn,
    required bool duplicate,
  }) = NetworkEvent_ChannelMessageReceived;
  const factory NetworkEvent.messageSent({
    required String toPeer,
    required String messageId,
    required PlatformInt64 timestamp,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_MessageSent;
  const factory NetworkEvent.channelMessageSent({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 timestamp,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageSent;
  const factory NetworkEvent.messageSendFailed({
    required String toPeer,
    required String error,
  }) = NetworkEvent_MessageSendFailed;
  const factory NetworkEvent.sessionEstablished({required String peerId}) =
      NetworkEvent_SessionEstablished;
  const factory NetworkEvent.error({required String message}) =
      NetworkEvent_Error;
  const factory NetworkEvent.serverCreated({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerCreated;
  const factory NetworkEvent.serverUpdated({required String serverId}) =
      NetworkEvent_ServerUpdated;

  /// Custom emote bytes arrived and verified, so Dart invalidates the hash-keyed
  /// providers and pending `[e:name:hash]` tokens re-render as images.
  const factory NetworkEvent.emoteAssetsReceived({
    required List<String> hashes,
  }) = NetworkEvent_EmoteAssetsReceived;

  /// The personal emote set changed through a sibling device, so Dart
  /// invalidates `personalEmotesProvider`.
  const factory NetworkEvent.personalEmotesUpdated() =
      NetworkEvent_PersonalEmotesUpdated;
  const factory NetworkEvent.channelAdded({
    required String serverId,
    required String channelId,
    required String name,
    required String channelType,
  }) = NetworkEvent_ChannelAdded;
  const factory NetworkEvent.channelRemoved({
    required String serverId,
    required String channelId,
  }) = NetworkEvent_ChannelRemoved;
  const factory NetworkEvent.channelRenamed({
    required String serverId,
    required String channelId,
    required String newName,
  }) = NetworkEvent_ChannelRenamed;
  const factory NetworkEvent.serverDeleted({required String serverId}) =
      NetworkEvent_ServerDeleted;
  const factory NetworkEvent.memberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberJoined;
  const factory NetworkEvent.memberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MemberLeft;
  const factory NetworkEvent.syncCompleted({
    required String serverId,
    required int opsApplied,
  }) = NetworkEvent_SyncCompleted;
  const factory NetworkEvent.serverJoined({
    required String serverId,
    required String name,
  }) = NetworkEvent_ServerJoined;
  const factory NetworkEvent.serverJoinFailed({
    required String serverId,
    required String reason,
  }) = NetworkEvent_ServerJoinFailed;

  /// Nobody was online to answer, so the request was PARKED (persisted plus
  /// deposited in the server room's join ring). Not a failure: the pending tile
  /// survives a restart.
  const factory NetworkEvent.serverJoinParked({required String serverId}) =
      NetworkEvent_ServerJoinParked;

  /// A parked join changed state: `rejected`, `admitted`, `ready` or
  /// `discarded`. `reason` carries the reject reason, empty otherwise.
  const factory NetworkEvent.pendingJoinUpdated({
    required String serverId,
    required String state,
    required String reason,
  }) = NetworkEvent_PendingJoinUpdated;
  const factory NetworkEvent.messageSyncStarted({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_MessageSyncStarted;
  const factory NetworkEvent.messageSyncCompleted({
    required String serverId,
    required int newMessageCount,
  }) = NetworkEvent_MessageSyncCompleted;
  const factory NetworkEvent.messageSyncFailed({
    required String serverId,
    required String error,
  }) = NetworkEvent_MessageSyncFailed;
  const factory NetworkEvent.messageSyncProgress({
    required String serverId,
    required String channelId,
    required int receivedCount,
    required int totalCount,
  }) = NetworkEvent_MessageSyncProgress;
  const factory NetworkEvent.roleChanged({
    required String serverId,
    required String peerId,
    required String newRole,
  }) = NetworkEvent_RoleChanged;
  const factory NetworkEvent.dmSyncCompleted({
    required String peerId,
    required int newMessageCount,
  }) = NetworkEvent_DmSyncCompleted;
  const factory NetworkEvent.profileUpdated({required String peerId}) =
      NetworkEvent_ProfileUpdated;

  /// A device list was ingested for `master_peer_id` (multi-device, Phase 6).
  const factory NetworkEvent.deviceListUpdated({required String masterPeerId}) =
      NetworkEvent_DeviceListUpdated;

  /// A contact's identity changed in a way worth showing: a new device joined their
  /// identity, or one re-keyed. `peer_id` is the MASTER, `kind` is `new_device` or
  /// `identity_key_changed`.
  const factory NetworkEvent.securityAlert({
    required String peerId,
    required String kind,
    required String detail,
    required PlatformInt64 createdAt,
  }) = NetworkEvent_SecurityAlert;

  /// THIS device was revoked (Step 7) — Dart self-nukes (wipe + relaunch).
  const factory NetworkEvent.selfRevoked() = NetworkEvent_SelfRevoked;
  const factory NetworkEvent.channelMessageEdited({
    required String serverId,
    required String channelId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_ChannelMessageEdited;
  const factory NetworkEvent.dmMessageEdited({
    required String peerId,
    required String messageId,
    required String newText,
    required PlatformInt64 editedAt,
    String? signature,
    String? publicKey,
  }) = NetworkEvent_DmMessageEdited;

  /// A link preview landed on an existing message. NOT an edit: `edited_at` is
  /// untouched, so the bubble must not gain an "(edited)" badge. `None` clears it.
  const factory NetworkEvent.channelLinkPreviewUpdated({
    required String serverId,
    required String channelId,
    required String messageId,
    LinkPreviewRef? preview,
  }) = NetworkEvent_ChannelLinkPreviewUpdated;
  const factory NetworkEvent.dmLinkPreviewUpdated({
    required String peerId,
    required String messageId,
    LinkPreviewRef? preview,
  }) = NetworkEvent_DmLinkPreviewUpdated;
  const factory NetworkEvent.channelMessageDeleted({
    required String serverId,
    required String channelId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_ChannelMessageDeleted;
  const factory NetworkEvent.dmMessageDeleted({
    required String peerId,
    required String messageId,
    required PlatformInt64 deletedAt,
  }) = NetworkEvent_DmMessageDeleted;
  const factory NetworkEvent.channelReactionAdded({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_ChannelReactionAdded;
  const factory NetworkEvent.dmReactionAdded({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 addedAt,
  }) = NetworkEvent_DmReactionAdded;
  const factory NetworkEvent.channelReactionRemoved({
    required String serverId,
    required String channelId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_ChannelReactionRemoved;
  const factory NetworkEvent.dmReactionRemoved({
    required String peerId,
    required String messageId,
    required String emoji,
    required String reactor,
    required PlatformInt64 removedAt,
  }) = NetworkEvent_DmReactionRemoved;
  const factory NetworkEvent.friendRequestReceived({required String peerId}) =
      NetworkEvent_FriendRequestReceived;
  const factory NetworkEvent.friendRequestAccepted({required String peerId}) =
      NetworkEvent_FriendRequestAccepted;
  const factory NetworkEvent.friendRequestRejected({required String peerId}) =
      NetworkEvent_FriendRequestRejected;
  const factory NetworkEvent.friendRemoved({required String peerId}) =
      NetworkEvent_FriendRemoved;

  /// Multi-device: a sibling device backfilled `count` new friends (Phase 6).
  const factory NetworkEvent.friendsBackfilled({required int count}) =
      NetworkEvent_FriendsBackfilled;
  const factory NetworkEvent.nicknameClaimed({required String nickname}) =
      NetworkEvent_NicknameClaimed;
  const factory NetworkEvent.nicknameReleased() = NetworkEvent_NicknameReleased;
  const factory NetworkEvent.nicknameClaimFailed({required String error}) =
      NetworkEvent_NicknameClaimFailed;
  const factory NetworkEvent.nicknameResolveFailed({
    required String nickname,
    required String error,
  }) = NetworkEvent_NicknameResolveFailed;
  const factory NetworkEvent.relayDisconnected() =
      NetworkEvent_RelayDisconnected;

  /// The WS relay connection was (re)established and authenticated.
  const factory NetworkEvent.relayConnected() = NetworkEvent_RelayConnected;

  /// A WS connect attempt is in progress. `reconnecting` distinguishes a
  /// backoff retry (after a drop) from the initial connect.
  const factory NetworkEvent.relayConnecting({required bool reconnecting}) =
      NetworkEvent_RelayConnecting;
  const factory NetworkEvent.channelNotificationHint({
    required String serverId,
    required String channelId,
    required String fromPeer,
    required String messageId,
    required bool hasEveryone,
    required List<String> mentionedNames,

    /// True only when the message replies to one of OUR messages. Hints
    /// from pre-0.9.1 senders carry no reply author, so this stays false.
    required bool isReplyToOwn,
  }) = NetworkEvent_ChannelNotificationHint;
  const factory NetworkEvent.typingStarted({
    required String peerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_TypingStarted;
  const factory NetworkEvent.peerStatusChanged({
    required String peerId,
    required String status,
  }) = NetworkEvent_PeerStatusChanged;
  const factory NetworkEvent.messagePinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessagePinned;
  const factory NetworkEvent.messageUnpinned({
    required String serverId,
    required String channelId,
    required String messageId,
  }) = NetworkEvent_MessageUnpinned;
  const factory NetworkEvent.fileHeaderReceived({
    required String fileId,
    required String fileName,
    required BigInt sizeBytes,
    required bool isImage,
    int? width,
    int? height,
    required String messageId,
    required String senderId,
    required String serverId,
    required String channelId,

    /// Video thumbnail back-reference, present when the FileHeader is a thumbnail
    /// for a vault video.
    VideoThumbRef? videoThumb,

    /// Hidden Share back-reference for large files / progressive video streaming.
    String? shareRootHash,
    String? shareKeyHex,

    /// Tiny base64 WebP placeholder thumbnail — rendered blurred under the
    /// Download button for gated/undownloaded images (issue #41 carry-over).
    String? thumbB64,
  }) = NetworkEvent_FileHeaderReceived;
  const factory NetworkEvent.fileProgress({
    required String fileId,
    required int chunksReceived,
    required int totalChunks,
  }) = NetworkEvent_FileProgress;
  const factory NetworkEvent.fileCompleted({
    required String fileId,
    required String diskPath,
  }) = NetworkEvent_FileCompleted;
  const factory NetworkEvent.fileFailed({
    required String fileId,
    required String error,
  }) = NetworkEvent_FileFailed;

  /// Honest file-card state for a file whose bytes are not on disk. `state` is
  /// "requesting" | "waiting" | "gone" | "expired"; `peer_id` is the MASTER the
  /// state is about, "" when none.
  const factory NetworkEvent.fileAvailability({
    required String fileId,
    required String state,
    required String peerId,
  }) = NetworkEvent_FileAvailability;

  /// Time-limited TURN credentials from the relay (over the authed WS).
  const factory NetworkEvent.turnCredentials({
    required String username,
    required String password,
    required BigInt ttl,
    required List<String> uris,
  }) = NetworkEvent_TurnCredentials;
  const factory NetworkEvent.linkCodeClaimed({required String code}) =
      NetworkEvent_LinkCodeClaimed;
  const factory NetworkEvent.linkCodeError({
    required String error,
    required String code,
  }) = NetworkEvent_LinkCodeError;
  const factory NetworkEvent.siblingLinkAvailable({
    required String peerId,
    required int theirMsgCount,
    required int theirFriendCount,
    required bool theirHasProfile,
  }) = NetworkEvent_SiblingLinkAvailable;
  const factory NetworkEvent.linkProgress({
    required String linkId,
    required BigInt bytesReceived,
    required BigInt totalBytes,
  }) = NetworkEvent_LinkProgress;
  const factory NetworkEvent.linkComplete({
    required String linkId,
    required int msgCount,
    required int friendCount,
    required int serverCount,
  }) = NetworkEvent_LinkComplete;
  const factory NetworkEvent.linkFailed({
    required String linkId,
    required String error,
  }) = NetworkEvent_LinkFailed;
  const factory NetworkEvent.linkPushComplete({required BigInt bytes}) =
      NetworkEvent_LinkPushComplete;
  const factory NetworkEvent.shardStored({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardStored;
  const factory NetworkEvent.shardStoreAckReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required bool success,
    required String error,
  }) = NetworkEvent_ShardStoreAckReceived;
  const factory NetworkEvent.shardStoreFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String targetPeer,
    required String error,
  }) = NetworkEvent_ShardStoreFailed;
  const factory NetworkEvent.shardDeleted({
    required String serverId,
    required String contentId,
  }) = NetworkEvent_ShardDeleted;
  const factory NetworkEvent.shardReceived({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String fromPeer,
  }) = NetworkEvent_ShardReceived;
  const factory NetworkEvent.shardRequestFailed({
    required String serverId,
    required String contentId,
    required int shardIndex,
    required String error,
  }) = NetworkEvent_ShardRequestFailed;
  const factory NetworkEvent.vaultUploadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultUploadProgress;
  const factory NetworkEvent.vaultUploadComplete({
    required String serverId,
    required String contentId,
    required String channelId,
  }) = NetworkEvent_VaultUploadComplete;
  const factory NetworkEvent.vaultUploadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultUploadFailed;
  const factory NetworkEvent.vaultDownloadProgress({
    required String serverId,
    required String contentId,
    required String phase,
    required double progress,
  }) = NetworkEvent_VaultDownloadProgress;
  const factory NetworkEvent.vaultDownloadComplete({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_VaultDownloadComplete;
  const factory NetworkEvent.vaultDownloadFailed({
    required String serverId,
    required String contentId,
    required String error,
  }) = NetworkEvent_VaultDownloadFailed;
  const factory NetworkEvent.rebalanceStarted({
    required String serverId,
    required int shardsToMove,
  }) = NetworkEvent_RebalanceStarted;
  const factory NetworkEvent.rebalanceProgress({
    required String serverId,
    required int moved,
    required int total,
  }) = NetworkEvent_RebalanceProgress;
  const factory NetworkEvent.rebalanceCompleted({required String serverId}) =
      NetworkEvent_RebalanceCompleted;
  const factory NetworkEvent.vaultUploadReplicationFallback({
    required String serverId,
    required String contentId,
    required BigInt online,
    required BigInt needed,
  }) = NetworkEvent_VaultUploadReplicationFallback;
  const factory NetworkEvent.keyExchangeStarted({required String peerId}) =
      NetworkEvent_KeyExchangeStarted;
  const factory NetworkEvent.keyExchangeProgress({
    required String peerId,
    required String stage,
  }) = NetworkEvent_KeyExchangeProgress;

  /// Forward incoming WebRTC signaling message to Dart.
  const factory NetworkEvent.webRtcSignal({
    required String peerId,
    required String signalType,
    required String payload,
    required String connId,
  }) = NetworkEvent_WebRtcSignal;

  /// Tell Dart to send a file over WebRTC data channel.
  const factory NetworkEvent.webRtcSendFile({
    required String peerId,
    required String transferId,
    required String filePath,
    required BigInt totalSize,
    required String kind,
    required int shardIndex,
    required int chunkIndex,
  }) = NetworkEvent_WebRtcSendFile;

  /// Forward incoming voice call signaling message to Dart.
  const factory NetworkEvent.callSignal({
    required String peerId,
    required String signalType,
    required String payload,
  }) = NetworkEvent_CallSignal;

  /// `is_self` = our own join/leave, decided by the Rust handler that knows. Dart
  /// branches on this flag, never on comparing peer_id to a local id: peer_id is the
  /// ROUTABLE DEVICE id, and id-form guessing caused the self-ghost dial bug.
  const factory NetworkEvent.voiceChannelJoined({
    required String serverId,
    required String channelId,
    required String peerId,
    required bool isSelf,
  }) = NetworkEvent_VoiceChannelJoined;
  const factory NetworkEvent.voiceChannelLeft({
    required String serverId,
    required String channelId,
    required String peerId,
    required bool isSelf,
  }) = NetworkEvent_VoiceChannelLeft;
  const factory NetworkEvent.voiceChannelSignal({
    required String serverId,
    required String channelId,
    required String peerId,
    required String signalType,
    required String payload,
  }) = NetworkEvent_VoiceChannelSignal;

  /// Client-bound `fwd_*` signal from a media forwarder. Dart must gate on "from the
  /// discovered forwarder AND origin watched+assigned" before acting.
  const factory NetworkEvent.forwarderSignal({
    required String fromPeer,
    required String signalType,
    required String payload,
  }) = NetworkEvent_ForwarderSignal;

  /// The relay's advertised media forwarder (static config; refreshed on
  /// every reconnect). Cached by Dart's forwarderInfoProvider.
  const factory NetworkEvent.mediaForwarderInfo({
    required String peerId,
    required bool online,
  }) = NetworkEvent_MediaForwarderInfo;
  const factory NetworkEvent.gossipConnect({required String peerId}) =
      NetworkEvent_GossipConnect;
  const factory NetworkEvent.gossipDisconnect({required String peerId}) =
      NetworkEvent_GossipDisconnect;
  const factory NetworkEvent.gossipRelayFile({
    required String broadcastId,
    required int ttl,
    required String originPeerId,
    required String filePath,
    required BigInt totalSize,
    required String kind,
    required int shardIndex,
    required String excludePeerId,
    required String serverId,
    required String channelId,
  }) = NetworkEvent_GossipRelayFile;

  /// Send a small gossip frame (type byte 0x04) to each target's open data channel,
  /// so CRDT ops flood peer-to-peer instead of paying the relay's O(N) egress.
  const factory NetworkEvent.gossipRelayOp({
    required List<String> targets,
    required Uint8List payload,
  }) = NetworkEvent_GossipRelayOp;
  const factory NetworkEvent.voiceChannelModeChanged({
    required String serverId,
    required String channelId,
    required String mode,
    required List<String> gossipNeighbors,
  }) = NetworkEvent_VoiceChannelModeChanged;

  /// MLS epoch changed, so the SFrame key for voice E2EE moved. `channel_id` set =
  /// a restricted channel's subgroup key, routed to that channel's cryptor only;
  /// `None` = the server-wide group key.
  const factory NetworkEvent.mlsEpochChanged({
    required String serverId,
    required BigInt epoch,
    required Uint8List sframeKey,
    String? channelId,
  }) = NetworkEvent_MlsEpochChanged;

  /// (Host) someone is in the waiting room. `avatar_hash` is a hash, never
  /// blob bytes; Dart computes the friend badge locally.
  const factory NetworkEvent.conferenceJoinRequestReceived({
    required String confId,
    required String peerId,
    required String displayName,
    required String avatarHash,
  }) = NetworkEvent_ConferenceJoinRequestReceived;

  /// (Joiner) declined / wrong code / meeting gone.
  const factory NetworkEvent.conferenceJoinDenied({
    required String confId,
    required String reason,
  }) = NetworkEvent_ConferenceJoinDenied;

  /// (Joiner) lobby banner: whose meeting we're waiting for.
  const factory NetworkEvent.conferenceLobbyInfo({
    required String confId,
    required String hostPeerId,
    required String hostName,
    required String hostAvatarHash,
  }) = NetworkEvent_ConferenceLobbyInfo;

  /// (Joiner) admitted — the conf MLS Welcome landed; join the call now.
  const factory NetworkEvent.conferenceAdmitted({required String confId}) =
      NetworkEvent_ConferenceAdmitted;

  /// RAM-only conference chat line (no persistence, no unread machinery).
  const factory NetworkEvent.conferenceChatMessage({
    required String confId,
    required String senderPeerId,
    required String text,
    required PlatformInt64 timestamp,
  }) = NetworkEvent_ConferenceChatMessage;

  /// Meeting over. Dart validates `by_peer_id` against the known host.
  const factory NetworkEvent.conferenceEnded({
    required String confId,
    required String byPeerId,
  }) = NetworkEvent_ConferenceEnded;

  /// We were removed from the meeting (host-validated in Dart).
  const factory NetworkEvent.conferenceKicked({
    required String confId,
    required String byPeerId,
  }) = NetworkEvent_ConferenceKicked;
  const factory NetworkEvent.recoveryPoolCreated({
    required String serverId,
    required String inviteLink,
  }) = NetworkEvent_RecoveryPoolCreated;
  const factory NetworkEvent.recoveryPoolJoined({required String serverId}) =
      NetworkEvent_RecoveryPoolJoined;
  const factory NetworkEvent.recoveryPoolJoinFailed({
    required String serverId,
    required String reason,
  }) = NetworkEvent_RecoveryPoolJoinFailed;
  const factory NetworkEvent.recoveryPoolMemberJoined({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_RecoveryPoolMemberJoined;
  const factory NetworkEvent.recoveryPoolMemberLeft({
    required String serverId,
    required String peerId,
  }) = NetworkEvent_RecoveryPoolMemberLeft;
  const factory NetworkEvent.recoveryPoolStatus({
    required String serverId,
    required int totalFiles,
    required int reconstructable,
    required int partial,
    required int noShards,
    required double progressPct,
  }) = NetworkEvent_RecoveryPoolStatus;
  const factory NetworkEvent.recoveryPoolShardTransferred({
    required String serverId,
    required String contentId,
    required int shardIndex,
  }) = NetworkEvent_RecoveryPoolShardTransferred;
  const factory NetworkEvent.recoveryPoolFileRecovered({
    required String serverId,
    required String contentId,
    required String diskPath,
  }) = NetworkEvent_RecoveryPoolFileRecovered;
  const factory NetworkEvent.recoveryPoolStopped({required String serverId}) =
      NetworkEvent_RecoveryPoolStopped;
  const factory NetworkEvent.shareManifestReady({
    required String rootHash,
    required String fileName,
    required BigInt totalSize,
    required int chunkCount,
  }) = NetworkEvent_ShareManifestReady;
  const factory NetworkEvent.shareProgress({
    required String rootHash,
    required int chunksHave,
    required int chunksTotal,
    required int seeders,
    required int leechers,
    required BigInt bytesPerSec,
  }) = NetworkEvent_ShareProgress;
  const factory NetworkEvent.shareCompleted({
    required String rootHash,
    required String diskPath,
  }) = NetworkEvent_ShareCompleted;
  const factory NetworkEvent.shareFailed({
    required String rootHash,
    required String error,
  }) = NetworkEvent_ShareFailed;
  const factory NetworkEvent.shareSeedingChanged({
    required String rootHash,
    required bool seeding,
    required int seeders,
    required int leechers,
    required BigInt bytesUploaded,
  }) = NetworkEvent_ShareSeedingChanged;
  const factory NetworkEvent.shareCreated({
    required String rootHash,
    required String link,
    required String fileName,
    required BigInt totalSize,
  }) = NetworkEvent_ShareCreated;
  const factory NetworkEvent.shareCreatedHidden({
    required String rootHash,
    required String keyHex,
    required String fileName,
    required BigInt totalSize,
  }) = NetworkEvent_ShareCreatedHidden;
  const factory NetworkEvent.shareList({required List<ShareEntry> entries}) =
      NetworkEvent_ShareList;
  const factory NetworkEvent.shareNeedWebRtc({
    required String peerId,
    required bool hidden,
  }) = NetworkEvent_ShareNeedWebRtc;
  const factory NetworkEvent.licenseError({required String reason}) =
      NetworkEvent_LicenseError;
  const factory NetworkEvent.twitchJoinRejected({
    required String serverId,
    required String reason,
  }) = NetworkEvent_TwitchJoinRejected;
  const factory NetworkEvent.roomBudgetUpdate({
    required int joined,
    required int limit,
  }) = NetworkEvent_RoomBudgetUpdate;
  const factory NetworkEvent.roomCapHit({required String room}) =
      NetworkEvent_RoomCapHit;
  const factory NetworkEvent.publicChannelListReceived({
    required String serverId,
    required String serverName,
    required List<PublicChannelEntryFfi> channels,
    Uint8List? serverAvatar,
    Uint8List? serverBannerThumb,
  }) = NetworkEvent_PublicChannelListReceived;
  const factory NetworkEvent.publicChannelSyncReceived({
    required String serverId,
    required String channelId,
    required List<GuestSyncMessageFfi> messages,
    required bool hasMore,
    required List<SyncSenderProfileFfi> senderProfiles,
  }) = NetworkEvent_PublicChannelSyncReceived;
  const factory NetworkEvent.publicChannelConfigChanged({
    required String serverId,
    required String channelId,
    required bool isPublic,
    required String channelName,
    String? category,
  }) = NetworkEvent_PublicChannelConfigChanged;
}

/// A piece of imported shop art and who made it.
class OwnedArt {
  final String hash;
  final String role;
  final String itemId;
  final String title;
  final String artistName;
  final String artistSlug;
  final String artistUrl;
  final String license;

  /// Unix milliseconds.
  final PlatformInt64 importedAt;

  const OwnedArt({
    required this.hash,
    required this.role,
    required this.itemId,
    required this.title,
    required this.artistName,
    required this.artistSlug,
    required this.artistUrl,
    required this.license,
    required this.importedAt,
  });

  @override
  int get hashCode =>
      hash.hashCode ^
      role.hashCode ^
      itemId.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      artistSlug.hashCode ^
      artistUrl.hashCode ^
      license.hashCode ^
      importedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnedArt &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          role == other.role &&
          itemId == other.itemId &&
          title == other.title &&
          artistName == other.artistName &&
          artistSlug == other.artistSlug &&
          artistUrl == other.artistUrl &&
          license == other.license &&
          importedAt == other.importedAt;
}

/// A frame blob that has been processed and cached locally, ready to be
/// named in `update_profile(avatar_frame: ...)`.
class ProcessedFrame {
  /// 64-hex SHA-256 of the processed bytes: the frame's identity, and what rides the
  /// profile announce.
  final String hash;
  final bool animated;

  /// The processed bytes, so the picker previews exactly what everyone else sees.
  final Uint8List bytes;

  const ProcessedFrame({
    required this.hash,
    required this.animated,
    required this.bytes,
  });

  @override
  int get hashCode => hash.hashCode ^ animated.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedFrame &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          animated == other.animated &&
          bytes == other.bytes;
}

/// An animated avatar or banner that has been processed and cached locally,
/// ready to be named in `update_profile(avatar_anim: ...)`.
class ProcessedProfileMedia {
  /// 64-hex SHA-256 of the ANIMATED bytes: the identity that rides the announce and
  /// what peers pull on the asset rail.
  final String hash;

  /// The animated WebP, so the picker previews exactly what everyone else sees.
  final Uint8List bytes;

  /// The STILL companion (frame 0, same ceiling), which the caller must pass as
  /// `avatar_bytes` / `banner_bytes`: it stays inside the pushed profile so old
  /// clients and the guest thumb still see a face.
  final Uint8List still;

  const ProcessedProfileMedia({
    required this.hash,
    required this.bytes,
    required this.still,
  });

  @override
  int get hashCode => hash.hashCode ^ bytes.hashCode ^ still.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedProfileMedia &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          bytes == other.bytes &&
          still == other.still;
}

/// FFI-facing public channel entry for guest viewer.
class PublicChannelEntryFfi {
  final String channelId;
  final String name;
  final String? category;

  const PublicChannelEntryFfi({
    required this.channelId,
    required this.name,
    this.category,
  });

  @override
  int get hashCode => channelId.hashCode ^ name.hashCode ^ category.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicChannelEntryFfi &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          name == other.name &&
          category == other.category;
}

/// Display metadata for a channel push notification (Tier 1-style: resolved
/// from the local DB, no node needed).
class PushChannelMeta {
  final String serverName;
  final String channelName;

  /// Effective LOCAL level for this channel (channel override, else the server
  /// default), so the Android background handler can drop a push whose relay-side
  /// filter was stale.
  final String notifLevel;

  const PushChannelMeta({
    required this.serverName,
    required this.channelName,
    required this.notifLevel,
  });

  @override
  int get hashCode =>
      serverName.hashCode ^ channelName.hashCode ^ notifLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushChannelMeta &&
          runtimeType == other.runtimeType &&
          serverName == other.serverName &&
          channelName == other.channelName &&
          notifLevel == other.notifLevel;
}

/// Profile data for push notifications (Tier 1: cached profile, no node needed).
class PushProfile {
  final String displayName;
  final Uint8List? avatarBytes;

  const PushProfile({required this.displayName, this.avatarBytes});

  @override
  int get hashCode => displayName.hashCode ^ avatarBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushProfile &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          avatarBytes == other.avatarBytes;
}

/// Lightweight FFI mirror of node::types::ShareEntryRef.
class ShareEntry {
  final String rootHash;
  final String fileName;
  final BigInt totalSize;
  final int chunksHave;
  final int chunksTotal;
  final String state;
  final bool seeding;
  final String? diskPath;
  final BigInt bytesUploaded;
  final String shareLink;
  final PlatformInt64 createdAt;
  final String? serverId;
  final String? contextType;

  const ShareEntry({
    required this.rootHash,
    required this.fileName,
    required this.totalSize,
    required this.chunksHave,
    required this.chunksTotal,
    required this.state,
    required this.seeding,
    this.diskPath,
    required this.bytesUploaded,
    required this.shareLink,
    required this.createdAt,
    this.serverId,
    this.contextType,
  });

  @override
  int get hashCode =>
      rootHash.hashCode ^
      fileName.hashCode ^
      totalSize.hashCode ^
      chunksHave.hashCode ^
      chunksTotal.hashCode ^
      state.hashCode ^
      seeding.hashCode ^
      diskPath.hashCode ^
      bytesUploaded.hashCode ^
      shareLink.hashCode ^
      createdAt.hashCode ^
      serverId.hashCode ^
      contextType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareEntry &&
          runtimeType == other.runtimeType &&
          rootHash == other.rootHash &&
          fileName == other.fileName &&
          totalSize == other.totalSize &&
          chunksHave == other.chunksHave &&
          chunksTotal == other.chunksTotal &&
          state == other.state &&
          seeding == other.seeding &&
          diskPath == other.diskPath &&
          bytesUploaded == other.bytesUploaded &&
          shareLink == other.shareLink &&
          createdAt == other.createdAt &&
          serverId == other.serverId &&
          contextType == other.contextType;
}

/// FFI-facing sender profile for guest sync.
class SyncSenderProfileFfi {
  final String peerId;
  final String? name;
  final Uint8List? avatar;

  const SyncSenderProfileFfi({required this.peerId, this.name, this.avatar});

  @override
  int get hashCode => peerId.hashCode ^ name.hashCode ^ avatar.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncSenderProfileFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          name == other.name &&
          avatar == other.avatar;
}

/// FFI-facing video thumbnail back-reference.
/// Present on a `FileHeaderReceived` when the file is a thumbnail for a video in
/// the vault; Dart renders the play overlay and calls `vault_download_file(cid)`.
class VideoThumbRef {
  /// Vault content_id (sha256 of ciphertext) of the underlying video.
  final String cid;

  /// Original video file extension (mp4, webm, mkv, ...).
  final String ext;

  /// Original video file name (used as the default for the Save As dialog).
  final String name;

  /// Video size in bytes.
  final BigInt size;

  /// Video duration in milliseconds.
  final int durMs;

  const VideoThumbRef({
    required this.cid,
    required this.ext,
    required this.name,
    required this.size,
    required this.durMs,
  });

  @override
  int get hashCode =>
      cid.hashCode ^
      ext.hashCode ^
      name.hashCode ^
      size.hashCode ^
      durMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoThumbRef &&
          runtimeType == other.runtimeType &&
          cid == other.cid &&
          ext == other.ext &&
          name == other.name &&
          size == other.size &&
          durMs == other.durMs;
}
