// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `changed`, `ctx`, `delegation_from`, `destroy_order`, `destroy_permission`, `erase_stored_phrase`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Ctx`

/// What our own roster says about every device, this one first.
Future<RosterStatus> rosterStatus() =>
    RustLib.instance.api.crateApiRosterRosterStatus();

/// Type the phrase to make it the root of the identity: a recovery keeping this
/// device and `keep`. Every other device stops counting at once. Also the one-time
/// confirmation of an identity from before 0.12, which erases the stored phrase.
Future<void> recoverWithPhrase({
  required String phrase,
  required List<String> keep,
}) => RustLib.instance.api.crateApiRosterRecoverWithPhrase(
  phrase: phrase,
  keep: keep,
);

/// Type the phrase on a device waiting to join: it joins at once, and nothing else
/// changes.
Future<void> joinWithPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiRosterJoinWithPhrase(phrase: phrase);

/// Whether `phrase` is this identity's recovery phrase. Checks only; signs nothing.
Future<bool> checkRecoveryPhrase({required String phrase}) =>
    RustLib.instance.api.crateApiRosterCheckRecoveryPhrase(phrase: phrase);

/// The phrase an identity from before 0.12 kept in its database, shown one last time
/// at the upgrade and erased once confirmed. `None` once it is gone.
Future<String?> storedPhraseForUpgrade() =>
    RustLib.instance.api.crateApiRosterStoredPhraseForUpgrade();

/// This device vouches for a device waiting to join.
Future<void> approveDevice({required String devicePeerId}) => RustLib
    .instance
    .api
    .crateApiRosterApproveDevice(devicePeerId: devicePeerId);

/// This device refuses a device waiting to join.
Future<void> refuseDevice({required String devicePeerId}) =>
    RustLib.instance.api.crateApiRosterRefuseDevice(devicePeerId: devicePeerId);

/// One device the roster knows about, for the Devices page.
class RosterDevice {
  final String devicePeerId;

  /// `member`, `pending` or `removed`.
  final String state;
  final bool thisDevice;

  /// When this device first saw a pending join (its seven days run from here).
  final PlatformInt64? firstSeenMs;

  const RosterDevice({
    required this.devicePeerId,
    required this.state,
    required this.thisDevice,
    this.firstSeenMs,
  });

  @override
  int get hashCode =>
      devicePeerId.hashCode ^
      state.hashCode ^
      thisDevice.hashCode ^
      firstSeenMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RosterDevice &&
          runtimeType == other.runtimeType &&
          devicePeerId == other.devicePeerId &&
          state == other.state &&
          thisDevice == other.thisDevice &&
          firstSeenMs == other.firstSeenMs;
}

/// What our own roster says, for the Devices page and the lock screens.
class RosterStatus {
  /// This device belongs to the identity.
  final bool member;

  /// The recovery phrase is the root (a recovery exists).
  final bool protected;

  /// This device asked to join and waits: when it becomes a member without anyone
  /// answering, on this device's clock.
  final PlatformInt64? joinsAtMs;

  /// This device was removed: by whom, and when it erases itself.
  final String? removedBy;
  final PlatformInt64? wipeAtMs;
  final List<RosterDevice> devices;

  const RosterStatus({
    required this.member,
    required this.protected,
    this.joinsAtMs,
    this.removedBy,
    this.wipeAtMs,
    required this.devices,
  });

  @override
  int get hashCode =>
      member.hashCode ^
      protected.hashCode ^
      joinsAtMs.hashCode ^
      removedBy.hashCode ^
      wipeAtMs.hashCode ^
      devices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RosterStatus &&
          runtimeType == other.runtimeType &&
          member == other.member &&
          protected == other.protected &&
          joinsAtMs == other.joinsAtMs &&
          removedBy == other.removedBy &&
          wipeAtMs == other.wipeAtMs &&
          devices == other.devices;
}
