// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode`, `decoder`, `encode`, `encoder`, `gain_target`, `new`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ScreenAudioDecoder`, `ScreenAudioEncoder`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `drop`

/// Set the screen-audio playback gain target (0.0..=1.0). The decoder ramps toward
/// it over the next `decode_screen_audio` calls, so changes are click-free.
Future<void> setScreenAudioGain({required double gain}) =>
    RustLib.instance.api.crateApiScreenAudioSetScreenAudioGain(gain: gain);

/// (Re)initialize the screen-audio decoder, clearing inter-packet state left by a
/// previous share session.
Future<void> resetScreenAudioDecoder() =>
    RustLib.instance.api.crateApiScreenAudioResetScreenAudioDecoder();

/// Decode one bare Opus packet (seq already stripped by Dart) into interleaved
/// s16le stereo PCM at 48 kHz. Empty input returns an empty `Vec`; the decoder is
/// created lazily if [`reset_screen_audio_decoder`] was not called first.
Future<Uint8List> decodeScreenAudio({required List<int> opus}) =>
    RustLib.instance.api.crateApiScreenAudioDecodeScreenAudio(opus: opus);

/// (Re)initialize the screen-audio encoder: clears prediction state, the PCM
/// residual and the wire seq, which the desktop exe also starts at 0.
Future<void> resetScreenAudioEncoder() =>
    RustLib.instance.api.crateApiScreenAudioResetScreenAudioEncoder();

/// Drop the encoder when share-audio capture stops; the next start recreates it.
Future<void> stopScreenAudioEncoder() =>
    RustLib.instance.api.crateApiScreenAudioStopScreenAudioEncoder();

/// Feed interleaved 48 kHz stereo s16le PCM of any length (capture callbacks are not
/// frame-aligned) and get back COMPLETE `[seq:4 LE][opus]` wire packets. Leftover PCM
/// stays buffered; the encoder is created lazily.
Future<List<Uint8List>> encodeScreenAudio({required List<int> pcm}) =>
    RustLib.instance.api.crateApiScreenAudioEncodeScreenAudio(pcm: pcm);
