// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `announce_support_creds`, `apply_hidden`, `badge_on`, `by_role`, `check_art_bytes`, `clamp`, `display_file_for`, `drop_other_twitch_owner_creds`, `fetch_bounded`, `fetch_pack`, `file_for_kind`, `forget_own_cred`, `forget_twitch_owner_creds`, `hidden_on`, `http`, `keep_own_cred_row`, `keep_own_credential`, `kind_of_role`, `kind_roles`, `lenient_vec`, `lenient`, `lookup_refusal`, `lookup_remote`, `lookup_status_is_dead`, `mint_twitch_credential`, `my_master_peer_id`, `own_credential_union`, `own_twitch_owner_entry`, `parse_catalog`, `post_json_bounded`, `price_label`, `primary_kind_of`, `published_creds_json`, `read_bounded`, `redeem_remote`, `removed_items`, `republish_support_creds`, `republish_to_row`, `sanitize_file`, `sanitize_listing`, `save_removed_items`, `shop_client`, `shop_refusal`, `support_badge_preference`, `twitch_post`, `twitch_refusal`, `twitch_request_body`, `union_json`, `valid_redeem_code`, `valid_slug`, `verify_twitch_owner_with`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawArtist`, `RawCatalog`, `RawFile`, `RawListing`, `RawLookupListing`, `RawLookup`, `RawRedeem`, `RawTwitchKey`, `TwitchVerifier`, `UnionEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`, `default`, `default`, `default`, `default`, `default`

/// The shop origin.
///
/// In DEBUG builds only, `HOLLOW_SHOP_ORIGIN` in the environment overrides it,
/// which is how the local dev shop at `http://localhost:3000` is reached.
/// Release builds ignore the variable: a store you can point elsewhere with an
/// environment variable is a store somebody else can point elsewhere.
Future<String> shopOrigin() => RustLib.instance.api.crateApiShopShopOrigin();

/// Fetch the shop's public catalog.
///
/// Runs on [`get_http_runtime`], never the node runtime: reqwest resolves DNS
/// on its runtime's blocking pool and the node's is routinely saturated by
/// SQLCipher bursts, so a shared runtime turns a browse into a stall.
Future<ShopCatalog> fetchShopCatalog() =>
    RustLib.instance.api.crateApiShopFetchShopCatalog();

/// Fetch one piece of preview art by its hash.
///
/// The bytes are RETURNED and stored nowhere. Preview art is not owned art: it
/// arrives with no pack, no licence and no provenance, and the rail is for
/// things this install actually has. The caller renders it and lets it go.
Future<Uint8List> fetchShopArt({required String hash}) =>
    RustLib.instance.api.crateApiShopFetchShopArt(hash: hash);

/// Keep a redeem code from a `hollow://redeem/<code>` link.
///
/// Returns whether it was newly kept; a code kept twice is a no-op rather than
/// an error, because the buyer clicking their thank-you link again is not a
/// mistake they should see a toast about.
Future<bool> keepRedeemCode({required String code}) =>
    RustLib.instance.api.crateApiShopKeepRedeemCode(code: code);

/// Every kept redeem code, newest first.
Future<List<KeptRedeemCode>> listRedeemCodes() =>
    RustLib.instance.api.crateApiShopListRedeemCodes();

/// Forget one kept redeem code.
Future<void> forgetRedeemCode({required String code}) =>
    RustLib.instance.api.crateApiShopForgetRedeemCode(code: code);

/// Look a code up: what it buys, and whether this identity already supports
/// it. Nothing burns.
Future<RedeemLookup> redeemLookup({required String code}) =>
    RustLib.instance.api.crateApiShopRedeemLookup(code: code);

/// Redeem a code: mint the credential, keep it, announce it, then fetch and
/// import the pack.
///
/// Order matters. The chain the shop published is verified against the
/// pinned root BEFORE the code is spent, so a shop with a broken key never
/// burns a purchase. The credential is stored and announced BEFORE the pack
/// is fetched, so a network hiccup after the burn costs a download the buyer
/// also has in their email, never the mark.
Future<RedeemOutcome> redeemCode({required String code}) =>
    RustLib.instance.api.crateApiShopRedeemCode(code: code);

/// Every credential this identity holds, as far as this device can tell:
/// the ones it minted first, with their names, then the ones that reached it
/// on our own profile row from a sibling, which carry no names and no redeem
/// date. Removed items are left out.
///
/// The announce cap is NOT applied here. The cap is about what rides a light
/// profile announce; a holder of four marks is holding four.
Future<List<OwnSupportCred>> listOwnSupportCreds() =>
    RustLib.instance.api.crateApiShopListOwnSupportCreds();

/// Whether OUR marks also sit next to our name (design 5.6). Off by default.
Future<bool> supportBadgeEnabled() =>
    RustLib.instance.api.crateApiShopSupportBadgeEnabled();

/// Show, or stop showing, our marks next to our name. One profile save.
///
/// The setting is the only copy of the answer: [`published_creds_json`]
/// stamps it onto every entry it publishes, table and profile row alike, so
/// the switch works from whichever device the holder is sitting at rather
/// than only from the one that redeemed.
Future<void> setSupportBadge({required bool show_}) =>
    RustLib.instance.api.crateApiShopSetSupportBadge(show_: show_);

/// Whether this device is holding our marks back (design 5.6, off by
/// default). Local to this device: a second install of the same identity
/// answers for itself.
Future<bool> supportMarksHidden() =>
    RustLib.instance.api.crateApiShopSupportMarksHidden();

/// Hide, or stop hiding, our marks. One profile save.
///
/// Hiding announces the explicit clear, so every peer drops what they stored
/// and nobody can tell a holder who is hiding from somebody who never bought
/// anything. The credentials themselves stay in the table, so switching it
/// back publishes exactly what was there.
Future<void> setSupportMarksHidden({required bool hidden}) =>
    RustLib.instance.api.crateApiShopSetSupportMarksHidden(hidden: hidden);

/// Forget one of our credentials, for good.
///
/// There is no way back: the code that minted it is spent (12.6), and the
/// shop will not sign a second one for the same purchase. The files stay in
/// the library; only the mark goes. Forgetting an item this identity never
/// held is not an error, so a double press costs nothing.
///
/// The removal is remembered locally as well as applied, because the same
/// credential can arrive again on our own profile row from a sibling. What
/// that does NOT cover is the sibling itself: a mark removed on a device
/// that did not mint it comes back if the MINTING device republishes, since
/// `support_creds_own` does not replicate. Removing it where it was minted
/// is final. See [`own_credential_union`].
Future<void> removeOwnSupportCred({required String item}) =>
    RustLib.instance.api.crateApiShopRemoveOwnSupportCred(item: item);

/// One redeem code this install is holding on to.
class KeptRedeemCode {
  final String code;

  /// Unix milliseconds.
  final PlatformInt64 receivedAt;

  const KeptRedeemCode({required this.code, required this.receivedAt});

  @override
  int get hashCode => code.hashCode ^ receivedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeptRedeemCode &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          receivedAt == other.receivedAt;
}

/// One of OUR credentials, for Settings.
class OwnSupportCred {
  final String item;
  final List<String> parts;
  final String slug;
  final String title;
  final String artistName;

  /// Unix milliseconds.
  final PlatformInt64 redeemedAt;
  final bool badge;

  const OwnSupportCred({
    required this.item,
    required this.parts,
    required this.slug,
    required this.title,
    required this.artistName,
    required this.redeemedAt,
    required this.badge,
  });

  @override
  int get hashCode =>
      item.hashCode ^
      parts.hashCode ^
      slug.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      redeemedAt.hashCode ^
      badge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OwnSupportCred &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          parts == other.parts &&
          slug == other.slug &&
          title == other.title &&
          artistName == other.artistName &&
          redeemedAt == other.redeemedAt &&
          badge == other.badge;
}

/// What `redeem_lookup` learned about a code.
class RedeemLookup {
  /// `ok`, or why not: `refused` (refunded), `burned` (already redeemed),
  /// `unknown` (not a key this shop sold), `nokey` (listed before
  /// credentials existed; the keeper can fix it).
  final String status;

  /// The shop's sentence when `status` is not `ok`.
  final String message;
  final String slug;
  final String title;
  final String artistName;
  final String artistSlug;
  final String itemUrl;
  final List<String> kinds;

  /// The credential's item hash, 64-hex, once `ok`.
  final String item;

  /// The file hashes the credential will vouch for.
  final List<String> parts;

  /// This identity already holds a credential for this item (13.23): a
  /// second redemption changes nothing, keep the code and gift it.
  final bool alreadySupported;

  const RedeemLookup({
    required this.status,
    required this.message,
    required this.slug,
    required this.title,
    required this.artistName,
    required this.artistSlug,
    required this.itemUrl,
    required this.kinds,
    required this.item,
    required this.parts,
    required this.alreadySupported,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      message.hashCode ^
      slug.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      artistSlug.hashCode ^
      itemUrl.hashCode ^
      kinds.hashCode ^
      item.hashCode ^
      parts.hashCode ^
      alreadySupported.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedeemLookup &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          message == other.message &&
          slug == other.slug &&
          title == other.title &&
          artistName == other.artistName &&
          artistSlug == other.artistSlug &&
          itemUrl == other.itemUrl &&
          kinds == other.kinds &&
          item == other.item &&
          parts == other.parts &&
          alreadySupported == other.alreadySupported;
}

/// What redeeming landed.
class RedeemOutcome {
  /// The credential's item hash. The mark is saved and announced.
  final String item;
  final String title;
  final String artistName;

  /// The pack, imported, when it arrived; `None` with `pack_error` set
  /// when it did not. The credential is kept either way.
  final HollowpackImport? imported;
  final String packError;

  /// Something to say that is not a failure: the pack's files and the
  /// credential's parts did not agree, say.
  final String warning;

  const RedeemOutcome({
    required this.item,
    required this.title,
    required this.artistName,
    this.imported,
    required this.packError,
    required this.warning,
  });

  @override
  int get hashCode =>
      item.hashCode ^
      title.hashCode ^
      artistName.hashCode ^
      imported.hashCode ^
      packError.hashCode ^
      warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedeemOutcome &&
          runtimeType == other.runtimeType &&
          item == other.item &&
          title == other.title &&
          artistName == other.artistName &&
          imported == other.imported &&
          packError == other.packError &&
          warning == other.warning;
}

/// Who made a listing.
class ShopArtist {
  final String slug;
  final String displayName;
  final String bio;

  /// Hash of the artist page's header art, `""` when there is none.
  final String headerHash;

  /// `{origin}/@{slug}`, or `""` when the slug is not a shape we will build
  /// a URL out of.
  final String url;

  const ShopArtist({
    required this.slug,
    required this.displayName,
    required this.bio,
    required this.headerHash,
    required this.url,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      displayName.hashCode ^
      bio.hashCode ^
      headerHash.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopArtist &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          displayName == other.displayName &&
          bio == other.bio &&
          headerHash == other.headerHash &&
          url == other.url;
}

/// The public catalog as the app consumes it.
class ShopCatalog {
  /// The origin it came from, so a card can build its own links without
  /// asking again.
  final String origin;
  final String generatedAt;
  final List<ShopListing> listings;

  const ShopCatalog({
    required this.origin,
    required this.generatedAt,
    required this.listings,
  });

  @override
  int get hashCode =>
      origin.hashCode ^ generatedAt.hashCode ^ listings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopCatalog &&
          runtimeType == other.runtimeType &&
          origin == other.origin &&
          generatedAt == other.generatedAt &&
          listings == other.listings;
}

/// One file of a listing, named by the SHA-256 of its processed bytes: the same
/// number `import_hollowpack` recomputes and the same number the profile field
/// carries once the art is worn.
class ShopFile {
  /// A `.hollowpack` role: `frame`, `avatar`, `avatar_anim`, `avatar_still`,
  /// `banner`, `banner_anim` or `banner_still`. Anything else was dropped.
  final String role;
  final String sha256;
  final BigInt bytes;

  /// 0 when the shop did not record a size.
  final int w;
  final int h;
  final bool animated;

  const ShopFile({
    required this.role,
    required this.sha256,
    required this.bytes,
    required this.w,
    required this.h,
    required this.animated,
  });

  @override
  int get hashCode =>
      role.hashCode ^
      sha256.hashCode ^
      bytes.hashCode ^
      w.hashCode ^
      h.hashCode ^
      animated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopFile &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          sha256 == other.sha256 &&
          bytes == other.bytes &&
          w == other.w &&
          h == other.h &&
          animated == other.animated;
}

/// One thing for sale, already reduced to what a card needs to draw.
class ShopListing {
  final String slug;
  final String title;
  final String description;

  /// The kinds a profile can WEAR from this listing, in the shop's fixed
  /// order (frame, avatar, banner) and never anything else.
  final List<String> kinds;
  final int priceCents;

  /// Always two decimals: `$5` beside `$4.99` reads as a rounding.
  final String priceLabel;

  /// The list price while the piece is on sale, 0 otherwise. `price_cents`
  /// is always what a buyer pays; this is the number the card strikes
  /// through beside it.
  final int wasCents;

  /// [`Self::was_cents`] as the shop writes it, `""` when there is no sale.
  final String wasLabel;
  final String license;
  final String createdAt;
  final ShopArtist artist;
  final List<ShopFile> files;

  /// The one picture that IS this item, and its address on the shop.
  final String displayHash;

  /// The still sibling of [`Self::display_hash`], for a viewer who asked for
  /// stillness. `""` when the display file is already still (or when no
  /// still was shipped: freezing an animation is not something we do).
  final String stillHash;

  /// The kind the card draws, `""` when the listing names none.
  final String primaryKind;

  /// Two kinds or more.
  final bool bundle;

  /// The display file is a wide strip (aspect 2:1 or wider) rather than a
  /// square.
  final bool wide;

  /// The support credential's item hash for this listing (64-hex), or `""`
  /// when the listing was put up before credentials existed. What
  /// `list_own_support_creds` items compare against: "you support this".
  final String credentialItem;

  /// `{origin}/item/{slug}`: the listing's own address. A hash is the ART's
  /// address, and a bundle carries the same frame hash as the single frame
  /// on purpose, so a link by hash opened whichever listing the shop found
  /// first (the bug Vitalik hit on 2026-09-02). The shop still redirects an
  /// old hash link, single before set.
  final String itemUrl;

  const ShopListing({
    required this.slug,
    required this.title,
    required this.description,
    required this.kinds,
    required this.priceCents,
    required this.priceLabel,
    required this.wasCents,
    required this.wasLabel,
    required this.license,
    required this.createdAt,
    required this.artist,
    required this.files,
    required this.displayHash,
    required this.stillHash,
    required this.primaryKind,
    required this.bundle,
    required this.wide,
    required this.credentialItem,
    required this.itemUrl,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      title.hashCode ^
      description.hashCode ^
      kinds.hashCode ^
      priceCents.hashCode ^
      priceLabel.hashCode ^
      wasCents.hashCode ^
      wasLabel.hashCode ^
      license.hashCode ^
      createdAt.hashCode ^
      artist.hashCode ^
      files.hashCode ^
      displayHash.hashCode ^
      stillHash.hashCode ^
      primaryKind.hashCode ^
      bundle.hashCode ^
      wide.hashCode ^
      credentialItem.hashCode ^
      itemUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopListing &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          title == other.title &&
          description == other.description &&
          kinds == other.kinds &&
          priceCents == other.priceCents &&
          priceLabel == other.priceLabel &&
          wasCents == other.wasCents &&
          wasLabel == other.wasLabel &&
          license == other.license &&
          createdAt == other.createdAt &&
          artist == other.artist &&
          files == other.files &&
          displayHash == other.displayHash &&
          stillHash == other.stillHash &&
          primaryKind == other.primaryKind &&
          bundle == other.bundle &&
          wide == other.wide &&
          credentialItem == other.credentialItem &&
          itemUrl == other.itemUrl;
}
