// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `by_role`, `check_art_bytes`, `clamp`, `display_file_for`, `fetch_bounded`, `file_for_kind`, `kind_of_role`, `kind_roles`, `lenient_vec`, `lenient`, `parse_catalog`, `price_label`, `primary_kind_of`, `sanitize_file`, `sanitize_listing`, `shop_client`, `valid_redeem_code`, `valid_slug`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawArtist`, `RawCatalog`, `RawFile`, `RawListing`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`, `default`, `default`, `default`

/// The shop origin.
///
/// In DEBUG builds only, `HOLLOW_SHOP_ORIGIN` in the environment overrides it,
/// which is how the local dev shop at `http://localhost:3000` is reached.
/// Release builds ignore the variable: a store you can point elsewhere with an
/// environment variable is a store somebody else can point elsewhere.
Future<String> shopOrigin() => RustLib.instance.api.crateApiShopShopOrigin();

/// Fetch the shop's public catalog.
///
/// Runs on [`get_http_runtime`], never the node runtime: reqwest resolves DNS
/// on its runtime's blocking pool and the node's is routinely saturated by
/// SQLCipher bursts, so a shared runtime turns a browse into a stall.
Future<ShopCatalog> fetchShopCatalog() =>
    RustLib.instance.api.crateApiShopFetchShopCatalog();

/// Fetch one piece of preview art by its hash.
///
/// The bytes are RETURNED and stored nowhere. Preview art is not owned art: it
/// arrives with no pack, no licence and no provenance, and the rail is for
/// things this install actually has. The caller renders it and lets it go.
Future<Uint8List> fetchShopArt({required String hash}) =>
    RustLib.instance.api.crateApiShopFetchShopArt(hash: hash);

/// Keep a redeem code from a `hollow://redeem/<code>` link.
///
/// Returns whether it was newly kept; a code kept twice is a no-op rather than
/// an error, because the buyer clicking their thank-you link again is not a
/// mistake they should see a toast about.
Future<bool> keepRedeemCode({required String code}) =>
    RustLib.instance.api.crateApiShopKeepRedeemCode(code: code);

/// Every kept redeem code, newest first.
Future<List<KeptRedeemCode>> listRedeemCodes() =>
    RustLib.instance.api.crateApiShopListRedeemCodes();

/// Forget one kept redeem code.
Future<void> forgetRedeemCode({required String code}) =>
    RustLib.instance.api.crateApiShopForgetRedeemCode(code: code);

/// One redeem code this install is holding on to.
class KeptRedeemCode {
  final String code;

  /// Unix milliseconds.
  final PlatformInt64 receivedAt;

  const KeptRedeemCode({required this.code, required this.receivedAt});

  @override
  int get hashCode => code.hashCode ^ receivedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeptRedeemCode &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          receivedAt == other.receivedAt;
}

/// Who made a listing.
class ShopArtist {
  final String slug;
  final String displayName;
  final String bio;

  /// Hash of the artist page's header art, `""` when there is none.
  final String headerHash;

  /// `{origin}/@{slug}`, or `""` when the slug is not a shape we will build
  /// a URL out of.
  final String url;

  const ShopArtist({
    required this.slug,
    required this.displayName,
    required this.bio,
    required this.headerHash,
    required this.url,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      displayName.hashCode ^
      bio.hashCode ^
      headerHash.hashCode ^
      url.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopArtist &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          displayName == other.displayName &&
          bio == other.bio &&
          headerHash == other.headerHash &&
          url == other.url;
}

/// The public catalog as the app consumes it.
class ShopCatalog {
  /// The origin it came from, so a card can build its own links without
  /// asking again.
  final String origin;
  final String generatedAt;
  final List<ShopListing> listings;

  const ShopCatalog({
    required this.origin,
    required this.generatedAt,
    required this.listings,
  });

  @override
  int get hashCode =>
      origin.hashCode ^ generatedAt.hashCode ^ listings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopCatalog &&
          runtimeType == other.runtimeType &&
          origin == other.origin &&
          generatedAt == other.generatedAt &&
          listings == other.listings;
}

/// One file of a listing, named by the SHA-256 of its processed bytes: the same
/// number `import_hollowpack` recomputes and the same number the profile field
/// carries once the art is worn.
class ShopFile {
  /// A `.hollowpack` role: `frame`, `avatar`, `avatar_anim`, `avatar_still`,
  /// `banner`, `banner_anim` or `banner_still`. Anything else was dropped.
  final String role;
  final String sha256;
  final BigInt bytes;

  /// 0 when the shop did not record a size.
  final int w;
  final int h;
  final bool animated;

  const ShopFile({
    required this.role,
    required this.sha256,
    required this.bytes,
    required this.w,
    required this.h,
    required this.animated,
  });

  @override
  int get hashCode =>
      role.hashCode ^
      sha256.hashCode ^
      bytes.hashCode ^
      w.hashCode ^
      h.hashCode ^
      animated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopFile &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          sha256 == other.sha256 &&
          bytes == other.bytes &&
          w == other.w &&
          h == other.h &&
          animated == other.animated;
}

/// One thing for sale, already reduced to what a card needs to draw.
class ShopListing {
  final String slug;
  final String title;
  final String description;

  /// The kinds a profile can WEAR from this listing, in the shop's fixed
  /// order (frame, avatar, banner) and never anything else.
  final List<String> kinds;
  final int priceCents;

  /// Always two decimals: `$5` beside `$4.99` reads as a rounding.
  final String priceLabel;
  final String license;
  final String createdAt;
  final ShopArtist artist;
  final List<ShopFile> files;

  /// The one picture that IS this item, and its address on the shop.
  final String displayHash;

  /// The still sibling of [`Self::display_hash`], for a viewer who asked for
  /// stillness. `""` when the display file is already still (or when no
  /// still was shipped: freezing an animation is not something we do).
  final String stillHash;

  /// The kind the card draws, `""` when the listing names none.
  final String primaryKind;

  /// Two kinds or more.
  final bool bundle;

  /// The display file is a wide strip (aspect 2:1 or wider) rather than a
  /// square.
  final bool wide;

  /// `{origin}/item/{display_hash}`.
  final String itemUrl;

  const ShopListing({
    required this.slug,
    required this.title,
    required this.description,
    required this.kinds,
    required this.priceCents,
    required this.priceLabel,
    required this.license,
    required this.createdAt,
    required this.artist,
    required this.files,
    required this.displayHash,
    required this.stillHash,
    required this.primaryKind,
    required this.bundle,
    required this.wide,
    required this.itemUrl,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      title.hashCode ^
      description.hashCode ^
      kinds.hashCode ^
      priceCents.hashCode ^
      priceLabel.hashCode ^
      license.hashCode ^
      createdAt.hashCode ^
      artist.hashCode ^
      files.hashCode ^
      displayHash.hashCode ^
      stillHash.hashCode ^
      primaryKind.hashCode ^
      bundle.hashCode ^
      wide.hashCode ^
      itemUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShopListing &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          title == other.title &&
          description == other.description &&
          kinds == other.kinds &&
          priceCents == other.priceCents &&
          priceLabel == other.priceLabel &&
          license == other.license &&
          createdAt == other.createdAt &&
          artist == other.artist &&
          files == other.files &&
          displayHash == other.displayHash &&
          stillHash == other.stillHash &&
          primaryKind == other.primaryKind &&
          bundle == other.bundle &&
          wide == other.wide &&
          itemUrl == other.itemUrl;
}
