// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'gifs.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_label`, `pack_signature_is_valid`, `pack_signing_payload`, `read_pack_manifest`, `send_command`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PackItem`, `PackManifest`

/// Wire token for a sticker, as inserted into message text.
String stickerToken({required String hash, required int w, required int h}) =>
    RustLib.instance.api.crateApiStickersStickerToken(hash: hash, w: w, h: h);

/// The authoring caps Dart should enforce in its own UI copy, rather than
/// mirroring the numbers (same rule as `default_role_permissions`):
/// `[per server, per pack, packs, vault total, label chars]`.
Uint32List stickerLimits() =>
    RustLib.instance.api.crateApiStickersStickerLimits();

/// Process a user-picked image (PNG/JPG/WebP/GIF, still or animated) into a
/// sticker blob and cache it locally. Re-encoding here IS the sanitization
/// step — the same argument emotes and GIFs make. Caller then registers it
/// via [add_personal_sticker] or [add_server_sticker].
Future<ProcessedSticker> processAndStoreSticker({
  required List<int> rawBytes,
}) => RustLib.instance.api.crateApiStickersProcessAndStoreSticker(
  rawBytes: rawBytes,
);

Future<void> addPersonalSticker({
  required String pack,
  required String hash,
  required String name,
  required bool animated,
  required int w,
  required int h,
  required String source,
}) => RustLib.instance.api.crateApiStickersAddPersonalSticker(
  pack: pack,
  hash: hash,
  name: name,
  animated: animated,
  w: w,
  h: h,
  source: source,
);

Future<void> removePersonalSticker({
  required String pack,
  required String hash,
}) => RustLib.instance.api.crateApiStickersRemovePersonalSticker(
  pack: pack,
  hash: hash,
);

/// Delete a whole pack. The blobs stay cached — they are content-addressed
/// and a message you already sent still points at them; the asset LRU
/// reclaims them once nothing references them.
Future<void> removePersonalStickerPack({required String pack}) =>
    RustLib.instance.api.crateApiStickersRemovePersonalStickerPack(pack: pack);

/// Rename a pack. Renaming onto an existing pack MERGES into it (rows there
/// with the same hash win) rather than failing.
Future<void> renamePersonalStickerPack({
  required String from,
  required String to,
}) => RustLib.instance.api.crateApiStickersRenamePersonalStickerPack(
  from: from,
  to: to,
);

/// The whole vault, pack-major and oldest-first inside each pack — upload
/// order IS pack order, which is what makes a multi-part pack readable.
Future<List<PersonalSticker>> listPersonalStickers() =>
    RustLib.instance.api.crateApiStickersListPersonalStickers();

/// A server's sticker set (replicated metadata; bytes pulled separately by
/// hash over the asset rail).
Future<List<ServerSticker>> getServerStickers({required String serverId}) =>
    RustLib.instance.api.crateApiStickersGetServerStickers(serverId: serverId);

/// Add (or re-label) a sticker in a server's set — `MANAGE_EMOTES`, the same
/// permission as emotes. The blob must already be cached locally so this
/// node can serve members' pull requests.
Future<void> addServerSticker({
  required String serverId,
  required String hash,
  required String name,
  required String pack,
  required bool animated,
  required int w,
  required int h,
}) => RustLib.instance.api.crateApiStickersAddServerSticker(
  serverId: serverId,
  hash: hash,
  name: name,
  pack: pack,
  animated: animated,
  w: w,
  h: h,
);

Future<void> removeServerSticker({
  required String serverId,
  required String hash,
}) => RustLib.instance.api.crateApiStickersRemoveServerSticker(
  serverId: serverId,
  hash: hash,
);

/// Search KLIPY stickers. `rating` is one of `gif_ratings()`.
Future<GifPage> stickerSearch({
  required String query,
  required int page,
  required String rating,
}) => RustLib.instance.api.crateApiStickersStickerSearch(
  query: query,
  page: page,
  rating: rating,
);

/// Trending KLIPY stickers — the catalog tab's default view.
Future<GifPage> stickerTrending({required int page, required String rating}) =>
    RustLib.instance.api.crateApiStickersStickerTrending(
      page: page,
      rating: rating,
    );

/// Sticker category names, if the provider offers any.
Future<List<String>> stickerCategories() =>
    RustLib.instance.api.crateApiStickersStickerCategories();

/// Download a picked KLIPY sticker, re-encode it into the ≤512px/≤512 KB
/// send format, and cache it as a `kind='sticker'` asset blob. Feed
/// hash/w/h into [sticker_token].
///
/// Same fetcher discipline as GIFs: proxy mode ignores `source_url` and
/// builds `{base}f/{id}` itself; direct mode resolves the variants our own
/// parse registered, falling back to `source_url` only on a registry miss
/// and only through the media host allowlist.
Future<StoredGif> stickerFetchAndStore({
  required String id,
  String? sourceUrl,
}) => RustLib.instance.api.crateApiStickersStickerFetchAndStore(
  id: id,
  sourceUrl: sourceUrl,
);

/// Export one personal pack as a `.hollow-pack` file. Returns its size.
Future<BigInt> exportPersonalStickerPack({
  required String pack,
  required String outputPath,
}) => RustLib.instance.api.crateApiStickersExportPersonalStickerPack(
  pack: pack,
  outputPath: outputPath,
);

/// Read a `.hollow-pack` manifest without importing anything.
Future<StickerPackPreview> previewStickerPack({required String path}) =>
    RustLib.instance.api.crateApiStickersPreviewStickerPack(path: path);

/// Import a `.hollow-pack` into the personal vault under [into_pack] (empty =
/// the name the file carries).
///
/// Every byte here is attacker-controlled, so nothing in the manifest is
/// trusted for anything load-bearing:
///   * the blob is keyed by the hash we COMPUTE, and an entry whose bytes do
///     not hash to their claimed name is rejected outright;
///   * `w`/`h` are re-derived from the decoded image, because those two
///     numbers go straight into the wire token;
///   * entry paths are never joined — the hash names the file we read;
///   * the vault caps are enforced per row, so a huge pack fills up to the
///     limit and reports the remainder as rejected rather than failing whole.
Future<StickerPackImportResult> importStickerPack({
  required String path,
  required String intoPack,
}) => RustLib.instance.api.crateApiStickersImportStickerPack(
  path: path,
  intoPack: intoPack,
);

/// One sticker of the user's personal vault.
class PersonalSticker {
  /// Free-form group name; `""` is the default (ungrouped) pack.
  final String pack;
  final String hash;
  final String name;
  final bool animated;
  final int w;
  final int h;

  /// `"upload"` | `"klipy:<id>"` — provenance only, never fetched at
  /// display time.
  final String source;

  const PersonalSticker({
    required this.pack,
    required this.hash,
    required this.name,
    required this.animated,
    required this.w,
    required this.h,
    required this.source,
  });

  @override
  int get hashCode =>
      pack.hashCode ^
      hash.hashCode ^
      name.hashCode ^
      animated.hashCode ^
      w.hashCode ^
      h.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonalSticker &&
          runtimeType == other.runtimeType &&
          pack == other.pack &&
          hash == other.hash &&
          name == other.name &&
          animated == other.animated &&
          w == other.w &&
          h == other.h &&
          source == other.source;
}

/// A processed sticker cached locally, ready to register in a pack or send.
/// `w`/`h` feed the `[a:s:hash:w:h]` token.
class ProcessedSticker {
  final String hash;
  final bool animated;
  final int w;
  final int h;

  const ProcessedSticker({
    required this.hash,
    required this.animated,
    required this.w,
    required this.h,
  });

  @override
  int get hashCode =>
      hash.hashCode ^ animated.hashCode ^ w.hashCode ^ h.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessedSticker &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          animated == other.animated &&
          w == other.w &&
          h == other.h;
}

/// One sticker of a server's CRDT-replicated set.
class ServerSticker {
  final String hash;
  final String name;
  final String pack;
  final bool animated;
  final int w;
  final int h;

  const ServerSticker({
    required this.hash,
    required this.name,
    required this.pack,
    required this.animated,
    required this.w,
    required this.h,
  });

  @override
  int get hashCode =>
      hash.hashCode ^
      name.hashCode ^
      pack.hashCode ^
      animated.hashCode ^
      w.hashCode ^
      h.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerSticker &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          name == other.name &&
          pack == other.pack &&
          animated == other.animated &&
          w == other.w &&
          h == other.h;
}

/// Outcome of an import. Partial by design: hitting a vault cap part-way
/// through must keep what already landed and SAY so, not roll back the lot.
class StickerPackImportResult {
  final String pack;
  final int added;

  /// Already in the pack — re-importing is idempotent, not an error.
  final int skipped;

  /// Failed validation or would not fit under the caps.
  final int rejected;

  const StickerPackImportResult({
    required this.pack,
    required this.added,
    required this.skipped,
    required this.rejected,
  });

  @override
  int get hashCode =>
      pack.hashCode ^ added.hashCode ^ skipped.hashCode ^ rejected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StickerPackImportResult &&
          runtimeType == other.runtimeType &&
          pack == other.pack &&
          added == other.added &&
          skipped == other.skipped &&
          rejected == other.rejected;
}

/// What a `.hollow-pack` says about itself, for the in-chat card and the
/// import confirmation — read WITHOUT touching the vault.
class StickerPackPreview {
  final String pack;

  /// Master peer_id of whoever exported it, `""` when unsigned or forged.
  final String author;

  /// True only when the signature verifies against `author`. Display only.
  final bool authorVerified;

  /// Stickers the file claims to carry.
  ///
  /// CLAIMS, not a promise: the count comes from the manifest and every
  /// entry still has to survive import validation. No thumbnail ships with
  /// this on purpose — previewing would mean handing un-validated bytes to
  /// an image decoder before we have checked a single one of them.
  final int count;

  const StickerPackPreview({
    required this.pack,
    required this.author,
    required this.authorVerified,
    required this.count,
  });

  @override
  int get hashCode =>
      pack.hashCode ^
      author.hashCode ^
      authorVerified.hashCode ^
      count.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StickerPackPreview &&
          runtimeType == other.runtimeType &&
          pack == other.pack &&
          author == other.author &&
          authorVerified == other.authorVerified &&
          count == other.count;
}
