// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_snapshot_bytes`, `derive_db_key_public`, `derive_db_key`, `dir_size_bytes`, `export_backup_bytes`, `get_peer_id`, `get_store`, `import_backup_bytes`, `import_snapshot_bytes`, `pending_link_blob_path`, `pending_link_code_path`, `pending_wipe_marker_path`, `referenced_asset_hashes`, `snapshot_state_summary`, `stash_pending_link`, `stored_file_to_ffi`

/// Open the encrypted message database. Must be called after identity is loaded.
/// Typically called once at app start (after `load_or_create_identity`).
Future<void> openMessageStore() =>
    RustLib.instance.api.crateApiStorageOpenMessageStore();

/// Load recent messages for a peer from the local database.
/// Returns messages ordered oldest-first, up to `limit`.
Future<List<StoredMessage>> loadMessages({
  required String peerId,
  required int limit,
}) => RustLib.instance.api.crateApiStorageLoadMessages(
  peerId: peerId,
  limit: limit,
);

/// Load ALL DM messages for a peer, including soft-deleted (hidden_at set).
/// No limit, ordered oldest-first. Used by the archive "My Data" viewer.
Future<List<StoredMessage>> loadAllDmMessages({required String peerId}) =>
    RustLib.instance.api.crateApiStorageLoadAllDmMessages(peerId: peerId);

/// Load ALL channel messages, including soft-deleted (hidden_at set).
/// No limit, ordered oldest-first. Used by the archive "My Data" viewer.
Future<List<StoredChannelMessage>> loadAllChannelMessages({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiStorageLoadAllChannelMessages(
  serverId: serverId,
  channelId: channelId,
);

/// Load edit history for a batch of message IDs.
/// Returns a flat list of edits sorted by edited_at ASC.
Future<List<StoredMessageEdit>> loadMessageEdits({
  required List<String> messageIds,
}) => RustLib.instance.api.crateApiStorageLoadMessageEdits(
  messageIds: messageIds,
);

/// Count all DM messages for a peer (including hidden/deleted).
Future<int> countDmMessages({required String peerId}) =>
    RustLib.instance.api.crateApiStorageCountDmMessages(peerId: peerId);

/// Count all visible DM messages across every conversation. Drives the Home
/// stats card — an honest multi-device sync-comparison number (DMs fully
/// converge across a person's devices; channel messages are lazy-paged and
/// would diverge, so they are deliberately not counted there).
Future<int> countAllDmMessages() =>
    RustLib.instance.api.crateApiStorageCountAllDmMessages();

/// Count all channel messages (including hidden/deleted).
Future<int> countChannelMessagesFfi({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiStorageCountChannelMessagesFfi(
  serverId: serverId,
  channelId: channelId,
);

/// Get a profile for a specific peer (or ourselves). Returns None if no profile stored.
Future<UserProfile?> getProfile({required String peerId}) =>
    RustLib.instance.api.crateApiStorageGetProfile(peerId: peerId);

/// Get all stored profiles (for populating the profile cache on startup).
Future<List<UserProfile>> getAllProfiles() =>
    RustLib.instance.api.crateApiStorageGetAllProfiles();

/// Get all stored profiles WITHOUT avatar/banner blobs (fast startup load).
Future<List<UserProfile>> getAllProfilesLight() =>
    RustLib.instance.api.crateApiStorageGetAllProfilesLight();

/// Get a single profile WITHOUT avatar/banner blobs (light reload on update).
Future<UserProfile?> getProfileLight({required String peerId}) =>
    RustLib.instance.api.crateApiStorageGetProfileLight(peerId: peerId);

/// Get only the avatar bytes for a peer (lazy load for HollowAvatar).
Future<Uint8List?> getAvatar({required String peerId}) =>
    RustLib.instance.api.crateApiStorageGetAvatar(peerId: peerId);

/// Get only the banner bytes for a peer (lazy load for profile card/DM header).
Future<Uint8List?> getBanner({required String peerId}) =>
    RustLib.instance.api.crateApiStorageGetBanner(peerId: peerId);

/// Save a key-value setting to the local database.
Future<void> saveSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiStorageSaveSetting(key: key, value: value);

/// Load a setting by key. Returns None if not set.
Future<String?> loadSetting({required String key}) =>
    RustLib.instance.api.crateApiStorageLoadSetting(key: key);

/// Load ALL settings whose key starts with `prefix` in ONE call — replaces
/// the per-key startup scans (`notif:*`, `seen:*`) that cost one FFI
/// round-trip per server/channel/DM.
Future<List<SettingEntry>> loadSettingsWithPrefix({required String prefix}) =>
    RustLib.instance.api.crateApiStorageLoadSettingsWithPrefix(prefix: prefix);

/// Count unread DM messages newer than the given last-seen message ID.
/// Only counts non-hidden messages from the other peer (is_mine = 0).
Future<int> countUnreadDm({
  required String peerId,
  required String lastSeenMessageId,
}) => RustLib.instance.api.crateApiStorageCountUnreadDm(
  peerId: peerId,
  lastSeenMessageId: lastSeenMessageId,
);

/// Count unread channel messages newer than the given last-seen message ID.
/// Only counts non-hidden messages from other members (is_mine = 0).
Future<int> countUnreadChannel({
  required String serverId,
  required String channelId,
  required String lastSeenMessageId,
}) => RustLib.instance.api.crateApiStorageCountUnreadChannel(
  serverId: serverId,
  channelId: channelId,
  lastSeenMessageId: lastSeenMessageId,
);

/// Count ALL non-hidden messages from others in a DM (for never-opened DMs).
Future<int> countAllUnreadDm({required String peerId}) =>
    RustLib.instance.api.crateApiStorageCountAllUnreadDm(peerId: peerId);

/// Count ALL non-hidden messages from others in a channel (for never-opened channels).
Future<int> countAllUnreadChannel({
  required String serverId,
  required String channelId,
}) => RustLib.instance.api.crateApiStorageCountAllUnreadChannel(
  serverId: serverId,
  channelId: channelId,
);

/// Count unread and mention-containing messages for a channel.
/// `mention_patterns` should include `@everyone`, `@DisplayName`, `@Nickname`.
Future<UnreadMentionCount> countUnreadChannelWithMentions({
  required String serverId,
  required String channelId,
  String? lastSeenMessageId,
  required List<String> mentionPatterns,
}) => RustLib.instance.api.crateApiStorageCountUnreadChannelWithMentions(
  serverId: serverId,
  channelId: channelId,
  lastSeenMessageId: lastSeenMessageId,
  mentionPatterns: mentionPatterns,
);

/// Get all distinct peer IDs that have DM messages in the local database.
Future<List<String>> getDmPeerIds() =>
    RustLib.instance.api.crateApiStorageGetDmPeerIds();

/// Load all friends, optionally filtered by status.
Future<List<FriendFfi>> loadFriends({String? status}) =>
    RustLib.instance.api.crateApiStorageLoadFriends(status: status);

/// Block an identity (MASTER-keyed). Persists the row and warms the in-memory
/// set the Rust ingest guards read, so it takes effect immediately. Purely
/// local — the blocked peer learns nothing. Pass any of the peer's ids; it is
/// collapsed to the master via the resolver.
Future<void> blockPeer({required String peerId}) =>
    RustLib.instance.api.crateApiStorageBlockPeer(peerId: peerId);

/// Unblock a previously blocked identity.
Future<void> unblockPeer({required String peerId}) =>
    RustLib.instance.api.crateApiStorageUnblockPeer(peerId: peerId);

/// All blocked master peer_ids, newest first.
Future<List<String>> loadBlockedPeers() =>
    RustLib.instance.api.crateApiStorageLoadBlockedPeers();

/// A single reaction on a message, returned to Dart.
/// Search channel messages by text.
Future<List<StoredChannelMessage>> searchChannelMessages({
  required String serverId,
  required String channelId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiStorageSearchChannelMessages(
  serverId: serverId,
  channelId: channelId,
  query: query,
  limit: limit,
);

/// Search DM messages by text.
Future<List<StoredMessage>> searchDmMessages({
  required String peerId,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateApiStorageSearchDmMessages(
  peerId: peerId,
  query: query,
  limit: limit,
);

/// Load all reactions for a list of message IDs.
/// Returns reactions grouped by message_id for efficient bulk loading.
Future<List<StoredReaction>> loadReactions({
  required List<String> messageIds,
}) => RustLib.instance.api.crateApiStorageLoadReactions(messageIds: messageIds);

/// Load recent channel messages from the local database.
/// Returns messages ordered oldest-first, up to `limit`.
Future<List<StoredChannelMessage>> loadChannelMessages({
  required String serverId,
  required String channelId,
  required int limit,
}) => RustLib.instance.api.crateApiStorageLoadChannelMessages(
  serverId: serverId,
  channelId: channelId,
  limit: limit,
);

/// Get file metadata by file ID.
Future<StoredFileInfo?> getFileMetadata({required String fileId}) =>
    RustLib.instance.api.crateApiStorageGetFileMetadata(fileId: fileId);

/// Get the vault content_id linked to a file by its file_id.
/// Returns None if no vault content_id is set (e.g. DM files, <6 member files).
Future<String?> getContentIdForFile({required String fileId}) =>
    RustLib.instance.api.crateApiStorageGetContentIdForFile(fileId: fileId);

/// Get all files attached to a message.
Future<List<StoredFileInfo>> getFilesForMessage({required String messageId}) =>
    RustLib.instance.api.crateApiStorageGetFilesForMessage(
      messageId: messageId,
    );

/// Get all incomplete files (for sync resume).
Future<List<StoredFileInfo>> getIncompleteFiles() =>
    RustLib.instance.api.crateApiStorageGetIncompleteFiles();

/// Mark a file as complete with its disk path (used for share-backed files).
Future<void> markFileComplete({
  required String fileId,
  required String diskPath,
}) => RustLib.instance.api.crateApiStorageMarkFileComplete(
  fileId: fileId,
  diskPath: diskPath,
);

/// Get file_ids from messages that have no completed file on disk.
/// Used to find files that need downloading after message sync.
Future<List<String>> getMissingFileIds() =>
    RustLib.instance.api.crateApiStorageGetMissingFileIds();

/// Missing file_ids scoped to ONE DM conversation (friend's MASTER peer id).
/// The chat-open sweep must never re-request account-wide ids from a DM peer.
Future<List<String>> getMissingFileIdsForDm({required String peerId}) =>
    RustLib.instance.api.crateApiStorageGetMissingFileIdsForDm(peerId: peerId);

/// Missing file_ids scoped to ONE server's channels.
Future<List<String>> getMissingFileIdsForServer({required String serverId}) =>
    RustLib.instance.api.crateApiStorageGetMissingFileIdsForServer(
      serverId: serverId,
    );

/// Reset completed files whose disk_path no longer exists on disk.
/// Returns the count of reset entries. They'll be re-requested from peers.
Future<int> resetStaleFiles() =>
    RustLib.instance.api.crateApiStorageResetStaleFiles();

/// Get the storage usage breakdown for the Storage Manager UI.
Future<StorageBreakdown> getStorageBreakdown() =>
    RustLib.instance.api.crateApiStorageGetStorageBreakdown();

/// Delete every cached asset blob not referenced by a personal set or a
/// server's CRDT state (Storage Manager "clear" action). Returns bytes freed.
Future<BigInt> clearUnreferencedAssetBlobs() =>
    RustLib.instance.api.crateApiStorageClearUnreferencedAssetBlobs();

/// Delete the file bytes for a single conversation/server (keep the signed
/// FileHeader rows so messages render as re-downloadable). Returns bytes freed.
Future<BigInt> clearFileBytesForContext({
  required String contextType,
  required String contextId,
}) => RustLib.instance.api.crateApiStorageClearFileBytesForContext(
  contextType: contextType,
  contextId: contextId,
);

/// Delete ALL downloaded file bytes (keep the signed FileHeader rows). Returns
/// bytes freed. Removes every file in `files/` then nulls the matching rows.
Future<BigInt> clearAllFileBytes() =>
    RustLib.instance.api.crateApiStorageClearAllFileBytes();

/// Enforce the downloaded-files LRU cap (`files/`), evicting oldest bytes until
/// under `cap_mb`. Keeps signed headers; nulls the rows whose bytes were
/// evicted (via `reset_stale_file_paths`). Returns bytes freed.
Future<BigInt> evictFilesCache({
  required BigInt capMb,
  required List<String> exemptPaths,
}) => RustLib.instance.api.crateApiStorageEvictFilesCache(
  capMb: capMb,
  exemptPaths: exemptPaths,
);

/// Clear the entire vault cache (`vault_cache/`) — pure cache, no signed headers
/// live there. Returns bytes freed.
Future<BigInt> clearVaultCache() =>
    RustLib.instance.api.crateApiStorageClearVaultCache();

/// Enforce the cache caps (files/ + vault_cache/ + the asset blob cache).
/// Called after a download completes so the user-set caps are actually
/// honored (the sliders were no-ops before this). Returns total bytes freed.
Future<BigInt> enforceStorageCaps({
  required BigInt filesCapMb,
  required BigInt vaultCacheCapMb,
  required BigInt assetCapMb,
  required List<String> exemptPaths,
}) => RustLib.instance.api.crateApiStorageEnforceStorageCaps(
  filesCapMb: filesCapMb,
  vaultCacheCapMb: vaultCacheCapMb,
  assetCapMb: assetCapMb,
  exemptPaths: exemptPaths,
);

/// Get file IDs for missing images in a specific server.
/// Used for late-joiner image sync in 6+ member servers.
Future<List<String>> getMissingImageFileIdsForServer({
  required String serverId,
}) => RustLib.instance.api.crateApiStorageGetMissingImageFileIdsForServer(
  serverId: serverId,
);

/// Save the recovery mnemonic to the database (called once on first identity generation).
Future<void> saveMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiStorageSaveMnemonic(mnemonic: mnemonic);

/// Retrieve the stored recovery mnemonic.
Future<String?> getMnemonic() =>
    RustLib.instance.api.crateApiStorageGetMnemonic();

/// Check if an identity key file exists on disk.
Future<bool> hasIdentity() => RustLib.instance.api.crateApiStorageHasIdentity();

/// Delete the on-disk identity + local DB so the next launch shows the Welcome
/// screen fresh. Used to discard a THROWAWAY identity created for the "Link a
/// device" first-run flow when the user cancels it. Best-effort — missing files
/// are ignored. The caller must restart the app afterward (the live DB handle
/// is still open). DESTRUCTIVE: only call on a throwaway with no real data.
Future<void> deleteIdentity() =>
    RustLib.instance.api.crateApiStorageDeleteIdentity();

Future<BigInt> exportBackup({
  required String outputPath,
  required bool includeVault,
  required bool includeFiles,
  required String passphrase,
}) => RustLib.instance.api.crateApiStorageExportBackup(
  outputPath: outputPath,
  includeVault: includeVault,
  includeFiles: includeFiles,
  passphrase: passphrase,
);

/// Import account backup from a passphrase-encrypted .hollow file.
/// Must be called BEFORE start_node() since it overwrites the data directory.
Future<void> importBackup({
  required String backupPath,
  required String passphrase,
}) => RustLib.instance.api.crateApiStorageImportBackup(
  backupPath: backupPath,
  passphrase: passphrase,
);

/// True if a pending link blob is waiting to be imported on launch.
Future<bool> hasPendingLink() =>
    RustLib.instance.api.crateApiStorageHasPendingLink();

/// (Receiver, at launch BEFORE start_node) Import a stashed link blob via the exact
/// same pipeline as a manual `.hollow` restore: delete the throwaway identity,
/// decrypt with the stashed code, extract into the data dir, then clean up the
/// stash. After this the bootstrap proceeds as a normal restored-backup launch.
Future<void> importPendingLink() =>
    RustLib.instance.api.crateApiStorageImportPendingLink();

/// Mark the data dir to be wiped clean on the next launch (pre-node-start). Call
/// this, then relaunch — do NOT try to delete the DB in-process while the node runs.
Future<void> stashPendingWipe() =>
    RustLib.instance.api.crateApiStorageStashPendingWipe();

/// True if a pending wipe is queued for this launch.
Future<bool> hasPendingWipe() =>
    RustLib.instance.api.crateApiStorageHasPendingWipe();

/// (At launch, BEFORE start_node) Delete every file/dir in the data dir so the next
/// Welcome starts from a truly clean slate. Preserves nothing identity-bearing:
/// removes `identity.key`/`identity.device`, `messages.db*`, `device_lists`, any
/// stashed `pending_link.*`, `vault/`, `files/`, etc. Keeps only the wipe marker
/// itself (removed last) and any `*.lock` single-instance guard. Idempotent.
Future<void> performPendingWipe() =>
    RustLib.instance.api.crateApiStoragePerformPendingWipe();

/// A friend entry returned to Dart.
class FriendFfi {
  final String peerId;
  final String status;
  final String direction;
  final PlatformInt64 requestedAt;
  final PlatformInt64 updatedAt;

  const FriendFfi({
    required this.peerId,
    required this.status,
    required this.direction,
    required this.requestedAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      status.hashCode ^
      direction.hashCode ^
      requestedAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FriendFfi &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          status == other.status &&
          direction == other.direction &&
          requestedAt == other.requestedAt &&
          updatedAt == other.updatedAt;
}

/// A single settings row for the batched prefix load.
class SettingEntry {
  final String key;
  final String value;

  const SettingEntry({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

/// Full storage picture for the Storage Manager UI.
class StorageBreakdown {
  /// Sum of size_bytes across all completed-on-disk files (from DB).
  final BigInt totalDbBytes;

  /// Actual `du` of the `files/` directory on disk (catches orphans/partials).
  final BigInt totalDiskBytes;

  /// Actual `du` of the `vault_cache/` directory.
  final BigInt vaultCacheBytes;

  /// Actual `du` of the `vault/` (held erasure shards) directory.
  final BigInt vaultShardBytes;

  /// Content-addressed asset blob cache (emotes, stickers, GIFs, banners)
  /// inside the encrypted DB.
  final BigInt assetBlobBytes;
  final int assetBlobCount;
  final List<StorageContextUsage> contexts;

  const StorageBreakdown({
    required this.totalDbBytes,
    required this.totalDiskBytes,
    required this.vaultCacheBytes,
    required this.vaultShardBytes,
    required this.assetBlobBytes,
    required this.assetBlobCount,
    required this.contexts,
  });

  @override
  int get hashCode =>
      totalDbBytes.hashCode ^
      totalDiskBytes.hashCode ^
      vaultCacheBytes.hashCode ^
      vaultShardBytes.hashCode ^
      assetBlobBytes.hashCode ^
      assetBlobCount.hashCode ^
      contexts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageBreakdown &&
          runtimeType == other.runtimeType &&
          totalDbBytes == other.totalDbBytes &&
          totalDiskBytes == other.totalDiskBytes &&
          vaultCacheBytes == other.vaultCacheBytes &&
          vaultShardBytes == other.vaultShardBytes &&
          assetBlobBytes == other.assetBlobBytes &&
          assetBlobCount == other.assetBlobCount &&
          contexts == other.contexts;
}

/// Per-conversation/server disk usage of downloaded files.
class StorageContextUsage {
  /// "dm" or "channel".
  final String contextType;

  /// DM = sender MASTER peer id; channel = "server_id:channel_id".
  final String contextId;

  /// Sum of `size_bytes` for completed-on-disk files in this context (from DB).
  final BigInt bytesDb;
  final int fileCount;

  const StorageContextUsage({
    required this.contextType,
    required this.contextId,
    required this.bytesDb,
    required this.fileCount,
  });

  @override
  int get hashCode =>
      contextType.hashCode ^
      contextId.hashCode ^
      bytesDb.hashCode ^
      fileCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StorageContextUsage &&
          runtimeType == other.runtimeType &&
          contextType == other.contextType &&
          contextId == other.contextId &&
          bytesDb == other.bytesDb &&
          fileCount == other.fileCount;
}

/// A channel message returned to Dart from the local database.
class StoredChannelMessage {
  final PlatformInt64 id;
  final String serverId;
  final String channelId;
  final String senderId;
  final String text;
  final bool isMine;
  final PlatformInt64 timestamp;
  final String? signature;
  final String? publicKey;
  final String? messageId;
  final PlatformInt64? editedAt;
  final PlatformInt64? hiddenAt;
  final String? replyToMid;
  final String? fileId;

  /// Link preview for the first URL in this message (Phase 6.75).
  final LinkPreviewRef? linkPreview;

  const StoredChannelMessage({
    required this.id,
    required this.serverId,
    required this.channelId,
    required this.senderId,
    required this.text,
    required this.isMine,
    required this.timestamp,
    this.signature,
    this.publicKey,
    this.messageId,
    this.editedAt,
    this.hiddenAt,
    this.replyToMid,
    this.fileId,
    this.linkPreview,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      serverId.hashCode ^
      channelId.hashCode ^
      senderId.hashCode ^
      text.hashCode ^
      isMine.hashCode ^
      timestamp.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      messageId.hashCode ^
      editedAt.hashCode ^
      hiddenAt.hashCode ^
      replyToMid.hashCode ^
      fileId.hashCode ^
      linkPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredChannelMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          serverId == other.serverId &&
          channelId == other.channelId &&
          senderId == other.senderId &&
          text == other.text &&
          isMine == other.isMine &&
          timestamp == other.timestamp &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          messageId == other.messageId &&
          editedAt == other.editedAt &&
          hiddenAt == other.hiddenAt &&
          replyToMid == other.replyToMid &&
          fileId == other.fileId &&
          linkPreview == other.linkPreview;
}

/// File metadata returned to Dart.
class StoredFileInfo {
  final String fileId;
  final String fileName;
  final String fileExt;
  final String mimeType;
  final BigInt sizeBytes;
  final int chunkCount;
  final int chunksReceived;
  final bool isImage;
  final int? width;
  final int? height;
  final String? messageId;
  final String contextType;
  final String contextId;
  final String senderId;
  final bool isMine;
  final PlatformInt64 createdAt;
  final PlatformInt64? completedAt;
  final String? diskPath;
  final PlatformInt64? expiredAt;

  /// Video thumbnail back-reference (Phase 6.75 video preview).
  /// When non-null, this file is a thumbnail image for a vault-stored video.
  /// The Dart UI uses this to render a play button overlay and trigger the
  /// vault download on tap.
  final VideoThumbRef? videoThumb;

  const StoredFileInfo({
    required this.fileId,
    required this.fileName,
    required this.fileExt,
    required this.mimeType,
    required this.sizeBytes,
    required this.chunkCount,
    required this.chunksReceived,
    required this.isImage,
    this.width,
    this.height,
    this.messageId,
    required this.contextType,
    required this.contextId,
    required this.senderId,
    required this.isMine,
    required this.createdAt,
    this.completedAt,
    this.diskPath,
    this.expiredAt,
    this.videoThumb,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      fileName.hashCode ^
      fileExt.hashCode ^
      mimeType.hashCode ^
      sizeBytes.hashCode ^
      chunkCount.hashCode ^
      chunksReceived.hashCode ^
      isImage.hashCode ^
      width.hashCode ^
      height.hashCode ^
      messageId.hashCode ^
      contextType.hashCode ^
      contextId.hashCode ^
      senderId.hashCode ^
      isMine.hashCode ^
      createdAt.hashCode ^
      completedAt.hashCode ^
      diskPath.hashCode ^
      expiredAt.hashCode ^
      videoThumb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredFileInfo &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          fileName == other.fileName &&
          fileExt == other.fileExt &&
          mimeType == other.mimeType &&
          sizeBytes == other.sizeBytes &&
          chunkCount == other.chunkCount &&
          chunksReceived == other.chunksReceived &&
          isImage == other.isImage &&
          width == other.width &&
          height == other.height &&
          messageId == other.messageId &&
          contextType == other.contextType &&
          contextId == other.contextId &&
          senderId == other.senderId &&
          isMine == other.isMine &&
          createdAt == other.createdAt &&
          completedAt == other.completedAt &&
          diskPath == other.diskPath &&
          expiredAt == other.expiredAt &&
          videoThumb == other.videoThumb;
}

/// A message returned to Dart from the local database.
class StoredMessage {
  final PlatformInt64 id;
  final String peerId;
  final String text;
  final bool isMine;
  final PlatformInt64 timestamp;
  final String? signature;
  final String? publicKey;
  final String? messageId;
  final PlatformInt64? editedAt;
  final PlatformInt64? hiddenAt;
  final String? replyToMid;
  final String? fileId;

  /// Link preview for the first URL in this message (Phase 6.75).
  final LinkPreviewRef? linkPreview;

  const StoredMessage({
    required this.id,
    required this.peerId,
    required this.text,
    required this.isMine,
    required this.timestamp,
    this.signature,
    this.publicKey,
    this.messageId,
    this.editedAt,
    this.hiddenAt,
    this.replyToMid,
    this.fileId,
    this.linkPreview,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      peerId.hashCode ^
      text.hashCode ^
      isMine.hashCode ^
      timestamp.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      messageId.hashCode ^
      editedAt.hashCode ^
      hiddenAt.hashCode ^
      replyToMid.hashCode ^
      fileId.hashCode ^
      linkPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          peerId == other.peerId &&
          text == other.text &&
          isMine == other.isMine &&
          timestamp == other.timestamp &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          messageId == other.messageId &&
          editedAt == other.editedAt &&
          hiddenAt == other.hiddenAt &&
          replyToMid == other.replyToMid &&
          fileId == other.fileId &&
          linkPreview == other.linkPreview;
}

/// A single edit history entry.
class StoredMessageEdit {
  final String messageId;
  final String oldText;
  final String newText;
  final PlatformInt64 editedAt;
  final String? signature;
  final String? publicKey;
  final String? prevSignature;
  final String? prevPublicKey;
  final PlatformInt64? prevTimestamp;

  const StoredMessageEdit({
    required this.messageId,
    required this.oldText,
    required this.newText,
    required this.editedAt,
    this.signature,
    this.publicKey,
    this.prevSignature,
    this.prevPublicKey,
    this.prevTimestamp,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      oldText.hashCode ^
      newText.hashCode ^
      editedAt.hashCode ^
      signature.hashCode ^
      publicKey.hashCode ^
      prevSignature.hashCode ^
      prevPublicKey.hashCode ^
      prevTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredMessageEdit &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          oldText == other.oldText &&
          newText == other.newText &&
          editedAt == other.editedAt &&
          signature == other.signature &&
          publicKey == other.publicKey &&
          prevSignature == other.prevSignature &&
          prevPublicKey == other.prevPublicKey &&
          prevTimestamp == other.prevTimestamp;
}

class StoredReaction {
  final String messageId;
  final String emoji;
  final String peerId;
  final PlatformInt64 addedAt;

  const StoredReaction({
    required this.messageId,
    required this.emoji,
    required this.peerId,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^ emoji.hashCode ^ peerId.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoredReaction &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          emoji == other.emoji &&
          peerId == other.peerId &&
          addedAt == other.addedAt;
}

/// Unread + mention counts returned from the database.
class UnreadMentionCount {
  final int total;
  final int mentions;

  const UnreadMentionCount({required this.total, required this.mentions});

  @override
  int get hashCode => total.hashCode ^ mentions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnreadMentionCount &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          mentions == other.mentions;
}

/// A user profile returned to Dart.
class UserProfile {
  final String peerId;
  final String displayName;
  final String status;
  final String aboutMe;
  final PlatformInt64 updatedAt;
  final Uint8List? avatarBytes;
  final Uint8List? bannerBytes;
  final String twitchUsername;

  /// Showcase board JSON (profile blocks; empty = no board).
  final String showcaseBoard;

  const UserProfile({
    required this.peerId,
    required this.displayName,
    required this.status,
    required this.aboutMe,
    required this.updatedAt,
    this.avatarBytes,
    this.bannerBytes,
    required this.twitchUsername,
    required this.showcaseBoard,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      displayName.hashCode ^
      status.hashCode ^
      aboutMe.hashCode ^
      updatedAt.hashCode ^
      avatarBytes.hashCode ^
      bannerBytes.hashCode ^
      twitchUsername.hashCode ^
      showcaseBoard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          status == other.status &&
          aboutMe == other.aboutMe &&
          updatedAt == other.updatedAt &&
          avatarBytes == other.avatarBytes &&
          bannerBytes == other.bannerBytes &&
          twitchUsername == other.twitchUsername &&
          showcaseBoard == other.showcaseBoard;
}
