// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_update_impl`, `detect_common_prefix`, `download_inner`, `extract_zip_to`, `fetch_bytes`, `install_kind_impl`, `launch_update_script_impl`, `normalise_expected_sha256`, `relaunch_snippet`, `signature_url`, `spawn_waiter`, `verify_manifest_signature_with`, `verify_manifest_signature`

String getCurrentVersion() =>
    RustLib.instance.api.crateApiUpdaterGetCurrentVersion();

/// How this Linux copy of Hollow was installed: `"flatpak"` or `"tarball"`.
/// Empty on every other platform. Dart branches its update UI on this (a
/// flatpak has a read-only `/app`, so the "can I write to the app dir" probe
/// is meaningless there), and every Linux path below reads the SAME detection.
String linuxInstallKind() =>
    RustLib.instance.api.crateApiUpdaterLinuxInstallKind();

/// Fetches `manifest.json` AND its `manifest.json.sig` sidecar, and returns
/// the manifest text only when the signature verifies against
/// [`MANIFEST_SIGNING_PUBKEYS`]. The signature covers the manifest's exact
/// bytes, so the text handed to Dart is byte for byte what was signed.
Future<String> fetchVersionManifest({required String manifestUrl}) => RustLib
    .instance
    .api
    .crateApiUpdaterFetchVersionManifest(manifestUrl: manifestUrl);

/// Plain fetch for the OTHER release-folder feeds (news.json, status.json):
/// display-only text with no signature sidecar. Nothing downloaded through
/// here is ever executed or installed; the update manifest itself must go
/// through [`fetch_version_manifest`].
Future<String> fetchReleaseFeed({required String url}) =>
    RustLib.instance.api.crateApiUpdaterFetchReleaseFeed(url: url);

/// Downloads `url` to `dest_path` and keeps the file ONLY if its SHA-256 is
/// `expected_sha256` (the value from the signed manifest). Any failure,
/// including a checksum mismatch or a cancelled stream, deletes the partial
/// file and ends the stream with `DownloadProgress::error` set.
Stream<DownloadProgress> downloadUpdate({
  required String url,
  required String destPath,
  required String expectedSha256,
}) => RustLib.instance.api.crateApiUpdaterDownloadUpdate(
  url: url,
  destPath: destPath,
  expectedSha256: expectedSha256,
);

Future<String> applyUpdate({
  required String zipPath,
  required String appDir,
  required String version,
}) => RustLib.instance.api.crateApiUpdaterApplyUpdate(
  zipPath: zipPath,
  appDir: appDir,
  version: version,
);

/// Starts the script [`apply_update`] returned so that it OUTLIVES this
/// process. Linux only; Dart calls this and then exits.
Future<void> launchUpdateScript({required String scriptPath}) => RustLib
    .instance
    .api
    .crateApiUpdaterLaunchUpdateScript(scriptPath: scriptPath);

/// Spawn a detached, windowless waiter that idles until this process exits,
/// then relaunches the app. Call right before a self-restart `exit(0)`.
Future<void> spawnRelaunchWaiter() =>
    RustLib.instance.api.crateApiUpdaterSpawnRelaunchWaiter();

class DownloadProgress {
  final BigInt bytesDownloaded;
  final BigInt totalBytes;

  /// Set on the final item when the download was refused or failed
  /// (checksum mismatch, non-https URL, transport error). The partial file
  /// is already deleted by then; Dart shows the reason and stops.
  final String? error;

  const DownloadProgress({
    required this.bytesDownloaded,
    required this.totalBytes,
    this.error,
  });

  @override
  int get hashCode =>
      bytesDownloaded.hashCode ^ totalBytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DownloadProgress &&
          runtimeType == other.runtimeType &&
          bytesDownloaded == other.bytesDownloaded &&
          totalBytes == other.totalBytes &&
          error == other.error;
}
