// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_master`

/// The 60-digit safety number shared by this identity and `peer_id`.
///
/// Both people see the IDENTICAL number, so verification is a single "do these
/// match?" — there is no yours/theirs ordering to get wrong.
///
/// Derived purely from the two MASTER Ed25519 keys, so it is stable across
/// reinstalls and across the contact adding or removing devices. It changes only
/// when the master identity does — i.e. when it is genuinely a different person.
Future<String> safetyNumberWith({required String peerId}) =>
    RustLib.instance.api.crateApiVerificationSafetyNumberWith(peerId: peerId);

/// Group a 60-digit safety number into 12 blocks of 5 for display.
///
/// Lives in Rust so desktop and mobile cannot drift into showing the same
/// number two different ways — two people comparing differently-grouped digits
/// is exactly the confusion this screen exists to remove. Input that is not the
/// expected length is returned untouched rather than mangled.
String formatSafetyNumber({required String number}) =>
    RustLib.instance.api.crateApiVerificationFormatSafetyNumber(number: number);

/// Compare a number the contact read out (or pasted) against `expected`.
///
/// Both sides are normalized to digits first, so spacing, line breaks or a
/// trailing newline never produce a false mismatch. A false alarm on a security
/// screen teaches users to ignore it.
bool safetyNumbersMatch({required String expected, required String provided}) =>
    RustLib.instance.api.crateApiVerificationSafetyNumbersMatch(
      expected: expected,
      provided: provided,
    );

/// Mark a contact as identity-verified (their safety number was confirmed out
/// of band). Stored against the MASTER identity, so it survives their device
/// changes — which is the whole point of a master-derived safety number.
Future<void> setPeerVerified({required String peerId}) =>
    RustLib.instance.api.crateApiVerificationSetPeerVerified(peerId: peerId);

/// Withdraw a contact's verified status.
Future<void> removePeerVerified({required String peerId}) =>
    RustLib.instance.api.crateApiVerificationRemovePeerVerified(peerId: peerId);

/// Whether this contact has been identity-verified.
Future<bool> isPeerVerified({required String peerId}) =>
    RustLib.instance.api.crateApiVerificationIsPeerVerified(peerId: peerId);

/// Every verified contact as `(master_peer_id, verified_at_ms)`.
Future<List<(String, PlatformInt64)>> getVerifiedPeers() =>
    RustLib.instance.api.crateApiVerificationGetVerifiedPeers();

/// All recorded alerts, newest first — read AND dismissed alike, so the history
/// survives scrollback rather than vanishing on dismiss.
Future<List<SecurityAlertFfi>> getSecurityAlerts() =>
    RustLib.instance.api.crateApiVerificationGetSecurityAlerts();

/// Mark one alert as read.
Future<void> acknowledgeSecurityAlert({required String alertId}) => RustLib
    .instance
    .api
    .crateApiVerificationAcknowledgeSecurityAlert(alertId: alertId);

/// Mark every outstanding alert for one contact as read (the conversation
/// banner's Dismiss, which speaks for all of them at once).
Future<void> acknowledgeSecurityAlertsForPeer({required String peerId}) =>
    RustLib.instance.api.crateApiVerificationAcknowledgeSecurityAlertsForPeer(
      peerId: peerId,
    );

/// A recorded identity change for a contact.
class SecurityAlertFfi {
  /// Stable id — pass to [`acknowledge_security_alert`].
  final String alertId;

  /// MASTER peer_id of the contact the alert is about.
  final String peerId;

  /// `new_device` (a device joined their identity — the one that carries an
  /// attack signal) or `identity_key_changed` (a device re-keyed, i.e. they
  /// reinstalled).
  final String kind;

  /// The device id that appeared, or the device whose key changed.
  final String detail;
  final PlatformInt64 createdAt;

  /// `None` while still unread.
  final PlatformInt64? acknowledgedAt;

  const SecurityAlertFfi({
    required this.alertId,
    required this.peerId,
    required this.kind,
    required this.detail,
    required this.createdAt,
    this.acknowledgedAt,
  });

  @override
  int get hashCode =>
      alertId.hashCode ^
      peerId.hashCode ^
      kind.hashCode ^
      detail.hashCode ^
      createdAt.hashCode ^
      acknowledgedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecurityAlertFfi &&
          runtimeType == other.runtimeType &&
          alertId == other.alertId &&
          peerId == other.peerId &&
          kind == other.kind &&
          detail == other.detail &&
          createdAt == other.createdAt &&
          acknowledgedAt == other.acknowledgedAt;
}
