// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_beside`, `clear`, `close_store_singleton`, `destroy_data_root`, `destroy_with`, `erase_recordings`, `is_hollow_temp`, `is_pasted_image`, `is_recording_name`, `is_recording_path`, `kept_by_wipe`, `looks_like_a_profile`, `mark_destroy`, `of_this_process`, `publish_scope`, `read_recordings`, `recorder_log`, `run_duress`, `same_folder`, `scrub`, `sweep_root`, `wait_for`, `write_recordings`, `zero_and_remove`, `zero_keys`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Outside`, `Signal`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

/// Scope (a), and the tail of every other. Leaves the node RUNNING for Dart's step 5.
Future<void> destroyLocal() => RustLib.instance.api.crateApiWipeDestroyLocal();

/// Erases a profile this process is not running (Settings, desktop): the same
/// routine against its root, marker and keys first. What belongs to the running
/// process (keystore slots, its log, the shared temp folder) is not touched.
Future<void> eraseProfileAt({required String dataDir}) =>
    RustLib.instance.api.crateApiWipeEraseProfileAt(dataDir: dataDir);

/// Lists a recording this profile is about to make, so the profile's wipe takes it.
/// Only Hollow's own names in a `Hollow Recordings` folder are accepted; entries no
/// longer on disk drop off.
Future<void> rememberRecording({required String path}) =>
    RustLib.instance.api.crateApiWipeRememberRecording(path: path);

/// `scope` is `device` | `device_revoke` | `identity`; its signal never blocks the wipe.
/// `identity` needs the recovery phrase once the identity has one (design ID-1): it is
/// checked BEFORE anything is erased, so a wrong phrase costs nothing.
Future<void> destroyWithScope({
  required String scope,
  required bool notifyFriends,
  String? phrase,
}) => RustLib.instance.api.crateApiWipeDestroyWithScope(
  scope: scope,
  notifyFriends: notifyFriends,
  phrase: phrase,
);

/// Drives the conversation banner. `None` = we were never told.
Future<PlatformInt64?> identityDestroyedAt({required String masterPeerId}) =>
    RustLib.instance.api.crateApiWipeIdentityDestroyedAt(
      masterPeerId: masterPeerId,
    );
